<!--
/**
 * @category   Webkul
 * @package    Webkul_MpAmazonConnector
 * @author     Webkul Software Private Limited
 * @copyright  Copyright (c)  Webkul Software Private Limited (https://webkul.com)
 * @license    https://store.webkul.com/license.html
 */ 
-->
<?php 
$helper = $this->helper('Webkul\Marketplace\Helper\Data');
/*
if ($helper->isSeller()){ ?>
	<li class="mp-amazon-connect nav item <?php  echo $block->getCurrentNavClass('mpamazonconnect/account')?>">  
		<?php if($block->getCurrentNavClass('mpamazonconnect/account')){ ?>   
		    <strong><?php  echo __('Amazon Connect') ?></strong>        
		<?php 
		} else { ?>    
		    <a href="#"><?php  echo __('Amazon Connect') ?></a>                
		<?php } ?>
		<ul class="nav items">
			<li class="nav item <?php  echo $block->getCurrentNavClass('mpamazonconnect/account/index');?>">
				<?php if ($block->getCurrentNavClass('mpamazonconnect/account/index')) { ?>   
				    <strong><?php  echo __('Manage Account') ?></strong>        
				<?php 
				} else { ?>    
				    <a href="<?php  echo $block->getDealUrl('mpamazonconnect/account/index')?>">
				        <?php  echo __('Manage Account') ?>
				    </a>                
				<?php } ?>
			</li>
			<li class="nav item <?php  echo $block->getCurrentNavClass('mpamazonconnect/product/index');?>">
				<?php if($block->getCurrentNavClass('mpamazonconnect/account/syncproduct')){ ?>   
				    <strong><?php  echo __('Mapped Product') ?></strong>        
				<?php 
				} else { ?>    
				    <a href="<?php  echo $block->getDealUrl('mpamazonconnect/product/index')?>">
				        <?php  echo __('Mapped Product') ?>
				    </a>                
				<?php } ?>
			</li>
			<li class="nav item <?php  @escapeNotVerified  echo $block->getCurrentNavClass('mpamazonconnect/account/unassigned');?>">
				<?php if($block->getCurrentNavClass('mpamazonconnect/product/unassigned')){ ?>   
				    <strong><?php  echo __('Unassigned Product') ?></strong>
				<?php 
				} else { ?>    
				    <a href="<?php  echo $block->getDealUrl('mpamazonconnect/product/unassigned')?>">
				        <?php  echo __('Unassigned Product') ?>
				    </a>                
				<?php } ?>
			</li>
			<li class="nav item <?php  echo $block->getCurrentNavClass('mpamazonconnect/producttoamazon/index');?>">
				<?php if($block->getCurrentNavClass('mpamazonconnect/producttoamazon/index')){ ?>   
				    <strong><?php  echo __('Export Product') ?></strong>
				<?php 
				} else { ?>    
				    <a href="<?php  echo $block->getDealUrl('mpamazonconnect/producttoamazon/index')?>">
				        <?php  echo __('Export Product') ?>
				    </a>                
				<?php } ?>
			</li>
			<li class="nav item <?php  echo $block->getCurrentNavClass('mpamazonconnect/order/index');?>">
				<?php if($block->getCurrentNavClass('mpamazonconnect/order/index')){ ?>   
				    <strong><?php  echo __('Mapped Order') ?></strong>
				<?php 
				} else { ?>    
				    <a href="<?php  echo $block->getDealUrl('mpamazonconnect/order/index')?>">
				        <?php  echo __('Mapped Order') ?>
				    </a>                
				<?php } ?>
			</li>
		</ul>   
	</li>
<?php } */ ?>