<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Review\Block\Product\Review $block */
?>
<?php
/*echo "<pre>";
print_r(get_class_methods($block));
print_r($block->debug());
echo "</pre>";*/
?>
<div id="product-review-container" data-role="product-review"></div>
<?php 
//Get Object Manager Instance
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

//Load product by product id
$reviewBlock = $objectManager->create('Magento\Review\Block\Product\View\ListView');
$_items = $reviewBlock->getReviewsCollection()->getItems();
$format = $reviewBlock->getDateFormat() ?: \IntlDateFormatter::SHORT;
?>
<?php if (!empty($_items)):?>

<?php endif;?>

<?php 
echo $this->getLayout()->createBlock('Magento\Review\Block\Product\View\ListView')->setTemplate('Magento_Review::product/view/list.phtml')->toHtml();
?>

<?php echo $block->getChildHtml(); ?>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Review/js/process-reviews": {
                "productReviewUrl": "<?= $block->escapeJs($block->escapeUrl($block->getProductReviewUrl())) ?>",
                "reviewsTabSelector": "#tab-label-reviews"
            }
        }
    }
</script>
