<?php 
$pageText = 'You are selling with myGermany to international end-customers. Each sales causes transactions costs, such as myGermany commission, exchange and payment transaction fees, which will be deducted from your earnings.';
?>
<div class="mis_price_cal_title_div">
    <h1 style="color: black;" class="mis_price_cal_title"><?php echo __('PROFIT & COST CALCULATOR');?></h1>
</div>
<br>
<div class="mis_price_cal_pagetext_div">
    <p class="mis_price_cal_pagetext"><?php echo __($pageText);?></p> 
</div>
<br>