<?php
/**
 * Mangoit Marketplace.
 *
 * @category  Mangoit
 * @package   Mangoit_Marketplace
 * @author    Mangoit
 */

// @codingStandardsIgnoreFile
$_helper = $this->helper('Webkul\Marketplace\Helper\Data');
$isPartner= $_helper->isSeller();
$magentoCurrentUrl = $block->getCurrentUrl();
?>
<?php /*
if($isPartner){ ?>
    <li class="nav item <?php echo strpos($magentoCurrentUrl,'marketplce/account/deactivate')? "current":"";?>">
        <a href="<?php echo $block->getUrl('marketplce/account/deactivate', ['_secure' => $this->getRequest()->isSecure()]); ?>">
            <?php  echo __('Deactivate Account') ?>
        </a>
    </li>
<?php } */ ?>
