<?php 
    $current_store = $this->getRequest()->getParam('store_id');
    if ( (!isset($current_store)) && (strlen($current_store) < 1)) {
        $current_store = 1;
    }
    /*echo "<pre>";
    print_r($this->getRequest()->getParams());
    echo "<br> current_store ".$current_store;
    die();*/
    $storeList = $this->getStoreList();
    $sections_array = $this->getSections();
    $count = 0;
    $tooltipHelper = $this->helper('Mangoit\MisTooltip\Helper\Data');
    $tooltipData = $tooltipHelper->getAllToolTipData($current_store); 
    $toolSelectedIds =  $tooltipHelper->getAssociatesOptions($current_store);
    // echo "<pre>";
    // print_r($tooltipData);
    // die();
    $selected_section_id = '';
?>

<style type="text/css">
    /*.data-grid.tooltip_grid tr td {
        padding: 2px !important;
    }*/
    td{
        padding-left: 10px;
        padding-right: 10px;
    }
    select{
        height: 25px;
        width: 100%;
    }
    .select_op_err{
        color: red;
        display: none;
    }

    .scroll_div_mis
    {
        height: 800px;
        overflow: scroll;
    }
</style>
<div >
    <form class="tooltipform" id="tooltipform" method="POST" action="<?php echo $this->getUrl('mistooltip/tool/save');?>" data-mage-init='{"validation":{}}'>
    <input name="form_key" type="hidden" value="<?php echo $this->getFormKey();?>">
    <!-- new added 01_nov_18  -->
    <input type="hidden" name="removed_ids" id="removed_ids" value="">
    <!-- new added  -->  
    
    <div class="page-main-actions">
        <div class="page-actions-placeholder"></div>
        <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
            <div class="page-actions-inner" data-title="Customers">
                <div class="page-actions-buttons">
                    <button id="back" title="back" type="button" class="action- scalable primary mis_back_btn" onclick="onBackButton();" >
                        <span><?php echo __('Back');?></span>
                    </button>
                    <button id="add" title="Save" type="submit" class="action- scalable primary mis_save_btn" onclick="" >
                        <span><?php echo __('Save');?></span>
                    </button>
                </div>
            </div>
        </div>
    </div>

    <div class="admin__field required">
        <label class="admin__field-label" for="store_select"><span><?php echo __('Select Language')?></span></label>
        <div class="admin__field-control">
            <select class="admin__control-select store_select" name="store" id="store_select" data-validate='{"required":true}'>
                <?php foreach ($storeList as $key => $value) :?>
                    <?php if((strlen($current_store) > 0) && ($key == $current_store)): ?>
                        <option selected="selected" value="<?php echo $key;?>"><?php echo __($value);?></option>
                    <?php elseif(isset($tooltipData[0]['store_id'])):?>
                        <?php if($key == $tooltipData[0]['store_id']): ?>
                            <option selected="selected" value="<?php echo $key;?>"><?php echo __($value);?></option>
                        <?php else: ?>
                            <option value="<?php echo $key;?>"><?php echo __($value);?></option>
                        <?php endif;?>
                    <?php else: ?>
                        <option value="<?php echo $key;?>"><?php echo __($value);?></option>
                    <?php endif;?>

                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="scroll_div_mis">
        <table class="data-grid tooltip_grid">
            <thead>
                <tr>
                    <th class="data-grid-th col-entity_id section-position-grid"><?php echo __('Section');?></th>
                    <th class="data-grid-th col-entity_id section-position-grid"><?php echo __('Position');?></th>
                    <th class="data-grid-th col-entity_id"><?php echo __('Information');?></th>
                    <th class="data-grid-th col-entity_id"><input type="button" name="add_more" class="add_more" value="<?php echo __('Add More');?>"></th>
                </tr>
            </thead>
            <tbody>
            <?php if(!empty($tooltipData)): ?>
                <?php foreach ($tooltipData as $toolkey => $toolvalue): ?>
                    <tr class='tr_class'>
                        <td>
                            <input type="hidden" name="tooltip[<?php echo $count;?>][id]" value="<?php echo $toolvalue['id'];?>">
                            <select class='section' data-row="<?php echo $count;?>" name="tooltip[<?php echo $count;?>][section_id]" data-validate='{"required":true}'>
                                <?php foreach ($sections_array as $key => $value): ?>

                                    <?php if (isset($toolvalue['section_id']) && ($toolvalue['section_id'] == $key)) :?>
                                        <?php $selected_section_id = $key ?>
                                        <option value="<?php echo $key;?>" selected="selected" data-tool="<?php $toolvalue['tooltip_id'];?>" ><?php echo __($value);?></option>
                                    <?php else :?>
                                        <option value="<?php echo $key;?>" data-tool="0"><?php echo __($value);?></option>
                                    <?php endif; ?>

                                <?php endforeach; ?>
                            </select>
                        </td>
                        <td>
                            <select class="section_opt_cls section_options<?php echo $count;?>" name="tooltip[<?php echo $count;?>][tooltip_id]" data-validate='{"required":true}' data-row="<?php echo $count;?>">
                                <option value=""  >
                                    <?php echo __('select');?>
                                    
                                </option>   
                                <?php if(isset($toolSelectedIds[$selected_section_id])): ?>                     
                                    <?php foreach ($toolSelectedIds[$selected_section_id] as $key => $value): ?>
                                        <?php if($key == $tooltipData[$count]['tooltip_id']): ?>
                                            <option value="<?php echo $key;?>" selected="selected" ><?php echo $value; ?></option>
                                        <?php else: ?>
                                            <option value="<?php echo $key;?>" ><?php echo $value; ?></option>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                <?php endif;?>
                            </select>
                            <span class="select_op_err select_options_err_<?php echo $count;?>"><?php echo __('Already in use.')?></span>
                        </td>
                        <td>
                            <textarea id="html_editor_<?php echo $count;?>" name="tooltip[<?php echo $count;?>][tooltip_text]"  class="html_editor textarea_uniq_cls" > 
                            <?php
                             if (isset($tooltipData[$count]['tooltip_text'])) {
                                  echo $tooltipData[$count]['tooltip_text'];
                              } 
                            ?></textarea>
                        </td>
                        <td>
                            <!-- New code 01_nov_18 -->
                            <input type='button' name='remove' data-attr="<?php echo (isset($toolvalue['id']) ? $toolvalue['id'] : 0 ) ?>" class='remove_btn mis_remove_btn' value='Remove' id='remove_btn'>
                            <!-- New code ends -->
                        </td>
                    </tr>
                <?php
                    $count++;
                 endforeach; ?>
             <?php else: ?>
                    <tr class='tr_class'>
                        <td>
                            <select class='section' data-row="<?php echo $count;?>" name="tooltip[<?php echo $count;?>][section_id]" data-validate='{"required":true}'>
                                <?php foreach ($sections_array as $key => $value): ?>

                                    <?php if (isset($toolvalue['section_id']) && ($toolvalue['section_id'] == $key)) :?>
                                        <?php $selected_section_id = $key ?>
                                        <option value="<?php echo $key;?>" selected="selected" data-tool="<?php $toolvalue['tooltip_id'];?>" ><?php echo __($value);?></option>
                                    <?php else :?>
                                        <option value="<?php echo $key;?>" data-tool="0"><?php echo __($value);?></option>
                                    <?php endif; ?>

                                <?php endforeach; ?>
                            </select>
                        </td>
                        <td>
                            <select class="section_opt_cls section_options<?php echo $count;?>" name="tooltip[<?php echo $count;?>][tooltip_id]" data-validate='{"required":true}' data-row="<?php echo $count;?>">
                                <option value=""  >
                                    <?php echo __('select');?>
                                    
                                </option>   
                                <?php if(isset($toolSelectedIds[$selected_section_id])): ?>                     
                                    <?php foreach ($toolSelectedIds[$selected_section_id] as $key => $value): ?>
                                        <?php if($key == $tooltipData[$count]['tooltip_id']): ?>
                                            <option value="<?php echo $key;?>" selected="selected" ><?php echo $value; ?></option>
                                        <?php else: ?>
                                            <option value="<?php echo $key;?>" ><?php echo $value; ?></option>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                <?php endif;?>
                            </select>
                            <span class="select_op_err select_options_err_<?php echo $count;?>"><?php echo __('Already in use.')?></span>
                        </td>
                        <td>
                            <textarea id="html_editor_<?php echo $count;?>" name="tooltip[<?php echo $count;?>][tooltip_text]"  class="html_editor textarea_uniq_cls" > 
                            <?php
                             if (isset($tooltipData[$count]['tooltip_text'])) {
                                  echo $tooltipData[$count]['tooltip_text'];
                              } 
                            ?></textarea>
                        </td>
                        <td>
                            <!-- New code 01_nov_18 -->
                            <input type='button' name='remove' data-attr="<?php echo (isset($toolvalue['id']) ? $toolvalue['id'] : 0 ) ?>" class='remove_btn mis_remove_btn' value='Remove' id='remove_btn'>
                            <!-- New code ends -->
                        </td>
                    </tr>
             <?php endif; ?>
            </tbody>
        </table>        
    </div>
    </form>
</div> 
<script>
    require([
        "jquery",
        "mage/translate",
        "mage/adminhtml/events",
        "mage/adminhtml/wysiwyg/tiny_mce/setup"
    ], function(jQuery) {

        jQuery('.textarea_uniq_cls').each(function(t){
            console.log(jQuery(this).attr('id'));
            var field_id = jQuery(this).attr('id');
                
            wysiwygDescription = new wysiwygSetup(field_id, {
                "width" : "100%",
                "height" : "200px",
                "plugins" : [{"name":"image"}],
                "tinymce4" : {
                    "toolbar":"undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | alignleft aligncenter alignright alignjustify | outdent indent |  numlist bullist checklist | forecolor backcolor permanentpen formatpainter removeformat | pagebreak | charmap emoticons | fullscreen  preview save print | insertfile image media pageembed template link anchor codesample",
                    "plugins":"advlist autolink lists link charmap media noneditable table contextmenu paste code help table fullscreen image link media",
                }
            });
            wysiwygDescription.setup("exact");
        });

        
    });
</script>
<script type="text/javascript">
var dashboardUrl = "<?php echo $this->getUrl('admin/dashboard/index');?>";
var current_url = "<?php echo $this->getUrl('mistooltip/tool/index');?>";
var html ='';
    var ajaxurl = "<?php echo $this->getUrl('mistooltip/tool/sectionoption') ?>";
    var counter = "<?php echo $count;?>";
    function onBackButton()
    {
        window.location.href = dashboardUrl;
    }

    function addRow(counter)
    {
        var tbl_row = "<tr class='tr_class'>"+
                            "<td>"+
                                "<select class='section' data-row='"+counter+"' name='tooltip["+counter+"][section_id]' data-validate='{required:true}'> "+
                                    <?php foreach ($sections_array as $key => $value): ?>
                                    "<option value=<?php echo $key;?>><?php echo __($value);?></option>"+
                                    <?php endforeach; ?>
                                "</select>"+
                            "</td>"+
                            "<td>"+
                                "<select class='section_opt_cls section_options"+counter+"' data-row='"+counter+"' name='tooltip["+counter+"][tooltip_id]' data-validate='{required:true}'>"+
                                    "<option value=''><?php echo __('select');?></option>"+
                                "</select>"+
                                "<span class='select_op_err select_options_err_"+counter+"'><?php echo __('Already in use.')?></span>"+
                            "</td>"+
                            "<td>"+
                               "<textarea id='html_editor_"+counter+"' name='tooltip["+counter+"][tooltip_text]' class='textarea_cls'></textarea>"+
                            "</td>"+
                            "<td>"+
                                "<input type='button' data-attr='0' name='remove mis_remove_btn' class='remove_btn' value='Remove' id='remove_btn'>"+
                            "</td>"+
                        "</tr>";
        return tbl_row;
    }

    
    
    require([
        'jquery',
        'mage/adminhtml/wysiwyg/tiny_mce/setup'
        ], function($) {

            /* ******** HTML Editor ****** */
            var config = {}, editor;

            jQuery.extend(config, {
                settings: {
                    width: "400",
                    theme_advanced_buttons1 : 'bold,italic,|,justifyleft,justifycenter,justifyright,|,' +
                                                'fontselect,fontsizeselect,|,forecolor,backcolor,|,link,unlink,image,|,bullist,numlist,|,code,|',
                    theme_advanced_buttons2: 'tablecontrols',
                    theme_advanced_buttons3: null,
                    theme_advanced_buttons4: null
                }
            });

            /* ******************************/
            
            /* New Codes */

            $(document).on('click', '.remove_btn', function(){
                var data_row = $(this).data('attr');
                if (data_row > 0) {
                    var removed_ids = $('#removed_ids').val();
                    if (removed_ids.length > 0) {
                        removed_ids = removed_ids+','+data_row;                        
                        $('#removed_ids').val(removed_ids);                        
                    } else {
                        $('#removed_ids').val(data_row);                        
                    }
                }
                $(this).parent().parent().remove();
            });
            /* New Codes ends */ 

            $(document).on('change', '.store_select', function(){
                var store_id_url = $(this).val();
                if (store_id_url.length > 0 ) {
                    window.location.href = current_url+'store_id/'+store_id_url;
                }
            });

            $(document).on('change', '.section_opt_cls', function(){
                var has_val = 0;
                var current_val = $(this).val();
                var current_row = $(this).data('row');
                console.log('current row css '+current_row);
                $('.section_opt_cls').each(function(){
                    if (current_val == $(this).val()) {
                        has_val++;
                    }
                });
                if (has_val > 1) {
                    $('.select_options_err_'+current_row).css('display', 'block');
                    $(this).prop('selectedIndex',0);
                } else {
                    $('.select_options_err_'+current_row).css('display', 'none');
                }
                console.log('has_val '+has_val);

            });

            $(document).on('click', '.add_more', function(){
                console.log('addmore');
                counter++;
                $('.tr_class').last().after(addRow(counter));

                /*editor = new tinyMceWysiwygSetup(
                    'html_editor_'+counter,
                    config
                );

                editor.turnOn();*/
                wysiwygDescription = new wysiwygSetup('html_editor_'+counter, {
                    "width" : "100%",
                    "height" : "200px",
                    "plugins" : [{"name":"image"}],
                    "tinymce4" : {
                        "toolbar":"undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | alignleft aligncenter alignright alignjustify | outdent indent |  numlist bullist checklist | forecolor backcolor permanentpen formatpainter removeformat | pagebreak | charmap emoticons | fullscreen  preview save print | insertfile image media pageembed template link anchor codesample",
                    "plugins":"advlist autolink lists link charmap media noneditable table contextmenu paste code help table fullscreen image link media",
                    }
                });
                wysiwygDescription.setup("exact");

                jQuery('#html_editor_'+counter).addClass('wysiwyg-editor').data('wysiwygEditor', editor);
            });
            $(document).on('change', '.section', function(){
                html = "<option value=''><?php echo ('select')?></option>";
                var row_no = $(this).data('row');
                var section_id = $(this).val();
                console.log(row_no);
                console.log($('.section_options'+row_no).html(''));
                $('.section_options'+row_no).html('');
                $.ajax({
                    type: "POST",
                    data : {'section_id': section_id},
                    async : true,
                    showLoader: true,
                    url: ajaxurl,
                    success: function (response) {
                        data = $.parseJSON(response);
                        $.each(data, function (i,v)
                        {
                          html += "<option value="+i+">"+v+"<option>"; 
                        });
                        $('.section_options'+row_no).append(html);
                    },
                    error: function (response) {

                    }
                });                
            });
        });
</script>
<<!-- script type="text/javascript">
    require([
            'jquery',
            'mage/adminhtml/wysiwyg/tiny_mce/setup'
        ], function(jQuery){
     
        var config = {}, 
            editor;
     
        jQuery.extend(config, {
            settings: {
                width: "400",
                theme_advanced_fonts : 'Andale Mono=andale mono,times;Oswald=Oswald;Open Sans=open sans;Arial=arial,helvetica,sans-serif;Arial Black=arial black,avant garde;Book Antiqua=book antiqua,palatino;Comic Sans MS=comic sans ms,sans-serif;Courier New=courier new,courier;Georgia=georgia,palatino;Helvetica=helvetica;Impact=impact,chicago;Symbol=symbol;Tahoma=tahoma,arial,helvetica,sans-serif;Terminal=terminal,monaco;Times New Roman=times new roman,times;Trebuchet MS=trebuchet ms,geneva;Verdana=verdana,geneva;Webdings=webdings;Wingdings=wingdings,zapf dingbats',
                theme_advanced_buttons1 : 'bold,italic,|,justifyleft,justifycenter,justifyright,|,' +
                                            'fontselect,fontsizeselect,|,forecolor,backcolor,|,link,unlink,image,|,bullist,numlist,|,code',
                theme_advanced_buttons2: 'tablecontrols',
                theme_advanced_buttons3: null,
                theme_advanced_buttons4: null
            }
        });

        jQuery('.textarea_uniq_cls').each(function(t){
            editor = new tinyMceWysiwygSetup(
                this.id,
                config
            );
            console.log(jQuery(this.id));
            editor.turnOn();
            jQuery(this.id)
                .addClass('wysiwyg-editor')
                .data(
                    'wysiwygEditor',
                    editor
                );
        });
    });
</script> -->
