<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpSellerCoupons
 * @author    Webkul Software Private Limited 
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

// @codingStandardsIgnoreFile
$_helper = $this->helper('Webkul\Marketplace\Helper\Data');
$isPartner= $_helper->isSeller();
$magentoCurrentUrl = $block->getCurrentUrl();
$isSellerGroup = $_helper->isSellerGroupModuleInstalled();
?>
<?php 
if($isPartner){ ?>
<?php if(($isSellerGroup && $_helper->isAllowedAction('mpsellercoupons/index/index')) || !$isSellerGroup) { ?>
    <li class="nav item notification-link wk-mp-item-coupoun level-0 <?php echo strpos($magentoCurrentUrl,'mpsellercoupons/index/index')? "active":"";?>">     
        <?php if(strpos($magentoCurrentUrl,'mpsellercoupons/index/index')!==FALSE){ ?>   
            <a href="#">
                <span><?php /* @escapeNotVerified */ echo __('Seller Coupons Manager') ?></span>
            </a>
        <?php 
        } else{ ?>    
            <a href="<?php echo $block->getUrl('mpsellercoupons/index/index', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                <?php /* @escapeNotVerified */ echo __('Seller Coupons Manager') ?>
            </a>                
        <?php 
        } ?>      
    </li>
<?php } ?>
<?php } ?>

