<?php
/**
 * Module_name : Cor_Customizations
 * Overrided file for adding back arrow before the product title
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$title = '';
if (trim($block->getPageHeading())) {
    $title = '<span class="base" data-ui-id="page-title-wrapper" ' .  $block->getAddBaseAttribute() . '>'
        . $block->escapeHtml($block->getPageHeading()) . '</span>';
}
?>
<?php if ($title): ?>
<div class="page-title-wrapper<?= /* @escapeNotVerified */ $cssClass ?>">
    <h1 class="page-title"
        <?php if ($block->getId()): ?> id="<?= /* @escapeNotVerified */ $block->getId() ?>" <?php endif; ?>
        <?php if ($block->getAddBaseAttributeAria()): ?>
            aria-labelledby="<?= /* @escapeNotVerified */ $block->getAddBaseAttributeAria() ?>"
        <?php endif; ?>><span><img class="mis_back_btn" src="<?php echo $this->getViewFileUrl('Cor_Customizations::images/back-arrow.png');?>" onclick="window.history.go(-1);"></span>
        <?= /* @escapeNotVerified */$title ?>
    </h1>
    <?= $block->getChildHtml() ?>
</div>
<?php endif; ?>
