<?php 
/**
 * @category   Webkul
 * @package    Webkul_MpAmazonConnector
 * @author     Webkul Software Private Limited
 * @copyright  Copyright (c)  Webkul Software Private Limited (https://webkul.com)
 * @license    https://store.webkul.com/license.html
 */

// @codingStandardsIgnoreFile

/** @var $block \Webkul\Marketplace\Block\Order\History */

$helper = $this->_objectManager->create('Webkul\Marketplace\Helper\Data');
$orderHelper = $this->helper('Webkul\Marketplace\Helper\Orders');
$paramData = $this->getRequest()->getParams();
$filterOrderId = '';
$filterOrderStatus = '';
$filterDateTo = '';
$filterDateFrom = '';

if(isset($paramData['s'])){
    $filterOrderId = $paramData['s'] != ""?$paramData['s']:"";
}
if(isset($paramData['orderstatus'])){
    $filterOrderStatus = $paramData['orderstatus'] != ""?$paramData['orderstatus']:"";
}
if(isset($paramData['from_date'])){
    $filterDateFrom = $paramData['from_date'] != ""?$paramData['from_date']:"";
}
if(isset($paramData['to_date'])){
    $filterDateTo = $paramData['to_date'] != ""?$paramData['to_date']:"";
} ?>
<div class="wk-mp-design">
	<fieldset class="fieldset info wk-mp-fieldset">
		<legend class="legend">
			<span><?php echo __('My Orders') ?></span>
		</legend>			
		<div class="grid">
			<div class="hor-scroll">
				<form action="<?php echo $block->getCurrentUrl();?>" method="get">
					<table cellspacing="0" class="border wk-mp-list-table">
					    <thead>
					        <tr id="wk-mp-tr-heading">
					            <th><span><?php echo __('Order Id') ?></span></th>
					            <th><span><?php echo __('Date') ?></span></th>
					            <th><span><?php echo __('Order Status') ?></span></th>
					            <th><span>&nbsp;</span></th>
					        </tr>
					    </thead>
					    <tbody class="wk-mp-body">
					    	<tr>
					    		<td>
					    			<input type="text" class="input-text" name="s" placeholder='<?php echo __('Search by Order Id') ?>' value="<?php echo $filterOrderId?>" style="width:99%;"/>
					    		</td>
					    		<td>
					    			<span class="wk-mp-td-span">
					    				<input name="from_date" id="special-from-date" class="input-text" value="<?php echo $filterDateFrom?>" type="text" placeholder='<?php echo __('Date From') ?>'/>
					    			</span>				    			
					    			<span class="wk-mp-td-span">
					    				<input name="to_date" id="special-to-date" class="input-text" value="<?php echo $filterDateTo?>" type="text" placeholder='<?php echo __('Date To') ?>'/>
					    			</span>
					    		</td>
					    		<td>
				    				<select name="orderstatus" class="input-text">
				    					<option value=""><?php echo __('All') ?></option>
				    					<?php 
				    					$orderstatusColl = $orderHelper->getOrderStatusData();
				    					foreach ($orderstatusColl as $orderstatus) {
				    						?>
				    						<option value="<?php echo $orderstatus['status']?>" <?php if($filterOrderStatus == $orderstatus['status']) echo 'selected="selected"'?>>
						    					<?php echo __($orderstatus['label']) ?>
						    				</option>
				    						<?php
				    					} 
				    					?>
					    			</select>
					    		</td>
					    		<td class="wk-mp-td-last">
					    			<button class="button" title="Save" id="save-btn" type="submit">
										<span><span><span><?php echo __('Submit') ?></span></span></span>
									</button>
					    		</td>
					    	</tr>
					    </tbody>
					</table>
				</form>
				<?php 
				if(count($block->getAllSalesOrder())==0){ ?>		
					<div class="fieldset wk-mp-fieldset">
						<div class="wk-emptymsg">
							<?php echo __('No Order Available') ?>
						</div>
					</div>
					<?php 
				} else{ ?>
					<?php $i=0;
					foreach($block->getAllSalesOrder() as $res){
						$order = $block->getMainOrder($res['order_id']);
						$state=$order->getState();
						$status=$order->getStatus();
						$name=$order->getCustomerName();
						$tracking=$orderHelper->getOrderinfo($res['order_id']);
						if($tracking->getIsCanceled()){
							$state='canceled';
							$status='Canceled';
						}
						$i++;?>
						<div class="wk-orderbox <?php if($i==1) echo "wk-first-order"?>">
							<div style="padding:7px 7px 0px 7px;">
								<div class="wk-orderbox-content1">
									<div class="wk-orderbox-details">
										<div class="color">
											<span class="wk-ordertitle-label"><?php echo __('Order') ?></span> <strong>#<?php echo $res['magerealorder_id']; ?></strong>
										</div>
										<div class="name">
											<?php echo $block->getpronamebyorder($res['order_id'])?>
										</div>
										<a href="<?php echo $block->getUrl('marketplace/order/view', ['id'=>$res['order_id'], '_secure' => $this->getRequest()->isSecure()])?>">
												<button class="button" title="<?php echo __('View Order') ?>" type="button">
													<span><span><span><?php echo __('View Order') ?></span></span></span>
												</button>
											</a>
									</div>
									<div class="wk-dash-orderstatus">
										<label for="name" class="wk-dash-label">
											<div class="status <?php echo strtolower($state); ?>"><?php echo strtoupper($status); ?> </div>
										</label> 
									</div>
								</div>
								<div class="wk-orderbox-content2">
									<div class="wk-orderbox-details">
										<?php if ($helper->getSellerProfileDisplayFlag()) { ?>
											<span class="wk-title-label"><?php echo __('Customer: ');?></span>
											<span class="wk-label"><?php echo $name;?></span>&nbsp;&nbsp;
										<?php } ?>
										<span class="wk-title-label"><?php echo __('Date: ');?></span>
										<span class="wk-label"><?php echo $block->formatDate($res['created_at'])?></span>
									</div>
									<div class="wk-orderbox-total">
										<span class="wk-title-label"><?php echo __('Order Total (Base)- ');?></span>
										<span class="wk-label">
											<strong>
												<?php 
												$orderPrice = $block->getPricebyorder($res['order_id']);
												echo $order->formatBasePrice($orderPrice);
												?>
											</strong>
										</span>
										<br />
										<span class="wk-title-label"><?php echo __('Order Total (Purchased)- ');?></span>
										<span class="wk-label">
											<strong>
												<?php 
												echo $order->formatPrice($block->getOrderedPricebyorder($res['currency_rate'], $orderPrice));
												?>
											</strong>
										</span>
									</div>
								</div>
							</div>
						</div>
						<div class="wk-clear"></div>
						<?php
					} 	?>
					<?php
				}?>
			</div>
		</div>	
		<?php if ($block->getPagerHtml()): ?>
	        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
	    <?php endif ?>	
	</fieldset>
</div>
<div class="buttons-set">
	<p class="back-link">
		<a href="javascript:;" onclick="javascript: window.history.back();" class="left">&laquo; <?php echo __('Back') ?></a>
	</p>
</div>
<script type="text/x-magento-init">
	{
		"*" : {
			"sellerOrderHistory" : {}
		}
	}
</script>