<?php 
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) 2010-2018 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

// @codingStandardsIgnoreFile
?>
<!-- set data in js window variable, used in navigation.js file -->
<script>
    window.notificationConfig = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getNotificationConfig()); ?>;
</script>
<!-- include js file defined in default.xml -->
<div id="notification-component" data-bind="scope:'faq-notification-content'" class="field">
    <script type="text/x-magento-init">
    {
        "#notification-component": {
            "Magento_Ui/js/core/app":  <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
        }
    }
    </script>
</div>
<!-- notification template called in navigation.js file -->
<script id="wk_faq_notification_template" type="text/x-magento-template">
    <div class="wk-notification-block faq-notification-block" style="    position: absolute;
    right: 28px;
    top: -2px;
    margin-right: 16px;    left: inherit;">
        <a href="" class="wk-notifications-action marketplace-dropdown" style="position: relative;    display: inline-block;">
        <img class="wk-notification-img" height="20" width="20" src="<%- data.notificationImage %>" />
        <% if (data.notificationCount > 5) { %>
            <span class="wk-notification-count">5+</span>
        <% } else { %>
            <span class="wk-notification-count"><%- data.notificationCount %></span>
        <% } %>
        </a>
        <ul class="marketplace-dropdown-menu faq-menu">
        <span class="notify-point"></span>
            <li class="wk-notifications-entry">
                <strong class="wk-notifications-entry-title">
                   <?php echo __('You have new FAQ request from vendor'); ?>
                </strong>
            </li>
        </ul>
    </div>
</script>

<!-- notification template called in navigation.js file -->
<script id="wk_sellser_profile_notification_template" type="text/x-magento-template">
    <div class="wk-notification-block seller-profile-notification-block" style="    position: absolute;
    right: 27px;
    top: -2px;
     left: inherit;">
        <a href="" class="wk-notifications-action marketplace-dropdown" style="position: relative;    display: inline-block;">
        <img class="wk-notification-img" height="20" width="20" src="<%- data.notificationImage %>" style="" />
        <% if (data.notificationCount > 5) { %>
            <span class="wk-notification-count" style="  background-color: #e22626;
        border-radius: 1em;
        color: #ffffff;
        display: inline-block;
        font-size: 1.1rem;
        font-weight: 700;
        left: 50%;
        margin-left: .3em;
        margin-top: -1.1em;
        /* padding: .3em .5em; */
        padding: .2em .3em;
        position: absolute;
        top: 25%;">5+</span>
        <% } else { %>
            <span class="wk-notification-count" style="  background-color: #e22626;
        border-radius: 1em;
        color: #ffffff;
        display: inline-block;
        font-size: 1.1rem;
        font-weight: 700;
        left: 50%;
        margin-left: .3em;
        margin-top: -1.1em;
        /* padding: .3em .5em; */
        padding: .2em .3em;
        position: absolute;
        top: 25%;"><%- data.notificationCount %></span>
        <% } %>
        </a>
       <!--  <ul class="marketplace-dropdown-menu faq-menu">
        <span class="notify-point"></span>
            <li class="wk-notifications-entry">
                <strong class="wk-notifications-entry-title">
                   <?php //echo __('You have new vendor profile request from vendor'); ?>
                </strong>
            </li>
        </ul> -->
        <ul class="marketplace-dropdown-menu seller-profile-dropdown-menu">
        <span class="notify-point"></span>
            <% count = 1 %>
            <% _.each(data.notifications, function(i) { %>
                <% if (count <= 5) { %>
                <li class="wk-notifications-entry">
                    <strong class="wk-notifications-entry-title">
                       <?php echo "<%= i.title %>"; ?>
                    </strong>
                    <p class="wk-notifications-entry-description _cutted">
                        <a href="<%- i.url %>" class="wk-notifications-entry-description-start">
                            <span>
                                <%= i.desc %>
                            </span>
                        </a>
                    </p>
                    <time class="wk-notifications-entry-time">
                        <%- i.updated_time %>
                    </time>
                </li>
                <% count++ %>
                <% } %>
            <%  }); %>
        <% if (count > 5) { %>
            <% if (data.notificationType == 'product') { %>
            <li class="wk-notifications-entry notifications-entry-last" style="background: #403934">
                <a href="<?php echo $block->getUrl('marketplace/product/index'); ?>">
                    <?php echo __('Click here to view product(s) list'); ?>
                </a>
            </li>
            <%  } %>
            <% if (data.notificationType == 'seller') { %>
            <li class="wk-notifications-entry notifications-entry-last" style="background: #403934">
                <a href="<?php echo $block->getUrl('marketplace/seller/index'); ?>">
                    <?php echo __('Click here to view seller(s) list'); ?>
                </a>
            </li>
            <%  } %>
            <% if (data.notificationType == 'feedback') { %>
            <li class="wk-notifications-entry notifications-entry-last" style="background: #403934">
                <a href="<?php echo $block->getUrl('marketplace/feedback/index'); ?>">
                    <?php echo __('Click here to view feedback(s) list'); ?>
                </a>
            </li>
            <%  } %>
        <%  } %>
        </ul>
    </div>
</script>