<?php 
/**
 * @category   Package
 * @package    Package_RakutenConnector
 * @author     Author
 * @copyright  Copyright (c)  Author
 * @license    license
 */

// @codingStandardsIgnoreFile

/** @var $block \Mangoit\RakutenConnector\Block\Account\Dashboard */ 

?>

<div style="padding-bottom:15px;">
	<div style="border:1px solid #cccccc;">
		<div style="border-bottom: 1px solid #ccc;padding:5px;">
			<?php echo __('Rakuten Order(s)') ?>
		</div>
		<div style="padding:5px;">
			<center><strong class="wk-dashboard-sales-font"><?php echo $block->getTotalSales(); ?></strong></center>
			<br />
			<span><?php echo "Orders:- ".count($block->getAmzOrders()); ?></span>
			&nbsp;&nbsp;&nbsp;&nbsp;
			<span><a href="<?php echo $block->getAmzOrdersViewUrl() ?>">View</a></span>
		</div>
	</div>
</div>
