<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$helper = $this->helper(\Webkul\Marketplace\Helper\Data::class);
$helperOrders = $this->helper(\Webkul\Marketplace\Helper\Orders::class);
$partner = $block->getProfileDetail();
if ($partner['shop_url']) {
    $bannerpic = $partner->getBannerPic()!=''?$partner->getBannerPic():"banner-image.png";
    $bannerpic = $helper->getMediaUrl().'avatar/'.$bannerpic;

    $logo = $partner->getLogoPic()!=''?$partner->getLogoPic():"noimage.png";
    $logo = $helper->getMediaUrl().'avatar/'.$logo;

    $sizeArr = $helper->getImageSize($logo);
    if (!empty($sizeArr) && !empty($sizeArr['width']) && !empty($sizeArr['height'])) {
        $width = $sizeArr['width'];
        $height = $sizeArr['height'];
        $calculatedHeight = 120;
        $calculatedWidth = ($width / $height) * $calculatedHeight;
        $calculatedPercent = ($width / $height) * 2.5;
        if ($calculatedHeight) { ?>
            <style>
                .wk-mp-collection-seller-title-container {
                    padding-left: calc(<?= /* @noEscape */ $calculatedPercent ?>% + <?= /* @noEscape */ $calculatedWidth ?>px);
                }
            </style>
            <?php
        }
    }

    $shopUrl = $block->escapeHtml($partner['shop_url']);
    $shoptitle = $block->escapeHtml($partner->getShopTitle());
    if (!$shoptitle) {
        $shoptitle = $shopUrl;
    }
    $sellerId = $partner->getSellerId();
    $locsearch = $block->escapeHtml($partner['company_locality']);
    $sellerProductCount = $helper->getSellerProCount($sellerId);
    if ($helper->getActiveColorPicker()) {?>
        <style>
            .marketplace-seller-collection .wk-mp-collection-product-count-container,
            .marketplace-seller-profile .wk-mp-collection-product-count-container,
            .marketplace-seller-feedback .wk-mp-collection-rating-count-container {
                border-bottom-color: <?= $block->escapeHtml($partner['background_width']);?>;
            }
        </style>
        <?php
    } ?>
    <div class="wk-mp-banner">
        <?php if ($helper->isSellerSliderModuleInstalled()) {
            echo $block->getChildHtml("marketplace_seller_slider_block");
        } ?>
        <img class="wk-mp-banner-image" src="<?= /* @noEscape */ $bannerpic; ?>">
    </div>
    <div class="wk-mp-collection-header-box">
        <div class="wk-mp-collection-seller-title-container">
            <a href="<?= /* @noEscape */ $helper->getRewriteUrl('marketplace/seller/profile/shop/'.$shopUrl);?>" >
                <img class="wk-mp-collection-logo" src="<?= /* @noEscape */ $logo;?>" />
            </a>
            <span class="wk-mp-collection-seller-title wk-mp-collection-header-css">
                <a href="<?= /* @noEscape */ $helper->getRewriteUrl('marketplace/seller/profile/shop/'.$shopUrl);?>">
                    <?= $block->escapeHtml($shoptitle)?>
                </a>
            </span>
            <?php if ($locsearch) { ?>
                <div class="wk-mp-collection-seller-title wk-mp-collection-header-bottom">
                    <a title="<?= $block->escapeHtml(__('Search')) ?>" href="<?= /* @noEscape */ $helper->getRewriteUrl('marketplace/seller/location/shop/'.$shopUrl)."?loc=".$locsearch?>" target="_blank">
                        <span class="wk-mp-collection-location wk-mp-collection-header-bottom-txt">
                            <?= /* @noEscape */ __($locsearch); ?>
                        </span>
                    </a>
                </div>
            <?php } ?>
        </div>
        <div class="wk-mp-collection-header-right-wrapper">
            <div class="wk-mp-collection-header-right wk-mp-seller-profile-wrapper">
                <div class="wk-mp-seller-profile-box wk-mp-collection-header-bottom-txt">
                    <a href="<?= /* @noEscape */ $helper->getRewriteUrl('marketplace/seller/profile/shop/'.$shopUrl);?>#about-us">
                        <?= $block->escapeHtml(__('About'))?>
                    </a>
                </div>
                <?= $block->getChildHtml("marketplace_seller_profile_contact")?>
                <?php if ($helper->getSellerPolicyApproval()) { ?>
                    <div class="wk-mp-seller-profile-box wk-mp-collection-header-bottom-txt">
                        <a href="<?= /* @noEscape */ $helper->getRewriteUrl('marketplace/seller/profile/shop/'.$shopUrl);?>#shipping-policy">
                            <?= $block->escapeHtml(__('Shipping'))?>
                        </a>
                    </div>
                    <div class="wk-mp-seller-profile-box wk-mp-collection-header-bottom-txt">
                        <a href="<?= /* @noEscape */ $helper->getRewriteUrl('marketplace/seller/profile/shop/'.$shopUrl);?>#return-policy">
                            <?= $block->escapeHtml(__('Return'))?>
                        </a>
                    </div>
                    <?php if (trim($partner['privacy_policy'])) { ?>
                        <div class="wk-mp-seller-profile-box wk-mp-collection-header-bottom-txt">
                            <a href="<?= /* @noEscape */ $helper->getRewriteUrl('marketplace/seller/policy/shop/'.$shopUrl);?>">
                                <?= $block->escapeHtml(__('Privacy Policy'))?>
                            </a>
                        </div>
                    <?php } ?>
                <?php } ?>
                <?= $block->getChildHtml("marketplace_seller_profile_menu")?>
                <?php if ($partner->getFbActive()) { ?>
                    <div class="wk-mp-seller-profile-box wk-mp-profile-icon-wrapper">
                        <a href="//facebook.com/<?= $block->escapeHtml($partner->getFacebookId());?>" target="blank">
                            <span class="wk-mp-profile-icon-css wk-mp-profile-icon-fb" title="<?= $block->escapeHtml(__('Check in Facebook'))?>"></span>
                        </a>
                    </div>
                    <?php
                }
                if ($partner->getTwActive()) { ?>
                    <div class="wk-mp-seller-profile-box wk-mp-profile-icon-wrapper">
                        <a href="//twitter.com/<?= $block->escapeHtml($partner->getTwitterId());?>" target="blank">
                            <span class="wk-mp-profile-icon-css wk-mp-profile-icon-tw" title="<?= $block->escapeHtml(__('Check in Twitter'))?>"></span>
                        </a>
                    </div>
                    <?php
                }
                if ($partner->getGplusActive()) { ?>
                    <div class="wk-mp-seller-profile-box wk-mp-profile-icon-wrapper">
                        <a href="//plus.google.com/<?= $block->escapeHtml($partner->getGplusId());?>" target="blank">
                            <span class="wk-mp-profile-icon-css wk-mp-profile-icon-gplus" title="<?= $block->escapeHtml(__('Check in Google+'))?>"></span>
                        </a>
                    </div>
                    <?php
                }
                if ($partner->getVimeoActive()) { ?>
                    <div class="wk-mp-seller-profile-box wk-mp-profile-icon-wrapper">
                        <a href="//vimeo.com/<?= $block->escapeHtml($partner->getVimeoId());?>" target="blank">
                            <span class="wk-mp-profile-icon-css wk-mp-profile-icon-vimeo" title="<?= $block->escapeHtml(__('Check in Vimeo'))?>"></span>
                        </a>
                    </div>
                    <?php
                }
                if ($partner->getYoutubeActive()) { ?>
                    <div class="wk-mp-seller-profile-box wk-mp-profile-icon-wrapper">
                        <a href="//www.youtube.com/user/<?= $block->escapeHtml($partner->getYoutubeId());?>" target="blank">
                            <span class="wk-mp-profile-icon-css wk-mp-profile-icon-youtube" title="<?= $block->escapeHtml(__('Check in Youtube'))?>"></span>
                        </a>
                    </div>
                    <?php
                }
                if ($partner->getInstagramActive()) { ?>
                    <div class="wk-mp-seller-profile-box wk-mp-profile-icon-wrapper">
                        <a href="//www.instagram.com/<?= $block->escapeHtml($partner->getInstagramId());?>" target="blank">
                            <span class="wk-mp-profile-icon-css wk-mp-profile-icon-instagram" title="<?= $block->escapeHtml(__('Check in Instagram'))?>"></span>
                        </a>
                    </div>
                    <?php
                }
                if ($partner->getPinterestActive()) { ?>
                    <div class="wk-mp-seller-profile-box wk-mp-profile-icon-wrapper">
                        <a href="//www.pinterest.com/<?= $block->escapeHtml($partner->getPinterestId());?>" target="blank">
                            <span class="wk-mp-profile-icon-css wk-mp-profile-icon-pinterest" title="<?= $block->escapeHtml(__('Check in Pinterest'))?>"></span>
                        </a>
                    </div>
                    <?php
                } ?>
            </div>
            <div class="wk-mp-collection-header-right wk-mp-collection-count-wrapper">
                <div class="wk-mp-collection-product-right">
                    <div class="wk-mp-collection-rating-count-container wk-mp-collection-header-css">
                        <div class="wk-mp-collection-count-txt">
                            <a class="store-name" href="<?= /* @noEscape */ $helper->getRewriteUrl('marketplace/seller/feedback/shop/'.$shopUrl)?>" title="<?= $block->escapeHtml(__('Make a Review'))?>">
                                    <?= /* @noEscape */ $helper->getSelleRating($sellerId); ?>
                                </a>
                            </div>
                        <div class="wk-mp-collection-header-bottom wk-mp-collection-header-bottom-txt">
                            <?= $block->escapeHtml(__('Rating'))?>
                        </div>
                    </div>
                    <div class="wk-mp-collection-order-count-container wk-mp-collection-header-css">
                        <div class="wk-mp-collection-count-txt">
                            <?= /* @noEscape */ $helperOrders->getSellerOrders($sellerId); ?>
                        </div>
                        <div class="wk-mp-collection-header-bottom wk-mp-collection-header-bottom-txt">
                            <?= $block->escapeHtml(__('Orders'))?>
                        </div>
                    </div>
                </div>
                <div class="wk-mp-collection-product-count-container wk-mp-collection-header-css">
                    <div class="wk-mp-collection-count-txt">
                        <a href="<?= /* @noEscape */ $helper->getRewriteUrl('marketplace/seller/collection/shop/'.$shopUrl);?>" title="<?= $block->escapeHtml(__('View Collection'))?>">
                            <?= $block->escapeHtml($sellerProductCount)?>
                        </a>
                    </div>
                    <div class="wk-mp-collection-header-bottom wk-mp-collection-header-bottom-txt">
                        <?= $block->escapeHtml(__('Products'))?>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php }  ?>
