<!-- 
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpAdvertisementManager
 * @author    Webkul
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */  
-->
<style type="text/css">
    .modal-footer
    {
        display: none;
    }
    .modal-header
    {
        border: none;
    }
</style>
<?php
    $html = ''; 
    $position = $block->getPosition();
    $store = $block->storeId();
    $isAdminAd = $block->isAdminAd($position);

	$currentAds = $block->getCurrentAds();
    $copyOfCurrentAds = $currentAds;
    $sessionVal = $block->getSessionVal();

    $random_key = null;

    /* my code */
    if ($sessionVal == null) {
        $random_key = 0;
    } else {
        $random_key = $sessionVal;
    }
    /* my code ends*/

    // if (isset($sessionVal) && $sessionVal != null) {
    //     unset($copyOfCurrentAds[$sessionVal]);
    //     if(!empty($copyOfCurrentAds)) {
    //         $random_key=array_rand($copyOfCurrentAds);
    //         $block->setSessionVal($random_key);
    //     }
    // } elseif ($sessionVal == 0) {
    //     unset($copyOfCurrentAds[$sessionVal]);
    //     if (!empty($copyOfCurrentAds)) {
    //         $random_key=array_rand($copyOfCurrentAds);
    //         $block->setSessionVal($random_key);
    //     }
    // } else {
    //     if (!empty($currentAds)) {
    //         $random_key=array_rand($currentAds);
    //         $block->setSessionVal($random_key);
    //     }
    // }
    if ($isAdminAd == 1) {
        $allAds = $block->getStoreWiseAds($position, $store);       
        $adsCount = count($allAds);
        if ($adsCount > 0) {
            $currentAds = $block->getAdminAdsStoreWise($allAds);
        }
    } else {
        $adsCount = count($currentAds);
    }

    $keysOfCurrentAds = array_keys($currentAds);
    // echo "<pre>";
    // echo "<br> adsCount ";
    // print_r($adsCount);
    // echo "<br> currentAds <br>";
    // print_r($currentAds);
    $keysOfCurrentAds = array_keys($currentAds);
    foreach ($currentAds as $key=>$currentAd) {
        if ($random_key == $key) {
            if (array_key_exists(($random_key+1), $currentAds)) {
                $block->setSessionVal(($random_key+1));
            } else {
                $block->setSessionVal(0);
            }        
        }
    }
    // echo "<br> Praveen <br>";
    // print_r($block->getPosition());
    // print_r(get_class($block));
    // print_r(get_class_methods($block));
    // print_r($currentAds);
    // echo "<br> valid";
    // print_r($block->getValidDays()); 
    // echo "<br>";
    // print_r($block->getSellerIds());
    // // print_r(var_dump($adsCount));
    // print_r($random_key);
    // die("<br> developer is working _praveen"); 
    $isOccupiedMessage = '';
    /*if ($adsCount > 0 ) {
        $isOccupiedMessage = __("this ad is already booked");
    } else {
        $isOccupiedMessage = __("this ad is open to book");
    }*/
    if (!$block->isAdsDemoEnabled()) {

        if ($adsCount > 0) {
             foreach ($currentAds as $key=>$currentAd) {

                $currentId = $currentAd['id'];
                $content = $block->getAdContent($currentId);
                $blockStoreId = $block->getBlockStoreId($currentId);
                 if ($random_key == $key) {
                    if ($content == 4) {
                        $html = "<div class='mis-category-page-html' style='width:100%;'>
                                    <a href=".$currentAd['url'].">".$currentAd['image_name']."</a></div>";
                    } else {
                        if ($isAdminAd == 1) {
                            if ($currentAd['store_id'] == 'All Store') {
                                $store = 0;
                            }
                            $html = "<div class=''><a href= ".$currentAd['url']."><img style='width:100%' src=".$block->getMediaUrl().'webkul/MpAdvertisementManager/'.$currentAd['seller_id'].'/'.$store.'/'.$currentAd['id'].'/'.$currentAd['image_name']."></a></div>";                                   
                        } else {
                            $html = "<div class=''><a href= ".$currentAd['url']."><img style='width:100%' src=".$block->getMediaUrl().'webkul/MpAdvertisementManager/'.$currentAd['seller_id'].'/'/*.$store.'/'*/.$currentAd['id'].'/'.$currentAd['image_name']."></a></div>";
                        }
                    }

                    if (array_key_exists(($random_key+1), $currentAds)) {
                        $block->setSessionVal(($random_key+1));
                    } else {
                        $block->setSessionVal(0);
                    } 
                }
             }
        }

    } else {
        $html = '<div class="single-ad-container-demo">
        <div class="single-ad-demo">
            <div class="ads-demo-title"><h2>'.$block->getPositionLabel().'</h2></div>
            <div class="ads-demo-sub-title"><h3>'. __("1000x500").'</h3></div>
            <span class="ads-demo-text">'.$isOccupiedMessage.'</span>
        </div>
    </div>';
    }
    
?>
<style type="text/css">
    .ads-demo-sub-title {
        color: #A9A9A9;
    }
</style>
<script id="ads-popup-html" type="text/x-magento-template">
   <?php echo $html; ?>
</script>

<script type="text/x-magento-init">
    {
        "*":{
            "adsPopup":{}
        }
    }
</script>
