<?php
$shipping_address_title = __('Shipping Address');
$shipping_methods_title = __('Shipping Methods');
$payment_methods_title = __('Payment Methods');
$choose_payment_method_msg = __('Please choose a payment method!');
$place_order_now = __('Place Order Now');
$order_summary = __('Order Summary');
$new_address_title = __('New Address');
$next_title = __('Next');
$no_quote_available_title = __('Sorry, no quotes are available for this order at this time');
$apply_discount_code_title = __('Apply Discount Code');
$apply_discount_title = __('Apply Discount');
$cancel_coupon_title = __('Cancel coupon');

$email_address = __('- Email Address');
$password = __('- Password');
$login = __('- Login');
$forgot_password = __('- Forgot Your Password?');
$create_account_message = __('- You can create an account after checkout.');
$already_have_account_message = __('- You already have an account with us. Sign in or continue as guest.');
?>
<script type="text/javascript">
    window.shipping_address_title = "<?php echo $shipping_address_title; ?>";
    window.shipping_methods_title = "<?php echo $shipping_methods_title; ?>";
    window.payment_methods_title = "<?php echo $payment_methods_title; ?>";
    window.choose_payment_method_msg = "<?php echo $choose_payment_method_msg; ?>";
    window.place_order_now = "<?php echo $place_order_now; ?>";
    window.order_summary = "<?php echo $order_summary; ?>";
    window.new_address_title = "<?php echo $new_address_title; ?>";
    window.next_title = "<?php echo $next_title; ?>";
    window.no_quote_available_title = "<?php echo $no_quote_available_title; ?>";
    window.apply_discount_code_title = "<?php echo $apply_discount_code_title; ?>";
    window.apply_discount_title = "<?php echo $apply_discount_title; ?>";
    window.cancel_coupon_title = "<?php echo $cancel_coupon_title; ?>";
    /* ---- */
    window.email_address = "<?php echo $email_address; ?>";
    window.password = "<?php echo $password; ?>";
    window.login = "<?php echo $login; ?>";
    window.forgot_password = "<?php echo $forgot_password; ?>";
    window.create_account_message = "<?php echo $create_account_message; ?>";
    window.already_have_account_message = "<?php echo $already_have_account_message; ?>";
    console.log("email_address: "+window.email_address+" password: "+window.password+" login: "+window.login+" forgot_password: "+window.forgot_password+" create_account_message: "+window.create_account_message+" already_have_account_message: "+window.already_have_account_message);
    /* ---- */
</script>