<style type="text/css">
.dispatch-order-printslip .block-order-details-view .box .box-content {
    min-height: auto;
    border-radius: 0 0 5px 5px;
}
.signature_div {
    margin-top: 50px;
}

.signature_div span.sign-text {
    margin-left: 15%;
}
</style>
<?php
/**
 * Mangoit Software.
 *
 * @category  Mangoit
 * @package   Webkul_Orderdispatch
 * @author    Mangoit
 */
$helper = $this->helper('Webkul\Marketplace\Helper\Data');
$orderHelper = $this->helper('Webkul\Marketplace\Helper\Orders');
$misHelper = $this->helper('Mangoit\Orderdispatch\Helper\Data');
$isPartner = $helper->isSeller();
if($isPartner == 1){
    $order_id = $this->getRequest()->getParam('id');
    $order = $block->Order->load($order_id);
    $orderStatusLabel = $order->getStatusLabel();
    $paymentCode = '';
    $payment_method = '';
    if($order->getPayment()){
        $paymentCode = $order->getPayment()->getMethod();
        $payment_method = $order->getPayment()->getMethodInstance()->getTitle();
    }

    $marketplace_orders = $block->getSellerOrderInfo($order_id);
    if(count($marketplace_orders)){
        $tracking=$orderHelper->getOrderinfo($order_id);
        if($tracking!="" && $paymentCode == 'mpcashondelivery'){
            $codcharges=$tracking->getCodCharges();
        }
        $is_canceled=$tracking->getIsCanceled();
        if($is_canceled){
            $orderStatusLabel='Canceled';
        }
        ?>
<!--  -->
<?php 
$htmlPdf = '<div id="mis_delivery_note">
    <h1 class="page-title">
        <span data-ui-id="page-title-wrapper" class="base">
            '.  __("#%1", $order->getIncrementId()) .'
        </span>
    </h1>
</div>
<div>
    <p>
        '. __("Date: ").'
        <span>'.date("d.m.Y").'</span>
    </p>
</div>';
?>
<div id="mis_delivery_note">
    <h1 class="page-title">
        <span data-ui-id="page-title-wrapper" class="base">
            <?php echo __('#%1', $order->getIncrementId()) ?>
        </span>
    </h1>
</div>
<div>
    <p>
        <?php echo __('Date: ');?>
        <span><?php echo date("d.m.y") ?></span>
    </p>
</div>
<?php
$vendorName = "";
$vendorContactNumber = "";
$vendorCompanyLocality = "";
$vendorId = "";
$vendorShippingDescription = "";
$paymentMethod = "";
$tableBodyContent = "";

/*echo "<br>";
var_dump($helper->getSellerProfileDisplayFlag());
echo "<br>";
var_dump($block->isOrderCanShip($order));*/
?>
<div class="block block-order-details-view">
    <div class="block-content">
        <?php if ($helper->getSellerProfileDisplayFlag()) { ?>
        <?php if ($block->isOrderCanShip($order) || true): ?>
        <div class="box box-order-shipping-method">
            <strong class="box-title">
                <span>
                    <?php echo __('Vendor Details') ?>
                </span>
            </strong>
            <div class="box-content">
                <div class="mis_seller_info">
                    <?php $vendorData =  $misHelper->getVendorDetails(); ?>
                    <div class="mis_vendor_contact">
                        <label>
                            <?php echo __('Name: '); ?>
                        </label>
                        <span>
                            <?php 
                                $vendorName = $misHelper->getVendorName()->getName();
                                echo $misHelper->getVendorName()->getName();
                            ?>
                        </span>
                    </div>
                    <?php if (!empty($vendorData->getContactNumber())): ?>
                    <div class="mis_vendor_contact">
                        <label>
                            <?php echo __('Contact Number: '); ?>
                        </label>
                        <span>
                            <?php 
                                $vendorContactNumber = $vendorData->getContactNumber();
                                echo $vendorData->getContactNumber();    
                            ?>
                        </span>
                    </div>
                    <?php endif; ?>
                    <?php if (!empty($vendorData->getCompanyLocality())): ?>
                    <div class="mis_vendor_contact">
                        <label>
                            <?php echo __('Address: '); ?>
                        </label>
                        <span>
                            <?php 
                                $vendorCompanyLocality = $vendorData->getCompanyLocality();
                                echo $vendorData->getCompanyLocality();
                            ?>
                        </span>
                    </div>
                    <?php endif; ?>
                    <?php if (!empty($vendorData->getSellerId())): ?>
                    <div class="mis_vendor_contact">
                        <label>
                            <?php echo __('Seller Id: '); ?>
                        </label>
                        <span>
                            <?php 
                                $vendorId = $vendorData->getSellerId();
                                echo $vendorData->getSellerId();
                            ?>
                        </span>
                    </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <div class="block-title">
            <strong>
                <?php echo __('Order Information') ?>
            </strong>
        </div>
        <div class="box box-order-shipping-method">
            <strong class="box-title">
                <span>
                    <?php echo __('Shipping Method') ?>
                </span>
            </strong>
            <div class="box-content">
                <?php if ($order->getShippingDescription()): ?>
                <?php 
                    $vendorShippingDescription = $block->escapeHtml($order->getShippingDescription());
                    echo $block->escapeHtml($order->getShippingDescription());
                ?>
                <?php else: ?>
                <?php 
                    $vendorShippingDescription = __('No shipping information available');
                    echo __('No shipping information available'); 
                ?>
                <?php endif; ?>
            </div>
        </div>
        <?php endif; ?>
        <?php } ?>
    </div>
</div>
<div class="wk_mp_design">
    <div class="fieldset wk_mp_fieldset" id="wk_mp_print_order">
        <div class="order-details-items ordered">
            <div class="order-title">
                <strong>
                    <?php echo __('Items Ordered') ?>
                </strong>
            </div>
            <div class="table-wrapper order-items">
                <table class="data table table-order-items" id="my-orders-table" summary="
                    <?php echo __('Items Ordered') ?>">
                    <caption class="table-caption">
                        <?php echo __('Items Ordered') ?>
                    </caption>
                    <thead>
                        <tr>
                            <th class="col name">
                                <?php echo __('Product Name') ?>
                            </th>
                            <th class="col sku">
                                <?php echo __('SKU') ?>
                            </th>

                            <th class="col dimension" data-th="
                                <?php echo __('Dimension'); ?>">
                                <?php echo __('Dimension'); ?>
                            </th>
                            <th class="col weight" data-th="
                                <?php echo __('Weight'); ?>">
                                <?php echo __('Weight'); ?>
                            </th>
                            <th class="col price">
                                <?php echo __('Price') ?>
                            </th>
                            <th class="col qty">
                                <?php echo __('Qty') ?>
                            </th>
                            <th class="col price">
                                <?php echo __('Total Price') ?>
                            </th>
                            <?php
                            if($paymentCode == 'mpcashondelivery'){?>
                            <th class="col price">
                                <?php 
                                    $paymentMethod = __('COD Charges');
                                    echo __('COD Charges');
                                ?>
                            </th>
                            <?php } ?>
                            <th class="col price">
                                <?php 
                                    $paymentMethod = __('Subtotal'); 
                                    echo __('Subtotal');
                                ?>
                            </th>
                        </tr>
                    </thead>
                    <?php
                            $_items = $order->getItemsCollection();
                            $i = 0;
                            $_count = $_items->count();
                            $subtotal = 0;
                            $vendor_subtotal =0;
                            $totaltax = 0;
                            $admin_subtotal =0;
                            $shippingamount = 0;
                            $couponamount = 0;
                            $codcharges_total = 0;
                            foreach ($_items as $_item){
                                if ($_item->getParentItem()) {
                                    continue;
                                }
                                $row_total = 0;
                                $available_seller_item = 0;
                                $shippingcharges = 0;
                                $couponcharges = 0;
                                $itemPrice = 0;
                                $seller_item_cost = 0;
                                $totaltax_peritem = 0;
                                $codcharges_peritem = 0;
                                $seller_item_commission = 0;
                                $orderid = $order_id;
                                $seller_orderslist = $block->getSellerOrdersList($orderid,$_item->getProductId(),$_item->getItemId());
                                foreach($seller_orderslist as $seller_item){
                                    $parentitem_falg = 0;
                                    $available_seller_item = 1;
                                    $totalamount = $seller_item->getTotalAmount();
                                    $seller_item_cost = $seller_item->getActualSellerAmount();
                                    $seller_item_commission = $seller_item->getTotalCommission();
                                    $shippingcharges = $seller_item->getShippingCharges();
                                    $couponcharges = $seller_item->getAppliedCouponAmount();
                                    $itemPrice = $seller_item->getMageproPrice();
                                    $totaltax_peritem = $seller_item->getTotalTax();
                                    if($paymentCode=='mpcashondelivery'){
                                        $codcharges_peritem = $seller_item->getCodCharges();
                                    }
                                }
                                if($available_seller_item == 1){
                                    $i++;
                                    $seller_item_qty = $_item->getQtyOrdered();
                                    $row_total=$itemPrice*$seller_item_qty;

                                    $vendor_subtotal=$vendor_subtotal+$seller_item_cost;
                                    $subtotal=$subtotal+$row_total;
                                    $admin_subtotal = $admin_subtotal +$seller_item_commission;
                                    $totaltax=$totaltax+$totaltax_peritem;
                                    $codcharges_total=$codcharges_total+$codcharges_peritem;
                                    $shippingamount = $shippingamount+$shippingcharges;
                                    $couponamount = $couponamount+$couponcharges;

                                    $result = array();
                                    if ($options = $_item->getProductOptions()) {
                                        if (isset($options['options'])) {
                                            $result = array_merge($result, $options['options']);
                                        }
                                        if (isset($options['additional_options'])) {
                                            $result = array_merge($result, $options['additional_options']);
                                        }
                                        if (isset($options['attributes_info'])) {
                                            $result = array_merge($result, $options['attributes_info']);
                                        }
                                    }
                                    // for bundle product
                                    $bundleitems = array_merge(array($_item), $_item->getChildrenItems());
                                    $_count = count ($bundleitems);
                                    $_index = 0;
                                    $_prevOptionId = '';
                                    ?>
                    <tbody>
                        <?php
                        $dimension = $misHelper->getProductDimension($_item->getProductId());
                        $table_rows = "";
                        if($_item->getProductType()!='bundle'){ ?>

                        <tr class="border" id="order-item-row-
                            <?php echo $_item->getId() ?>">
                            <?php
                                                if($_item->getProductType()=='downloadable'){ ?>
                            <td class="col name" data-th="
                                <?php echo $block->escapeHtml(__('Product Name')); ?>">
                                <strong class="product name product-item-name">
                                    <?php echo $block->escapeHtml($_item->getName()) ?>
                                </strong>
                                <?php if ($_options = $block->getItemOptions()): ?>
                                <dl class="item-options links">
                                    <?php foreach ($_options as $_option) : ?>
                                    <dt>
                                        <?php echo $block->escapeHtml($_option['label']) ?>
                                    </dt>
                                    <?php if (!$block->getPrintStatus()): ?>
                                    <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                                    <dd>
                                        <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                        <?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?>
                                        <?php else: ?>
                                        <?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
                                        <?php endif; ?>
                                    </dd>
                                    <?php else: ?>
                                    <dd>
                                        <?php echo $block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value'])) ?>
                                    </dd>
                                    <?php endif; ?>
                                    <?php endforeach; ?>
                                </dl>
                                <?php endif; ?>
                                <?php /* downloadable */?>
                                <?php if ($links = $block->getDownloadableLinks($_item->getId())): ?>
                                <dl class="item-options links">
                                    <dt>
                                        <?php /* @escapeNotVerified */ echo $block->getLinksTitle($_item->getId()) ?>
                                    </dt>
                                    <?php foreach ($links->getPurchasedItems() as $link): ?>
                                    <dd>
                                        <?php echo $block->escapeHtml($link->getLinkTitle()); ?>
                                    </dd>
                                    <?php endforeach; ?>
                                </dl>
                                <?php endif; ?>
                                <?php /* EOF downloadable */?>
                                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                                <?php if ($addInfoBlock) :?>
                                <?php echo $addInfoBlock->setItem($_item->getOrderItem())->toHtml(); ?>
                                <?php endif; ?>
                                <?php echo $block->escapeHtml($_item->getDescription()) ?>
                            </td>
                            <?php }else{ ?>
                            <td class="col name" data-th="
                                <?php echo $block->escapeHtml(__('Product Name')); ?>">
                                <strong class="product name product-item-name">
                                    <?php echo $block->escapeHtml($_item->getName()) ?>
                                </strong>
                                <?php if($_options = $result): ?>
                                <dl class="item-options">
                                    <?php foreach ($_options as $_option) : ?>
                                    <dt>
                                        <?php echo $block->escapeHtml($_option['label']) ?>
                                    </dt>
                                    <?php if (!$block->getPrintStatus()): ?>
                                    <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                                    <dd>
                                        <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                        <?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?>
                                        <?php else: ?>
                                        <?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
                                        <?php endif; ?>
                                    </dd>
                                    <?php else: ?>
                                    <dd>
                                        <?php echo nl2br($block->escapeHtml( (isset($_option['print_value']) ? $_option['print_value'] : $_option['value']) )) ?>
                                    </dd>
                                    <?php endif; ?>
                                    <?php endforeach; ?>
                                </dl>
                                <?php endif; ?>
                            </td>
                            <?php }?>
                            <td class="col sku" data-th="
                                <?php echo $block->escapeHtml(__('SKU')); ?>">
                                <?php echo $_item->getSku() ?>
                            </td>
                            <td class="col dimension" data-th="
                                <?php echo $block->escapeHtml(__('Dimension')); ?>">
                                <?php echo $dimension; ?>
                            </td>
                            <td class="col weight" data-th="
                                <?php echo $block->escapeHtml(__('Weight')); ?>">
                                <?php echo $_item->getWeight(); ?>
                            </td>
                            <td class="col price" data-th="
                                <?php echo $block->escapeHtml(__('Price')); ?>">
                                <span class="price-excluding-tax" data-label="
                                    <?php echo $block->escapeHtml(__('Excl. Tax')); ?>">
                                    <span class="cart-price">
                                        <?php echo $order->formatPrice($_item->getPrice()); ?>
                                    </span>
                                </span>
                            </td>
                            <td class="col qty" data-th="
                                <?php echo $block->escapeHtml(__('Qty')); ?>">
                                <ul class="items-qty">
                                    <?php if ($_item->getQtyOrdered() > 0): ?>
                                    <li class="item">
                                        <span class="title">
                                            <?php echo __('Ordered'); ?>
                                        </span>
                                        <span class="content">
                                            <?php echo $_item->getQtyOrdered()*1 ?>
                                        </span>
                                    </li>
                                    <?php endif; ?>
                                    <?php if ($_item->getQtyInvoiced() > 0): ?>
                                    <li class="item">
                                        <span class="title">
                                            <?php echo __('Invoiced'); ?>
                                        </span>
                                        <span class="content">
                                            <?php echo $_item->getQtyInvoiced()*1 ?>
                                        </span>
                                    </li>
                                    <?php endif; ?>
                                    <?php if ($_item->getQtyShipped() > 0): ?>
                                    <li class="item">
                                        <span class="title">
                                            <?php echo __('Shipped'); ?>
                                        </span>
                                        <span class="content">
                                            <?php echo $_item->getQtyShipped()*1 ?>
                                        </span>
                                    </li>
                                    <?php endif; ?>
                                    <?php if ($_item->getQtyCanceled() > 0): ?>
                                    <li class="item">
                                        <span class="title">
                                            <?php echo __('Canceled'); ?>
                                        </span>
                                        <span class="content">
                                            <?php echo $_item->getQtyCanceled()*1 ?>
                                        </span>
                                    </li>
                                    <?php endif; ?>
                                    <?php if ($_item->getQtyRefunded() > 0): ?>
                                    <li class="item">
                                        <span class="title">
                                            <?php echo __('Refunded'); ?>
                                        </span>
                                        <span class="content">
                                            <?php echo $_item->getQtyRefunded()*1 ?>
                                        </span>
                                    </li>
                                    <?php endif; ?>
                                </ul>
                            </td>
                            <td class="col price" data-th="
                                <?php echo $block->escapeHtml(__('Total Price')); ?>">
                                <?php echo $order->formatPrice($block->getOrderedPricebyorder($order, $row_total));?>
                            </td>
                            <?php
                                                if($paymentCode == 'mpcashondelivery'){?>
                            <td class="col price" data-th="
                                <?php echo $block->escapeHtml(__('COD Charges')) ?>">
                                <?php echo $order->formatPrice($block->getOrderedPricebyorder($order, $codcharges_peritem));?>
                            </td>
                            <?php } ?>
                            <td class="col subtotal" data-th="
                                <?php echo $block->escapeHtml(__('Subtotal')); ?>">
                                <?php echo $order->formatPrice($block->getOrderedPricebyorder($order, $row_total));?>
                            </td>
                        </tr>
                        <?php }else{ ?>
                        <?php foreach ($bundleitems as $_bundleitem): ?>
                        <?php $attributes_option = $block->getSelectionAttribute($_bundleitem); ?>
                        <?php if ($_bundleitem->getParentItem()): ?>
                        <?php $attributes = $attributes_option ?>
                        <?php if ($_prevOptionId != $attributes['option_id']): ?>
                        <tr class="options-label">
                            <td class="col label" colspan="8" data-th="
                                <?php echo $block->escapeHtml(__('Product Name')); ?>">
                                <?php echo $attributes['option_label'] ?>
                            </td>
                        </tr>
                        <?php $_prevOptionId = $attributes['option_id'] ?>
                        <?php endif; ?>
                        <?php endif; ?>
                        <tr
                            <?php echo (++$_index==$_count)?' class="border bundle"':' class="bundle"' ?> id="order-item-row-
                            <?php echo $_bundleitem->getId() ?>">
                            <?php 
                                                    if (!$_bundleitem->getParentItem()){?>
                            <td>
                                <h3 class="product-name">
                                    <?php echo $block->escapeHtml($_bundleitem->getName()) ?>
                                </h3>
                            </td>
                            <td class="col sku" data-th="
                                <?php echo $block->escapeHtml(__('SKU')); ?>">
                                <?php echo $_bundleitem->getSku() ?>
                            </td>
                            <td class="col price" data-rwd-label="
                                <?php echo __('Price') ?>">
                                <span class="price-excluding-tax" data-label="
                                    <?php echo $block->escapeHtml(__('Excl. Tax')); ?>">
                                    <?php echo $order->formatPrice($_item->getPrice());?>
                                </span>
                            </td>
                            <td class="col qty item_status" data-rwd-label="
                                <?php echo __('Status') ?>">
                                <ul class="items-qty">
                                    <?php if ($_item->getQtyOrdered() > 0): ?>
                                    <li class="item">
                                        <span class="title">
                                            <?php echo __('Ordered'); ?>
                                        </span>
                                        <span class="content">
                                            <?php echo $_item->getQtyOrdered()*1 ?>
                                        </span>
                                    </li>
                                    <?php endif; ?>
                                </ul>
                            </td>
                            <td class="lin-hide">&nbsp;</td>
                            <td class="lin-hide">&nbsp;</td>
                            <td class="lin-hide">&nbsp;</td>
                            <td class="lin-hide">&nbsp;</td>
                            <?php
                                                    } else { ?>
                            <?php
                                                        $row_total = 0;
                                                        $available_seller_item = 0;
                                                        $shippingcharges = 0;
                                                        $couponcharges = 0;
                                                        $itemPrice = 0;
                                                        $seller_item_cost = 0;
                                                        $totaltax_peritem = 0;
                                                        $codcharges_peritem = 0;
                                                        $seller_item_commission = 0;
                                                        $orderid = $order_id;
                                                        $seller_orderslist = $block->getSellerOrdersList(
                                                            $orderid, $_bundleitem->getProductId(), $_bundleitem->getItemId()
                                                        );
                                                        foreach($seller_orderslist as $seller_item){
                                                            $parentitem_falg = 0;
                                                            $available_seller_item = 1;
                                                            $totalamount = $seller_item->getTotalAmount();
                                                            $seller_item_cost = $seller_item->getActualSellerAmount();
                                                            $seller_item_commission = $seller_item->getTotalCommission();
                                                            $shippingcharges = $seller_item->getShippingCharges();
                                                            $couponcharges = $seller_item->getAppliedCouponAmount();
                                                            $itemPrice = $seller_item->getMageproPrice();
                                                            $totaltax_peritem = $seller_item->getTotalTax();
                                                            if($paymentCode=='mpcashondelivery'){
                                                                $codcharges_peritem = $seller_item->getCodCharges();
                                                            }
                                                        }
                                                        $i++;
                                                        $seller_item_qty = $_bundleitem->getQtyOrdered();
                                                        $row_total=$itemPrice*$seller_item_qty;
                                                        $vendor_subtotal=$vendor_subtotal+$seller_item_cost;
                                                        $subtotal=$subtotal+$row_total;
                                                        $admin_subtotal = $admin_subtotal +$seller_item_commission;
                                                        $totaltax=$totaltax+$totaltax_peritem;
                                                        $codcharges_total=$codcharges_total+$codcharges_peritem;
                                                        $shippingamount = $shippingamount+$shippingcharges;
                                                        $couponamount = $couponamount+$couponcharges;
                                                        ?>
                            <td class="col value" data-th="
                                <?php echo $block->escapeHtml(__('Product Name')); ?>">
                                <?php echo $block->getValueHtml($_bundleitem)?>
                                <?php $addInfoBlock = $block->getOrderItemAdditionalInfoBlock(); ?>
                                <?php if ($addInfoBlock): ?>
                                <?php echo $addInfoBlock->setItem($_bundleitem)->toHtml() ?>
                                <?php endif;?>
                            </td>
                            <td class="col sku" data-th="
                                <?php echo $block->escapeHtml(__('SKU')); ?>">
                                <?php echo $_bundleitem->getSku() ?>
                            </td>
                            <td class="col price" data-rwd-label="
                                <?php echo __('Price') ?>">
                                <?php echo $order->formatPrice($_bundleitem->getPrice());?>
                            </td>
                            <td class="col qty item_status" data-rwd-label="
                                <?php echo __('Status') ?>">
                                <ul class="items-qty">
                                    <?php if ($_bundleitem->getQtyOrdered() > 0): ?>
                                    <li class="item">
                                        <span class="title">
                                            <?php echo __('Ordered'); ?>
                                        </span>
                                        <span class="content">
                                            <?php echo $_bundleitem->getQtyOrdered()*1 ?>
                                        </span>
                                    </li>
                                    <?php endif; ?>
                                    <?php if ($_bundleitem->getQtyInvoiced() > 0): ?>
                                    <li class="item">
                                        <span class="title">
                                            <?php echo __('Invoiced'); ?>
                                        </span>
                                        <span class="content">
                                            <?php echo $_bundleitem->getQtyInvoiced()*1 ?>
                                        </span>
                                    </li>
                                    <?php endif; ?>
                                    <?php if ($_bundleitem->getQtyShipped() > 0 && !$block->isShipmentSeparately()): ?>
                                    <li class="item">
                                        <span class="title">
                                            <?php echo __('Shipped'); ?>
                                        </span>
                                        <span class="content">
                                            <?php echo $_bundleitem->getQtyShipped()*1 ?>
                                        </span>
                                    </li>
                                    <?php endif; ?>
                                    <?php if ($_bundleitem->getQtyCanceled() > 0): ?>
                                    <li class="item">
                                        <span class="title">
                                            <?php echo __('Canceled'); ?>
                                        </span>
                                        <span class="content">
                                            <?php echo $_bundleitem->getQtyCanceled()*1 ?>
                                        </span>
                                    </li>
                                    <?php endif; ?>
                                    <?php if ($_bundleitem->getQtyRefunded() > 0): ?>
                                    <li class="item">
                                        <span class="title">
                                            <?php echo __('Refunded'); ?>
                                        </span>
                                        <span class="content">
                                            <?php echo $_bundleitem->getQtyRefunded()*1 ?>
                                        </span>
                                    </li>
                                    <?php endif; ?>
                                </ul>
                            </td>
                            <td class="col price" data-th="
                                <?php echo $block->escapeHtml(__('Total Price')); ?>">
                                <?php echo $order->formatPrice($block->getOrderedPricebyorder($order, $row_total));?>
                            </td>
                            <?php
                                                        if($paymentCode == 'mpcashondelivery'){?>
                            <td class="col price" data-th="
                                <?php echo $block->escapeHtml(__('COD Charges')) ?>">
                                <?php echo $order->formatPrice($block->getOrderedPricebyorder($order, $codcharges_peritem));?>
                            </td>
                            <?php
                                                        } ?>
                            <?php /*
                            <td class="col price" data-th="
                                <?php echo $block->escapeHtml(__('Admin Commission')); ?>">
                                <?php echo $order->formatPrice($block->getOrderedPricebyorder($order, $seller_item_commission));?>
                            </td>
                            <td class="col price" data-th="
                                <?php echo $block->escapeHtml(__('Vendor Total')); ?>">
                                <?php echo $order->formatPrice($block->getOrderedPricebyorder($order, $seller_item_cost));?>
                            </td> */?>
                            <td class="col subtotal" data-th="
                                <?php echo $block->escapeHtml(__('Subtotal')); ?>">
                                <?php echo $order->formatPrice($block->getOrderedPricebyorder($order, $row_total));?>
                            </td>
                            <?php
                                                    }?>
                        </tr>
                        <?php endforeach; ?>
                        <?php
                                        }?>
                    </tbody>
                    <?php
                                }
                            }?>
                    <?php
                            $refundedShippingAmount = 0;
                            $totalCouponAmount = 0;
                            $totalTaxAmount = 0;
                            $taxToSeller = $helper->getConfigTaxManage();
                            foreach($marketplace_orders as $tracking){
                                $shippingamount=$tracking->getShippingCharges();
                                $totalCouponAmount=$tracking->getCouponAmount();
                                $totalTaxAmount=$tracking->getTotalTax();
                                $refundedShippingAmount=$tracking->getRefundedShippingCharges();
                                $taxToSeller=$tracking['tax_to_seller'];
                            }
                            if($paymentCode == 'mpcashondelivery'){
                                $count_td = 8;
                            }else{
                                $count_td = 7;
                            } ?>
                </table>
            </div>
        </div>
        <?php if ($helper->getSellerProfileDisplayFlag()) { ?>
        <div class="block block-order-details-view">
            <div class="block-title">
                <strong>
                    <?php echo __('Buyer Information') ?>
                </strong>
            </div>
            <div class="block-content">
                <div class="box-content">
                    <div class="box">
                        <div class="wk_row">
                            <span class="label">
                                <?php echo __('Customer Name')?> : 
                            </span>
                            <span class="value">
                                <?php echo $order->getCustomerName(); ?>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php } ?>
        <hr>
            <div class="enclose_div">
                <span style="display: inherit;">
                    <?php echo __('I hereby confirm that I enclose the packing slip with the package to myGermany.'); ?>
                </span>
                <span style="display: inherit;">
                    <?php echo __('I hereby confirm that the package contains exactly the items that were ordered.In case of wrongly delivered goods, additional costs may be incurred (AGB).'); ?>
                </span>
            </div>
            <div class="signature_div">
                <span>
                    <?php echo __('----------------------------------------------------------------------------  '); ?>
                </span>
                <span class="sign-text">
                    <?php echo __('Signature'); ?>
                </span>
            </div>
        </div>
    </div>
    <?php
    }
}?>
    <script type="text/javascript">
        /*<![CDATA[
     require([
        'jquery',
        'jquery/ui',
        'jquery/validate',
        'mage/validation'
        ], function($){ 
     });*/
</script>

<?php 



/*$htmlSlip = $this->getLayout()->createBlock('Mangoit\Orderdispatch\Block\Printslip')->setTemplate("Mangoit_Orderdispatch::printslip.phtml")->toHtml();
echo $htmlSlip;
*/

$packagePdfHelper = $this->helper('Mangoit\Orderdispatch\Helper\PackagingSlip');
$packagePdfHelper->generatePdfSlip('
<!DOCTYPE html>
<html>
<head>
<title> PDF testing</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="content-type" content="text/html; charset=utf-8">
<meta name="keywords" content="">
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
.box {
    width: 100%;
    box-sizing: border-box;
}
.block-order-details-view .block-content .box {
    margin-bottom: 30px;
}
.enclose_div{ margin-top: 20px; margin-bottom: 20px;}
.buyer_info{ margin-top: 20px; margin-bottom: 20px;}
#wk_mp_print_order .order-details-items {  padding:0px;  border:none; border-spacing: 0;
    border-collapse: collapse;}
.box-title {
    display: block;
}
.product-item-name, .product.name a {
    font-weight: 400;
}
.abs-margin-for-blocks-and-widgets-desktop, .page-main .block, .customer-review .product-details {
    margin-bottom: 0 !important;
}
.block .block-title {
    color: #222;
}
.block .block-title {
    margin: 5px 0 10px;
    line-height: 1.2;
    font-size: 16px;
}
.block-order-details-view .block-title {
    padding: 0 10px;
}
 ul {
  list-style-type: none;
 }
.table-caption{ margin-bottom: 10px;}
.block-order-details-view .box .box-content { box-sizing: border-box; }
</style>
</head>
<body style="margin: auto; background:#FFF;font-family:Arial">
'.$htmlPdf.'
<div class="block block-order-details-view">
    <div class="block-content">
        <div class="box box-order-shipping-method">
            <strong class="box-title">
                <span>
                    '. __("Vendor Details") .'
                </span>
            </strong>
            <div class="box-content">
                <div class="mis_seller_info">
                    <div class="mis_vendor_contact">
                        <label>
                            '. __("Name: ") .'
                        </label>
                        <span>
                            '. $vendorName .'
                        </span>
                    </div>
                    <div class="mis_vendor_contact">
                        <label>
                            '. __("Contact Number: ") .'
                        </label>
                        <span>
                            '. $vendorContactNumber .'
                        </span>
                    </div>
                    <div class="mis_vendor_contact">
                        <label>
                            '. __("Address: ") .'
                        </label>
                        <span>
                            '. $vendorCompanyLocality .'
                        </span>
                    </div>
                    <div class="mis_vendor_contact">
                        <label>
                            '. __("Seller Id: ") .'
                        </label>
                        <span>
                            '. $vendorId .'
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="box box-order-shipping-method">
            <strong class="box-title">
                <span>
                    '. __('Shipping Method') .'
                </span>
            </strong>
            <div class="box-content">
                '.$vendorShippingDescription.'
            </div>
        </div>
        <div class="box box-order-shipping-method">
            <strong class="box-title">
                <span>
                    '. __('Order Details') .'
                </span>
            </strong>
            <div class="box-content">
                <div class="mis_vendor_contact">
                    <label>
                        '. __("Tracking ID: ") .'
                    </label>
                    <span>
                        '. __('ABCD700125698'). '
                    </span>
                </div>
                <div class="mis_vendor_contact">
                    <label>
                        '. __("Order ID: ") .'
                    </label>
                    <span>
                        '. $order->getIncrementId() .'
                    </span>
                </div>
                <div class="mis_vendor_contact">
                    <label>
                        '. __("Internal Order ID: ") .'
                    </label>
                    <span>
                        '. 'life-ray-'.$order->getIncrementId() .'
                    </span>
                </div>
                <div class="mis_vendor_contact">
                    <label>
                        '. __("Barcode: ") .'
                    </label>
                    <span>
                        '. __('||||||||||||||||') .'
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="wk_mp_design">
    <div class="fieldset wk_mp_fieldset" id="wk_mp_print_order">
        <div class="order-details-items ordered">
            <div class="table-wrapper order-items">
                <table>
                    <caption class="table-caption">
                        '.__('Items Ordered').'
                    </caption>
                    <thead>
                        <tr>
                            <th class="col name">
                                '. __('Product Name') .'
                            </th>
                            <th class="col sku">
                                '. __('SKU') .'
                            </th>

                            <th class="col dimension" >
                                '. __('Dimension') .'
                            </th>
                            <th class="col weight">
                                '. __('Weight') .'
                            </th>
                            <th class="col price">
                                '. __('Price') .'
                            </th>
                            <th class="col qty">
                                '. __('Qty') .'
                            </th>
                            <th class="col price">
                                '. __('Total Price').'
                            </th>
                            <th class="col price">                                
                                '. $paymentMethod .'
                            </th>
                        </tr>
                    </thead>
                    '.$packagePdfHelper->getTableRows($order, $block, $order_id, $paymentCode, $misHelper).'
                </table>
            </div>
        </div>
        <div class="block buyer_info">
            <div class="block-title">
                <strong>
                    '.__('Buyer Information').'
                </strong>
            </div>
            <div class="block-content">
                <div class="box-content">
                    <div class="box">
                        <div class="wk_row">
                            <span class="label">
                                '.__('Customer Name').'
                            </span>: 
                            <span class="value">
                                '.$order->getCustomerName().'
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <hr>
            <div class="enclose_div">
                <span style="display: inherit;">
                    '. __('I hereby confirm that I enclose the packing slip with the package to myGermany.').'
                </span>
                <span style="display: inherit;">
                    '. __('I hereby confirm that the package contains exactly the items that were ordered.In case of wrongly delivered goods, additional costs may be incurred (AGB).') .'
                </span>
            </div>
            <div class="signature_div">
                <span>
                    '. __('----------------------------------------------------------------------------  ').'
                </span>
                <span class="sign-text">
                    '. __('Signature') .'
                </span>
            </div>
        </div>
    </div>
</div>    
</body>
', $vendorName, $order->getIncrementId(), $vendorId);

?>