<!-- Last updated 29-Jan-2019  -->
<?php ?>
<table class="data-table admin__table-secondary order-subtotal-table">
    <?php $_totals = $block->getTotals('footer')?>
    <?php
        if ($block->getOrder()->getShippingAddress()) {
        $countryId = $block->getOrder()->getShippingAddress()->getCountryId();
    } else {
        $countryId = 'DE';
    }
        $misMrketplaceHelper = $this->helper('Mangoit\Marketplace\Helper\Data');
        $euCountry = $misMrketplaceHelper->isEuCountry($countryId);
     ?>
    <?php if ($_totals):?>
        <tfoot>
            <?php foreach ($block->getTotals('footer') as $_code => $_total):  ?>
                <?php if ($_total->getBlockName()): ?>
                    <?= $block->getChildHtml($_total->getBlockName(), false) ?>
                <?php else:?>
                <tr class="col-<?= /* @escapeNotVerified */ $_code ?>">
                    <td <?= /* @escapeNotVerified */ $block->getLabelProperties() ?> class="label">
                        <strong><?= $block->escapeHtml($_total->getLabel()) ?></strong>
                        <?php if($_code ==  'grand_total' && ($euCountry)):?>
                            <span style="font-size: 10px;" class="mis_inclusive_label"><?php echo __(' incl. VAT');?></span>
                        <?php endif;?>
                    </td>
                    <td <?= /* @escapeNotVerified */ $block->getValueProperties() ?>>
                        <strong><?= /* @escapeNotVerified */ $block->formatValue($_total) ?></strong>
                    </td>
                </tr>
                <?php endif?>
            <?php endforeach?>
        </tfoot>
    <?php endif?>

    <?php $_totals = $block->getTotals('')?>
    <?php if ($_totals):?>
        <tbody>
            <?php foreach ($_totals as $_code => $_total): ?>
                <?php if ($_total->getBlockName()): ?>
                    <?= $block->getChildHtml($_total->getBlockName(), false) ?>
                <?php else:?>
                    <tr class="col-<?= /* @escapeNotVerified */ $_code ?> 47">
                        <td <?= /* @escapeNotVerified */ $block->getLabelProperties() ?> class="label">
                            <?php if ($_total->getStrong()):?>
                            <strong><?= $block->escapeHtml($_total->getLabel()) ?></strong>
                            <?php else:?>
                            <?= $block->escapeHtml($_total->getLabel()) ?>
                            <?php endif?>
                        </td>

                        <?php if ($_total->getStrong()):?>
                            <td <?= /* @escapeNotVerified */ $block->getValueProperties() ?>>
                                <strong><?= /* @escapeNotVerified */ $block->formatValue($_total) ?></strong>
                            </td>
                        <?php else:?>
                            <td <?= /* @escapeNotVerified */ $block->getValueProperties() ?>>
                                <span><?= /* @escapeNotVerified */ $block->formatValue($_total) ?></span>
                            </td>
                        <?php endif?>
                    </tr>
                <?php endif?>
            <?php endforeach?>
        </tbody>
    <?php endif?>
</table>
