<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpMassUpload
 * @author    Webkul
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

$helper = $this->helper("Webkul\MpMassUpload\Helper\Data");
$isPartner = $this->helper('Webkul\Marketplace\Helper\Data')->isSeller();
$getAllCustomAttributes = $helper->getAttributeDetails();
$wholeData = $this->helper("Webkul\MpMassUpload\Helper\Export")
            ->prepareFileColumnRow('simple', []);
?>
<?php if($isPartner == 1): ?>
    <style>
        th.wk-check-first-td, td.wk-check-first-td {
            width: 2%;
            text-align: center;
        }
    </style>
    <!-- Start : Export Proucts in file -->
    <form method="post" action="<?php echo $block->getUrl('mpmassupload/product/export'); ?>" id="wk_massupload_product_export_form" class="wk-massupload-container" enctype="multipart/form-data" data-mage-init='{"validation":{}}'>
        <fieldset class="fieldset">
            <?php echo $block->getBlockHtml('formkey') ?>
			<?php echo $block->getBlockHtml('seller.formkey')?>
            <legend class="legend">
                <span><?php echo __("Export Products (csv, Excel, XML, JSON file format)"); ?></span>
            </legend>
            <div class="field required">
                <label for="attribute_set" class="label">
                    <span><?php echo __("Select Product Type"); ?></span>
                </label>
                <div class="control">
                    <select data-validate="{'validate-select':true}" title="<?php echo __("Attribute Set"); ?>" class="required-entry" id="product_type" name="product_type" aria-required="true">
						<option value=''><?php echo __('Please Select') ?></option>
						<option value='simple'><?php echo __('Export Simple Products') ?></option>
						<option value='configurable'><?php echo __('Export Configurable Products') ?></option>
						<!-- <option value='virtual'><?php //echo __('Export Virtual Products') ?></option> -->
						<!-- <option value='downloadable'><?php //echo __('Export Downloadable Products') ?></option> -->
                    </select>
                </div>
            </div>
            <div class="field required">
                <label for="attribute_set" class="label">
                    <span><?php echo __("Export File Type"); ?></span>
                </label>
                <div class="control">
                    <select data-validate="{'validate-select':true}" title="<?php echo __("Export File Type"); ?>" class="required-entry" id="export_type" name="export_type" aria-required="true">
                        <option value=''><?php echo __('Please Select') ?></option>
                        <option value='Excel'><?php echo __('Excel') ?></option>
                        <option value='CSV'><?php echo __('CSV') ?></option>
                        <option value='JSON'><?php echo __('JSON') ?></option>
                        <option value='XML'><?php echo __('XML') ?></option>
                    </select>
                </div>
            <?php
            if (!empty($getAllCustomAttributes)) { ?>
                <div class="field">
                    <label for="attribute_set" class="label">
                        <span><?php echo __("Select Custom Attributes to export in file"); ?></span>
                    </label>
                    <div class="control">
                        <table cellspacing="0" class="border wk-mp-list-table wk-mp-list-container-table">
                            <thead>
                                <tr class="wk-content">
                                    <th class="wk-check-first-td">
                                        <span>
                                            <input type="checkbox" name="dataflow_profile_select_all" value="all" id="dataflow-profile-select-all"/>
                                        </span>
                                    </th>
                                    <th class="wk-first-td">
                                        <span class="label name">
                                            <?php echo __('Attribute Code')?>
                                        </span>
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 0;
                                $totalAttr = count($getAllCustomAttributes);
                                foreach ($getAllCustomAttributes as $id => $code) {
                                    $code = trim($code);
                                    if (!in_array($code, $wholeData)) {
                                        $i = $i+1; ?>
                                        <tr class="wk-row-view <?php echo $class = ($i == $totalAttr)? 'wk_last_tr':''?>">
                                            <td class="wk-check-first-td">
                                                <span>
                                                    <input type="checkbox" name="custom_attributes[]" value="<?php echo $code?>" class="mpcheckbox"/>
                                                </span>
                                            </td>
                                            <td class="wk-first-td">
                                                <input type="hidden" class="hidden_id" value="<?php echo $code; ?>" />
                                                <span class="label">
                                                    <?php echo $code; ?>
                                                </span>
                                            </td>
                                        </tr/>
                                        <?php
                                    }
                                } ?>
                      </table>
                    </div>
                </div>
            <?php } ?>
            <div>
                <button class="button wk-mp-btn" type="submit">
                    <span><span><?php echo __("Export"); ?></span></span>
                </button>                
            </div>
        </fieldset>
    </form><br/>
    <div class="buttons-set">
        <p class="back-link">
            <a href="javascript:;" onclick="javascript: window.history.back();" class="left">&laquo; <?php echo __('Back') ?></a>
        </p>
    </div>
    <script type="text/x-magento-init">
        {
            "*": {
                "dataflowprofile": {}
            }
        }
    </script>
    <!-- End : Export Products -->
<?php else: ?>
    <h2 class="wk-mp-error-msg">
        <?php echo __("To Become Seller Please Contact to Admin."); ?>
    </h2>
<?php endif; ?>
