<?php $_options = $this->getHeaderOptions(); ?>
<tr>
    <th class='data-grid-th'><?php echo __('Product');?></th>
    <?php if(!empty($_options)): ?>
        <?php foreach ($_options as $_option) :?>
            <th class='data-grid-th'><?php echo __($_option);?></th>
        <?php endforeach; ?>
    <?php endif; ?>
    <th class='data-grid-th'><?php echo __('Price');?></th>
    <th class='data-grid-th'><?php echo __('Purchase Order');?></th>
    <th class='data-grid-th'><?php echo __('Count In');?></th>
    <th class='data-grid-th'><?php echo __('Add');?></th>
    <th class='data-grid-th'><?php echo __('Total In');?></th>
    <th class='data-grid-th'><?php echo __('Comp');?></th>
    <th class='data-grid-th'><?php echo __('Count Out');?></th>
    <th class='data-grid-th'><?php echo __('Total Sold');?></th>
    <th class='data-grid-th'><?php echo __('Gross Sale');?></th>
</tr>