<style type="text/css">
.tooltip {
    position: relative;
    display: inline-block;
    opacity: inherit !important;
}
    
.tooltip .tooltiptext {
    visibility: hidden;
    width: 400px;
    background-color: #555;
    color: #fff;
    text-align: center;
    border-radius: 6px;
    padding: 5px 0;
    position: absolute;
    z-index: 1;
    bottom: 125%;
    left: 50%;
    margin-left: -60px;
    opacity: 0;
    transition: opacity 0.3s;
}

.tooltip .tooltiptext::after {
    content: "";
    position: absolute;
    top: 100%;
    left: 15%;
    margin-left: -5px;
    border-width: 5px;
    border-style: solid;
    border-color: #555 transparent transparent transparent;
}

.tooltip:hover .tooltiptext {
    visibility: visible;
    opacity: 1;
}
</style>
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* TESTING */
$misHelper = $this->helper('Mangoit\Marketplace\Helper\Data');

$tooltipHelper = $this->helper('Mangoit\MisTooltip\Helper\Data');
$imgHelper = $this->helper('Webkul\Marketplace\Helper\Data');
$section_id = 'my_account';
$marketplace_orders_status_tooltip_id = 'marketplace_orders_status';
$store_id = $tooltipHelper->getStoreId();
$orderBlockTooltip = $tooltipHelper->getToolTipData($store_id, $section_id, $marketplace_orders_status_tooltip_id);

?>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info') ?>
<?php if ($_orders && count($_orders)): ?>
    <?php 
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $customerSession = $objectManager->create('Magento\Customer\Model\Session');
        $customerId = $customerSession->getCustomerId();
        $model = $objectManager->create(
            'Webkul\Marketplace\Model\Seller'
        )->getCollection()
        ->addFieldToFilter('seller_id', $customerId);
        $sellerStatus = 0;
        foreach ($model as $value) {
            $sellerStatus = $value->getIsSeller();
        }
    ?>
    <div class="table-wrapper orders-history">
        <fieldset class="fieldset info wk-mp-fieldset">
            <legend class="legend">
                <span><?php echo __('Marketplace Orders & Status') ?></span>
            </legend>   
            <div >
            <?php if(count($orderBlockTooltip) > 0): ?>
                <?php echo ( (count($orderBlockTooltip) > 0) ? $orderBlockTooltip[0]['tooltip_text'] : '');?>
            <?php endif; ?>
            </div>
            <table class="data table table-order-items history" id="my-orders-table">
                <caption class="table-caption"><?= /* @escapeNotVerified */ __('Orders') ?></caption>
                <thead>
                    <tr>
                        <th scope="col" class="col id"><?= /* @escapeNotVerified */ __('Order #') ?></th>
                        <th scope="col" class="col date"><?= /* @escapeNotVerified */ __('Date') ?></th>
                        <?= /* @noEscape */ $block->getChildHtml('extra.column.header') ?>
                        <th scope="col" class="col shipping"><?= /* @escapeNotVerified */ __('Ship To') ?></th>
                        <th scope="col" class="col total"><?= /* @escapeNotVerified */ __('Order Total') ?></th>
                        <th scope="col" class="col status"><?= /* @escapeNotVerified */ __('Status') ?></th>
                        <th scope="col" class="col actions"><?= /* @escapeNotVerified */ __('Action') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($_orders as $_order): ?>
                        <tr>
                            <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id"><?= /* @escapeNotVerified */ $_order->getRealOrderId() ?></td>
                            <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date"><?= /* @escapeNotVerified */ date_format(date_create($_order->getCreatedAt()),"d.m.Y")
                            /*$block->formatDate($_order->getCreatedAt())*/ ?></td>
                            <?php $extra = $block->getChildBlock('extra.container'); ?>
                            <?php if ($extra): ?>
                                <?php $extra->setOrder($_order); ?>
                                <?= /* @noEscape */ $extra->getChildHtml() ?>
                            <?php endif; ?>
                            <td data-th="<?= $block->escapeHtml(__('Ship To')) ?>" class="col shipping">
                                <?php 
                                    if ($sellerStatus != 1) {
                                        if ($_order->getShippingMethod() == 'dropship_dropship') {
                                            $fullname = $_order->getCustomerFirstname().' '.$_order->getCustomerLastname();
                                            echo __("Drop Shipment ".$fullname);
                                        } else {
                                            echo __("myGermany Warehouse  ");           
                                        }
                                    } else {
                                        echo ($_order->getShippingAddress() ? $block->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' );
                                    }
                                ?>
                                    
                            </td>
                            <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total"><?= /* @escapeNotVerified */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
                            <?php
                                // Old Code Commented on 14 Sept, 2018
                                //   if ($statusLabel == 'Canceled' || ($statusLabel == 'Return')) {
                                //       $status = $_order->getStatusLabel();
                                //   } else {
                                //       if ($_order->getShippingMethod() == 'dropship_dropship') {
                                //           if ($_order->getStatusLabel() == 'Pending' || ($statusLabel == 'Order Processed') || ($statusLabel == 'Sent to myGermany') || ($statusLabel == 'Received') || ($statusLabel == 'Processing')) {
                                //               $status = "Pending";
                                //           } elseif ($statusLabel == 'Order Processed') {
                                //               $status = "Shipped";
                                //           }

                                //       } elseif ($_order->getShippingMethod() == 'warehouse_warehouse') {
                                //           if ($_order->getStatusLabel() == 'Pending' || ($statusLabel == 'Order Processed') || ($statusLabel == 'Compliance Check') || ($statusLabel == 'Sent to myGermany') || ($statusLabel == 'Processing')) {
                                //               $status = "Expected";
                                //           } elseif ($_order->getStatusLabel() == 'Received' || ($statusLabel == 'Order Verified') || ($statusLabel == 'Closed')) {
                                //               $status = "Received";
                                //           }
                                //       } 
                                //   }

                                $statusLabel = $_order->getStatusLabel();
                                $status = $_order->getStatus();
                                if ($statusLabel == 'Canceled' || ($statusLabel == 'Return')) {
                                    $statusLabel = $statusLabel;
                                } else {
                                    if ($_order->getShippingMethod() == 'dropship_dropship') {
                                        if ($status == 'pending' || ($status == 'order_processed') || ($status == 'sent_to_mygermany') || ($status == 'received') || ($status == 'processing')) {
                                            $statusLabel = __("In Process");
                                        } elseif ($status == 'order_verified') {
                                            $statusLabel = __("Shipped");
                                        }

                                    } elseif ($_order->getShippingMethod() == 'warehouse_warehouse') {
                                        if ($status == 'pending' || ($status == 'order_processed') || ($status == 'compliance_check') || ($status == 'sent_to_mygermany') || ($status == 'processing')) {
                                            $statusLabel = __("Expected");
                                        } elseif ($status == 'received' || ($status == 'order_verified') || ($status == 'closed')) {
                                            if ($status == 'closed') {
                                                $statusLabel = __("Closed");
                                            } else {
                                                $statusLabel = __("Received");
                                            }
                                        }
                                    } else {
                                        if ($status == 'pending' || ($status == 'order_processed') || ($status == 'compliance_check') || ($status == 'sent_to_mygermany') || ($status == 'processing')) {
                                            $statusLabel = __("Expected");
                                        } elseif ($status == 'received' || ($status == 'order_verified') || ($status == 'closed')) {
                                            $statusLabel = __("Received");
                                        }
                                    } 
                                }

                                $statusLink = '#';
                                if($_order->getShippingMethod() == 'dropship_dropship') {
                                    if($statusLabel == 'Shipped') {
                                        $statusLink = 'https://account.mygermany.com/en/web/content/orders?tabselected=3';
                                    }
                                } elseif ($_order->getShippingMethod() == 'warehouse_warehouse') {
                                    if($statusLabel == 'Expected' || $statusLabel == 'In Process') {
                                        $statusLink = 'https://account.mygermany.com/en/web/content/orders?tabselected=1';
                                    } elseif ($statusLabel == 'Received') {
                                        $statusLink = 'https://account.mygermany.com/en/web/content/orders?tabselected=2';
                                    } elseif ($statusLabel == 'Shipped') {
                                        $statusLink = 'https://account.mygermany.com/en/web/content/orders?tabselected=3';
                                    }
                                }
                            ?>
                            <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status"><span><?php echo __($statusLabel); ?></span></td>
                            <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                                <a href="<?= /* @escapeNotVerified */ $block->getViewUrl($_order) ?>" class="action view">
                                    <span><?= /* @escapeNotVerified */ __('View Order') ?></span>
                                </a>
                                <?php if ($this->helper('Magento\Sales\Helper\Reorder')->canReorder($_order->getEntityId())) : ?>
                                    <a href="#" data-post='<?php /* @escapeNotVerified */ echo
                                    $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                        ->getPostData($block->getReorderUrl($_order))
                                    ?>' class="action order">
                                        <span><?= /* @escapeNotVerified */ __('Reorder') ?></span>
                                    </a>
                                <?php endif ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </fieldset>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?= /* @escapeNotVerified */ __('You have placed no orders.') ?></span></div>
<?php endif ?>
