<!-- Last edited : 29-Jan-2019 -->
<style type="text/css">
img
{
    width: 100px;
    height: 100px;
}
.imagefile
{
    display: none;
}

.imagenote
{
    cursor: pointer;
    color: blue;
}

.admin__field-control
{
    display: inline-block;
    vertical-align: middle;
    margin-left: 25px;
}
</style>
<?php


$id =  $this->getRequest()->getParam('id');
$path = $block->getImageOfAd($id);
$productId = 'null';
$categoryId = 'null';
$url = $block->getUrlOfAd($id);
$title = $block->getTitleOfAd($id);
$status = $block->getStatusOfAd($id);
$storeId = $block->getStoreIdOfAd($id);
if ($storeId == 'All Store') {
    $storeId = 0;
}
$contenttype = $block->getContentTypeOfAd($id);
$storeCollection = $block->getAllStoreList();
$productModel = $block->getProductList();
$productModel->addAttributeToSelect('*');
$categoryCollection = $block->getCategories();
$categoryCollection->addAttributeToSelect('*');
?>
<div>
    <form id="editForm" method="post" enctype="multipart/form-data" action="<?php echo $this->getUrl('advertisement/adminads/editsave'); ?>">
        <input name="form_key" type="hidden" value="<?php echo $this->getFormKey();?>">
        <input name="ad_id" type="hidden" value="<?php echo $id;?>">

        <div class="page-main-actions">
            <div class="page-actions-placeholder">        
            </div>
            <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
                <div class="page-actions-inner" data-title="Manage Pricing">
                    <div class="page-actions-buttons">
                        <button id="back" title="Back" type="button" class="action-default scalable back" onclick="goBack()" >
                            <span>Back</span>
                        </button>
                        <button id="save" title="Save" type="submit" class="action- scalable primary" data-ui-id="add-button">
                            <span>Save</span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <?php  if ($contenttype == 1) { ?>

            <div class="imagecls admin__field _required">
                <label class="admin__field-label" for="image_store">
                    <span><?php echo __('Store View'); ?></span>
                </label>
                <div class="admin__field-control" >
                    <select class="admin__control-select store" id="image_store"  name="image[image_store]">
                        <option value=""><?php echo __('Select'); ?></option>
                        <option value="0"><?php echo __('All Store'); ?></option>
                        <?php  foreach ($storeCollection as $store) {
                            if (($store['group_id'] >= 1) && ($store['is_active'] == 1)) { ?>
                                <option value="<?php echo $store['store_id'] ?>" data-storeid="<?php echo $store['code']; ?>" ><?php echo __($store['name']); ?></option>
                            <?php }
                        }?>                          
                    </select>
                    <span style='display: none; color: red'><?php echo __('Please select any store.'); ?></span>
                </div>
            </div>

            <div class="imagecls admin__field _required">
                <label class="admin__field-label" for="image_image">
                    <span><?php echo __('Image'); ?></span>
                </label>
                <div class="admin__field-control" >
                    <img src="<?php echo $path;?>">
                    <span class="imagenote" id="image" ><small><?php echo __('Click here to change this image.'); ?></small></span>
                    <input type="file"  accept="image/*" class="imagefile" id="image_image" disabled="disabled">
                    <span style='display: none; color: red'><?php echo __('Please upload an image.'); ?></span>
                </div>
            </div>

            <div class="imagecls admin__field _required">
                <label class="admin__field-label" for="image_title">
                    <span><?php echo __('Title')?></span>
                </label>
                <div class="admin__field-control" >
                    <input type="text" name="image[image_title]" id="image_title" class="title" value="<?php echo $title; ?>">
                    <span style='display: none; color: red'><?php echo __('Title value is invalid.'); ?></span>
                </div>
            </div>

            <div class="imagecls admin__field _required">
                <label class="admin__field-label" for="image_url">
                    <span><?php echo __('Url'); ?></span>
                </label>
                <div class="admin__field-control" >
                    <input type="text" name="image[image_url]" id="image_url" class="Url" value="<?php echo $url; ?>">
                    <span style='display: none; color: red'><?php echo __('Url is not valid.'); ?></span>
                </div>
            </div>

            <div class="imagecls admin__field _required">
                <label class="admin__field-label" for="image_enable">
                    <span><?php echo __('Enable'); ?></span>
                </label>
                <div class="admin__field-control" >
                    <select  class="admin__control-select status" id="image_enable" name="image[image_enable]">
                        <option value="2"><?php echo __('Select'); ?></option>  
                        <?php if ($status == 1) { ?>
                            <option selected="selected" value="1"><?php echo __('Enabled'); ?></option>
                            <option value="0" ><?php echo __('Disabled'); ?></option>
                        <?php } else { ?>
                            <option selected="selected" value="0"><?php echo __('Disabled'); ?></option>
                            <option value="1" ><?php echo __('Enabled'); ?></option>
                        <?php }  ?>                      
                    </select>
                    <span style='display: none; color: red'><?php echo __('Please select at least one option.'); ?></span>
                </div>
            </div>

        <?php } else if ($contenttype == 2) {  $productId = $block->getProductIdOfAd($id); ?>

            <div class="product admin__field _required">
                <label class="admin__field-label" for="product_store">
                    <span><?php echo __('Store View')?></span>
                </label>
                <div class="admin__field-control" >
                    <select  class="admin__control-select store" id="product_store"  name="product[product_store]" >
                        <option value=""><?php echo __('Select'); ?></option>
                        <option value="0"><?php echo __('All Store'); ?></option>   
                        <?php foreach ($storeCollection as $store) {
                            if (($store['group_id'] >= 1) && ($store['is_active'] == 1)) { ?>
                                <option value="<?php echo $store['store_id'] ?>" data-storeid="<?php echo $store['code']?>" ><?php echo __($store['name'])?></option>
                            <?php }
                        } ?>                         
                    </select>
                    <span style='display: none; color: red'><?php echo __('Please select any store.')?></span>
                </div>
            </div>

            <div class="product admin__field _required">
                <label class="admin__field-label" for="product_image">
                    <span><?php echo __('Image')?></span>
                </label>
                <div class="admin__field-control" >
                    <img src="<?php echo $path;?>">
                    <span class="imagenote" id="product"><small><?php echo __('Click here to change this image.')?></small></span>
                    <input type="file" class="imagefile" accept="image/*" id="product_image" disabled="disabled">
                    <span style='display: none; color: red'><?php echo __('Please upload an image.')?></span>
                </div>
            </div>

            <div class="product admin__field _required">
                <label class="admin__field-label" for="product_id">
                    <span><?php echo __('Product')?></span>
                </label>
                <div class="admin__field-control" >
                    <select  class="admin__control-select mis_product_select" id="product_id" name="product[product_id]">
                        <option value="0"><?php echo __('Select');?></option>
                        <?php foreach ($productModel as $item) {  ?>
                         <option value="<?php echo $item->getEntityId()?>" data-row='1' data-url="<?php echo $item->getProductUrl()?>"><?php echo $item->getName()?></option>
                     <?php } ?>
                 </select>
                 <span style='display: none; color: red'><?php echo __('Please select any product.')?></span>
             </div>
         </div>

         <div class="product admin__field _required">
            <label class="admin__field-label" for="product_title">
                <span><?php echo __('Title')?></span>
            </label>
            <div class="admin__field-control" >
                <input type="text" name="product[product_title]" id="product_title" class="title" value="<?php echo $title;?>">
                <span style='display: none; color: red'><?php echo __('Title is invalid.')?></span>
            </div>
        </div>

        <div class="product admin__field _required">
            <label class="admin__field-label" for="product_url">
                <span><?php echo __('Url')?></span>
            </label>
            <div class="admin__field-control" >
                <input type="text" name="product[product_url]" id="product_url" class="Url" value="<?php echo $url;?>">
                <span style='display: none; color: red'><?php echo __('Url is invalid.')?></span>
            </div>
        </div>

        <div class="product admin__field _required">
            <label class="admin__field-label" for="product_enable">
                <span><?php echo __('Enable')?></span>
            </label>
            <div class="admin__field-control" >
                <select  class="admin__control-select status" id="product_enable" name="product[product_enable]">
                    <option value="2"><?php echo __('Select');?></option>   
                    <?php if ($status == 1) { ?>
                        <option selected="selected" value="1"><?php echo __('Enabled')?></option>
                        <option value="0" ><?php echo __('Disabled')?></option>
                    <?php } else { ?>
                        <option selected="selected" value="0"><?php echo __('Disabled')?></option>
                        <option value="1" ><?php echo __('Enabled')?></option>
                    <?php }  ?>                      
                </select>
                <span style='display: none; color: red'><?php echo __('Please select any store.')?></span>
            </div>
        </div>

    <?php } else if ($contenttype == 3) { $categoryId = $block->getCategoryIdOfAd($id); ?>

        <div class="category admin__field _required">
            <label class="admin__field-label" for="category_store">
                <span><?php echo __('Store View')?></span>
            </label>
            <div class="admin__field-control" >
                <select  class="admin__control-select store" id="category_store"  name="category[category_store]">
                    <option value=""><?php echo __('Select'); ?></option>
                    <option value="0"><?php echo __('All Store'); ?></option>
                    <?php foreach ($storeCollection as $store) {
                        if (($store['group_id'] >= 1) && ($store['is_active'] == 1)) { ?>
                            <option value="<?php echo $store['store_id'] ?>" data-storeid="<?php echo $store['code']?>" ><?php echo __($store['name'])?></option>
                        <?php }
                    } ?>                         
                </select>
                <span style='display: none; color: red'><?php echo __('Please select any store.')?></span>
            </div>
        </div>

        <div class="category admin__field _required">
            <label class="admin__field-label" for="category_image">
                <span><?php echo __('Image')?></span>
            </label>
            <div class="admin__field-control" >
                <img src="<?php echo $path;?>">
                <span class="imagenote" id="category" ><small><?php echo __('Click here to change this image.')?></small></span>
                <input type="file"  accept="image/*" class="imagefile" id="category_image" disabled="disabled">
                <span style='display: none; color: red'><?php echo __('Please upload an image.')?></span>
            </div>
        </div>

        <div class="category admin__field _required">
            <label class="admin__field-label" for="category_id">
                <span><?php echo __('Category')?></span>
            </label>
            <div class="admin__field-control" >
                <select  class="admin__control-select mis_category_select" id="category_id" name="category[category_id]">
                    <option value="0"><?php echo __('Select');?></option>
                    <?php
                    foreach ($categoryCollection as $item) { 
                        if ($item->getEntityId() > 2) {?>
                            <option value="<?php echo $item->getEntityId()?>" data-row='1' data-caturl="<?php echo $item->getUrl()?>"><?php echo $item->getName()?></option>
                        <?php   }
                    }
                    ?>
                </select>
                <span style='display: none; color: red'><?php echo __('Please select any category.')?></span>
            </div>
        </div>

        <div class="category admin__field _required">
            <label class="admin__field-label" for="category_title">
                <span><?php echo __('Title')?></span>
            </label>
            <div class="admin__field-control" >
                <input type="text" name="category[category_title]" id="category_title" class="title" value="<?php echo $title;?>">
                <span style='display: none; color: red'><?php echo __('Title is invalid.')?></span>
            </div>
        </div>

        <div class="category admin__field _required">
            <label class="admin__field-label" for="category_url">
                <span><?php echo __('Url')?></span>
            </label>
            <div class="admin__field-control" >
                <input type="text" name="category[category_url]" id="category_url" class="Url" value="<?php echo $url;?>">
                <span style='display: none; color: red'><?php echo __('Url is invalid.')?></span>
            </div>
        </div>

        <div class="category admin__field _required">
            <label class="admin__field-label" for="category_enable">
                <span><?php echo __('Enable')?></span>
            </label>
            <div class="admin__field-control" >
                <select  class="admin__control-select status" id="category_enable" name="category[category_enable]">
                    <option value="2"><?php echo __('Select');?></option>   
                    <?php if ($status == 1) { ?>
                        <option selected="selected" value="1"><?php echo __('Enabled')?></option>
                        <option value="0" ><?php echo __('Disabled')?></option>
                    <?php } else { ?>
                        <option selected="selected" value="0"><?php echo __('Disabled')?></option>
                        <option value="1" ><?php echo __('Enabled')?></option>
                    <?php }  ?>                      
                </select>
                <span style='display: none; color: red'><?php echo __('Please select at least one value.')?></span>
            </div>
        </div>

    <?php } else { ?>

        <div class="html admin__field _required">
            <label class="admin__field-label" for="html_store">
                <span><?php echo __('Store View')?></span>
            </label>
            <div class="admin__field-control" >
                <select  class="admin__control-select store" id="html_store"  name="html[html_store]">
                    <option value=""><?php echo __('Select'); ?></option>
                    <option value="0"><?php echo __('All Store'); ?></option>
                    <?php foreach ($storeCollection as $store) {
                        if (($store['group_id'] >= 1) && ($store['is_active'] == 1)) { ?>
                            <option value="<?php echo $store['store_id'] ?>" data-storeid="<?php echo $store['code']?>" ><?php echo __($store['name'])?></option>
                        <?php }
                    } ?>                         
                </select>
                <span style='display: none; color: red'><?php echo __('Please select any store.')?></span>
            </div>
        </div>

        <div class="html admin__field _required">
            <label class="admin__field-label" for="html_id">
                <span><?php echo __('Html Editor')?></span>
            </label>
            <div class="admin__field-control" >
                <textarea id="html_editor" name="html[html_editor]" class="required-entry input-text required-entry _required"><?php echo $block->getHtmlOfAd($id);?></textarea>
                <span style='display: none; color: red'><?php echo __('Field should not be empty.')?></span>
            </div>
        </div>

        <div class="html admin__field _required">
            <label class="admin__field-label" for="html_title">
                <span><?php echo __('Title')?></span>
            </label>
            <div class="admin__field-control" >
                <input type="text" name="html[html_title]" id="html_title" class="title" value="<?php echo $title;?>">
                <span style='display: none; color: red'><?php echo __('Title is invalid.')?></span>
            </div>
        </div>

        <div class="html admin__field _required">
            <label class="admin__field-label" for="html_url">
                <span><?php echo __('Url')?></span>
            </label>
            <div class="admin__field-control" >
                <input type="text" name="html[html_url]" id="html_url" class="Url" value="<?php echo $url;?>">
                <span style='display: none; color: red'><?php echo __('Url is invalid.')?></span>
            </div>
        </div>

        <div class="html admin__field _required">
            <label class="admin__field-label" for="html_enable">
                <span><?php echo __('Enable')?></span>
            </label>
            <div class="admin__field-control" >
                <select  class="admin__control-select status" id="html_enable" name="html[html_enable]">
                    <option value="2"><?php echo __('Select');?></option>   
                    <?php if ($status == 1) { ?>
                        <option selected="selected" value="1"><?php echo __('Enabled')?></option>
                        <option value="0" ><?php echo __('Disabled')?></option>
                    <?php } else { ?>
                        <option selected="selected" value="0"><?php echo __('Disabled')?></option>
                        <option value="1" ><?php echo __('Enabled')?></option>
                    <?php }  ?>                      
                </select>
                <span style='display: none; color: red'><?php echo __('Please select atleast one value')?></span>
            </div>
        </div>


    <?php } ?>

</form>
</div>

<script type="text/javascript">
    var imageflag = 0;
    var contenttype = "<?php echo $contenttype;?>";
    var storeId = "<?php echo $storeId; ?>";
    if (contenttype == 1) {
        setTimeout(
            function(){ 
                jQuery("#image_store option[value="+storeId+"]").attr('selected', 'selected');  
                jQuery('.category').find('*').attr('disabled', true);
                jQuery('.product').find('*').attr('disabled', true);
                jQuery('.html').find('*').attr('disabled', true);
                jQuery('.imagecls').find('*').attr('disabled', false);
                jQuery('#image_store').attr('disabled', true);
            }, 3000);
    }
    if (contenttype == 2) {
        var productId = "<?php echo $productId; ?>"; 
        setTimeout(
            function(){ 
                jQuery("#product_id option[value="+productId+"]").attr('selected', 'selected');
                jQuery("#product_store option[value="+storeId+"]").attr('selected', 'selected');

                jQuery('.category').find('*').attr('disabled', true);
                jQuery('.product').find('*').attr('disabled', false);
                jQuery('.html').find('*').attr('disabled', true);
                jQuery('.imagecls').find('*').attr('disabled', true);
                jQuery('#product_store').attr('disabled', true);

            }, 3000);   
    }
    if (contenttype == 3) {
        var categoryId = "<?php echo $categoryId; ?>";
        setTimeout(
            function(){ 
                jQuery("#category_id option[value="+categoryId+"]").attr('selected', 'selected');
                jQuery("#category_store option[value="+storeId+"]").attr('selected', 'selected');   
                jQuery('.category').find('*').attr('disabled', false);
                jQuery('.product').find('*').attr('disabled', true);
                jQuery('.html').find('*').attr('disabled', true);
                jQuery('.imagecls').find('*').attr('disabled', true);
                jQuery('#category_store').attr('disabled', true);
            }, 3000);
    }
    if (contenttype == 4) {
        setTimeout(
            function(){ 
                jQuery("#html_store option[value="+storeId+"]").attr('selected', 'selected');   
                jQuery('.category').find('*').attr('disabled', true);
                jQuery('.product').find('*').attr('disabled', true);
                jQuery('.html').find('*').attr('disabled', false);
                jQuery('.imagecls').find('*').attr('disabled', true);
                jQuery('#html_store').attr('disabled', true);
            }, 3000);
    }

    function urlonly(url){
        var patt = /https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/;
        if (patt.test(url) ) {
            console.log(patt.test(url));
            return true;
        } else {
            console.log(patt.test(url));
            return false;
        }
    }

    function goBack()
    {
     window.location.href= "<?php echo $this->getUrl('advertisement/adminads/index');?>";
 }

 require(['jquery', 'jquery/ui'], function($){ 
    jQuery(document).on('change', '#html_editor_ifr', function(){
        console.log('i am here');
    });

    jQuery(document).on('click', 'img', function(){
        console.log('hi here');
        var url = jQuery(this).attr('src');
        window.open(url, '_blank');
        console.log(url);
    });

    jQuery(document).on('change', '.mis_product_select', function(){
        var selectedVal = jQuery(this).val();
        if (selectedVal == '') {
           jQuery('.Url').val('');
       }
       var productUrl = this.options[this.selectedIndex].getAttribute('data-url')
       var pro_row_num = this.options[this.selectedIndex].getAttribute('data-row');
       console.log('Url '+productUrl);
       jQuery('.Url').val(productUrl);
   });

    jQuery(document).on('change', '.mis_category_select', function(){
        var selectedVal = jQuery(this).val();
        var catUrl = this.options[this.selectedIndex].getAttribute('data-caturl')
        var cat_row_num = this.options[this.selectedIndex].getAttribute('data-row');
        console.log('catUrl Url '+catUrl);
        jQuery('.Url').val(catUrl);
        if (selectedVal == '') {
           jQuery('.Url').val('');
       }
   });

    jQuery(document).on('click', '.imagenote', function(){
        imageflag = 1;
        var id = jQuery(this).attr('id');
        if (id == 'image') {
            jQuery('.imagefile').attr('name','image[image_image]');
        } else if (id == 'product') {
            jQuery('.imagefile').attr('name','product[product_image]');
        } else if (id == 'category') {
            jQuery('.imagefile').attr('name','category[category_image]');
        }
        
        jQuery('img').attr('disabled', true);
        jQuery('img').css('display', 'none');

        jQuery('.imagenote').attr('disabled', true);
        jQuery('.imagenote').css('display', 'none');
        jQuery('.imagefile').attr('disabled', false);
        jQuery('.imagefile').css('display', 'block');
    });

    jQuery(document).on('click', '#save', function(){
    jQuery(".Url").each(function() {
        if (jQuery(this).val().trim() == '') {
            event.preventDefault();
            jQuery(this).next().css({"color": "red", 'display':'block'});
        } else if (! urlonly(jQuery(this).val().trim())) {
            event.preventDefault();
            jQuery(this).next().css({"color": "red", 'display':'block'});
        } else {
            console.log(jQuery(this).val().trim());
            jQuery(this).next().css({'display':'none'});
        }
    });

     jQuery('.imagefile').each(function(){
        console.log('imageflag '+imageflag);
        if (imageflag == 1) {
            if (jQuery(this).val().trim() == '') {
                event.preventDefault();
                jQuery(this).next().text("Please upload image.");
                jQuery(this).next().css({"color": "red", 'display':'block'});
            } else if (jQuery(this)[0].files[0].size > 2024000) {
                event.preventDefault();
                jQuery(this).next().text("Image size should be lesser than 2 MB.");
                jQuery(this).next().css({"color": "red", 'display':'block'});
            } else {
                jQuery(this).next().css({"color": "red", 'display':'none'});
            }                       
        }

    });

     jQuery(".title").each(function() {
        if (jQuery(this).val().trim() == '') {
            event.preventDefault();
            jQuery(this).next().css({"color": "red", 'display':'block'});
        } else {
            console.log(jQuery(this).val().trim());
            jQuery(this).next().css({'display':'none'});
        }
    });

     jQuery(".store").each(function() {
       console.log('htmlStoreDrop '+jQuery(this).val()); 
       if (jQuery(this).val() == '' || jQuery(this).val() == null) {
        event.preventDefault();
        jQuery(this).next().css({"color": "red", 'display':'block'});
    } else {
        console.log(jQuery(this).val());
        jQuery(this).next().css({'display':'none'});
    }
});


     if (contenttype == 0) {
     } else if (contenttype == 1) {
     } else if (contenttype == 2) {
        jQuery(".mis_product_select").each(function() {
            if (jQuery(this).val() == 0) {
                event.preventDefault();
                jQuery(this).next().css({"color": "red", 'display':'block'});
            } else {
                jQuery(this).next().css({'display':'none'});
            }
        });
    } else if (contenttype == 3) {
        jQuery(".mis_category_select").each(function() {
            if (jQuery(this).val() == 0) {
                event.preventDefault();
                jQuery(this).next().css({"color": "red", 'display':'block'});
            } else {
                jQuery(this).next().css({'display':'none'});
            }
        });
    } else if (contenttype == 4) {
    }
});

    jQuery('form').submit(function () {
        jQuery('.imagefile').each(function(){
            if (imageflag == 1) {
                console.log('imageflag submit'+imageflag);

                if (jQuery(this).val().trim() == '') {
                    event.preventDefault();
                    jQuery(this).next().text("Please upload image.");
                    jQuery(this).next().css({"color": "red", 'display':'block'});
                } else if (jQuery(this)[0].files[0].size > 2024000) {
                    event.preventDefault();
                    jQuery(this).next().text("Image size should be lesser than 2 MB.");
                    jQuery(this).next().css({"color": "red", 'display':'block'});
                } else {
                    jQuery(this).next().css({"color": "red", 'display':'none'});
                }
                
            }
        });

        jQuery(".Url").each(function() {
            if (jQuery(this).val().trim() == '') {
                event.preventDefault();
                jQuery(this).next().css({"color": "red", 'display':'block'});
            } else if (! urlonly(jQuery(this).val().trim())) {
                event.preventDefault();
                jQuery(this).next().css({"color": "red", 'display':'block'});
            } else {
                console.log(jQuery(this).val().trim());
                jQuery(this).next().css({'display':'none'});
            }
        });

        jQuery('.imagefile').each(function(){
            if (imageflag == 1) {
                if (jQuery(this).val().trim() == '') {
                    event.preventDefault();
                    jQuery(this).next().text("Please upload image.");
                    jQuery(this).next().css({"color": "red", 'display':'block'});
                } else if (jQuery(this)[0].files[0].size > 2024000) {
                    event.preventDefault();
                    jQuery(this).next().text("Image size should be lesser than 2 MB.");
                    jQuery(this).next().css({"color": "red", 'display':'block'});
                } else {
                    jQuery(this).next().css({"color": "red", 'display':'none'});
                }

            }
        });

        jQuery(".title").each(function() {
            if (jQuery(this).val().trim() == '') {
                event.preventDefault();
                jQuery(this).next().css({"color": "red", 'display':'block'});
            } else {
                console.log(jQuery(this).val().trim());
                jQuery(this).next().css({'display':'none'});
            }
        });

        jQuery(".store").each(function() {
           console.log('store '+jQuery(this).val()); 
           if (jQuery(this).val() == '' || jQuery(this).val() == null) {
            event.preventDefault();
            jQuery(this).next().css({"color": "red", 'display':'block'});
        } else {
            console.log(jQuery(this).val());
            jQuery(this).next().css({'display':'none'});
        }
    });

        jQuery(".status").each(function() {
           console.log('status '+jQuery(this).val()); 
           if (jQuery(this).val() == '0' || jQuery(this).val() == null) {
            event.preventDefault();
            jQuery(this).next().css({"color": "red", 'display':'block'});
        } else {
            console.log(jQuery(this).val());
            jQuery(this).next().css({'display':'none'});
        }
    });


        if (contenttype == 0) {
        } else if (contenttype == 2) {
            jQuery(".mis_product_select").each(function() {
                if (jQuery(this).val() == 0) {
                    event.preventDefault();
                    jQuery(this).next().css({"color": "red", 'display':'block'});
                } else {
                    jQuery(this).next().css({'display':'none'});
                }
            });


        } else if (contenttype == 3) {
            jQuery(".mis_category_select").each(function() {
                if (jQuery(this).val() == 0) {
                    event.preventDefault();
                    jQuery(this).next().css({"color": "red", 'display':'block'});
                } else {
                    jQuery(this).next().css({'display':'none'});
                }
            });
        } 
    });
});
</script>
<script type="text/javascript">
    require([
        'jquery',
        'mage/adminhtml/wysiwyg/tiny_mce/setup'
        ], function(jQuery){

            var config = {}, 
            editor;

            jQuery.extend(config, {
                settings: {
                    theme_advanced_buttons1 : 'bold,italic,|,justifyleft,justifycenter,justifyright,|,' +
                    'fontselect,fontsizeselect,|,forecolor,backcolor,|,link,unlink,image,|,bullist,numlist,|,code',
                    theme_advanced_buttons2: null,
                    theme_advanced_buttons3: null,
                    theme_advanced_buttons4: null
                }
            });
            editor = new tinyMceWysiwygSetup(
                'html_editor',
                config
                );
            editor.turnOn();
            jQuery('#html_editor')
            .addClass('wysiwyg-editor')
            .data(
                'wysiwygEditor',
                editor
                );
        });
</script>
