<!-- Last edited : 29-Jan-2019 -->
<?php
$currentId = $this->getRequest()->getParam('id');
$adsData = $block->getPrimaryAdvertisementData($currentId);
$contentType = $adsData['content_type'];
$url = $adsData['url'];
$title = $adsData['title'];
$status = $block->getStatusOfAd($currentId);
$approvalStatus = $block->getApprovalStatusOfAd($currentId);
$productId = $adsData['product_id'];
$categoryId = $adsData['category_id'];
$path = $block->getImageOfAd($currentId);
if ($contentType == 4) {
    $imageHtml = $adsData['image_name'];
}

$storeId = $block->getStoreIdOfAd($currentId);
$storeCollection = $block->getAllStoreList();
$productModel = $block->getProductList();
$productModel->addAttributeToSelect('*');
$categoryCollection = $block->getCategories();
$categoryCollection->addAttributeToSelect('*');
?>

<div>
    <form id="editForm" method="post" enctype="multipart/form-data" action="<?php echo $this->getUrl('advertisement/adminads/enablevendorads'); ?>">
        <input name="form_key" type="hidden" value="<?php echo $this->getFormKey();?>">
        <input name="ad_id" type="hidden" value="<?php echo $currentId;?>">
        <div class="page-main-actions">
            <div class="page-actions-placeholder">        
            </div>
            <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
                <div class="page-actions-inner" data-title="Manage Pricing">
                    <div class="page-actions-buttons">
                        <button id="back" title="Back" type="button" class="action-default scalable back" onclick="goBack()" >
                            <span>Back</span>
                        </button>
                        <button id="save" title="Save" type="submit" class="action- scalable primary" data-ui-id="add-button">
                            <span>Save</span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <?php 
        if ($contentType == 1) { ?>
            <div class="imagecls admin__field _required">
                <label class="admin__field-label" for="image_store">
                    <span><?php echo __('Store View'); ?></span>
                </label>
                <div class="admin__field-control" >
                    <select class="admin__control-select store" id="image_store"  name="image[image_store]">
                        <option value="0"><?php echo __('Select'); ?></option>
                        <?php  foreach ($storeCollection as $store) {
                            if (($store['group_id'] >= 1) && ($store['is_active'] == 1)) { ?>
                                <option value="<?php echo $store['store_id'] ?>" data-storeid="<?php echo $store['code']; ?>" ><?php echo __($store['name']); ?></option>
                            <?php }
                        }?>                          
                    </select>
                    <span style='display: none; color: red'><?php echo __('Please select any store.'); ?></span>
                </div>
            </div>

            <div class="imagecls admin__field _required">
                <label class="admin__field-label" for="image_image">
                    <span><?php echo __('Image'); ?></span>
                </label>
                <div class="admin__field-control" >
                    <img src="<?php echo $path;?>">
                </div>
            </div>

            <div class="imagecls admin__field _required">
                <label class="admin__field-label" for="image_title">
                    <span><?php echo __('Title')?></span>
                </label>
                <div class="admin__field-control" >
                    <input type="text" name="image[image_title]" id="image_title" class="title" value="<?php echo $title; ?>">
                    <span style='display: none; color: red'><?php echo __('Title value is invalid.'); ?></span>
                </div>
            </div>

            <div class="imagecls admin__field _required">
                <label class="admin__field-label" for="image_url">
                    <span><?php echo __('Url'); ?></span>
                </label>
                <div class="admin__field-control" >
                    <input type="text" name="image[image_url]" id="image_url" class="Url" value="<?php echo $url; ?>">
                    <span style='display: none; color: red'><?php echo __('Url is not valid.'); ?></span>
                </div>
            </div>

            <div class="admin__field _required">
                <label class="admin__field-label" for="image_enable">
                    <span><?php echo __('Enable'); ?></span>
                </label>
                <div class="admin__field-control" >
                    <select  class="admin__control-select status" id="image_enable" name="image[image_enable]">
                        <option value="2"><?php echo __('Select'); ?></option>  
                        <?php if ($status == 1) { ?>
                            <option selected="selected" value="1"><?php echo __('Enabled'); ?></option>
                            <option value="0" ><?php echo __('Disabled'); ?></option>
                        <?php } else { ?>
                            <option selected="selected" value="0"><?php echo __('Disabled'); ?></option>
                            <option value="1" ><?php echo __('Enabled'); ?></option>
                        <?php }  ?>                      
                    </select>
                    <span style='display: none; color: red'><?php echo __('Please select at least one option.'); ?></span>
                </div>
            </div>
            <?php
        } else if ($contentType == 2) { ?>
            <div class="product admin__field _required">
                <label class="admin__field-label" for="product_store">
                    <span><?php echo __('Store View')?></span>
                </label>
                <div class="admin__field-control" >
                    <select  class="admin__control-select store" id="product_store"  name="product[product_store]">
                        <option value="0"><?php echo __('Select');?></option>   
                        <?php foreach ($storeCollection as $store) {
                            if (($store['group_id'] >= 1) && ($store['is_active'] == 1)) { ?>
                                <option value="<?php echo $store['store_id'] ?>" data-storeid="<?php echo $store['code']?>" ><?php echo __($store['name'])?></option>
                            <?php }
                        } ?>                         
                    </select>
                    <span style='display: none; color: red'><?php echo __('Please select any store.')?></span>
                </div>
            </div>

            <div class="product admin__field _required">
                <label class="admin__field-label" for="product_image">
                    <span><?php echo __('Image')?></span>
                </label>
                <div class="admin__field-control" >
                    <img src="<?php echo $path;?>">
                    <span style='display: none; color: red'><?php echo __('Please upload an image.')?></span>
                </div>
            </div>

            <div class="product admin__field _required">
                <label class="admin__field-label" for="product_id">
                    <span><?php echo __('Product')?></span>
                </label>
                <div class="admin__field-control" >
                    <select  class="admin__control-select mis_product_select" id="product_id" name="product[product_id]">
                        <option value="0"><?php echo __('Select');?></option>
                        <?php foreach ($productModel as $item) {  ?>
                            <option value="<?php echo $item->getEntityId()?>" data-row='1' data-url="<?php echo $item->getProductUrl()?>"><?php echo $item->getName()?></option>
                        <?php } ?>
                    </select>
                    <span style='display: none; color: red'><?php echo __('Please select any product.')?></span>
                </div>
            </div>

            <div class="product admin__field _required">
                <label class="admin__field-label" for="product_title">
                    <span><?php echo __('Title')?></span>
                </label>
                <div class="admin__field-control" >
                    <input type="text" name="product[product_title]" id="product_title" class="title" value="<?php echo $title;?>">
                    <span style='display: none; color: red'><?php echo __('Title is invalid.')?></span>
                </div>
            </div>

            <div class="product admin__field _required">
                <label class="admin__field-label" for="product_url">
                    <span><?php echo __('Url')?></span>
                </label>
                <div class="admin__field-control" >
                    <input type="text" name="product[product_url]" id="product_url" class="Url" value="<?php echo $url;?>">
                    <span style='display: none; color: red'><?php echo __('Url is invalid.')?></span>
                </div>
            </div>

            <div class="admin__field _required">
                <label class="admin__field-label" for="product_enable">
                    <span><?php echo __('Enable')?></span>
                </label>
                <div class="admin__field-control" >
                    <select  class="admin__control-select status" id="product_enable" name="product[product_enable]">
                        <option value="2"><?php echo __('Select');?></option>   
                        <?php if ($status == 1) { ?>
                            <option selected="selected" value="1"><?php echo __('Enabled')?></option>
                            <option value="0" ><?php echo __('Disabled')?></option>
                        <?php } else { ?>
                            <option selected="selected" value="0"><?php echo __('Disabled')?></option>
                            <option value="1" ><?php echo __('Enabled')?></option>
                        <?php }  ?>                      
                    </select>
                    <span style='display: none; color: red'><?php echo __('Please select any store.')?></span>
                </div>
            </div>
        <?php   } else if ($contentType == 3) { ?>

            <div class="category admin__field _required">
                <label class="admin__field-label" for="category_store">
                    <span><?php echo __('Store View')?></span>
                </label>
                <div class="admin__field-control" >
                    <select  class="admin__control-select store" id="category_store"  name="category[category_store]">
                        <option value="0"><?php echo __('Select');?></option>   
                        <?php foreach ($storeCollection as $store) {
                            if (($store['group_id'] >= 1) && ($store['is_active'] == 1)) { ?>
                                <option value="<?php echo $store['store_id'] ?>" data-storeid="<?php echo $store['code']?>" ><?php echo __($store['name'])?></option>
                            <?php }
                        } ?>                         
                    </select>
                    <span style='display: none; color: red'><?php echo __('Please select any store.')?></span>
                </div>
            </div>

            <div class="category admin__field _required">
                <label class="admin__field-label" for="category_image">
                    <span><?php echo __('Image')?></span>
                </label>
                <div class="admin__field-control" >
                    <img src="<?php echo $path;?>">
                    <span style='display: none; color: red'><?php echo __('Please upload an image.')?></span>
                </div>
            </div>

            <div class="category admin__field _required">
                <label class="admin__field-label" for="category_id">
                    <span><?php echo __('Category')?></span>
                </label>
                <div class="admin__field-control" >
                    <select  class="admin__control-select mis_category_select" id="category_id" name="category[category_id]">
                        <option value="0"><?php echo __('Select');?></option>
                        <?php
                        foreach ($categoryCollection as $item) { 
                            if ($item->getEntityId() > 2) {?>
                                <option value="<?php echo $item->getEntityId()?>" data-row='1' data-caturl="<?php echo $item->getUrl()?>"><?php echo $item->getName()?></option>
                            <?php   }
                        }
                        ?>
                    </select>
                    <span style='display: none; color: red'><?php echo __('Please select any category.')?></span>
                </div>
            </div>

            <div class="category admin__field _required">
                <label class="admin__field-label" for="category_title">
                    <span><?php echo __('Title')?></span>
                </label>
                <div class="admin__field-control" >
                    <input type="text" name="category[category_title]" id="category_title" class="title" value="<?php echo $title;?>">
                    <span style='display: none; color: red'><?php echo __('Title is invalid.')?></span>
                </div>
            </div>

            <div class="category admin__field _required">
                <label class="admin__field-label" for="category_url">
                    <span><?php echo __('Url')?></span>
                </label>
                <div class="admin__field-control" >
                    <input type="text" name="category[category_url]" id="category_url" class="Url" value="<?php echo $url;?>">
                    <span style='display: none; color: red'><?php echo __('Url is invalid.')?></span>
                </div>
            </div>

            <div class="category admin__field _required">
                <label class="admin__field-label" for="category_enable">
                    <span><?php echo __('Enable')?></span>
                </label>
                <div class="admin__field-control" >
                    <select  class="admin__control-select status" id="category_enable" name="category[category_enable]">
                        <option value="2"><?php echo __('Select');?></option>   
                        <?php if ($status == 1) { ?>
                            <option selected="selected" value="1"><?php echo __('Enabled')?></option>
                            <option value="0" ><?php echo __('Disabled')?></option>
                        <?php } else { ?>
                            <option selected="selected" value="0"><?php echo __('Disabled')?></option>
                            <option value="1" ><?php echo __('Enabled')?></option>
                        <?php }  ?>                      
                    </select>
                    <span style='display: none; color: red'><?php echo __('Please select at least one value.')?></span>
                </div>
            </div>
        <?php } else if ($contentType == 4) { ?>
            <div class="html admin__field _required">
                <label class="admin__field-label" for="html_store">
                    <span><?php echo __('Store View')?></span>
                </label>
                <div class="admin__field-control" >
                    <select  class="admin__control-select store" id="html_store"  name="html[html_store]">
                        <option value="0"><?php echo __('Select');?></option>   
                        <?php foreach ($storeCollection as $store) {
                            if (($store['group_id'] >= 1) && ($store['is_active'] == 1)) { ?>
                                <option value="<?php echo $store['store_id'] ?>" data-storeid="<?php echo $store['code']?>" ><?php echo __($store['name'])?></option>
                            <?php }
                        } ?>                         
                    </select>
                    <span style='display: none; color: red'><?php echo __('Please select any store.')?></span>
                </div>
            </div>

            <div class="html admin__field _required">
                <label class="admin__field-label" for="html_id">
                    <span><?php echo __('Html Editor')?></span>
                </label>
                <div class="admin__field-control" >
                    <?php echo $imageHtml;?>
                </div>
            </div>

            <div class="html admin__field _required">
                <label class="admin__field-label" for="html_title">
                    <span><?php echo __('Title')?></span>
                </label>
                <div class="admin__field-control" >
                    <input type="text" name="html[html_title]" id="html_title" class="title" value="<?php echo $title;?>">
                    <span style='display: none; color: red'><?php echo __('Title is invalid.')?></span>
                </div>
            </div>

            <div class="html admin__field _required">
                <label class="admin__field-label" for="html_url">
                    <span><?php echo __('Url')?></span>
                </label>
                <div class="admin__field-control" >
                    <input type="text" name="html[html_url]" id="html_url" class="Url" value="<?php echo $url;?>">
                    <span style='display: none; color: red'><?php echo __('Url is invalid.')?></span>
                </div>
            </div>

            <div class="admin__field _required">
                <label class="admin__field-label" for="html_enable">
                    <span><?php echo __('Enable')?></span>
                </label>
                <div class="admin__field-control" >
                    <select  class="admin__control-select status" id="html_enable" name="html[html_enable]">
                        <option value="2"><?php echo __('Select');?></option>   
                        <?php if ($status == 1) { ?>
                            <option selected="selected" value="1"><?php echo __('Enabled')?></option>
                            <option value="0" ><?php echo __('Disabled')?></option>
                        <?php } else { ?>
                            <option selected="selected" value="0"><?php echo __('Disabled')?></option>
                            <option value="1" ><?php echo __('Enabled')?></option>
                        <?php }  ?>                      
                    </select>
                    <span style='display: none; color: red'><?php echo __('Please select atleast one value')?></span>
                </div>
            </div>
            <?php
        }
        ?>
        <div class="admin__field _required">
            <label class="admin__field-label" for="approvalStatus">
                <span><?php echo __('Approval')?></span>
            </label>
            <div class="admin__field-control" >
                <select  class="admin__control-select approval_status" id="approvalStatus" name="approvalStatus">
                    <option value=""><?php echo __('Select');?></option>    
                    <option <?php echo ($approvalStatus==0)?'selected':'';?> value="0"><?php echo __('Pending')?></option>
                    <option <?php echo ($approvalStatus==1)?'selected':'';?> value="1"><?php echo __('Approved')?></option>
                    <option <?php echo ($approvalStatus==2)?'selected':'';?> value="2"><?php echo __('Declined')?></option>
                </select>
                <span style='display: none; color: red'><?php echo __('Please select atleast one value')?></span>
            </div>
        </div>

        <div class="admin__field _required" style='display: none;'>
            <label class="admin__field-label" for="declineMsg">
                <span><?php echo __('Reason of Ad. Decline')?></span>
            </label>
            <div class="admin__field-control" >
                <textarea id="declineMsg" name="declineMsg" class="input-text decline_msg admin__control-textarea"></textarea>
                <span style='display: none; color: red'><?php echo __('Please select atleast one value')?></span>
            </div>
        </div>
    </form>
</div>

<script type="text/javascript">
    var imageflag = 0;
    var contentType = "<?php echo $contentType;?>";
    var storeId = "<?php echo $storeId; ?>";
    function goBack()
    {
        window.location.href= "<?php echo $this->getUrl('mpadvertisementmanager/pricing/selleradspurchasedetail');?>";
    }
    require(['jquery', 'jquery/ui'], function($){ 
        if (contentType == 1) {
            setTimeout(
                function(){ 
                    jQuery("#image_store option[value="+storeId+"]").attr('selected', 'selected');  
                    jQuery('.category').find('*').attr('disabled', true);
                    jQuery('.product').find('*').attr('disabled', true);
                    jQuery('.html').find('*').attr('disabled', true);
                    jQuery('.imagecls').find('*').attr('disabled', true);
                }, 0500);
        }
        if (contentType == 2) {
            var productId = "<?php echo $productId; ?>"; 
            setTimeout(
                function(){ 
                    jQuery("#product_id option[value="+productId+"]").attr('selected', 'selected');
                    jQuery("#product_store option[value="+storeId+"]").attr('selected', 'selected');
                    jQuery('.category').find('*').attr('disabled', true);
                    jQuery('.product').find('*').attr('disabled', true);
                    jQuery('.imagecls').find('*').attr('disabled', true);
                    
                }, 0500);   
        }
        if (contentType == 3) {
            var categoryId = "<?php echo $categoryId; ?>";
            setTimeout(
                function(){ 
                    jQuery("#category_id option[value="+categoryId+"]").attr('selected', 'selected');
                    jQuery("#category_store option[value="+storeId+"]").attr('selected', 'selected');   
                    jQuery('.category').find('*').attr('disabled', true);
                    jQuery('.product').find('*').attr('disabled', true);
                    jQuery('.html').find('*').attr('disabled', true);
                    jQuery('.imagecls').find('*').attr('disabled', true);
                }, 0500);
        }
        if (contentType == 4) {
            setTimeout(
                function(){ 
                    jQuery("#html_store option[value="+storeId+"]").attr('selected', 'selected');   
                    jQuery('.category').find('*').attr('disabled', true);
                    jQuery('.product').find('*').attr('disabled', true);
                    jQuery('.html').find('*').attr('disabled', true);
                    jQuery('.imagecls').find('*').attr('disabled', true);
                }, 0500);
        }
        
        jQuery(document).on('click', '#save', function(){
            if (jQuery(".status").val() == '2' || jQuery(".status").val() == null) {
                event.preventDefault();
                jQuery(".status").next().css({"color": "red", 'display':'block'});
            } else {
                jQuery(".status").next().css({'display':'none'});
            }

            if (!jQuery(".approval_status").val()) {
                event.preventDefault();
                jQuery(".approval_status").next().css({"color": "red", 'display':'block'});
            } else {
                jQuery(".approval_status").next().css({'display':'none'});
            }

            if (!jQuery(".require.decline_msg").val() && jQuery(".require.decline_msg").length) {
                event.preventDefault();
                jQuery(".require.decline_msg").next().css({"color": "red", 'display':'block'});
            } else {
                jQuery(".require.decline_msg").next().css({'display':'none'});
            }
        });
        jQuery(document).on('change', '#approvalStatus', function(){
            if (jQuery(this).val() != 2) {
                jQuery(".decline_msg").closest('._required').hide();
                jQuery(".decline_msg").removeClass('require');
            } else {
                jQuery(".decline_msg").closest('._required').show();
                jQuery(".decline_msg").addClass('require');
            }
        });

    });


</script>
<script type="text/javascript">
    require([
        'jquery',
        'mage/adminhtml/wysiwyg/tiny_mce/setup'
        ], function(jQuery){

            var config = {}, 
            editor;

            jQuery.extend(config, {
                settings: {
                    theme_advanced_buttons1 : 'bold,italic,|,justifyleft,justifycenter,justifyright,|,' +
                    'fontselect,fontsizeselect,|,forecolor,backcolor,|,link,unlink,image,|,bullist,numlist,|,code',
                    theme_advanced_buttons2: null,
                    theme_advanced_buttons3: null,
                    theme_advanced_buttons4: null
                }
            });

            editor = new tinyMceWysiwygSetup(
                'html_editor',
                config
                );

            editor.turnOn();

            jQuery('#html_editor')
            .addClass('wysiwyg-editor')
            .data('wysiwygEditor', editor);
        });
    </script>
