<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpMassUpload
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

$helper = $this->helper("Webkul\MpMassUpload\Helper\Data");
$id = (int)$this->getRequest()->getParam('id');
if ($id) {
    $dataflowProfile = $block->getDataflowProfileById($id);
    $mappedProfileFields = $block->getMappedProfileFields($id);
    $attributeSetId = $dataflowProfile->getAttributeSetId();
    $attributeIds = $block->getAllAttributes($attributeSetId);
    ?>
    <script id="fieldmapTemplate" type="text/x-jquery-tmpl">
        <tr class="field-row">
            <td><?php echo __("In Database"); ?>:</td>
            <td>
                <select name="mage_attribute[<%- data.fieldIndex %>]" class=" required-entry _required select admin__control-select wk-fieldmap-attr-select" data-validate="{'validate-select':true}">
                    <option value=""><?php echo __("Choose an attribute"); ?></option>
                    <?php
                    foreach ($attributeIds as $attributeId) {
                        $attribute = $block->getCatalogResourceEavAttribute($attributeId);
                        ?>
                        <option value="<?php echo $attribute['attribute_code']; ?>">
                            <?php echo $attribute['attribute_code']; ?>
                        </option>
                        <?php
                    } ?>
                </select>
            </td>
            <td>
                &lt;--&gt;
            </td>
            <td>
                <?php echo __("In File"); ?>:
            </td>
            <td>
                <input class="wk-fieldmap-attr-input input-text admin__control-text required-entry _required" type="text" name="file_attribute[<%- data.fieldIndex %>]" data-validate="{required:true}">
            </td>
            <td>
                <button title="Remove" type="button" class="scalable delete wk-fieldmap-row-delete">
                    <span>
                        <span>
                            <?php echo __("Remove"); ?>
                        </span>
                    </span>
                </button>
            </td>
        </tr>
    </script>
    <div class="admin__field field field-profile_name  required _required" id="wk-dataflow-profile-field-wrapper" style="display:none;">
        <label for="profile_name" class="admin__field-label">
            <span><?php echo __("Field Mapping"); ?></span>
        </label>
        <fieldset>
            <legend><?php echo __("Field Mapping"); ?></legend>
            <div class="profile_entity_type_product">
                <table id="wk-fieldmap-container">
                    <?php
                    $i = 0;
                    foreach ($mappedProfileFields as $mappedProfileField) {
                        $mageAttribute = $mappedProfileField['mage_attribute'];
                        $fileAttribute = $block->escapeHtml($mappedProfileField['file_attribute']);
                        ?>
                        <tr class="field-row">
                            <td><?php echo __("In Database"); ?>:</td>
                            <td>
                                <select name="mage_attribute[<?php echo $i?>]" class=" required-entry _required select admin__control-select wk-fieldmap-attr-select" data-validate="{'validate-select':true}" aria-required='true'>
                                    <option value=""><?php echo __("Choose an attribute"); ?></option>
                                    <?php
                                    foreach ($attributeIds as $attributeId) {
                                        $attribute = $block->getCatalogResourceEavAttribute($attributeId);
                                        ?>
                                        <option value="<?php echo $attribute['attribute_code']; ?>" <?php if ($mageAttribute == $attribute['attribute_code']): ?>selected<?php endif; ?>>
                                            <?php echo $attribute['attribute_code']; ?>
                                        </option>
                                        <?php
                                    } ?>
                                </select>
                            </td>
                            <td>
                                &lt;--&gt;
                            </td>
                            <td>
                                <?php echo __("In File"); ?>:
                            </td>
                            <td>
                                <input class="wk-fieldmap-attr-input input-text admin__control-text required-entry _required" type="text" name="file_attribute[<?php echo $i?>]" data-validate="{required:true}" value="<?php echo $fileAttribute; ?>" aria-required='true'>
                            </td>
                            <td>
                                <button title="Remove" type="button" class="scalable delete wk-fieldmap-row-delete">
                                    <span>
                                        <span>
                                            <?php echo __("Remove"); ?>
                                        </span>
                                    </span>
                                </button>
                            </td>
                        </tr>
                        <?php
                        $i = $i+1;
                    } ?>
                </table>
            </div>
            <button title="Remove" type="button" class="scalable wk-fieldmap-row-add">
                <span>
                    <span>
                        <?php echo __("Add Field Mapping"); ?>
                    </span>
                </span>
            </button>
        </fieldset>
    </div>
    <?php
    $data = [
        "fieldIndex" => $i
    ];
    $data = $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($data);
    ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "dataflowprofile":  <?php echo $data ?>
            }
        }
    </script>
<?php
} ?>
