<!-- last edited 30-Jan-2019 -->
<?php
use Magento\Framework\App\Action\Action;
?>
<?php
$fskProductCounter = 0;
$fskUser = 0;
$loggin = 0;

$loggedInCustomerdata = $this->helper('Mangoit\FskRestricted\Helper\Data')->getCustomerModelSession();
$loggin = $loggedInCustomerdata['is_login'];
if ($loggin != 0) {
    $customerRepository = $loggedInCustomerdata['customerRepository'];
}

/*$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
if($customerSession->isLoggedIn()) {
 $customerId = $customerSession->getCustomer()->getId();
 $customerRepository = $objectManager->create('Magento\Customer\Model\Customer')->load($customerId);
 $loggin = 1;
}*/
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');

$_category_config = $this->helper('Smartwave\Porto\Helper\Data')->getConfig('porto_settings/category');
$_category_grid_config = $this->helper('Smartwave\Porto\Helper\Data')->getConfig('porto_settings/category_grid');
$_product_label_config = $this->helper('Smartwave\Porto\Helper\Data')->getConfig('porto_settings/product_label');
$move_actions = "";
$flex_grid = "";
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php echo __('We can\'t find products matching the selection.') ?></div></div>
    <?php else: ?>
        <?php echo $block->getToolbarHtml() ?>
        <?php echo $block->getAdditionalHtml() ?>
        <?php
        if ($block->getMode() == 'grid') {
            $viewMode = 'grid';
            $image = 'category_page_grid';
            $hover_image = 'category_page_grid-hover';
            $showDescription = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $columns = 'columns'.$_category_grid_config['columns'];
            $move_actions = $_category_grid_config['move_actions'];
            if(isset($_category_grid_config['flex_grid']) && $_category_grid_config['flex_grid'])
                $flex_grid = "flex-grid";
        } else {
            $viewMode = 'list';
            $image = 'category_page_list';
            $hover_image = 'category_page_list-hover';
            $showDescription = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
            $columns = '';
        }
        $image_width = ($_category_config['ratio_width'])?$_category_config['ratio_width']:300;
        $image_height = ($_category_config['ratio_height'])?$_category_config['ratio_height']:300;
        ?>
        <div class="products wrapper <?php echo $viewMode; ?> <?php echo $columns; ?> <?php echo $flex_grid; ?> products-<?php echo $viewMode; ?>">
            <?php $iterator = 1; ?>
            <ol class="products list items product-items <?php if(isset($_category_config['qty_field']) && $_category_config['qty_field']):?>has-qty<?php endif;?>">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($_productCollection as $_product): ?>
                    <?php echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                    <div class="product-item-info" data-container="product-grid">
                        <!-- Product Image -->
                        <div class="product photo product-item-photo">
                            <a href="<?php echo $_product->getProductUrl() ?>" tabindex="-1">
                                <?php
                                if($_category_config['aspect_ratio'])
                                    $productImage = $_imagehelper->init($_product, $image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($image_width);
                                else
                                    $productImage = $_imagehelper->init($_product, $image)->resize($image_width, $image_height);
                                $productImageUrl = $productImage->getUrl();
                                ?>
                                <img class="product-image-photo default_image" src="<?php echo $productImageUrl; ?>" alt="<?php echo $productImage->getLabel(); ?>"/>
                                <?php if($_category_config['alternative_image']): ?>
                                    <?php
                                    if($_category_config['aspect_ratio'])
                                        $productHoverImage = $_imagehelper->init($_product, $hover_image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($image_width);
                                    else
                                        $productHoverImage = $_imagehelper->init($_product, $hover_image)->resize($image_width, $image_height);
                                    $productHoverImageUrl = $productHoverImage->getUrl();
                                    ?>
                                    <?php if($productImageUrl != str_replace("/thumbnail/","/small_image/",$productHoverImageUrl)): ?>
                                        <img class="product-image-photo hover_image" src="<?php echo $productHoverImageUrl; ?>" alt="<?php echo $productHoverImage->getLabel(); ?>"/>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </a>
                            <?php
                            $product_label = "";
                            if($_product_label_config['sale_label']) {
                                $orgprice = $_product->getPrice();
                                $specialprice = $_product->getSpecialPrice();
                                $specialfromdate = $_product->getSpecialFromDate();
                                $specialtodate = $_product->getSpecialToDate();
                                $today = time();
                                if(!$specialprice)
                                    $specialprice = $orgprice;
                                if($specialprice < $orgprice) {
                                    if((is_null($specialfromdate) && is_null($specialtodate)) || ($today >= strtotime($specialfromdate) && is_null($specialtodate)) || ($today <= strtotime($specialtodate) && is_null($specialfromdate)) || ($today >= strtotime($specialfromdate) && $today <= strtotime($specialtodate))){
                                        if($_product_label_config['sale_label_percent']) {
                                            $save_percent = 100-round(($specialprice/$orgprice)*100);
                                            $product_label .= '<div class="product-label sale-label">'.'-'.$save_percent.'%'.'</div>';
                                        } else {
                                            $product_label .= '<div class="product-label sale-label">'.$_product_label_config['sale_label_text'].'</div>';
                                        }
                                    }
                                }
                            }
                            if($_product_label_config['new_label']) {
                                $now = date("Y-m-d");
                                $newsFrom= substr($_product->getData('news_from_date'),0,10);
                                $newsTo=  substr($_product->getData('news_to_date'),0,10);
                                
                                if ($newsTo != '' || $newsFrom != ''){
                                    if (($newsTo != '' && $newsFrom != '' && $now>=$newsFrom && $now<=$newsTo) || ($newsTo == '' && $now >=$newsFrom) || ($newsFrom == '' && $now<=$newsTo)) {
                                        $product_label .= '<div class="product-label new-label">'.$_product_label_config['new_label_text'].'</div>';
                                    }
                                }
                            }
                            if($product_label)
                                echo '<div class="product-labels">'.$product_label.'</div>';
                            ?>
                            <?php if($_category_config['actions'] && $move_actions): ?>
                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions">
                                        <div class="actions-primary">
                                            <?php if ($_product->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form" action="<?php echo $postParams['action']; ?>" method="post">
                                                    <input type="hidden" name="product" value="<?php echo $postParams['data']['product']; ?>">
                                                    <input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                    <?php if(isset($_category_config['qty_field']) && $_category_config['qty_field']):?>
                                                        <div class="qty-box">
                                                            <a href="javascript:void(0)" class="qtyminus"><i class="porto-icon-minus"></i></a>
                                                            <input type="text" name="qty" id="qty" maxlength="12" value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>" title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty" data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"/>
                                                            <a href="javascript:void(0)" class="qtyplus"><i class="porto-icon-plus"></i></a>
                                                        </div>
                                                    <?php endif;?>
                                                    <?php echo $block->getBlockHtml('formkey')?>
                                                    <button type="submit"
                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart primary">
                                                    <span><?php echo __('Add to Cart') ?></span>
                                                </button>
                                            </form>
                                            <?php else: ?>
                                                <?php if ($_product->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="mis_btn stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                            <?php if ($block->getMode() == 'grid'): ?>
                                                <?php if($_category_config['addtowishlist']): ?>
                                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                    <a href="#"
                                                    class="action towishlist actions-secondary"
                                                    title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                    aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                    data-post='<?php echo $block->getAddToWishlistParams($_product); ?>'
                                                    data-action="add-to-wishlist"
                                                    role="button">
                                                    <span><?php echo __('Add to Wish List') ?></span>
                                                </a>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    <?php if($_category_config['addtocompare']): ?>
                                        <?php
                                        $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                        ?>
                                        <a href="#"
                                        class="action tocompare actions-secondary"
                                        title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                        aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                        data-post='<?php echo $compareHelper->getPostDataParams($_product); ?>'
                                        role="button">
                                        <span><?php echo __('Add to Compare') ?></span>
                                    </a>
                                <?php endif; ?>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
                <div class="product details product-item-details">
                    <?php
                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                    ?>
                    <?php if(!$_category_grid_config['move_title']):?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                            href="<?php echo $_product->getProductUrl() ?>"><?php
                            $in = $_helper->productAttribute($_product, $_product->getName(), 'name');
                            $name = strlen($in) > 45 ? substr($in,0,45)."..." : $in;
                            echo $name;
                            ?></a>
                        </strong>
                    <?php endif;?>
                    <?php if($_category_config['rating_star']): ?>
                        <?php
                        $review_html = $block->getReviewsSummaryHtml($_product, $templateType);
                        ?>
                        <?php if($review_html): ?>
                            <?php echo $review_html; ?>
                            <?php else: ?>
                                <div class="product-reviews-summary short">
                                    <div class="rating-summary">
                                        <span class="label"><span>Rating:</span></span>
                                        <div class="rating-result" title="0%">
                                            <span style="width:0"><span>0%</span></span>
                                        </div>
                                    </div>
                                </div>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if($_category_grid_config['move_title']):?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                href="<?php echo $_product->getProductUrl() ?>"><?php
                                $in = $_helper->productAttribute($_product, $_product->getName(), 'name');
                                $name = strlen($in) > 45 ? substr($in,0,45)."..." : $in;
                                echo $name;
                                ?></a>
                            </strong>
                        <?php endif;?>
                        <?php if ($showDescription):?>
                            <div class="product description product-item-description">
                                <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>"
                                 class="action more"><?php echo __('Learn More') ?></a>
                             </div>
                         <?php endif; ?>
                         <?php if($_category_config['product_price']): ?>
                            <?php echo $block->getProductPrice($_product) ?>
                        <?php endif; ?>
                        <?php echo $block->getProductDetailsHtml($_product); ?>
                        
                        <?php if($_category_config['actions'] && !$move_actions): ?>
                            <div class="product-item-inner">
                                <div class="product actions product-item-actions">
                                    <?php if ($block->getMode() == 'grid'): ?>
                                        <?php if($_category_config['addtowishlist']): ?>
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                            <a href="#"
                                            class="action towishlist actions-secondary <?php if(isset($_category_config['qty_field']) && $_category_config['qty_field']):?>has-qty<?php endif;?>"
                                            title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                            aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                            data-post='<?php echo $block->getAddToWishlistParams($_product); ?>'
                                            data-action="add-to-wishlist"
                                            role="button">
                                            <span><?php echo __('Add to Wish List') ?></span>
                                        </a>
                                    <?php endif; ?>
                                <?php endif; ?>
                            <?php endif; ?>
                            <div class="actions-primary">
                                <?php if ($_product->isSaleable()): ?>
                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                    <form data-role="tocart-form" action="<?php echo $postParams['action']; ?>" method="post" class="add_to_cart_<?php echo $postParams['data']['product']; ?>">
                                        <input type="hidden" name="product" value="<?php echo $postParams['data']['product']; ?>">
                                        <input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                        <?php if(isset($_category_config['qty_field']) && $_category_config['qty_field']):?>
                                            <div class="qty-box">
                                                <a href="javascript:void(0)" class="qtyminus"><i class="porto-icon-minus"></i></a>
                                                <input type="text" name="qty" id="qty" maxlength="12" value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>" title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty" data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"/>
                                                <a href="javascript:void(0)" class="qtyplus"><i class="porto-icon-plus"></i></a>
                                            </div>
                                        <?php endif;?>
                                        <?php echo $block->getBlockHtml('formkey')?>
                                        <?php 
                                        if ($loggin == 1) {
                                           $fsk = $_product->getFskProductType();
                                           $fskUser = $customerRepository->getFskCustomer();
                                       } else {
                                           $fsk = $_product->getFskProductType();
                                           $fskUser = '0';
                                       }
                                       ?>
                                       <?php if(($fsk == '1') && ( ($fskUser == '0' ) || ($fskUser == '') )  ) :?>
                                       <button type="button"
                                       title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                       class="action tocart primary fsk-product-addtocart-button"
                                       id="fsk-product-addtocart-button_<?php echo $fskProductCounter;?>" data-attr="<?php echo $postParams['data']['product']; ?>" >
                                       <span><?php echo __('Add to Cart'); $fskProductCounter++; ?></span>
                                   </button>
                                   <?php elseif (($fsk == '1') && ($fskUser == '1' ) ): ?>
                                   <button type="submit"
                                   title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                   class="action tocart primary" data-attr="<?php echo $postParams['data']['product']; ?>">
                                   <span><?php echo __('Add to Cart') ?></span>
                               </button>
                               <?php elseif ($fsk == '0' || $fsk ==''): ?>
                                <button type="submit"
                                title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                class="action tocart primary" data-attr="<?php echo $postParams['data']['product']; ?>">
                                <span><?php echo __('Add to Cart') ?></span>
                            </button>
                        <?php endif; ?>
                    </form>

                    <?php else: ?>
                        <?php if ($_product->getIsSalable()): ?>
                            <div class="stock available"><span><?php echo __('In stock') ?></span></div>
                            <?php else: ?>
                                <div class=" mis_btn stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>
                    <?php if ($block->getMode() != 'grid'): ?>
                        <?php if($_category_config['addtowishlist']): ?>
                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                            <a href="#"
                            class="action towishlist actions-secondary <?php if(isset($_category_config['qty_field']) && $_category_config['qty_field']):?>has-qty<?php endif;?>"
                            title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                            aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                            data-post='<?php echo $block->getAddToWishlistParams($_product); ?>'
                            data-action="add-to-wishlist"
                            role="button">
                            <span><?php echo __('Add to Wish List') ?></span>
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
            <?php endif; ?>
            <?php if($_category_config['addtocompare']): ?>
                <?php
                $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                ?>
                <a href="#"
                class="action tocompare actions-secondary <?php if(isset($_category_config['qty_field']) && $_category_config['qty_field']):?>has-qty<?php endif;?>"
                title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                data-post='<?php echo $compareHelper->getPostDataParams($_product); ?>'
                role="button">
                <span><?php echo __('Add to Compare') ?></span>
            </a>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>
</div>
</div>
<?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
<?php endforeach; ?>
</ol>
</div>
<?php if(isset($_category_grid_config['infinite_scroller']) && $_category_grid_config['infinite_scroller']):?>
    <div class="infinite-loader"><span class="loading"><i class="ajax-loader small animate-spin"></i><?php echo __("Loading ..."); ?></span><a href="javascript:void(0)" class="btn-load-more"><?php echo __("Load More ..."); ?></a></div>
<?php endif;?>
<?php echo $block->getToolbarHtml() ?>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {}
        }
    }
</script>
<?php endif; ?>
<?php if ($block->getMode() == 'grid'): ?>
    <script type="text/javascript">
        require([
            'jquery'        
            ], function ($) {
                $('.main .products.grid .product-items li.product-item:nth-child(2n)').addClass('nth-child-2n');
                $('.main .products.grid .product-items li.product-item:nth-child(2n+1)').addClass('nth-child-2np1');
                $('.main .products.grid .product-items li.product-item:nth-child(3n)').addClass('nth-child-3n');
                $('.main .products.grid .product-items li.product-item:nth-child(3n+1)').addClass('nth-child-3np1');
                $('.main .products.grid .product-items li.product-item:nth-child(4n)').addClass('nth-child-4n');
                $('.main .products.grid .product-items li.product-item:nth-child(4n+1)').addClass('nth-child-4np1');
                $('.main .products.grid .product-items li.product-item:nth-child(5n)').addClass('nth-child-5n');
                $('.main .products.grid .product-items li.product-item:nth-child(5n+1)').addClass('nth-child-5np1');
                $('.main .products.grid .product-items li.product-item:nth-child(6n)').addClass('nth-child-6n');
                $('.main .products.grid .product-items li.product-item:nth-child(6n+1)').addClass('nth-child-6np1');
                $('.main .products.grid .product-items li.product-item:nth-child(7n)').addClass('nth-child-7n');
                $('.main .products.grid .product-items li.product-item:nth-child(7n+1)').addClass('nth-child-7np1');
                $('.main .products.grid .product-items li.product-item:nth-child(8n)').addClass('nth-child-8n');
                $('.main .products.grid .product-items li.product-item:nth-child(8n+1)').addClass('nth-child-8np1');
            });
        </script>
    <?php endif; ?>
<?php endif; ?>
<?php
echo $block->getChildHtml('filter_toggle');
?>
<div id="loginMessage" style="display: none;">
    <p><?php echo __('If you want to purches this item you have to login first.'); ?></p>
    <input type="button" id="btn-close" value="Close">
</div>
<input type="hidden" class="product-to-cart">
<div id="fskMessage" style="display: none;">
    <p><?php echo __('You are going to order a product, which can be purchased from legal age only (mind. 18 years old) as per merchant.')?></p>
    <p><?php echo __('You can order only if you are 18 years an older!')?></p>
    <p><?php echo __('The delivery will happen against an age verification check only. This will happen while the logistic company hands over the item personally to an adult only..')?></p> 
    <input type="button" id="btn-verify" value="<?php echo __('Verify Now'); ?>">
    <input type="button" id="btn-continue" value="<?php echo __('Continue');?>">
    <input type="button" id="btn-cancel" value="<?php echo __('Cancel');?>">
</div>
<div id="verify-form" style="display: none;">
 <form class="form" id="uploadForm_list" action="<?php echo $this->getUrl('fskverified/fsk/fskdoc') ?>" method="post" enctype="multipart/form-data" >
     <fieldset class="fieldset">
         <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Upload Passport/ Identity Card.') ?></span></legend>
         <input name="form_key" type="hidden" value="<?php echo $this->getFormKey();?>">
         <br>
         <div class="field required">
             <label for="number" class="label">
                 <span><?php /* @escapeNotVerified */ echo __('Upload File') ?></span>
             </label>
             <div class="control">
             </div>
         </div>
     </fieldset>

     <div class="actions-toolbar">
         <div class="primary">
             <button type="submit" class="action submit primary" id="submit-btn_list">
                 <span><?php  echo __('Submit') ?></span>
             </button>
         </div>
     </div>

 </form>
</div>

<script type="text/javascript">
    require(['jquery','vesallFancybox'],
        function($) { 
            $(document).on('click','.fsk-product-addtocart-button', function() {
                var productId = $(this).attr('data-attr');
                $('.product-to-cart').val(productId);
                var loging = "<?php echo $loggin;?>";
                console.log("log : "+loging);
                var fskCustomer = "<?php echo $fskUser;?>";
                console.log("fskuser : "+fskCustomer);
                if (loging < 1) {
                    $.fancybox({
                        'padding': '0px',
                        'autoScale': true,
                        'closeBtn' : true,
                        'transitionIn': 'fade',
                        'transitionOut': 'fade',
                        'type': 'inline',
                        'href': '#loginMessage',
                        'onComplete': function() {

                            $.cookie('fskPopUp', 'shown');
                        },
                        'helpers': {
                            overlay: {
                                closeClick: false,
                                locked: false
                            }
                        }
                    });
                } else {
                    if (fskCustomer != '1') {
                        $.fancybox({
                            'padding': '0px',
                            'autoScale': true,
                            'closeBtn' : true,
                            'transitionIn': 'fade',
                            'transitionOut': 'fade',
                            'type': 'inline',
                            'href': '#fskMessage',
                            'onComplete': function() {

                                $.cookie('fskPopUp', 'shown');
                            },
                            'helpers': {
                                overlay: {
                                    closeClick: false,
                                    locked: false
                                }
                            }
                        });
                    }
                }


                $("#btn-close").click(function(){
                    $.fancybox.close();
                });

                $("#btn-cancel").click(function(){
                    $.fancybox.close();
                });

                $("#btn-verify").click(function(){
                    $.fancybox.close();
                    $.fancybox({
                        'padding': '5px',
                        'autoScale': true,
                        'closeBtn' : true,
                        'transitionIn': 'fade',
                        'transitionOut': 'fade',
                        'type': 'inline',
                        'href': '#verify-form',
                        'onComplete': function() {

                            $.cookie('fskPopUp', 'shown');
                        },
                        'helpers': {
                            overlay: {
                                closeClick: false,
                                locked: false
                            }
                        }
                    });            
                });

                $("#submit-btn_list").click(function(e){
                    var fileUpload = $('#customer-file').val().split('.').pop().toLowerCase();
                    var fileName = $('#customer-file').val();
                    console.log("file name :"+fileName);
                    if($.inArray(fileUpload, ['gif','png','jpg','jpeg','pdf']) == -1) {
                        alert('invalid file!');
                        e.preventDefault();
                    } else {
                        var pId = $('.product-to-cart').val();
                        $('.add_to_cart_'+pId).submit();  
                    }        
                });

            });
            $("#btn-continue").click(function(){
                $.fancybox.close(true); 
                var pId = $('.product-to-cart').val();
                $('.add_to_cart_'+pId).submit();         
            });
        });
</script>
<script type="text/javascript">
require(['jquery','vesallFancybox'],
        function($) { 
    var btn_text = '';
    var btn_text_array = [];

    jQuery('.tocart').each(function(){
      console.log(jQuery(this).find("span").text());
      btn_text_array.push(jQuery(this).find("span").text());  
    });

    function unique(list) {
        var result = [];
        jQuery.each(list, function(i, e) {
            if (jQuery.inArray(e, result) == -1) result.push(e);
        });
        return result;
    }

    window.language_text = unique(btn_text_array)[0];
    window.language_adding = "<?php echo __('Adding...');?>";
    window.language_added = "<?php echo __('Added');?>";

    console.log('language_text'+language_text);
    console.log('language_adding'+language_adding);
    console.log('language_added'+language_added);

    setTimeout(
        function(){ 
            var count = 0;
            jQuery('.product-item-details').each(function(){
                if( jQuery(this).find('.price-box').length > 0){
                   /*console.log(count++);*/
                } else {
                    jQuery(this).find('.product-item-name').after("<div class='mis_price_div'></div>");
                }
            });
        },
    10);

});
</script>