
<?php
    $faqCollection = $block->getSellerProductCollection();
    // echo "<pre>";
    // print_r($faqCollection->getData());
    // die('died');

 ?>

<div class="mis_faq_list">
    <?php /*<h2 class="block-title"><?php echo __('Faq list')?></h2>
    <div class="mis_faq">
        <a href="<?php echo $this->getUrl('faqs/product/newfaq'); ?>"><?php echo __('Add New Faq');?></a>
    </div> */?>


    <form action="<?php echo $this->getUrl('amazon/producttoamazon/synctoamazon'); ?>" method="get" id="form-productlist-filter" name="formProductlistFilter" novalidate="novalidate" class="__web-inspector-hide-shortcut__">
        <button class="button" title="Delete Products" type="submit" style="float: left;padding: 5px 5px 5px 0;" id="mass-delete-butn">
            <span><span><?php echo __('Move to amazon'); ?></span></span>
        </button>
        <table cellspacing="0" class="border wk-mp-list-table wk-mp-list-container-table">
            <thead>
                <tr class="wk-content">
                    <th class="wk-check-first-td">
                        <span>
                            <input type="checkbox" name="mpselecctall" value="all" id="mpselecctall"/>
                        </span>
                    </th>
                    <th class="wk-first-td">
                        <span class="label mis-name">
                            <?php echo __('Id')?>
                        </span>
                    </th>
                    <th>
                        <span class="label mis-name">
                            <?php echo __('Name')?>
                        </span>
                    </th>
                    <th>
                        <span class="label mis-identifier">
                            <?php echo __('Product Identifier')?>
                        </span>
                    </th>
                    <th class="wk-list-th-display">
                        <span class="label mis-type">
                            <?php echo __('Type')?>
                        </span>
                    </th>
                    <th class="wk-list-th-display">
                        <span class="label mis-sku">
                            <?php echo __('Sku')?>
                        </span>
                    </th>                       
                </tr>
            </thead>
            <tbody>
                <?php
                    if (!empty($faqCollection)): ?>
                        <?php foreach ($faqCollection as $faqValue): 
                            $productDetail = $block->getLoadProduct($faqValue->getMageproductId());
                            $attrVal = $productDetail->getIdentificationValue(); 
                            // echo "<pre>";
                            // print_r(get_class_methods($productDetail));
                            // print_r($attrVal);
                            // die('died');
                        ?>  
                            <input type="hidden" name="seller_id" value="<?php echo $faqValue->getSellerId(); ?>"/>
                             <tr class="wk-row-view">
                                <td class="wk-check-first-td">
                                    <span>
                                        <input type="checkbox" name="mageProEntityIds[]" class="mpcheckbox" value="<?php echo $faqValue->getMageproductId(); ?>"/>
                                    </span>
                                </td>
                                <td class="wk-first_td">
                                    <input type="hidden" class="hidden-id" value="<?php echo $faqValue->getId(); ?>" />
                                    <div class="label name">
                                        <div class="wk-pro-divide2">
                                            <div style="width:100%;">
                                                <a href="<?php echo $this->getUrl('marketplace/product/edit/',['id' => $faqValue->getProductId()]) ?>">
                                                    <?php echo $productDetail->getName() ?>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <td>        
                                    <span class="label amz-name">
                                        <?php echo $productDetail->getName() ?>
                                    </span>
                                </td>
                                <td>        
                                    <span class="label amz-description">
                                        <?php echo $attrVal ?>
                                    </span>
                                </td>
                                <td>        
                                    <span class="label amz-is-active">
                                        <?php echo $productDetail->getTypeId(); ?>
                                    </span>
                                </td>
                                <td>        
                                    <span class="label amz-edit-individual">
                                        <?php echo $productDetail->getSku() ?>
                                    </span>
                                </td>                     
                            </tr>
                    <?php  endforeach; ?>
                        
                <?php endif; ?>
            </tbody>
        </table>
    </form>
    <?php  if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>  
</div>
<script type="text/javascript">
    jQuery(document).on('click','#mpselecctall', function (event) {
        if (this.checked) {
            jQuery('.mpcheckbox').each(function () {
                this.checked = true;
            });
        } else {
            jQuery('.mpcheckbox').each(function () {
                this.checked = false;
            });
        }
    });
</script>