<!-- Last Edited 30-Jan-2019 -->
<style type="text/css">
#product_addtocart_form .box-tocart .fieldset > div {
 margin-bottom: 10px !important;
 display: inline-block;
 vertical-align: top;
}
.paypal-button {display: none;}
#instant-purchase {display: none;}
</style>
<?php
$fskProductCounter = 0;
/** @var $block \Magento\Catalog\Block\Product\View */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$loggin = 0;
if($customerSession->isLoggedIn()) {
 $customerId = $customerSession->getCustomer()->getId();
 $customerRepository = $objectManager->create('Magento\Customer\Model\Customer')->load($customerId);
 $loggin = 1;
}
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
                    <div class="control">
                        <input type="number"
                        name="qty"
                        id="qty"
                        maxlength="12"
                        value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                        title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                        data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                    </div>
                    <div class="qty-changer">
                        <a href="javascript:void(0)" class="qty-inc"><i class="porto-icon-up-dir"></i></a>
                        <a href="javascript:void(0)" class="qty-dec"><i class="porto-icon-down-dir"></i></a>
                    </div>
                </div>
            <?php endif; ?>
            <?php 
            if ($customerSession->isLoggedIn()) {
                $fsk = $_product->getFskProductType();
                $fskUser = $customerRepository->getFskCustomer();
                if ($fskUser != 1) {
                 $fskUser = 0;
             }            
         } else {
            $fsk = $_product->getFskProductType();
            $fskUser = 0;
        }
        ?>
        <div class="actions">
            <?php if(($fsk == "1") && ($fskUser != 1)) { ?>
                <button type="button"
                title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                class="action primary tocart fsk-product-addtocart-button"
                id="fsk-product-addtocart-button_<?php echo $fskProductCounter;?>">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle;?></span>
            </button>
            <button type="submit"
            title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
            class="action primary tocart"
            id="product-addtocart-button" style="display: none;">
            <span><?php /* @escapeNotVerified */ echo $buttonTitle;?></span>
        </button>  
    <?php 
            $fskProductCounter++; 
        } elseif (($fsk == "1") && ($fskUser == 1)) { ?>
        <button type="submit"
        title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
        class="action primary tocart"
        id="product-addtocart-button">
        <span><?php /* @escapeNotVerified */ echo $buttonTitle;?></span>
    </button> 
<?php } else { ?>
    <button type="submit"
    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
    class="action primary tocart"
    id="product-addtocart-button">
    <span><?php /* @escapeNotVerified */ echo $buttonTitle;?></span>
</button>  
<?php } ?>

<?php echo $block->getChildHtml('', true) ?>
</div>

</div>
</div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
            "radioCheckboxClosest": ".nested"
        }
    }
}
</script>
<?php else : ?>
    <script>
        require([
            'jquery',
            'mage/mage',
            'Magento_Catalog/product/view/validation',
            'Magento_Catalog/js/catalog-add-to-cart'
            ], function ($) {
                'use strict';

                $('#product_addtocart_form').mage('validation', {
                    radioCheckboxClosest: '.nested',
                    submitHandler: function (form) {
                        var widget = $(form).catalogAddToCart({
                            bindSubmit: false
                        });
                        widget.catalogAddToCart('submitForm', $(form));

                        return false;
                    }
                });
            });
        </script>
    <?php endif; ?>
    <script type="text/javascript">
        require(["jquery","vesallFancybox"], function ($) {
            $(window).load(function(){
                $(".fsk-product-addtocart-button").click(function(){
                    var isLoggin = "<?php echo $loggin;?>";
                    var fskCustomer = "<?php echo $fskUser;?>";
                    if (isLoggin < 1) {
                        console.log("nothing");
                        $.fancybox({
                            'padding': '0px',
                            'autoScale': true,
                            'closeBtn' : true,
                            'transitionIn': 'fade',
                            'transitionOut': 'fade',
                            'type': 'inline',
                            'href': '#loginMessage',
                            'onComplete': function() {

                                $.cookie('fskPopUp', 'shown');
                            },
                            'helpers': {
                                overlay: {
                                    closeClick: false,
                                    locked: false
                                }
                            }
                        });
                    } else {
                        if (fskCustomer < 1) {
                            $.fancybox({
                                'padding': '0px',
                                'autoScale': true,
                                'closeBtn' : true,
                                'transitionIn': 'fade',
                                'transitionOut': 'fade',
                                'type': 'inline',
                                'href': '#fskMessage',
                                'onComplete': function() {

                                    $.cookie('fskPopUp', 'shown');
                                },
                                'helpers': {
                                    overlay: {
                                        closeClick: false,
                                        locked: false
                                    }
                                }
                            });
                        }
                    }
                });

                $("#btn-close").click(function(){
                    $.fancybox.close();
                });

                $("#btn-cancel").click(function(){
                    $.fancybox.close();
                });

                $("#btn-verify").click(function(){
                    $.fancybox.close();
                    $.fancybox({
                        'padding': '5px',
                        'autoScale': true,
                        'closeBtn' : true,
                        'transitionIn': 'fade',
                        'transitionOut': 'fade',
                        'type': 'inline',
                        'href': '#verify-form',
                        'onComplete': function() {

                            $.cookie('fskPopUp', 'shown');
                        },
                        'helpers': {
                            overlay: {
                                closeClick: false,
                                locked: false
                            }
                        }
                    });            
                });

                $("#btn-continue").click(function(){
                    $.fancybox.close(true); 
                    /*$('#product_addtocart_form').submit();*/ 
                    $('#product-addtocart-button').trigger( "click" );
                });

                $("#submit-btn").click(function(e){
                    var fileUpload = $('#customer-file').val().split('.').pop().toLowerCase();
                    var fileName = $('#customer-file').val();
                    if($.inArray(fileUpload, ['gif','png','jpg','jpeg','pdf']) == -1) {
                        alert('invalid file!');
                        e.preventDefault();
                    } else {
                        $('#product_addtocart_form').submit();  
                    }
                });
            });
});
</script>
<div id="loginMessage" style="display: none;">
    <p><?php echo __('If you want to purches this item you have to login first.'); ?></p>
    <input type="button" id="btn-close" value="Close">
</div>
<div id="fskMessage" style="display: none;">
    <p><?php echo __('You are going to order a product, which can be purchased from legal age only (mind. 18 years old) as per merchant.')?></p>
    <p><?php echo __('You can order only if you are 18 years an older!')?></p>
    <p><?php echo __('The delivery will happen against an age verification check only. This will happen while the logistic company hands over the item personally to an adult only..')?></p> 
<input type="button" id="btn-verify" value="<?php echo __('Verify Now');?>">
<input type="button" id="btn-continue" value="<?php echo __('Continue');?>">
<input type="button" id="btn-cancel" value="<?php echo __('Cancel');?>">
</div>
