<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var \Magento\Catalog\Block\Product\View\Details $block */
?>
<style type="text/css">
.ticket-cls{
    line-height: 22px;
    font-weight: 400;
    font-family: "Oswald";
    letter-spacing: 1px;
    text-transform: uppercase;
    color: #fff;
    cursor: pointer;
    font-size: 1.4rem;
    background: #FEC10D;
}
</style>
<?php
$_product = \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Framework\Registry::class)->registry('product');
$loggedIn =  $this->helper('Mangoit\FskRestricted\Helper\Data')->isLoggedIn();
$session = $this->helper('Mangoit\FskRestricted\Helper\Data')->getSession();
$productName = 'Product Name :'.$_product->getName();
$productId = $_product->getId();
$vendorEmail =  $this->helper('Mangoit\FskRestricted\Helper\Data')->getVendorEmail($productId);
$session->start();
$session->unsetVendorEmail();
$session->setVendorEmail($vendorEmail);
$ticketAction = 'po_zendesk/ticket/create/';
?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>
<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $porto_helper = $this->helper('Smartwave\Porto\Helper\Data');
    $_helper = $this->helper('Smartwave\Porto\Helper\Customtabs');
    $product_config = $porto_helper->getConfig('porto_settings/product');
    $static_block_tab = $product_config['custom_block_next_tab'];
    $custom_block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
    /*$_product = \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Framework\Registry::class)->registry('product');*/
    $page_type = $_product->getData('product_page_type');
    if(!$page_type)
        $page_type = isset($_config['product_page_type'])?$_config['product_page_type']:'';
    if($custom_block) {
        $custom_block->setBlockId($static_block_tab);
    }
    $tab_style = "";
    if(isset($product_config['tab_style']) && $product_config['tab_style'])
        $tab_style = $product_config['tab_style'];
    if($page_type == 'wide_grid')
        $tab_style = 'vertical';
?>
    <?php if($product_config['tab_full_background']):?>
    <div class="move-product-tab">
        <div class="row">
            <div class="<?php if(!$page_type && $custom_block && $static_block_tab):?>col-md-9<?php else:?>col-md-12<?php endif;?>">
    <?php endif;?>
                <div class="product info detailed <?php echo $tab_style; ?> <?php if($page_type == 'sticky_right'): ?>fullwidth-row<?php endif; ?>">
                <?php $layout = $block->getLayout(); ?>
                <?php if(!$tab_style || $tab_style != "sticky"): ?>
                    <div class="product data items <?php if($page_type == 'sticky_right'): ?>container<?php endif; ?>" data-mage-init='{"tabs":{"openedState":"active"}}'>
                        <?php foreach ($detailedInfoGroup as $name):?>
                            <?php
                            $html = $layout->renderElement($name);
                            if (!trim($html)) {
                                continue;
                            }
                            $alias = $layout->getElementAlias($name);
                            $label = $block->getChildData($alias, 'title');
                            ?>
                            <div class="data item title"
                                 aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title"
                                 data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>">
                                <a class="data switch"
                                   tabindex="-1"
                                   data-toggle="switch"
                                   href="#<?php /* @escapeNotVerified */ echo $alias; ?>"
                                   id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title">
                                    <span><?php /* @escapeNotVerified */ echo $label; ?></span>
                                </a>
                            </div>
                            <div class="data item content" id="<?php /* @escapeNotVerified */ echo $alias; ?>" data-role="content">
                                <?php /* @escapeNotVerified */ echo $html; ?>
                            </div>
                        <?php endforeach;?>
                        <?php
                        if($custom_cms_tabs = $_helper->getCustomTabs($_product)) {
                            $i = 1;
                            foreach($custom_cms_tabs as $_item) {
                                ?>
                                <div class="data item title"
                                     aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo "custom-".$i;?>-title"
                                     data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo "custom-".$i;?>">
                                    <a class="data switch"
                                       tabindex="-1"
                                       data-toggle="switch"
                                       href="#<?php /* @escapeNotVerified */ echo "custom-".$i; ?>"
                                       id="tab-label-<?php /* @escapeNotVerified */ echo "custom-".$i;?>-title">
                                        <span><?php /* @escapeNotVerified */ echo $_item['tab_title']; ?></span>
                                    </a>
                                </div>
                                <div class="data item content" id="<?php /* @escapeNotVerified */ echo "custom-".$i; ?>" data-role="content">
                                    <?php /* @escapeNotVerified */ echo $_item['tab_content']; ?>
                                </div>
                                <?php
                                $i++;
                            }
                        }
                        ?>
                    </div>
                <?php elseif($tab_style && $tab_style == "sticky"): ?>
                    <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
                        <?php foreach ($detailedInfoGroup as $name):?>
                            <?php
                            $html = $layout->renderElement($name);
                            if (!trim($html)) {
                                continue;
                            }
                            $alias = $layout->getElementAlias($name);
                            $label = $block->getChildData($alias, 'title');
                            $alias = str_replace(".","_",$alias);
                            ?>
                            <div class="data item title <?php if($alias == 'reviews'):?>active<?php endif; ?>" aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>"
                            data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>">
                                <a class="data switch" href="#<?php /* @escapeNotVerified */ echo $alias; ?>">
                                    <?php /* @escapeNotVerified */ echo $label.'55'; ?>
                                </a>
                            </div>
                        <?php endforeach;?>
                        <?php
                        if($custom_cms_tabs = $_helper->getCustomTabs($_product)) {
                            $i = 1;
                            foreach($custom_cms_tabs as $_item) {
                                ?>
                                <div class="data item title active">
                                    <a class="data switch" href="#<?php /* @escapeNotVerified */ echo "custom-".$i; ?>">
                                        <?php /* @escapeNotVerified */ echo $_item['tab_title']; ?>
                                    </a>
                                </div>
                                <?php
                                $i++;
                            }
                        }
                        ?>
                        <?php foreach ($detailedInfoGroup as $name):?>
                            <?php
                            $html = $layout->renderElement($name);
                            if (!trim($html)) {
                                continue;
                            }
                            $alias = $layout->getElementAlias($name);
                            $label = $block->getChildData($alias, 'title');
                            $alias = str_replace(".","_",$alias);
                            ?>
                            <div class="data item content" id="<?php /* @escapeNotVerified */ echo $alias; ?>">
                                <?php /* @escapeNotVerified */ echo $html; ?>
                            </div>
                        <?php endforeach;?>
                        <?php
                        if($custom_cms_tabs = $_helper->getCustomTabs($_product)) {
                            $i = 1;
                            foreach($custom_cms_tabs as $_item) {
                                ?>
                                <div class="data item content" id="<?php /* @escapeNotVerified */ echo "custom-".$i; ?>">
                                    <?php /* @escapeNotVerified */ echo $_item['tab_content']; ?>
                                </div>
                                <?php
                                $i++;
                            }
                        }
                        ?>
                    </div>
                <?php endif; ?>
                <script type="text/javascript">
                    require([
                        'jquery'
                    ], function ($) {
                        $(document).ready(function(){
                            <?php if($tab_style && $tab_style == "vertical"): ?>
                            $(".product.info.detailed.vertical .product.data.items .data.item.title").off("classadded").on("classadded",function(){
                                $(this).parent().css("min-height",$(this).next().outerHeight()+"px");
                            });
                            <?php elseif($tab_style && $tab_style == "sticky"): ?>
                            var sticky_tabs;
                            var is_sticky = false;
                            $(window).scroll(function(){
                                if($(window).scrollTop() >= $(".product.info.detailed").offset().top-50){
                                    if(!is_sticky){
                                        $(".product.info.detailed.sticky").before('<div class="product-tabs-container"><div class="container"></div></div>');
                                        $(".product.info.detailed.sticky .product.data.items > .item.title").each(function(){
                                            $(".product-tabs-container > .container").append($(this).clone().detach());
                                        });
                                        $(".product-tabs-container .item.title > a").off("click").on("click", function(){
                                            $($(this).attr("href")).scrollToMe();
                                            return false;
                                        });
                                        <?php if ($porto_helper->getConfig('porto_settings/header/sticky_header')): ?>
                                        $(".product-tabs-container").addClass("has-sticky-header");
                                        <?php endif; ?>
                                        <?php if ($porto_helper->getConfig('porto_settings/header/mobile_sticky_header')): ?>
                                        $(".product-tabs-container").addClass("has-mobile-sticky-header");
                                        <?php endif; ?>
                                        is_sticky = true;
                                    }
                                } else {
                                    $(".product-tabs-container").remove();
                                    is_sticky = false;
                                }
                            });
                            $(".product.info.detailed.sticky .product.data.items > .item.title > a").off("click").on("click", function(){
                                $($(this).attr("href")).scrollToMe();
                                return false;
                            });
                            $(".product-reviews-summary .reviews-actions a.action.view").off("click").on("click", function(){
                                $("#reviews").scrollToMe();
                                return false;
                            });
                            $(".product-reviews-summary .reviews-actions a.action.add").off("click").on("click", function(){
                                $("#review-form").scrollToMe();
                                return false;
                            });
                            <?php endif; ?>
                        });
                    });
                </script>
                </div>
    <?php if($product_config['tab_full_background']):?>
            </div>
            <?php if(!$page_type && $custom_block && $static_block_tab):?>
            <div class="col-md-3">
                <div class="custom-block-tab">
                    <?php echo $custom_block->toHtml(); ?>
                </div>
            </div>
            <?php endif;?>
        </div>
    </div>
    <?php endif;?>
<?php endif; ?>
<div class="primary submit">
    <input type="button" name="ticket" class="ticket-cls" value="<?php echo __('Ask Question');?>">
</div>
<script type="text/javascript">
    require([
        'jquery'
        ], function ($) {
            $(document).on('click', '.ticket-cls', function(){
                var loggedInUser = "<?php echo $loggedIn; ?>";
                if (loggedInUser >= 1) {
                    $.fancybox({
                        'padding': '5px',
                        'autoScale': true,
                        'closeBtn' : true,
                        'transitionIn': 'fade',
                        'transitionOut': 'fade',
                        'type': 'inline',
                        'href': '#ticket-form',
                        'onComplete': function() {

                            $.cookie('fskPopUp', 'shown');
                        },
                        'helpers': {
                            overlay: {
                                closeClick: false,
                                locked: false
                            }
                        }
                    }); 
                } else {
                    $.fancybox({
                        'padding': '5px',
                        'autoScale': true,
                        'closeBtn' : true,
                        'transitionIn': 'fade',
                        'transitionOut': 'fade',
                        'type': 'inline',
                        'href': '#loginmsg',
                        'onComplete': function() {

                            $.cookie('fskPopUp', 'shown');
                        },
                        'helpers': {
                            overlay: {
                                closeClick: false,
                                locked: false
                            }
                        }
                    });
                }
            });

            $(document).on('click', '#submit', function(){
                var productName = "<?php echo $productName;?>"
                var ticketSub =  $("#ticket_subject").val();
                var comment =  $("#comment").val();
                if ((ticketSub.trim().length == 0) && (comment.trim().length == 0)) {
                    event.preventDefault();
                    $("#error").html("<?php echo __('Subject and Comment are required.');?>");
                    $("#ticket_subject").css('border', 'red');
                } else if ((ticketSub.trim().length) == 0) {
                    event.preventDefault();
                    $("#error").html("<?php echo __('Subject is required.');?>");
                    $("#ticket_subject").css('border', 'red');
                } else if ((comment.trim().length) == 0) {
                    event.preventDefault();
                    $("#error").html("<?php echo __('Comment is required.');?>");
                    $("#comment").css('border', 'red');
                } else {
                    $("#error").html("");
                    $("#comment").css('border', 'white');
                } 
            });
        });
    </script>
    <div style="display: none" id="ticket-form">
        <p id="error" style="color: red"></p>
        <form method="post" id="zendesk-ticket-form" action="<?php echo $this->getUrl().$ticketAction;?>" enctype="multipart/form-data">
            <h3 style="text-align: center;"><span><?php echo __('New Question');?></span></h3>
            <table>
             <tr>
                 <td><input name="form_key" type="hidden" value="<?php echo $block->getFormKey() ?>"/></td>
             </tr>
             <tr>
                 <td><?php echo __('Subject');?><span>*</span></td>
                 <td><input type="text" id="ticket_subject" name="subject"></td>
             </tr>
             <tr>
                 <td><?php echo __('Comment');?><span>*</span></td>
                 <td><textarea name="comment" style="width:100%" title="comment" id="comment" class="input-text" cols="5" rows="3"><?php echo $productName;?></textarea></td>
             </tr>
             <tr>
                <td>
                    <?php echo __('Upload File')?>
                </td>
                <td>
                    <input type="file" name="file[]" id="zendesk_upload_button" class="zendesk-editor--item">
                </td>
            </tr>
            <tr>
             <td>
                 <input type="submit" name="ticketbtn" value="<?php echo __('Submit');?>" id="submit">
             </td>
         </tr>
     </table>
 </form>
</div>
<div style="display: none" id="loginmsg">
    <p> <?php echo __('To ask new question you have to login first.');?></p>
</div>
