<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) 2010-2018 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

// @codingStandardsIgnoreFile

/** @var $block \Webkul\Marketplace\Block\Product\Create */

$helper = $this->helper('Webkul\Marketplace\Helper\Data');
$tooltipHelper = $this->helper('Mangoit\MisTooltip\Helper\Data');
$section_id = 'new_product';
$product_type_id = 'product_type';
$store_id = $tooltipHelper->getStoreId();
$productTypeToolTip = $tooltipHelper->getToolTipData($store_id, $section_id, $product_type_id);


$partner=$helper->getSeller();
if(($partner['twitter_id']=='')||($partner['facebook_id']=='')||($partner['banner_pic']=='')||($partner['logo_pic']=='')||($partner['company_locality']=='')||($partner['country_pic']=='')||($partner['company_description']=='')){?>
		<div class="wk-profile-alert" style="display: none;">
			<strong><?php echo __('Warning')?>! </strong><?php echo __('Please Complete')?>
			<a href="<?php echo $block->getUrl('marketplace/account/editprofile', ['_secure' => $this->getRequest()->isSecure()])?>" style="color: inherit;"><?php echo __('Your Profile')?></a>
			<span class="wk-close">X</span>
		</div>
<?php 
} ?>
<style type="text/css">
.tooltip {
    position: relative;
    display: inline-block ;
    opacity: 1 !important;

    /*border-bottom: 1px dotted black;*/
}

span.tooltip {
    display: inline-block;
    vertical-align: middle;
    opacity: inherit !important;
}

.field.profile label {
    display: inline-block;
    vertical-align: middle;
    width: 100%;
}

.tooltip .tooltiptext {
    visibility: hidden;
    width: 400px;
    background-color: #555;
    color: #fff;
    text-align: center;
    border-radius: 6px;
    padding: 5px 0;
    position: absolute;
    z-index: 1;
    bottom: 125%;
    left: 50%;
    margin-left: -60px;
    opacity: 0;
    transition: opacity 0.3s;
}

.tooltip .tooltiptext::after {
    content: "";
    position: absolute;
    top: 100%;
    left: 15%;
    margin-left: -5px;
    border-width: 5px;
    border-style: solid;
    border-color: #555 transparent transparent transparent;
}

.tooltip:hover .tooltiptext {
    visibility: visible;
    opacity: 1;
}
</style>
<form action="<?php echo $block->getUrl('marketplace/product/create', ['_secure' => $this->getRequest()->isSecure()]) ?>" enctype="multipart/form-data" method="post" id="form-customer-product-new" data-mage-init='{"validation":{}}'>
	<div class="wk-mp-design">
		<fieldset class="fieldset info wk-mp-fieldset">
			<legend class="legend">
				<span><?php echo __('Add New Product') ?></span>
				<button class="button wk-mp-btn" title="Continue" type="submit" style="display: none;">
                    <span><span><?php echo __('Continue') ?></span></span>
                </button>
                <button class="button wk-mp-btn" title="Continue" id="mis_profile_check" type="button">
					<span><span><?php echo __('Continue') ?></span></span>
				</button>
			</legend>
			<?php echo $block->getBlockHtml('formkey')?>
			<?php echo $block->getBlockHtml('seller.formkey')?>
			<?php if (count($helper->getAllowedSets()) > 1) { ?>
				<div class="field required">
					<label class="label"><?php echo __('Attribute Set') ?>:</label>
					<div class="control">
						<select name="set" class="required-entry">
						<?php foreach($helper->getAllowedSets() as $set) {?>
							<option value="<?php echo $set['value'] ?>"><?php echo __($set['label'])?></option>
						<?php } ?>
						</select>
					</div>
				</div>
			<?php 
			} else { 
				$allowedSets = $helper->getAllowedSets();
				?>
				<input type="hidden" name="set" value="<?php echo $allowedSets[0]['value'] ?>" />
				<?php 
			} ?>
			<?php if (count($helper->getAllowedProductTypes()) > 1) { ?>
				<div class="field required">
					<label class="label"><?php echo __('Product Type') ?>:
                    <?php if(count($productTypeToolTip) > 0):?>
                        <span class="tooltip mis_tooltip">
                            <img src="<?php echo $helper->getMediaUrl().'marketplace/icon/info.png'?>" width="20px"/>
                            <span class="price_cal tooltiptext">
                                <?php echo ( (count($productTypeToolTip) > 0) ? $productTypeToolTip[0]['tooltip_text'] : '');?>
                            </span>                            
                        </span>
                    <?php endif; ?>
                    </label>
					<div class="control">
						<select name="type" class="required-entry">
						<?php 
						foreach($helper->getAllowedProductTypes() as $type) {?>
							<option value="<?php echo $type['value'] ?>"><?php echo __($type['label'])?></option>
						<?php } ?>
						</select>
					</div>
				</div>
			<?php 
			} else { 
				$allowedProducts = $helper->getAllowedProductTypes();
				?>
				<input type="hidden" name="type" value="<?php echo $allowedProducts[0]['value'] ?>" />
				<?php 
			} ?>
			<?php echo $block->getChildHtml(); ?>
		</fieldset>
	</div>		
</form>
<div class="buttons-set">
	<p class="required">* <?php echo __('Required Fields') ?></p>		
	<p class="back-link">
		<a href="javascript:;" onclick="javascript: window.history.back();" class="left">&laquo; <?php echo __('Back') ?></a>
	</p>
</div>

<div id="profile_required" style="display: none;">
	<p><?php echo __('Please complete you profile details to add new product') ?></p>		
</div>
<script type="text/javascript">
	require([
        'jquery',
        'Magento_Ui/js/modal/modal',
        'vesallFancybox',
        ], function($, modal){
        	var attention_title = "<?php echo __('Attention')?>";
        	console.log('Attention: '+attention_title);
        	$('#mis_profile_check').on('click', function(event){
                var self = this;
        		event.preventDefault();
                var url = "<?php echo $this->getUrl('marketplce/vendor/checkvendorprofile'); ?>";
                $.ajax({
                    type: "POST",
                    url: url,
                    async : true,
                    showLoader: true,
                    success: function(data)
                    { 
                    	if (data == 0) {
	                        var options = {
				                type: 'popup',
				                responsive: true,
				                innerScroll: true,
				                title: ''+attention_title,
				                buttons: [{
				                    text: $.mage.__('Okay'),
				                    class: 'mis_profile_okay',
				                    click: function () {
				                        // this.closeModal();
                                        window.location.href = "<?php echo $this->getUrl('marketplace/account/editprofile/') ?>";
				                    }
				                }]
				            };
				            var popup = modal(options, $('#profile_required'));
				            $("#profile_required").modal("openModal");
                    	} else {
                            $('#form-customer-product-new').submit();
                        }
                    }
                });
        	})
        });
</script>