<?php 
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) 2010-2018 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

// @codingStandardsIgnoreFile

/** @var $block \Webkul\Marketplace\Block\Product\Create */
$tooltipHelper = $this->helper('Mangoit\MisTooltip\Helper\Data');
$section_id = 'new_product';

$product_type_id = 'product_type';
$fsk_id = 'fsk';
$product_cat_type_id = 'product_cat_type';
$product_meta_title_id = 'product_meta_title';
$product_meta_keywords_id = 'product_meta_keywords';
$product_meta_description_id = 'product_meta_description';
$related_product_id = 'related_product';
$internal_note_tooltip = 'internal_note';
$visibility_tooltip = 'visibility';
$net_shipping_price_to_myGermany = 'shipping_price_to_mygermany';
$net_price = 'net_price';
 
$store_id = $tooltipHelper->getStoreId();
$productTypeToolTip = $tooltipHelper->getToolTipData($store_id, $section_id, $product_type_id);
$fskToolTip = $tooltipHelper->getToolTipData($store_id, $section_id, $fsk_id);
$productCatTypeToolTip = $tooltipHelper->getToolTipData($store_id, $section_id, $product_cat_type_id);
$productMetaTitleToolTip = $tooltipHelper->getToolTipData($store_id, $section_id, $product_meta_title_id);
$productMetaDescToolTip = $tooltipHelper->getToolTipData($store_id, $section_id, $product_meta_description_id);
$productMetaKeywordToolTip = $tooltipHelper->getToolTipData($store_id, $section_id, $product_meta_keywords_id);
$relatedProductToolTip = $tooltipHelper->getToolTipData($store_id, $section_id, $related_product_id);
$internalNoteToolTip = $tooltipHelper->getToolTipData($store_id, $section_id, $internal_note_tooltip);
$visibilityToolTip = $tooltipHelper->getToolTipData($store_id, $section_id, $visibility_tooltip);
$net_shipping_price_to_myGermany_ToolTip = $tooltipHelper->getToolTipData($store_id, $section_id, $net_shipping_price_to_myGermany);
$netPriceToolTip = $tooltipHelper->getToolTipData($store_id, $section_id, $net_price);


$helper = $this->helper('Webkul\Marketplace\Helper\Data');
$misHelper = $this->helper('Mangoit\Marketplace\Helper\Data');
$totalCustomField = 0;
$formula = 'Click here to check your Earnings! =  Your Price + Shipping Costs - Fees (myGermany + Exchange + Payment).';
 $priceCalUrl = $this->getUrl('mygermany-price-calculation');   



$attrArray = $this->helper('Mangoit\Vendorcommission\Helper\Data')->getCustomAttributeOption();
// ---------------------- Working of Custom Field -------------------------
$productId = $this->getRequest()->getParam('id');
$fieldModel = $this->helper('Mangoit\VendorField\Helper\Data')->getModel($productId);
$row = 0;
$faqRow = 0;
// ----------------------- End Working of Custom Field ------------------------
$productNoteCollection = $this->helper('Mangoit\Vendorcommission\Helper\Data')->getProductNoteAttribute();
// working of vendor attribute
$customerSession = $this->helper('Mangoit\VendorAttribute\Helper\Data')->getCustomerIdFromSession();
$vendorAttributeCollection = $this->helper('Mangoit\VendorAttribute\Helper\Data')->getVendorProductAttribute();
// $vendorData = $vendorAttributeCollection->getCollection()->addFieldToFilter('vendor_id',['eq' => $customerSession]);
$vendorData = $vendorAttributeCollection->getCollection()->addFieldToFilter('vendor_id',['eq' => $customerSession])->addFieldToFilter('is_visible',['eq' => '1']);
$adminAttribute = $vendorAttributeCollection->getCollection()->addFieldToFilter('vendor_id',['eq' => '0'])->addFieldToFilter('is_visible',['eq' => '1']);
// end of work

$product_hint_status = $helper->getProductHintStatus();
$currency_code = $helper->getCurrentCurrencyCode();
$currency_symbol = $helper->getCurrencySymbol();
$product_id=$this->getRequest()->getParam('id');
$product_coll = $block->getProduct($product_id);
if ($product_coll->getCustomAttribute('product_note')) {
    $productNote = $product_coll->getCustomAttribute('product_note')->getValue();
} else {
    $productNote = '';
}

// ****************************** Working of fsk ********************
if ($product_coll->getCustomAttribute('fsk_product_type')) {
    $fskVal = $product_coll->getCustomAttribute('fsk_product_type')->getValue();
} else {
    $fskVal = '';
}
// ****************************** Working end ***********************

// ****************************** Working of restricted ********************
if ($product_coll->getCustomAttribute('restricted_product')) {
    $restrictedProduct = $product_coll->getCustomAttribute('restricted_product')->getValue();
} else {
    $restrictedProduct = '';
}
// ****************************** Working end ***********************
// ****************************** Working of cashback ********************
if ($product_coll->getCustomAttribute('wallet_cash_back')) {
    $cashback = $product_coll->getCustomAttribute('wallet_cash_back')->getValue();
} else {
    $cashback = 0;
}
// ****************************** Working end ***********************

/* validation */

$is_configurable = 0;
if ($product_coll['type_id']=='configurable') {
    $is_configurable = 1;
}    
/* */

$catIds = [];
foreach ($product_coll->getCategoryIds() as $key => $value) {
    array_push($catIds, $value);    
}
$attribute_set_id = $product_coll['attribute_set_id'];
if ($this->getRequest()->getParam('set')) {
    $attribute_set_id = $this->getRequest()->getParam('set');
}
$product_collNew = $block->getProductBySku($product_coll->getsku());
$skuType = $helper->getSkuType();
//FAQ collection 
$faqCollection = $misHelper->getProductFaqCollection($customerSession, $productId);


$sensitiveAttrs = $misHelper->getSensitiveAttributes();
$productSensitiveAttrs = $misHelper->getProductSensitiveAttributes($productId);
$unserAttrs = '';
if ($productSensitiveAttrs->getSensitiveAttributes()) {
    $unserAttrs = unserialize($productSensitiveAttrs->getSensitiveAttributes());
}

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

$product_attribute = $objectManager->create('\Magento\Catalog\Model\ResourceModel\Product\Attribute\Collection');
$attribute_code_array = ['product_cat_type','lithium','liquid_check','liquid','oil','restricted_product','fsk_product_type'];
$attribute_label_array = [];

foreach ($product_attribute as $attr_value) {
    if (in_array($attr_value->getAttributeCode(), $attribute_code_array)) {
        $attribute_label_array[$attr_value->getAttributeCode()] = $attr_value->getStoreLabel();
    }
}

?>
<style type="text/css">
	.page-actions-buttons
    {
        display: none;
    }
    .pricetool
    {
        text-decoration: none;
    }
    .err-text
    {
        display: none;
        color: red;
    }
    .add-field
    {
        padding: 5px;
        background-color: #dbdbdb!important;
        color: #514943!important;
        text-decoration: none;
    }
    .sensitive_attr, .custom_field_change{
        float: left;
        margin-right: 10px;
    }
    .mis_hidden_class{display: none}
    
    .tooltip {
        position: relative;
        display: inline-block;
        opacity: inherit !important;
    /*border-bottom: 1px dotted black;*/
    }
    
.tooltip .tooltiptext {
    visibility: hidden;
    width: 400px;
    background-color: #555;
    color: #fff;
    text-align: center;
    border-radius: 6px;
    padding: 5px 0;
    position: absolute;
    z-index: 1;
    bottom: 125%;
    left: 50%;
    margin-left: -60px;
    opacity: 0;
    transition: opacity 0.3s;
}

.tooltip .tooltiptext::after {
    content: "";
    position: absolute;
    top: 100%;
    left: 15%;
    margin-left: -5px;
    border-width: 5px;
    border-style: solid;
    border-color: #555 transparent transparent transparent;
}
    /*.tooltip .tooltiptext {
        text-decoration: none;
        visibility: hidden;
        width: 150px;
        background-color: black;
        color: #fff;
        text-align: center;
        border-radius: 6px;
        padding: 5px 0;

        position: absolute;
        z-index: 1;
    }*/

.tooltip:hover .tooltiptext {
    visibility: visible;
    opacity: 1;
}
</style>
<form action="<?php echo $block->getUrl('marketplace/product/save', ['_secure' => $this->getRequest()->isSecure()]) ?>" enctype="multipart/form-data" method="post" id="edit-product" data-form="edit-product" data-mage-init='{"validation":{}}'>
    <div class="wk-mp-design" id="wk-bodymain">
        <fieldset class="fieldset info wk-mp-fieldset">
            <div data-mage-init='{"formButtonAction": {}}' class="wk-mp-page-title legend">
                <span><?php echo __('Edit Product') ?></span>
                <button class="button btn_type wk-mp-btn mis-edit-btn" title="<?php echo __('Save') ?>" type="submit" id="save-btn" style="display: none;">
                    <span><span><?php echo __('Save') ?></span></span>
                </button>
                <?php if($product_coll->getStatus()==1 && $product_coll->getVisibility()!=1) { ?>
                    <a href="<?php echo $product_coll->getProductUrl()?>" target="blank">
                <?php } else {?>
                    <a href="<?php echo $this->getUrl('marketplace/catalog/view/',['id'=>$product_coll->getId()]) ?>" target="blank">
                <?php }?>
                    <button class="button wk-mp-btn" title="<?php echo __('Preview') ?>" type="button">
                        <span><span><?php echo __('Preview') ?></span></span>
                    </button>
                </a>
                <button class="button btn_type wk-mp-btn mis-edit-btn" title="<?php echo __('Save') ?>" id="btn_type">
                    <span><span><?php echo __('Save') ?></span></span>
                </button>
            </div>
            <input type="hidden" name="selectedCategories" id="selectedCategories" value=''>
            <?php echo $block->getBlockHtml('formkey')?>
            <?php echo $block->getBlockHtml('seller.formkey')?>
            <input id="product_type_id" name="type" type="hidden" value="<?php echo $product_coll['type_id']?>">                    
            <input type="hidden" name="id" value="<?php echo $product_id; ?>" />
            <input type="hidden" name="product_id" value="<?php echo $product_id; ?>" />
            <input type="hidden"  name="product[website_ids][]" id="website" value="<?php echo $product_coll->getStore()->getWebsiteId()?>" title="wstoreids" class="" />               
            <?php if (count($helper->getAllowedSets()) > 1) { ?>
                <div class="field required">
                    <label class="label"><?php echo __('Attribute Set') ?></label>
                    <div class="control">
                        <select name="set" id="attribute-set-id"  class="required-entry">
                        <?php foreach($helper->getAllowedSets() as $set) {?>
                            <option value="<?php echo $set['value'] ?>" <?php if($attribute_set_id==$set['value']){ ?> selected="selected" <?php } ?>><?php echo $set['label']?></option>
                        <?php } ?>
                        </select>
                    </div>
                </div>
            <?php 
            } else { 
                $allowedSets = $helper->getAllowedSets();
                if (!empty($allowedSets)) { ?>
                    <input type="hidden" name="set" id="attribute-set-id" value="<?php echo $allowedSets[0]['value'] ?>" />
                    <?php 
                } else { ?>
                    <input type="hidden" name="set" id="attribute-set-id" value="<?php echo $attribute_set_id ?>" />
                    <?php 
                }
            } ?>    
            <div class="field">
                <label class="label"><?php echo __('Product Category') ?></label>
                <?php
                if($product_hint_status && $helper->getProductHintCategory()){?>
                    <img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProductHintCategory() ?>"/>
                <?php
                } ?>
                
                <?php if ($helper->getIsAdminViewCategoryTree()) { ?>
                    <div data-bind="scope: 'sellerCategory'">
                        <!-- ko template: getTemplate() --><!-- /ko -->
                    </div>
                    <?php $categories = $product_coll->getCategoryIds();?>
                    <script type="text/x-magento-init">
                        {
                            "*": {
                                "Magento_Ui/js/core/app": {
                                    "components": {
                                        "sellerCategory": {
                                            "component": "Webkul_Marketplace/js/product/seller-category-tree",
                                            "template" : "Webkul_Marketplace/seller-category-tree",
                                            "filterOptions": true,
                                            "levelsVisibility": "1",
                                            "options": <?php echo $block->getCategoriesTree()?>,
                                            "value": <?php echo json_encode($categories)?>
                                        }
                                    }
                                }
                            }
                        }
                    </script>
                <?php } else { ?>
                    <div class="wk-field wk-category">
                        <div class="wk-for-validation">
                            <div id="wk-category-label"><?php echo __("CATEGORIES"); ?></div>
                            <?php 
                            $categories = $product_coll->getCategoryIds();
                            $cat_ids=implode(",",$categories);
                            foreach ($categories as $value) {
                                ?>
                                <input type="hidden" name="product[category_ids][]" value="<?php echo $value; ?>" id="wk-cat-hide<?php echo $value; ?>"/>
                                <?php
                            }
                            ?>
                            <?php
                            if($helper->getAllowedCategoryIds()){
                                $storeconfig_catids = explode(',',trim($helper->getAllowedCategoryIds()));
                                foreach($storeconfig_catids as $storeconfig_catid)  {
                                    $cat_model = $block->getCategory()->load($storeconfig_catid); 
                                    if(isset($cat_model["entity_id"]) && $cat_model["entity_id"]){
                                        ?>
                                        <div class="wk-cat-container">
                                            </span><span class="wk-foldersign"></span>
                                            <span class="wk-elements wk-cat-name"><?php echo $cat_model->getName() ?></span>
                                            <?php 
                                            if(in_array($cat_model["entity_id"],$categories)) {?>
                                                <input class="wk-elements" type="checkbox" name="product[category_ids][]" value=<?php echo $cat_model['entity_id'] ?> checked />
                                                <?php 
                                            }else { ?>
                                                <input class="wk-elements" type="checkbox" name="product[category_ids][]" value='<?php echo $cat_model['entity_id'] ?>'/>
                                            <?php 
                                            } ?>
                                        </div> 
                                        <?php 
                                    }
                                }
                            }else{
                                $count = 0;
                                $category_helper = $this->helper('Magento\Catalog\Helper\Category');
                                $category_model = $block->getCategory();
                                $_categories = $category_helper->getStoreCategories();
                                foreach($_categories as $_category) {
                                    $count++;
                                    if(count($category_model->getAllChildren($category_model->load($_category['entity_id'])))-1 > 0){ ?>
                                        <div class="wk-cat-container" style="margin-left:0px;">
                                            <span class="wk-plus">
                                            </span><span class="wk-foldersign"></span>
                                            <span class="wk-elements wk-cat-name"><?php echo $_category->getName() ?></span>
                                            <?php 
                                            if(in_array($_category["entity_id"],$categories)) {?>
                                                <input class="wk-elements" type="checkbox" name="product[category_ids][]" value=<?php echo $_category['entity_id'] ?> checked />
                                                <?php 
                                            }else { ?>
                                                <input class="wk-elements" type="checkbox" name="product[category_ids][]" value='<?php echo $_category['entity_id'] ?>'/>
                                            <?php 
                                            } ?>
                                        </div>
                                        <?php
                                    }else { ?>
                                        <div class="wk-cat-container">
                                            </span><span class="wk-foldersign"></span>
                                            <span class="wk-elements wk-cat-name"><?php echo $_category->getName() ?></span>
                                            <?php 
                                            if(in_array($_category["entity_id"],$categories)) {?>
                                                <input class="wk-elements" type="checkbox" name="product[category_ids][]" value=<?php echo $_category['entity_id'] ?> checked />
                                                <?php 
                                            }else { ?>
                                                <input class="wk-elements" type="checkbox" name="product[category_ids][]" value='<?php echo $_category['entity_id'] ?>'/>
                                            <?php 
                                            } ?>
                                        </div> 
                                        <?php 
                                    }
                                } 
                            } ?>
                        </div>
                    </div>
                <?php } ?>
            </div>
             <?php $product_type_attr =  __('Select Product Type'); ?>
            <div class="field required">
                <label class="label">
                    <?php echo __(
                        (isset($attribute_label_array['product_cat_type'])) ? $attribute_label_array['product_cat_type'] : $product_type_attr);  ?>                        
                <?php if(count($productCatTypeToolTip) > 0): ?>
                <div class="tooltip">
                    <img src="<?php echo $helper->getMediaUrl().'marketplace/icon/info.png'?>" width="20px"/>
                    <span class="tooltiptext">
                        <?php echo ( (count($productCatTypeToolTip) > 0) ? $productCatTypeToolTip[0]['tooltip_text'] : '');?>                    
                    </span>
                </div>
                <?php endif; ?>
                </label>
                <?php
                if($product_hint_status && $helper->getProductHintStock()){?>
                    <img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProductHintStock() ?>"/>
                <?php
                } ?>
                <?php $arrayData = $block->getAttributeArray();?>
                <div class="control">
                    <select id="" class="select" name="product[product_cat_type]">
                    <?php foreach ($attrArray as $key => $value): ?>
                        <option <?php echo $product_coll->getProductCatType()==$value['value']? 'selected':''; ?> value="<?php echo $value['value']; ?>" ><?php echo __($value['label']); ?></option>
                    <?php endforeach; ?>
                    </select>
                </div>
            </div>

            <div class="field required">
                <label class="label">
                    <?php echo __(
                        (isset($attribute_label_array['fsk_product_type'])) ? $attribute_label_array['fsk_product_type'] : 'FSK Compulsory'); ?>
                <?php if(count($fskToolTip) > 0): ?>
                    <div class="tooltip">
                        <img src="<?php echo $helper->getMediaUrl().'marketplace/icon/info.png'?>" width="20px"/>
                        <span class="tooltiptext">
                            <?php echo ( (count($fskToolTip) > 0) ? $fskToolTip[0]['tooltip_text'] : '');?>
                        </span>
                    </div>
                <?php endif; ?>
                </label>
                <?php
                if($product_hint_status && $helper->getProductHintStock()){?>
                    <img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProductHintStock() ?>"/>
                <?php
                } ?>
                <div class="control">
                    <select id="" class="select" name="product[fsk_product_type]">
                        <?php if ($fskVal == 1) { ?>
                            <option value="1" selected="selected"><?php echo __('Yes');?></option>
                            <option value="0"><?php echo __('No');?></option>
                        <?php  } else { ?>
                            <option value="0" selected="selected"><?php echo __('No');?></option>
                            <option value="1"><?php echo __('Yes');?></option>
                        <?php   } ?>
                    </select>
                </div>
            </div>

            <!-- Sensitive attributes work - Start -->
            <?php if (!empty($sensitiveAttrs)): ?>
                <?php foreach ($sensitiveAttrs as $sensAttrValues): 
                    $isRequired = $sensAttrValues->getIsRequired();
                    $attributeSet = '';
                    if (isset($product_coll[$sensAttrValues->getAttributeCode()])) {
                        $attributeSet = $product_coll[$sensAttrValues->getAttributeCode()];
                    }
                    $attrTooltip = $tooltipHelper->getToolTipData($store_id, $section_id, $sensAttrValues->getAttributeCode());
                ?>
                    <div class="field <?php echo (($isRequired) ? 'required' : '') ?>">
                        <label class="label">
                            <?php echo (isset($attribute_label_array[$sensAttrValues->getAttributeCode()])) ? $attribute_label_array[$sensAttrValues->getAttributeCode()] : $sensAttrValues['frontend_label']; ?>
                            <?php if(count($attrTooltip) > 0): ?>
                                <div class="tooltip">
                                    <img src="<?php echo $helper->getMediaUrl().'marketplace/icon/info.png'?>" width="20px"/>
                                    <span class="tooltiptext">
                                        <?php echo ( (count($attrTooltip) > 0) ? $attrTooltip[0]['tooltip_text'] : '');?>
                                    </span>
                                </div>
                            <?php endif; ?>
                        </label>
                        <div class="control">
                            <select id="<?php echo $sensAttrValues->getAttributeCode(); ?>" class="sensitive_attr <?php echo (($isRequired) ? 'required-entry' : '') ?>  select" name="product[mis_2_41_35_sensitive_<?php echo $sensAttrValues->getAttributeCode(); ?>]" style="width: 20%" data-exist="<?php echo (isset($attributeSet) ? (($attributeSet == 1) ? 1 : 0) : '')  ?>" data-attr="<?php echo $sensAttrValues->getAttributeCode(); ?>" >
                                <option value=""><?php echo __('Please select')?></option>
                                <option value="0" <?php echo (isset($attributeSet) ? (($attributeSet == 0) ? 'selected' : '') : '') ?>><?php echo __('No')?></option>
                                <option value="1" <?php echo (isset($attributeSet) ? (($attributeSet == 1) ? 'selected' : '') : '') ?>><?php echo __('Yes')?></option>
                            </select>
                            <?php if($attributeSet && (is_array($unserAttrs))): ?>
                            <?php $valueForCommentBox = $unserAttrs['mis_2_41_35_sensitive_'.$sensAttrValues->getAttributeCode().'_mis_2_41_35_comment']; ?>
                                <input type="text" name="product[mis_2_41_35_sensitive_<?php echo $sensAttrValues->getAttributeCode(); ?>_mis_2_41_35_comment]" class=" sensitive_comment_box" placeholder="Enter comment here" style="width:50% !important;float:left;" value="<?php echo $valueForCommentBox; ?>" />
                            <?php endif; ?>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
            <!-- Sensitive attributes work - End -->
        
            <?php /*if (count($fieldModel->count()) > 0):*/ ?> 
            <?php if (count($fieldModel->getData()) > 0): ?> 
                <?php foreach ($fieldModel as $customVal): ?>
                <?php $isCustomFieldReq  = $customVal->getCustomFieldValue(); ?>
                <?php $vendorInput  = $customVal->getVendorInput(); ?>
                    <div class="field <?php echo (($isCustomFieldReq) ? 'required' : '') ?>">
                        <label class="label"><?php echo $customVal->getCustomFields() ?></label>
                        <!-- <input type="hidden" name="custom_field_value[current_id]" value="<?php //echo $customVal->getId(); ?>"> -->
                        <input type="hidden" name="custom_field_value[<?php echo $customVal->getId(); ?>][field_name]" value="<?php echo $customVal->getCustomFields(); ?>">
                        <div class="control">
                            <select name="custom_field_value[<?php echo $customVal->getId(); ?>][input]" class="custom_field_change <?php echo (($isCustomFieldReq) ? 'required-entry' : '') ?>  select"  style="width: 20%" data-exist="<?php echo (isset($vendorInput) ? (($vendorInput == 1) ? 1 : 0) : '')  ?>" data-attr="<?php echo $customVal->getCustomFields() ?>" data-id="<?php echo $customVal->getId(); ?>">
                                <option value=""><?php echo __('Please select')?></option>
                                <option value="0" <?php echo (isset($vendorInput) ? (($vendorInput == 0) ? 'selected' : '') : '') ?>><?php echo __('No')?></option>
                                <option value="1" <?php echo (isset($vendorInput) ? (($vendorInput == 1) ? 'selected' : '') : '') ?>><?php echo __('Yes')?></option>
                            </select>
                            <?php  if($vendorInput): ?>
                                <input type="text" name="custom_field_value[<?php echo $customVal->getId(); ?>][comment]" class="required-entry custom_field_comment_box" placeholder="Enter comment here" style="width:50%;float:left;" value="<?php echo $customVal->getVendorComments(); ?>" />
                            <?php endif; ?>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>

            <div class="field required">
                <label class="label"><?php echo __('Product Name') ?></label>
                <?php
                if($product_hint_status && $helper->getProductHintName()){?>
                    <img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProductHintName() ?>"/>
                <?php
                } ?>
                <div class="control">
                    <input type="text" class="required-entry input-text" name="product[name]" id="name" value="<?php echo $product_coll->getName(); ?>"/>
                </div>
            </div>
            

            <div class="field" style="display: none;">
                <label class="label"><?php echo __('Country Wise Restricted') ?></label>
                <?php
                if($product_hint_status && $helper->getProductHintStock()){?>
                    <img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProductHintStock() ?>"/>
                <?php
                } ?>
                <div class="control">
                    <select id="" class="select" name="product[restricted_product]">
                        <?php if ($restrictedProduct == 1) { ?>
                            <option value="1" selected="selected"><?php echo __('Yes');?></option>
                            <option value="0"><?php echo __('No');?></option>
                        <?php  } else { ?>
                            <option value="0" selected="selected"><?php echo __('No');?></option>
                            <option value="1"><?php echo __('Yes');?></option>
                        <?php   } ?>
                    </select>
                </div>
            </div>

            <div class="field" style="display: none;">
                <label class="label"><?php echo __('Wallet Cash Back') ?></label>
                <?php
                if($product_hint_status && $helper->getProductHintStock()){?>
                    <img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProductHintStock() ?>"/>
                <?php
                } ?>
                <div class="control">
                    <input type="text" name="product[wallet_cash_back]" value="<?php echo $cashback;?>">
                </div>
            </div>

            <div class="field">
                <label class="label"><?php echo __('Internal Note') ?>
                <?php if(count($internalNoteToolTip) > 0): ?>
                    <div class="tooltip">
                        <img src="<?php echo $helper->getMediaUrl().'marketplace/icon/info.png'?>" width="20px"/>
                        <span class="tooltiptext">
                            <?php echo ( (count($internalNoteToolTip) > 0) ? $internalNoteToolTip[0]['tooltip_text'] : '');?>
                        </span>
                    </div>
                <?php endif; ?>
                </label>
                <div class="control">
                    <textarea class="textarea" id="" name="product[product_note]" ><?php echo $productNote; ?></textarea>
                </div>
            </div>

            <div class="field required">
                <label class="label"><?php echo __('Description') ?></label>
                <?php
                if($product_hint_status && $helper->getProductHintDesc()){?>
                    <img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProductHintDesc() ?>"/>
                <?php
                } ?>
                <div class="control">
                    <textarea name="product[description]" class="required-entry input-text" id="description" rows="5" cols="75" >
                        <?php echo $product_coll->getDescription(); ?>
                    </textarea>      
                    <script type="text/javascript">
                            require([
                                "jquery",
                                "mage/translate",
                                "mage/adminhtml/events",
                                "mage/adminhtml/wysiwyg/tiny_mce/setup"
                            ], function(jQuery) {
                                wysiwygHtmlEditor = new wysiwygSetup("description", {
                                    "width" : "100%",
                                    "height" : "200px",                  
                                    "plugins" : [{"name":"image"},{"name":"code"}],
                                    "tinymce4" : {
                                        "toolbar":"formatselect | bold italic underline | alignleft aligncenter alignright | bullist numlist | link table charmap","plugins":"advlist autolink lists link charmap media noneditable table contextmenu paste code help table",
                                    },
                                    theme_advanced_buttons2: "code"
                                });
                                wysiwygHtmlEditor.setup("exact");
                            });
                    </script>
                </div>
            </div>
            <div class="field">
                <label class="label"><?php echo __('Short Description') ?></label>
                <?php
                if($product_hint_status && $helper->getProductHintShortDesc()){?>
                    <img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProductHintShortDesc() ?>"/>
                <?php
                } ?>
                <div class="control">
                    <textarea name="product[short_description]" class="input-text" id="short_description" rows="5" cols="75" ><?php echo $product_coll->getShortDescription(); ?></textarea>     
                    <script type="text/javascript">
                            require([
                                "jquery",
                                "mage/translate",
                                "mage/adminhtml/events",
                                "mage/adminhtml/wysiwyg/tiny_mce/setup"
                            ], function(jQuery) {
                                wysiwygHtmlEditor = new wysiwygSetup("short_description", {
                                    "width" : "100%",
                                    "height" : "200px",                  
                                    "plugins" : [{"name":"image"},{"name":"code"}],
                                    "tinymce4" : {
                                        "toolbar":"formatselect | bold italic underline | alignleft aligncenter alignright | bullist numlist | link table charmap","plugins":"advlist autolink lists link charmap media noneditable table contextmenu paste code help table",
                                    },
                                    theme_advanced_buttons2: "code"
                                });
                                wysiwygHtmlEditor.setup("exact");
                            });
                    </script>
                </div>
            </div>
            <?php

            $mp_pro_status = 0;
            $mp_pro_coll = $helper->getSellerProductDataByProductId($product_id);
            foreach ($mp_pro_coll as $key => $value) {
                $mp_pro_status = $value['status'];
            }
            if(!$helper->getIsProductEditApproval() && $mp_pro_status==1 || !$helper->getIsProductApproval() && !$helper->getIsProductEditApproval() ){ ?>
                <div class="field required">
                    <label class="label"><?php echo __('Status') ?></label>
                    <?php
                    if($product_hint_status && $helper->getProductHintEnable()){?>
                        <img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProductHintStatus() ?>"/>
                    <?php
                    } ?>
                    <div class="control">
                        <input type="radio" name="status" id="status1" value="1" <?php if($product_coll->getStatus()==1){ echo 'checked="checked"'; } ?>/><?php echo __("Enable"); ?><br>
                        <input type="radio" name="status" id="status2" value="2" <?php if($product_coll->getStatus()==2){ echo 'checked="checked"'; } ?>/><?php echo __("Disable"); ?>
                    </div>
                </div>
            <?php
            } ?>
            <?php 
            if ($skuType == 'static') { ?>
                <div class="field required">
                    <label class="label"><?php echo __('SKU') ?></label>
                    <?php
                    if($product_hint_status && $helper->getProductHintSku()){?>
                        <img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProductHintSku() ?>"/>
                    <?php
                    } ?>
                    <div class="control">
                        <input name="product[sku]" id="sku" class="required-entry input-text" type="text" value="<?php  echo $product_coll->getsku(); ?>"/>
                    </div>
                    <div id="skuavail" >
                        <span class="success-msg skuavailable"><?php echo __('SKU Available') ?></span>
                    </div>
                    <div id="skunotavail" >
                        <span class="error-msg err-text skunotavailable"><?php echo __('SKU Already Exist') ?></span>
                    </div>
                </div>
            <?php
            } ?>
            <div class="field required <?php if($product_coll['type_id']=='configurable'){ ?> no-display <?php } ?>">
                <label class="label"><?php echo __('Net Price') ?><b><?php echo  " (".$currency_symbol.")"; ?></b></label>
                <?php if(count($netPriceToolTip) > 0): ?>
                    <div class="tooltip">
                        <img src="<?php echo $helper->getMediaUrl().'marketplace/icon/info.png'?>" width="20px"/>
                        <span class="tooltiptext">
                            <?php echo ( (count($netPriceToolTip) > 0) ? $netPriceToolTip[0]['tooltip_text'] : '');?>
                        </span>
                    </div>
                <?php endif; ?>
                
                <?php
                if($product_hint_status && $helper->getProductHintPrice()){?>
                    <img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProductHintPrice() ?>"/>
                <?php
                } ?>
                <div class="control">
                    <input type="text" class="required-entry validate-zero-or-greater input-text" name="product[price]" id="price" value="<?php echo number_format($product_coll->getPrice(), 2, '.', ''); ?>" data-ui-id="product-tabs-attributes-tab-fieldset-element-text-product-price"/>
                </div>
            </div>

            <div class="field">
                <label class="label"><?php echo __('Meta Title') ?>
                <?php if(count($productMetaTitleToolTip) > 0): ?>
                    <div class="tooltip">
                        <img src="<?php echo $helper->getMediaUrl().'marketplace/icon/info.png'?>" width="20px"/>
                        <span class="tooltiptext">
                            <?php echo ( (count($productMetaTitleToolTip) > 0) ? $productMetaTitleToolTip[0]['tooltip_text'] : '');?>
                        </span>
                    </div>
                <?php endif; ?>
                </label>
                <div class="control">
                    <input type="text" class="input-text" name="product[meta_title]" id="meta_title" value="<?php echo $product_coll['meta_title'] ?>"/>
                </div>
            </div>
            <div class="field">
                <label class="label"><?php echo __('Meta Keywords') ?>
                <?php if(count($productMetaKeywordToolTip) > 0): ?>
                    <div class="tooltip">
                        <img src="<?php echo $helper->getMediaUrl().'marketplace/icon/info.png'?>" width="20px"/>
                        <span class="tooltiptext">
                            <?php echo ( (count($productMetaKeywordToolTip) > 0) ? $productMetaKeywordToolTip[0]['tooltip_text'] : '');?>
                        </span>
                    </div>
                <?php endif; ?>
                </label>
                <div class="control">
                    <textarea class="textarea" id="meta_keyword" name="product[meta_keyword]"><?php echo $product_coll['meta_keyword'] ?></textarea>
                </div>
            </div>
            <div class="field">
                <label class="label"><?php echo __('Meta Description') ?>
                <?php if(count($productMetaDescToolTip) > 0): ?>
                    <div class="tooltip">
                        <img src="<?php echo $helper->getMediaUrl().'marketplace/icon/info.png'?>" width="20px"/>
                        <span class="tooltiptext">
                            <?php echo ( (count($productMetaDescToolTip) > 0) ? $productMetaDescToolTip[0]['tooltip_text'] : '');?>
                        </span>
                    </div>
                <?php endif; ?>
                </label>
                <div class="control">
                    <textarea class="textarea" id="meta_description" name="product[meta_description]"><?php echo $product_coll['meta_description'] ?></textarea>
                </div>
            </div>
             <div class="field required">
                <label class="label"><?php echo __('Net shipping price to myGermany GmbH') ?><b><?php echo  " (".$currency_symbol.")"; ?></b>
                    <?php if(count($net_shipping_price_to_myGermany_ToolTip) > 0): ?>
                        <div class="tooltip">
                            <img src="<?php echo $helper->getMediaUrl().'marketplace/icon/info.png'?>" width="20px"/>
                            <span class="tooltiptext">
                                <?php echo ( (count($net_shipping_price_to_myGermany_ToolTip) > 0) ? $net_shipping_price_to_myGermany_ToolTip[0]['tooltip_text'] : '');?>
                            </span>
                        </div>
                    <?php endif; ?>
                </label>
                <div class="control">
                    <input type="text" class="required-entry validate-zero-or-greater input-text" name="product[shipping_price_to_mygmbh]" id="shipping_price_to_mygmbh" value="<?php echo number_format($product_coll->getShippingPriceToMygmbh(), 2, '.', ''); ?>" data-ui-id="product-tabs-attributes-tab-fieldset-element-text-product-shipping-price-to-mygmbh"/>
                </div>
            </div>

            <div class="field required mis_fixed_fields">
                <label class="label"><?php echo __('Length of item') ?><b><?php echo __(' (cm)'); ?></b></label>
                <div class="control">
                    <input type="text" class="required-entry validate-zero-or-greater input-text" name="product[mygmbh_shipping_product_length]" id="mygmbh_shipping_product_length" value="<?php echo number_format($product_coll->getMygmbhShippingProductLength(), 2, '.', ''); ?>" data-ui-id="product-tabs-attributes-tab-fieldset-element-text-product-shipping-price-to-mygmbh"/>
                </div>
            </div>
            <div class="field required mis_fixed_fields">
                <label class="label"><?php echo __('Width of item') ?><b><?php echo __(' (cm)'); ?></b></label>
                <div class="control">
                    <input type="text" class="required-entry validate-zero-or-greater input-text" name="product[mygmbh_shipping_product_width]" id="mygmbh_shipping_product_width" value="<?php echo number_format($product_coll->getMygmbhShippingProductWidth(), 2, '.', ''); ?>" data-ui-id="product-tabs-attributes-tab-fieldset-element-text-product-shipping-price-to-mygmbh"/>
                </div>
            </div>
            <div class="field required mis_fixed_fields">
                <label class="label"><?php echo __('Height of item') ?><b><?php echo __(' (cm)'); ?></b></label>
                <div class="control">
                    <input type="text" class="required-entry validate-zero-or-greater input-text" name="product[mygmbh_shipping_product_height]" id="mygmbh_shipping_product_height" value="<?php echo number_format($product_coll->getMygmbhShippingProductHeight(), 2, '.', ''); ?>" data-ui-id="product-tabs-attributes-tab-fieldset-element-text-product-shipping-price-to-mygmbh"/>
                </div>
            </div>
            <div class="field required mis_fixed_fields">
                <label class="label"><?php echo __('Weight of item') ?><b><?php echo __(' (Kg)'); ?></b></label>
                <?php
                if($product_hint_status && $helper->getProductHintWeight()){?>
                    <img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProductHintWeight() ?>"/>
                <?php
                } ?>
                <?php /*<div data-role="weight-switcher">
                    <label data-ui-id="product-tabs-attributes-tab-element-radios-product-product-has-weight-label" for="weight-switcher">
                        <span><?php echo __('Does this have a weight?')?></span>
                    </label>
                    <div class="control">
                        <div class="control">
                            <input type="radio" <?php if ($product_coll['type_id']=='simple' || ($product_coll['type_id']=='configurable' && !empty($product_coll['weight']))) { ?>checked="checked" <?php } ?> class="weight-switcher" id="weight-switcher1" value="1" name="product[product_has_weight]">
                            <label for="weight-switcher1">
                                <span><?php echo __('Yes')?></span>
                            </label>
                        </div>
                        <div class="control">
                            <input type="radio" <?php if ($product_coll['type_id']=='downloadable'||$product_coll['type_id']=='virtual' || ($product_coll['type_id']=='configurable' && empty($product_coll['weight']))) { ?>checked="checked" <?php } ?> class="weight-switcher" id="weight-switcher0" value="0" name="product[product_has_weight]">
                            <label for="weight-switcher0">
                                <span><?php echo __('No')?></span>
                            </label>
                        </div>
                    </div>
                </div> */?>
                <div class="control">
                    <input type="text" class="validate-zero-or-greater input-text required-entry" name="product[weight]" id="weight" value="<?php echo number_format($product_coll->getWeight(), 2, '.', '');?>" <?php if($product_coll['type_id']=='downloadable'||$product_coll['type_id']=='virtual'){ ?> <?php } ?>/>
                    <input type="hidden"  class="weight-switcher" id="weight-switcher1" value="1" name="product[product_has_weight]">
                </div>
            </div>
            <!-- Delivery days work - Start -->
            <?php 
            $deliveryFromDate = 0;
            if ($product_coll->getDeliveryDaysFrom()) {
                $deliveryFromDate = $product_coll->getDeliveryDaysFrom();
            }
            $deliveryFromTo = 0;
            if ($product_coll->getDeliveryDaysTo()) {
                $deliveryFromTo = $product_coll->getDeliveryDaysTo();
            } 
            ?>
            <div class="field required mis_fixed_fields">
                <label class="label"><?php echo __('Delivery days from') ?></label>
                <div class="tooltip">
                    <img src="<?php echo $helper->getMediaUrl().'marketplace/icon/info.png'?>" width="20px"/>
                    <span class="tooltiptext"><?php echo __('Delivery date from vendor\'s warehouse to myGermany warehouse')?></span>
                </div>
                <div class="control">
                    <select class="delivery_days_from select required-entry" style="width: 20%" name="product[delivery_days_from]">
                        <option value=""><?php echo __('Please select')?></option>
                        <?php for ($i=1; $i < 30; $i++){ ?>
                            <option value="<?php echo $i; ?>" <?php echo (($deliveryFromDate == $i) ? 'selected' : '') ?>><?php echo $i; ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>
            <div class="field required mis_fixed_fields">
                <label class="label"><?php echo __('Delivery days to') ?></label>
                <div class="tooltip">
                    <img src="<?php echo $helper->getMediaUrl().'marketplace/icon/info.png'?>" width="20px"/>
                    <span class="tooltiptext"><?php echo __('Delivery date from vendor\'s warehouse to myGermany warehouse')?></span>
                </div>
                <div class="control">
                    <select class="delivery_days_to select required-entry" style="width: 20%" name="product[delivery_days_to]">
                        <option value=""><?php echo __('Please select')?></option>
                        <?php for ($i=1; $i < 31; $i++){ ?>
                            <option value="<?php echo $i; ?>" <?php echo (($deliveryFromTo == $i) ? 'selected' : '');  echo (($deliveryFromDate >= $i) ? 'disabled' : '') ?> ><?php echo $i; ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>
            <!-- Delivery days work - End -->
            <?php if($product_coll['type_id']!='configurable'){ ?>
                <?php echo $block->getChildHtml('customoption_option_edit'); ?>
            <?php } ?>
            <?php echo $block->getChildHtml('marketplace_product_add_configurable'); ?>
            <?php 
                foreach ($adminAttribute->getData() as $key => $value) {
                    $attributeCode = $value['attribute_code'];
                    $attributeData = $this->helper(
                            'Mangoit\VendorAttribute\Helper\Data')->getCustomAttributeOption($attributeCode);
                    $frontType = $attributeData->getFrontendInput();
                    $frontLabel = $attributeData->getFrontendLabel();
                    switch ($frontType) {
                        case 'text':
                            include ($block->getTemplateFile('Webkul_Marketplace::product/textEdit.phtml'));
                            break;
                        case 'textarea':
                            include ($block->getTemplateFile('Webkul_Marketplace::product/textareaEdit.phtml'));
                            break;
                        // case 'date':
                        //     include ($block->getTemplateFile('Webkul_Marketplace::product/dateEdit.phtml'));
                        //     break;
                        // case 'boolean':
                        //     include ($block->getTemplateFile('Webkul_Marketplace::product/yesNoEdit.phtml'));
                        //     break;
                        
                        // case 'select':
                        //     include ($block->getTemplateFile('Webkul_Marketplace::product/selectEdit.phtml'));
                        //     break;

                        case 'multiselect':
                            include ($block->getTemplateFile('Webkul_Marketplace::product/multiselectEdit.phtml'));
                            break;
                            
                        default:
                            break;
                    }
                } // admin attribute
                
            ?>
            <?php 
                
                foreach ($vendorData->getData() as $key => $value) {
                    $attributeCode = $value['attribute_code'];
                    $attributeData = $this->helper(
                            'Mangoit\VendorAttribute\Helper\Data')->getCustomAttributeOption($attributeCode);
                    $frontType = $attributeData->getFrontendInput();
                    $frontLabel = $attributeData->getFrontendLabel();
                    switch ($frontType) {
                        case 'text':
                            include ($block->getTemplateFile('Webkul_Marketplace::product/textEdit.phtml'));
                            break;
                        case 'textarea':
                            include ($block->getTemplateFile('Webkul_Marketplace::product/textareaEdit.phtml'));
                            break;
                        // case 'date':
                        //     include ($block->getTemplateFile('Webkul_Marketplace::product/dateEdit.phtml'));
                        //     break;
                        // case 'boolean':
                        //     include ($block->getTemplateFile('Webkul_Marketplace::product/yesNoEdit.phtml'));
                        //     break;
                        
                        // case 'select':
                        //     include ($block->getTemplateFile('Webkul_Marketplace::product/selectEdit.phtml'));
                        //     break;

                        case 'multiselect':
                            include ($block->getTemplateFile('Webkul_Marketplace::product/multiselectEdit.phtml'));
                            break;
                            
                        default:
                            break;
                    }
                } // customer attribute
                
            ?>
            <?php if($product_coll['type_id']!='configurable'){ ?>
                <div class="field">
                    <label class="label"><?php echo __('Special Price') ?><b><?php echo  " (".$currency_symbol.")"; ?></b></label>
                    <div class="tooltip">
                        <img src="<?php echo $helper->getMediaUrl().'marketplace/icon/info.png'?>" width="20px"/>
                        <span class="price_cal"><a class="tooltiptext pricetool" target="_blank" href="<?php echo $priceCalUrl;?>"><?php echo __($formula)?></a></span>
                    </div>
                    <?php
                    if($product_hint_status && $helper->getProductHintSpecialPrice()){?>
                        <img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProductHintSpecialPrice() ?>"/>
                    <?php
                    } 
                    if ($product_coll->getSpecialPrice()) {
                        $specialPrice = number_format($product_coll->getSpecialPrice(), 2, '.', '');
                    } else {
                        $specialPrice = '';
                    }
                    ?>
                    <div class="control">
                        <input type="text" class="widthinput input-text validate-zero-or-greater" name="product[special_price]" id="special-price" value="<?php echo $specialPrice; ?>"/>
                    </div>
                </div>
                <div class="field">
                    <label class="label"><?php echo __('Special Price From') ?></label>
                    <?php
                    if($product_hint_status && $helper->getProductHintStartDate()){?>
                        <img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProductHintStartDate() ?>"/>
                    <?php
                    } ?>
                    <?php 
                    if($product_coll->getData('special_from_date')){
                        if (date('m/d/y') == (trim($product_coll->getData('special_from_date')))) {
                            $special_from_date = '';
                        }
                       $special_from_date = $block->formatDate($product_coll->getData('special_from_date')); 
                    }else{
                       $special_from_date = '';
                    } ?>
                    <div class="control">
                        <input type="text" name="product[special_from_date]" id="special-from-date" class="input-text" value="<?php echo $special_from_date ?>"/>
                    </div>
                </div>
                <div class="field">
                    <label class="label"><?php echo __('Special Price To') ?></label>
                    <?php
                    if($product_hint_status && $helper->getProductHintEndDate()){?>
                        <img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProductHintEndDate() ?>"/>
                    <?php
                    } ?>
                    <?php 
                    if($product_coll->getData('special_to_date')){
                        $special_to_date = $block->formatDate($product_coll->getData('special_to_date')); 
                    }else{
                        $special_to_date = '';
                    } ?>
                    <div class="control">
                        <input type="text" name="product[special_to_date]" id="special-to-date" class="input-text" value="<?php echo $special_to_date ?>" />
                    </div>
                </div>
            <?php
            } ?>
            <?php echo $block->getChildHtml('mppreorder_attribute_edit'); ?>
            <input id="inventory_manage_stock" type="hidden" name="product[stock_data][manage_stock]" value="<?php echo $product_coll['stock_data']['manage_stock']?>">
            <input type="hidden" value="1" name="product[stock_data][use_config_manage_stock]" id="inventory_use_config_manage_stock">
            <div class="field required">
                <label class="label"><?php echo __('Stock') ?></label>
                <?php
                if($product_hint_status && $helper->getProductHintQty()){?>
                    <img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProductHintQty() ?>"/>
                <?php
                } ?>
                <div class="control">
                    <input type="text" class="required-entry validate-number input-text" name="product[quantity_and_stock_status][qty]" id="qty" value="<?php echo $product_coll['quantity_and_stock_status']['qty'] ?>"/>
                </div>
            </div>
            <div class="field required">
                <label class="label"><?php echo __('Stock Availability') ?></label>
                <?php
                if($product_hint_status && $helper->getProductHintStock()){?>
                    <img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProductHintStock() ?>"/>
                <?php
                } ?>
                <?php
                $is_in_stock = $product_coll['quantity_and_stock_status']['is_in_stock'];
                ?>
                <div class="control">
                    <select id="" class="select" name="product[quantity_and_stock_status][is_in_stock]">
                        <option <?php if($is_in_stock==1) echo "selected"; ?> value="1"><?php echo __("In Stock"); ?></option>
                        <option <?php if($is_in_stock==0) echo "selected"; ?> value="0"><?php echo __("Out of Stock"); ?></option>
                    </select>
                </div>
            </div>
            <div class="field required">
                <label class="label"><?php echo __('Visibility') ?>
                <?php if(count($visibilityToolTip) > 0): ?>
                    <div class="tooltip">
                        <img src="<?php echo $helper->getMediaUrl().'marketplace/icon/info.png'?>" width="20px"/>
                        <span class="tooltiptext">
                            <?php echo ( (count($visibilityToolTip) > 0) ? $visibilityToolTip[0]['tooltip_text'] : '');?>
                        </span>
                    </div>
                <?php endif; ?>
                </label>
                <div class="control">
                    <select id="visibility" class=" required-entry required-entry select" name="product[visibility]">                        
                        <option value="4" selected="selected"><?php echo __("Catalog Search")?></option>
                    </select>
                </div>
            </div>
            <div class="field required">
                <label class="label"><?php echo __('Tax Class') ?></label>
                <?php
                if($product_hint_status && $helper->getProductHintTax()){?>
                    <img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProductHintTax() ?>"/>
                <?php
                } ?>
                <div class="control">
                    <select id="tax-class-id" class=" required-entry required-entry select" name="product[tax_class_id]">
                        <?php
                        $taxid=$product_coll->getData('tax_class_id');
                        $taxes=$helper->getTaxClassModel();
                        foreach($taxes as $tax){
                            ?>
                            <option <?php echo $taxid==$tax->getId()? 'selected':''; ?> value="<?php echo $tax->getId() ?>"><?php echo $tax->getClassName()?></option>
                        <?php 
                        } ?>
                    </select>
                </div>
            </div>
            
            <div class="field">
                <label class="label"></label>
                <input type="button" name="addFaqField" class="add-faq-field yellow-button" value="<?php echo __('Add Product FAQ')?>">
            </div>
            <div class="field mis-faq-field" style="display: none;">
                <table name="faq_fields" class="mis_faq_field_value">
                    <input type="hidden" name="hasValue" id="hasValue" value="0">
                    <input type="hidden" name="deletValue" id="deletValue" value="0">
                    <tr>
                        <th><?php echo __('Title');?></th>
                        <th><?php echo __('Answer');?></th>                     
                        <th><?php echo __('Action');?></th> 
                        <td>
                            <input type='button' name='add' class='faq-add-btn yellow-button' value="<?= __('Add FAQ');?>">
                        </td>                   
                    </tr>   
                </table>
            </div>
            <?php $faqGridCounter = 1; ?>
            <?php 

            if ($faqCollection->count() > 0): ?>
            <!-- <form action="javascript:void(0)" method="get" id="faq_grid_form" name="faq_grid_form" novalidate="novalidate" class="__web-inspector-hide-shortcut__"> -->
                <a href="javascript:void(0)" class="button yellow-button" title="Delete Products" onclick="deleteFaqs()">
                    <span><span><?php echo __('Delete FAQs'); ?></span></span>
                </a>
                <table cellspacing="0" class="border wk-mp-list-table wk-mp-list-container-table">
                    <thead>
                        <tr class="wk-content">
                            <th class="wk-check-first-td">
                                <span>
                                    <input type="checkbox" name="mpselecctall" value="all" id="mpselecctall"/>
                                </span>
                            </th>
                            <th>
                                <span class="label faq-title">
                                    <?php echo __('Title')?>
                                </span>
                            </th>
                            <th>
                                <span class="label faq-desc">
                                    <?php echo __('Description')?>
                                </span>
                            </th>
                            <th class="wk-list-th-display">
                                <span class="label status">
                                    <?php echo __('Status')?>
                                </span>
                            </th>
                            <th class="wk-list-th-display">
                                <span class="label faq-edit">
                                    <?php echo __('Action')?>
                                </span>
                            </th>                       
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($faqCollection as $faqValue): ?>
                            <tr class="wk-row-view">
                                <td class="wk-check-first-td">
                                    <span>
                                        <input type="checkbox" name="faq_mass_delete[]" class="mpcheckbox mpcheckbox-[<?php echo $faqGridCounter?>]" value="<?php echo $faqValue->getId(); ?>"/>
                                    </span>
                                </td>
                                <td>        
                                    <span class="label faq-label-<?php echo $faqGridCounter?>" contenteditable="false">
                                        <?php echo $faqValue->getTitle() ?>
                                    </span>
                                    <span style='display: none; color: red' class="label_error_<?php echo $faqGridCounter?>"><?php echo __('This is required Field.')?></span>
                                </td>
                                <td>        
                                    <span class="label faq-description-<?php echo $faqGridCounter?>" contenteditable="false">
                                        <?php echo $faqValue->getDescription() ?>
                                    </span>
                                    <span style='display: none; color: red' class="description_error_<?php echo $faqGridCounter?>"><?php echo __('This is required Field.')?></span>
                                </td>
                                <td>        
                                    <span class="label faq-is-active">
                                        <?php echo ($faqValue->getIsActive() == 1 ? 'Approved': 'Disapproved') ?>
                                    </span>
                                </td>
                                <td>        
                                    <span class="label faq-edit-individual">
                                        <a href="javascript:void(0)" class="faq-edit faq-edit-<?php echo $faqGridCounter ?>" data-attr="<?php echo $faqGridCounter ?>"><?php echo __('Edit'); ?></a>
                                        <a href="javascript:void(0)" class="faq-cancel faq-cancel-<?php echo $faqGridCounter ?>" data-attr="<?php echo $faqGridCounter ?>" style="display: none" >
                                            <?php echo __('Cancel'); ?>
                                        </a>
                                        <a href="javascript:void(0)" data-attr="<?php echo $faqGridCounter ?>" data-faq="<?php echo $faqValue->getId();?>" class="faq-save faq-save-<?php echo $faqGridCounter ?>" style="display: none" >
                                            <?php echo __('Save'); ?>
                                        </a>
                                    </span>
                                </td>                   
                            </tr>
                        <?php  $faqGridCounter++; ?>   
                        <?php  endforeach; ?>   
                    </tbody>
                </table>
            <!-- </form> -->
            <?php endif; ?>
            <?php /*
            <div class="field">
                <label class="label"></label>
                <input type="button" name="addField" class="add-field" value="<?php echo __('Add Custom Fields')?>">
            </div>
            <div class="field custom-field" style="display: none;">
                <table name="custom_field_value" class="mis_custom_field_value">
                    <input type="hidden" name="hasValue" id="hasValue" value="0">
                    <input type="hidden" name="deletValue" id="deletValue" value="0">
                    <tr>
                        <th><?php echo __('Label');?></th>
                        <th><?php echo __('Option');?></th>                     
                        <th><?php echo __('Action');?></th> 
                        <td>
                            <input type='button' name='add' class='add-btn' value='Add'>
                        </td>                   
                    </tr>
                    <?php if (count($fieldModel->getData()) >= 1) { ?>                  
                        <?php foreach ($fieldModel->getData() as $item) { 
                                $totalCustomField++;
                            ?>                      
                            <tr class='fields-row'>
                                <td>
                                    <input type="hidden" name="custom_field_value[<?php echo $row; ?>][current_id]" value="<?php echo $item['id']?>">
                                    <input type='text' name="custom_field_value[<?php echo $row; ?>][label_name]" class='lable-name' data-value="0" value="<?php echo $item['custom_fields'];?>">
                                    <span style='display: none; color: red'><?php echo __('Only alphanumeric chatacters allowed.')?></span>
                                </td>
                                <td>
                                    <select name="custom_field_value[<?php echo $row; ?>][label_value]">
                                    <?php if ($item['custom_field_value'] == 1) { ?>
                                        <option value='0'><?php echo __('No');?></option>
                                        <option value='1' selected="selected"><?php echo __('Yes');?></option>
                                    <?php } else if ($item['custom_field_value'] == 2) {?>
                                        <option value='2' selected="selected"><?php echo __('select')?></option>
                                        <option value='0'><?php echo __('No');?></option>
                                        <option value='1'><?php echo __('Yes');?></option>
                                    <?php } else {?>
                                        <option value='2'><?php echo __('select')?></option>
                                        <option value='0' selected="selected"><?php echo __('No');?></option>
                                        <option value='1'><?php echo __('Yes');?></option>
                                    <?php }?>
                                    </select>
                                </td>
                                <?php //if ($row != 0): ?> 
                                    <td>
                                        <input type='button' name='remove' class='remove-btn' value='Remove' data-attr="<?php echo $row; ?>">
                                    </td>
                                <?php //endif; ?>
                                <td>
                                    <p class='error0 err-text'></p>
                                </td>
                            </tr>
                        <?php 
                        $row++;
                        } ?>
                    <?php } else { ?>
                            <tr class='fields-row'>
                                <td>
                                <input type='text' name='custom_field_value[0][label_name]' class='lable-name'>
                                <span style='display: none; color: red'><?php echo __('Only alphanumeric chatacters allowed.')?></span>
                                </td>
                                <td>
                                    <select name='custom_field_value[0][label_value]'>
                                       <option value='0'><?php echo __('No');?></option>
                                       <option value='1'><?php echo __('Yes');?></option>
                                    </select>
                                </td>
                                <td>
                                    <input type='button' name='remove' class='remove-btn' value='Remove' data-attr="0">
                                </td>
                                <td>
                                    <p class='error0 err-text'></p>
                                </td>
                            </tr>
                    <?php } ?>
                </table>
            </div> */ ?>
            <?php echo $block->getChildHtml('marketplace_product_gallery'); ?>
            <?php echo $block->getChildHtml('mpamazonconnector_edit'); ?>
        </fieldset>
    </div>
</form>
<div id="config_image_not_available" style="display: none;">
    <p><?php echo __('Please upload image with associate products.');?></p>
</div>
<div id="image_not_available" style="display: none;">
    <p><?php echo __('Please add at least one image with this product.');?></p>
</div>
<div id="config_product_pop" style="display: none;">
    <p><?php echo __('Please add at least one child product with this configurable product.');?></p>
</div>
<div id="category_pop" style="display: none;">
    <p><?php echo __('Please select at least one category for product.');?></p>
</div>
<div id="discription_pop" style="display: none;">
    <p><?php echo __('Please add discription of product.');?></p>
</div>
<?php
$formData = [
    'productTypeId'       => $product_coll['type_id'],
    'categories'          => implode(',',$categories),
    'countryPicSelector'  => '#country-pic',
    'verifySkuAjaxUrl'    => $block->getUrl('marketplace/product/verifysku', ['_secure' => $this->getRequest()->isSecure()]),
    'categoryTreeAjaxUrl' => $block->getUrl('marketplace/product/categorytree/', ['_secure' => $this->getRequest()->isSecure()])
];
$serializedFormData = $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($formData);
?>

<script type="text/x-magento-init">
    {
        "*": {
            "sellerEditProduct": <?php /* @noEscape */ echo $serializedFormData; ?>
        }
    }
</script>
<script type='text/javascript'>
var customFieldRow = "<?php echo $totalCustomField;?>";
    require(['jquery', 'prototype', 'domReady!'], function($) {
        var qty = $('#qty'),
            productType = $('#product_type_id').val(),
            stockAvailabilityField = $('#quantity_and_stock_status'),
            manageStockField = $('#inventory_manage_stock'),
            useConfigManageStockField = $('#inventory_use_config_manage_stock'),
            fieldsAssociations = {
                'qty': 'inventory_qty',
                'quantity_and_stock_status': 'inventory_stock_availability'
            };

        var qtyDefaultValue = qty.val();
    })
</script>
<!-- <script>
    require([
        "jquery",
        "Webkul_Marketplace/catalog/type-events"
    ], function($, TypeSwitcher){
        var $form = $('[data-form=edit-product]');
        $form.data('typeSwitcher', TypeSwitcher.init());
    });
</script> -->
<script>
    require([
        "jquery",
        "Webkul_Marketplace/catalog/type-events"
    ], function($, TypeSwitcher){
        var $form = $('[data-form=edit-product]');
        $form.data('typeSwitcher', TypeSwitcher.init());

        $(document).on('load', function(){
            $("#weight").attr('disabled','false');
            $("#qty").attr('disabled','false');
        });

        setTimeout(
            function(){ 
                $("#weight").removeAttr("disabled");    
                $("#qty").removeAttr("disabled");    
                console.log('removed disabled');
            }, 3000);
    });
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "Webkul_Marketplace/catalog/apply-to-type-switcher": {}
        }
    }
</script>
<script type="text/javascript">
var checkboxArray = [];
<?php 

   foreach ($catIds as $key => $value) { ?>
      checkboxArray.push("<?php echo $value;?>");

 <?php   }

?>
</script>
<script type="text/javascript">
var is_configurable = "<?php echo $is_configurable; ?>";

    function uploadImagePopMessage(){
        jQuery.fancybox({
            'padding': '5px',
            'autoScale': true,
            'closeBtn' : true,
            'transitionIn': 'fade',
            'transitionOut': 'fade',
            'type': 'inline',
            'href': '#image_not_available',
            'onComplete': function() {
                $.cookie('image_not_available', 'shown');
            },
            'helpers': {
                overlay: {
                    closeClick: false,
                    locked: false
                }
            }
        }); 
    }

    function uploadConfigImagePopMessage(){
        jQuery.fancybox({
            'padding': '5px',
            'autoScale': true,
            'closeBtn' : true,
            'transitionIn': 'fade',
            'transitionOut': 'fade',
            'type': 'inline',
            'href': '#config_image_not_available',
            'onComplete': function() {
                $.cookie('config_image_not_available', 'shown');
            },
            'helpers': {
                overlay: {
                    closeClick: false,
                    locked: false
                }
            }
        }); 
    }

    function checkboxPopMessage(){
        jQuery.fancybox({
            'padding': '5px',
            'autoScale': true,
            'closeBtn' : true,
            'transitionIn': 'fade',
            'transitionOut': 'fade',
            'type': 'inline',
            'href': '#category_pop',
            'onComplete': function() {
                $.cookie('category_pop', 'shown');
            },
            'helpers': {
                overlay: {
                    closeClick: false,
                    locked: false
                }
            }
        }); 
    }

    function descriptionPopMessage(){
        jQuery.fancybox({
            'padding': '5px',
            'autoScale': true,
            'closeBtn' : true,
            'transitionIn': 'fade',
            'transitionOut': 'fade',
            'type': 'inline',
            'href': '#discription_pop',
            'onComplete': function() {
                $.cookie('category_pop', 'shown');
            },
            'helpers': {
                overlay: {
                    closeClick: false,
                    locked: false
                }
            }
        }); 
    }

    function configurablePopUp()
    {
        jQuery.fancybox({
            'padding': '5px',
            'autoScale': true,
            'closeBtn' : true,
            'transitionIn': 'fade',
            'transitionOut': 'fade',
            'type': 'inline',
            'href': '#config_product_pop',
            'onComplete': function() {
                $.cookie('config_product_pop', 'shown');
            },
            'helpers': {
                overlay: {
                    closeClick: false,
                    locked: false
                }
            }
        });
    }
// console.log(is_configurable);
    require(['jquery','mage/translate','jquery/ui', 'vesallFancybox'], function($,$t){ 

        /*$('#edit-product').submit(function(event){
            event.preventDefault();
            return false;
        });*/

        $('#btn_type').on('click', function(event){
            // event.preventDefault();
            // console.log('is_configurable '+is_configurable);
            var config_pro_err = false;
            var discriptiopn_err = false;
            var checkbox_err = true;
            var imageUploadErrConfig = false;

            $('.wk-elements').each(function(){
                // console.log('category checked '+$(this).is(':checked'));
                if ($(this).is(':checked')) {
                    checkbox_err = false;
                }
            });
            if (is_configurable == 1) {
                // console.log('first condition : ');
                // console.log($('#product-variations-matrix').hasClass("col-name").length);
                // console.log($('.col-price').text().length);
                // console.log('second condition : ');
                // console.log($('.col-price').text().length < 1);
                if ($('.col-price').text().length < 1) {
                    configurablePopUp();
                    config_pro_err = true;
                } else {
                    config_pro_err = false;
                    if ($('div.action-upload input[name="image"]').length !=
                        $('div.action-upload .variation').length) {
                    // if ($('div.action-upload .variation').length < 1) {
                        imageUploadErrConfig = true;
                        uploadConfigImagePopMessage();
                    }
                }                
            }

            if ($('#description').val().trim().length < 1 ) {
                descriptionPopMessage();
                discriptiopn_err = true;
            }  else {
                discriptiopn_err = false;
            }

            // console.log(checkbox_err); savebtn
            if (checkbox_err == true) {
                checkboxPopMessage();
            }
            // config_pro_err == true;
            if ((checkbox_err == false) && (imageUploadErrConfig == false) && (discriptiopn_err == false) && (config_pro_err == false) && 
                ($('div.image:not(.removed) .product-image').length > 0 )) {
                $('#edit-product').submit();
            } else {
                if ($('div.image:not(.removed) .product-image').length < 1 ) {
                    uploadImagePopMessage();
                }
                event.preventDefault();
            }

        });
        $(document).on('change', '.sensitive_attr', function(){
            var attr_code = $(this).attr('data-attr');
            var isExist = $(this).attr('data-exist');
            var attrVal = $(this).val();
            if (attrVal == 1) {
                if (isExist == 0) {
                    $('<input>').attr({
                        type: 'text',
                        name: 'product[mis_2_41_35_sensitive_'+attr_code+'_mis_2_41_35_comment]',
                        class: 'sensitive_comment_box',
                        style: 'width:50% !important;float:left;',
                        placeholder: 'Enter comment here',
                        value: ''
                    }).insertAfter(this);
                } else {
                    $(this).next('.sensitive_comment_box').toggleClass('mis_hidden_class');
                }
            } else {
                if (isExist == 1) {
                    $(this).next('.sensitive_comment_box').toggleClass('mis_hidden_class');
                } else {
                    $(this).next('.sensitive_comment_box').remove();
                }
            }
        });

        $(document).on('change', '.custom_field_change', function(){
            var customFeidlLabel = $(this).attr('data-attr');
            var fieldId = $(this).attr('data-id');
            var isExist = $(this).attr('data-exist');
            var isSelected = $(this).val();
            if (isSelected == 1) {
                if (isExist == 0) {
                    $('<input>').attr({
                        type: 'text',
                        name: 'custom_field_value['+fieldId+'][comment]',
                        class: 'custom_field_comment_box required-entry',
                        style: 'width:50%;float:left;',
                        placeholder: 'Enter comment here',
                        value: ''
                    }).insertAfter(this);
                } else {
                    $(this).next('.custom_field_comment_box').toggleClass('mis_hidden_class');
                }
            } else {
                if (isExist == 1) {
                    $(this).next('.custom_field_comment_box').toggleClass('mis_hidden_class');
                } else {
                    $(this).next('.custom_field_comment_box').remove();
                }
            }
        });
        //Vendor delivery days code - Start
        $('.delivery_days_from').on('change', function(){
            var deliveryFrom = parseInt($(this).val());
            $('.delivery_days_to option').each(function(){
                var deliveryTo = parseInt($(this).val());
                if (deliveryTo != '' && (deliveryTo <= deliveryFrom)) {
                    $(this).prop('disabled', 'disable');
                } else {
                    $(this).prop('disabled', '');
                }
                $('.delivery_days_to').val('');
            });
        });
        //Vendor delivery days code - End
        var clickCount = checkboxArray.length;
        $('#deletValue').val(customFieldRow);
        
        $(document).on('click',".wk-elements",function(){
            var index = checkboxArray.indexOf(this.value);

             if (jQuery.inArray(this.value, checkboxArray) > -1) {
                checkboxArray.splice(index, 1);
                clickCount--; 
            } else {
                if (checkboxArray.length < 3) {
                
                checkboxArray[clickCount] = this.value;
                clickCount++;
                } else {
                   $(this).attr('checked', false);
                } 

            }

            var categories = JSON.stringify(checkboxArray);
            $('#selectedCategories').val(categories);
               
        });
        $(document).on('click', '.add-field', function(event){
            event.preventDefault();
            $('.custom-field').css('display', 'block');
        });


        $(document).on('click', '.add-btn', function(){
            fieldAdd = 1;
            customFieldRow++;
            $('#deletValue').val(customFieldRow);
            $('.mis_custom_field_value').append(addRow(counter,$t));
            counter++;
        });

        var faqCounter = 0;

        // FAQ jQuery - Start
        $(document).on('click', '.add-faq-field', function(event){
            event.preventDefault();
            $('.mis-faq-field').css('display', 'block');
        });

        $(document).on('click', '.faq-add-btn', function(){
            $('.mis_faq_field_value').append(addFaqRow(faqCounter, $t));
            faqCounter++;
        });

        $(document).on('click', '.faq-edit', function(){
            var counterVal = $(this).attr('data-attr');
            var faqLabel = $('.faq-label-'+counterVal).text();
            var faqDesc = $('.faq-description-'+counterVal).text();
            
            //append text field in label
            $('<input>').attr({
                type: 'text',
                name: 'faq-edit-label-'+counterVal,
                class: 'required-entry faq-edit-label-'+counterVal,
                value: $.trim(faqLabel)
            }).insertAfter('.faq-label-'+counterVal);
            $('.faq-label-'+counterVal).hide();

            //append text area in Description
            $('<textarea>').attr({
                name: 'faq-edit-description-'+counterVal,
                class: 'required-entry faq-edit-description-'+counterVal,
                value: $.trim(faqDesc)
            }).insertAfter('.faq-description-'+counterVal); 
            $('.faq-description-'+counterVal).hide();
            
            $('.faq-save-'+counterVal).show();
            $('.faq-cancel-'+counterVal).show();
            $('.faq-edit-'+counterVal).hide();
        });

        $(document).on('click', '.faq-cancel', function(){
            var counterVal = $(this).attr('data-attr');
            
            //remove text field in label and showing default 
            $('.faq-edit-label-'+counterVal).remove();
            $('.faq-label-'+counterVal).show();

            //remove textarea in Description and showing default value
            $('.faq-edit-description-'+counterVal).remove();
            $('.faq-description-'+counterVal).show();

            $('.faq-save-'+counterVal).hide();
            $('.faq-cancel-'+counterVal).hide();
            $('.faq-edit-'+counterVal).show();
        });

        $(document).on('click', '.faq-save', function(){
            var counterVal = $(this).attr('data-attr');
            var faqId = $(this).attr('data-faq');
            var changedFaqLabel = $('.faq-edit-label-'+counterVal).val();
            var changedFaqDescription = $('.faq-edit-description-'+counterVal).val();
            if (!changedFaqLabel || (!changedFaqDescription)) {
                if (!changedFaqLabel) {
                    $('.label_error_'+counterVal).css({"color": "red", 'display':'block'});
                } else{
                    $('.label_error_'+counterVal).hide(500);
                }
                if (!changedFaqDescription) {
                    $('.description_error_'+counterVal).css({"color": "red", 'display':'block'});
                } else {
                    $('.description_error_'+counterVal).hide(500);

                }
            } else {
                $('.label_error_'+counterVal).hide(500);
                $('.description_error_'+counterVal).hide(500);
                var url = "<?php echo $this->getUrl('faqs/product/save'); ?>";
                $.ajax({
                    type: "POST",
                    url: url,
                    async : true,
                    showLoader : true,
                    data : {id:faqId,title:changedFaqLabel,description: changedFaqDescription,productfaq:true},
                    success: function(data)
                    {
                        $('.faq-label-'+counterVal).text(changedFaqLabel);
                        $('.faq-description-'+counterVal).text(changedFaqDescription);

                        //remove text field in label and showing default 
                        $('.faq-edit-label-'+counterVal).remove();
                        $('.faq-label-'+counterVal).show();

                        //remove textarea in Description and showing default value
                        $('.faq-edit-description-'+counterVal).remove();
                        $('.faq-description-'+counterVal).show();


                        $('.faq-save-'+counterVal).hide();
                        $('.faq-cancel-'+counterVal).hide();
                        $('.faq-edit-'+counterVal).show();
                    }
                });
            }
        });
    });
  

    /*       -------------------- Working of Custom Fields -------------------------   */

    var counter = "<?php echo $row > 0 ? $row : 1; ?>";
    var remove = "<?php echo __('Remove');?>";
    var fieldAdd = 0;
    function addRow(counter, $t) {
    var remove = $t('Remove');
    var field = "<tr class='fields-row'>"+
                    "<td><input type='text' name='custom_field_value["+counter+"][label_name]' class='lable-name' data-value="+counter+">"+
                        "<span style='display: none; color: red'><?php echo __('Only alphanumeric chatacters allowed.')?></span>"+
                    "</td>"+
                    "<td>"+
                        "<select name='custom_field_value["+counter+"][label_value]'>"+
                            "<option value='2'><?php echo __('select')?></option>"+
                            "<option value='0'><?php echo __('No');?></option>"+
                            "<option value='1'><?php echo __('Yes');?></option>"+
                        "</select>"+
                    "</td>"+
                        "<td>"+
                            "<input type='button' name='remove' class='remove-btn yellow-button' value='"+remove+"' data-attr='"+counter+"'>"+
                        "</td>"+
                    "</tr>";
        return field;

    }
    var faqCounter = 0;
    function addFaqRow(faqCounter, $t) {
    var remove = $t('Remove');    
    var field = "<tr class='fields-row'>"+
                    "<td><input type='text' name='faq_fields["+faqCounter+"][title]' class='required-entry' data-value="+faqCounter+">"+
                        "<span style='display: none; color: red'><?php echo __('This is required Field.')?></span>"+
                    "</td>"+
                    "<td>"+
                    "<textarea rows='4' cols='50' name='faq_fields["+faqCounter+"][description]' class='required-entry'></textarea>"+
                    "</td>"+
                        "<td colspan='2'>"+
                            "<input type='button' name='remove' class='faq-remove-btn yellow-button' value='"+remove+"' data-attr='"+faqCounter+"'>"+
                        "</td>"+
                    "</tr>";
        return field;

    }

    function deleteFaqs() {
        var selected = new Array();
        jQuery(".mpcheckbox:checked").each(function() {
               selected.push(jQuery(this).val());
        });
        if (selected.length > 0) {
            var url = "<?php echo $this->getUrl('faqs/product/delete'); ?>";
            jQuery.ajax({
                type: "POST",
                url: url,
                async : true,
                showLoader : true,
                data : {deleteIds:selected},
                success: function(data)
                {
                    location.reload();
                }
            });
            
        }
    }

    require(['jquery'], function($){ 
        $(document).on('click', '.remove-btn', function(){
            customFieldRow--;
            $('#deletValue').val(customFieldRow);
            $(this).parent().parent().remove();
        });

        $(document).on('change', '.lable-name', function(){
            $('#hasValue').val(1);
            var patt = /^[a-zA-Z0-9\s]+$/;
            var errnum =  jQuery(this).data('value');
            if ($(this).val().trim().length <= 0) {
                $(this).next().css({"color": "red", 'display':'block'});
            } else if (! (patt.test($(this).val().trim()))) {
                $(this).next().css({"color": "red", 'display':'block'});
            } else {
                $(this).next().css({'display':'none'});
            }

        });
        // FAQ jQuery - Start
        $(document).on('click', '.faq-remove-btn', function(){
            if (faqCounter == 0 || faqCounter < 0) {
                faqCounter = 0;
            } else {
                faqCounter--;
            }
            $(this).parent().parent().remove();
        });

        $(document).on('click','#mpselecctall', function (event) {
            if (this.checked) {
                $('.mpcheckbox').each(function () {
                    this.checked = true;
                });
            } else {
                $('.mpcheckbox').each(function () {
                    this.checked = false;
                });
            }
        });
        // FAQ jQuery - End
        $(document).on('click', '.mis-edit-btn', function(){
            $(".lable-name").each(function() {
                if ($(this).val().trim().length == 0) {
                    $(this).next().css({"color": "red", 'display':'block'});
                } else {
                    $(this).next().css({'display':'none'});
                }
            });
        });
          // Code to uppercase the first latter of the product name.
        $(document).on('blur', '#name', function(){
            var caps = $(this).val();
            caps = caps.charAt(0).toUpperCase() + caps.slice(1);
            $(this).val(caps);
        });
    });
  
</script>

<div class="mis-loader-mask" style="display: none;" >
    <img src="<?php echo $block->getViewFileUrl('Mangoit_Marketplace::image/loader-img.gif'); ?>" />
</div>
<div id="mis_attribute_list" style="display: none">
    <?php include ($block->getTemplateFile('Mangoit_Marketplace::product/edit/attribute/steps/newAttribute.phtml'));?>
</div>
<script>
    require([
        "jquery"
    ], function($){
        setTimeout(function(){  
            var next_btn = "<?php echo __('Next');?>";
            var back_btn = "<?php echo __('Back');?>";

            $(document).on('click', '.product-create-configuration-action', function(){
                $(".action-next-step").html(next_btn);
                $(".action-back-step").html(back_btn);
              
            });
            $(document).on('click', '.action-next-step', function(){
                $(".action-next-step").html(next_btn);
                $(".action-back-step").html(back_btn);
          
            });
            $(document).on('click', '.action-back-step', function(){
                $(".action-next-step").html(next_btn);
                $(".action-back-step").html(back_btn);

            });

        }, 2000);
        setTimeout(function(){  
            $("#qty").removeAttr("disabled");
            $("#weight").removeAttr("disabled");
        }, 4000);
    });
</script>