
<?php
if (empty($product_coll->getCustomAttribute($attributeCode))) { ?>
    <div>
        <label class="label"><?php echo __($frontLabel) ?>:</label>
        <div class="control">
            <select id="" class="select" name="<?php echo "product[$attributeCode][]";?>" multiple>
                <?php 
                    foreach ($attributeData->getSource()->getAllOptions() as $key => $value) { 
                      if ($value['value']>0) {  ?>
                           <option value="<?php echo $value['value'];?>"><?php echo $value['label'];?></option>
                <?php } // end of if
                } // end of foreach  ?>
            </select>
        </div>
    </div>
<?php } else { 

   $textData = $product_coll->getCustomAttribute($attributeCode)->getValue();
   $selectedValues = explode(',', $textData);
?>
<div>
    <label class="label"><?php echo __($frontLabel) ?>:</label>
    <div class="control">
        <select id="" class="select" name="<?php echo "product[$attributeCode][]";?>" multiple>
            <?php 
                foreach ($attributeData->getSource()->getAllOptions() as $key => $value) { 
                  if ($value['value']>0) { 
                        if (in_array($value['value'], $selectedValues)) {
                        ?>
                       <option selected="selected" value="<?php echo $value['value'];?>"><?php echo $value['label'];?></option>
            <?php } else { ?>
                        <option value="<?php echo $value['value'];?>"><?php echo $value['label'];?></option>
           <?php   }
            } 
            }
            ?>
        </select>
    </div>
</div>
<?php } //end of else  ?>