<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) 2010-2018 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

// @codingStandardsIgnoreFile

/** @var $block \Webkul\Marketplace\Block\Product\Productlist */
die('died');
$helper = $this->helper('Webkul\Marketplace\Helper\Data');
$paramData = $this->getRequest()->getParams();
$filter = '';
$filterStatus = '';
$filterDateFrom = '';
$filterDateTo = '';
$id = '';
$alp = '';
$cat = '';
$price_from = '';
$price_to = '';
$sortByName = '';
$order = '';
if (isset($paramData['id'])) {
    $id = $paramData['id'] != '' ? $paramData['id'] : '';
}
if (isset($paramData['alp'])) {
    $alp = $paramData['alp'] != '' ? $paramData['alp'] : '';
}
if (isset($paramData['cat'])) {
    $cat = $paramData['cat'] != '' ? $paramData['cat'] : '';
}

if (isset($paramData['price_from'])) {
    $price_from = $paramData['price_from'] != '' ? $paramData['price_from'] : '';
}

if (isset($paramData['price_to'])) {
    $price_to = $paramData['price_to'] != '' ? $paramData['price_to'] : '';
}

if (isset($paramData['n'])) {
    $sortByName = ($paramData['n'] == 'DESC') ? 'DESC' : (($paramData['n'] == 'ASC') ? 'ASC' : '') ;
}

if (isset($paramData['order'])) {
    $order = $paramData['order'] != '' ? $paramData['order'] : '';
}


if (isset($paramData['s'])) {
    $filter = $paramData['s'] != '' ? $paramData['s'] : '';
}
if (isset($paramData['status'])) {
    $filterStatus = $paramData['status'] != '' ? $paramData['status'] : '';
}
if (isset($paramData['from_date'])) {
    $filterDateFrom = $paramData['from_date'] != '' ? $paramData['from_date'] : '';
}
if (isset($paramData['to_date'])) {
    $filterDateTo = $paramData['to_date'] != '' ? $paramData['to_date'] : '';
}
$_products_coll = $block->getAllProducts();
if ($helper->getIsProductApproval() || $helper->getIsProductEditApproval()) {
    $enabledStatusText = __('Approved');
    $disabledStatusText = __('Pending');
} else {
    $enabledStatusText = __('Enabled');
    $disabledStatusText = __('Disabled');
}
?>
<style type="text/css">
    .hidden{
        display: none;
    }
</style>
<div class="wk-mp-design">
    <fieldset class="fieldset info wk-mp-fieldset">
        <legend class="legend">
            <span><?php echo __('Product List') ?></span>
        </legend>
        <div class="grid">
            <div class="hor-scroll">
                <form action="<?php echo $block->getUrl('marketplace/product/productlist', ['_secure' => $this->getRequest()->isSecure()])?>" method="get" id="form-productlist-filter"  name="formProductlistFilter" data-mage-init='{"validation":{}}'>
                    <table cellspacing="0" class="border wk-mp-list-table">
                        <thead>
                            <tr id="wk-mp-tr-heading">
                                <th><span><?php echo __('ID') ?></span></th>
                                <!-- <th><span><?php //echo __('Alphabet') ?></span></th> -->
                                <th><span><?php echo __('Category') ?></span></th>
                                <th><span><?php echo __('Price') ?></span></th>
                                <th><span><?php echo __('Product Name') ?></span></th>
                                <th><span><?php echo __('Date') ?></span></th>
                                <th><span><?php echo __('Product Status') ?></span></th>
                                <th><span>&nbsp;</span></th>
                            </tr>
                        </thead>
                        <tbody class="wk-mp-body" id="colender-check">
                            <tr>
                                <td>
                                    <input type="text" class="input-text" name="id" placeholder='<?php echo __('ID') ?>' value="<?php echo $id ?>"/>
                                </td>
                             <!--    <td>
                                    <input type="text" class="input-text" name="alp" placeholder='<?php //echo __('Alphabet') ?>' value="<?php echo $alp ?>"/>
                                </td> -->
                                <td>
                                    <select name="cat" >
                                        <option>
                                            <?php foreach ($block->getCategoryCollection() as $catkey => $catValue): ?>
                                                <option value="<?php echo $catkey; ?>" <?php echo (($cat == $catkey) ? 'selected': '') ?>><?php echo $catValue; ?></option>
                                            <?php endforeach; ?>
                                            
                                        </option>
                                    </select>
                                </td>
                                <td>
                                    <span class="wk-mp-td-span">
                                        <?php echo __('From: ') ?>
                                        <input name="price_from" id="price_from" class="input-text" value="<?php echo $price_from; ?>" />
                                    </span>                             
                                    <span class="wk-mp-td-span">
                                        <?php echo __('To: ') ?>
                                        <input name="price_to" id="price_to" class="input-text" value="<?php echo $price_to; ?>" />
                                    </span>
                                </td>
                                <td>
                                    <input type="text" class="input-text" name="s" placeholder='<?php echo __('Search by product name') ?>' value="<?php echo $filter ?>"/>
                                </td>
                                <td>
                                    <span class="wk-mp-td-span">
                                        <?php echo __('From: ') ?>
                                        <input name="from_date" id="special-from-date" class="input-text" value="<?php echo $filterDateFrom?>" />
                                    </span>				    			
                                    <span class="wk-mp-td-span">
                                        <?php echo __('To: ') ?>
                                        <input name="to_date" id="special-to-date" class="input-text" value="<?php echo $filterDateTo?>" />
                                    </span>
                                </td>
                                <td>
                                    <select name="status" class="input-text">
                                        <option value=""><?php echo __('All') ?></option>
                                        <option value="1" <?php if($filterStatus == 1) echo 'selected="selected"'?>>
                                            <?php echo $enabledStatusText ?>
                                        </option>
                                        <option value="2" <?php if($filterStatus == 2) echo 'selected="selected"'?>>
                                            <?php echo $disabledStatusText ?>
                                        </option>
                                    </select>
                                </td>
                                <td>
                                    <button class="button" title="Save" type="submit">
                                        <span><span><span><?php echo __('Submit') ?></span></span></span>
                                    </button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </form>
                <?php $urlInterface = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\UrlInterface');
                    $params = $this->getRequest()->getParams();
                    $url = $urlInterface->getCurrentUrl(); ?>
                <div data-bind="scope: 'product-list-component'">	
                <?php if ($_products_coll && count($_products_coll)): ?>
                    <form action="<?php echo $block->getUrl('marketplace/product/massDelete', ['_secure' => $this->getRequest()->isSecure()]) ?>" method="post" id="form-productlist-massdelete" name="formProductlistMassdelete" data-mage-init='{"validation":{}}'>
                        <?php echo $block->getBlockHtml('formkey')?>
                        <button class="button" title="<?php echo __('Delete Products') ?>" type="submit" style="float: left;padding: 5px 5px 5px 0;"  id="mass-delete-butn">
                            <span><span><?php echo __('Delete Products') ?></span></span>
                        </button>
                        <div style="float: right;">
                            <select name="sort_by_name" class="sort_by_name" style="width:100%;">
                                <option value="0"><?php echo __('Select') ?></option>
                                <option value="1" <?php echo (isset($paramData['order']) ? 'selected': '') ?>><?php echo __('Sort by Product Name') ?></option>
                            </select>
                            <span class="asc_desc <?php echo (isset($paramData['order']) ? '': 'hidden') ?> ">
                                <?php if (isset($paramData['order'])): ?>
                                    <a title="<?php echo __('Set Ascending Direction');?>" href="javascript:void(0)" class="action sorter-action sort-asc <?php  echo (($paramData['order'] == 'DESC') ? '': 'hidden') ?>" data-value="ASC">
                                        <span><?php echo __('Set Ascending Direction');?></span>
                                    </a>
                                    <a title="<?php echo __('Set Descending Direction');?>" href="javascript:void(0)" class="<?php echo (($paramData['order'] == 'ASC') ? '': 'hidden') ?> action sorter-action sort-desc" data-value="DESC">
                                        <span><?php echo __('Set Descending Direction');?></span>
                                    </a>
                                <?php endif; ?>
                            </span>
                        </div>
                            <!-- ko template: getTemplate() --><!-- /ko -->
                        <table cellspacing="0" class="border wk-mp-list-table wk-mp-list-container-table">
                            <thead>
                                <tr class="wk-content">
                                    <th class="wk-check-first-td">
                                        <span>
                                            <input type="checkbox" name="mpselecctall" value="all" id="mpselecctall"/>
                                        </span>
                                    </th>
                                    <th class="id">
                                        <span class="label id">
                                            <?php echo __('ID')?>
                                        </span>
                                    </th>
                                    <th class="wk-first-td">
                                        <span class="label name">
                                            <?php echo __('Product')?>
                                        </span>
                                    </th>
                                    <th>
                                        <span class="label pro-status">
                                            <?php echo __('Type')?>
                                        </span>
                                    </th>
                                    <th>
                                        <span class="label pro-status">
                                            <?php echo __('Status')?>
                                        </span>
                                    </th>
                                    <th class="wk-list-th-display">
                                        <span class="label qty">
                                            <?php echo __('Qty. Confirmed')?>
                                        </span>
                                    </th>
                                    <th class="wk-list-th-display">
                                        <span class="label qty">
                                            <?php echo __('Qty. Pending')?>
                                        </span>
                                    </th>	
                                    <th class="wk-list-th-display">
                                        <span class="label qty">
                                            <?php echo __('Qty. Sold')?>
                                        </span>
                                    </th>
                                    <th class="wk-list-th-display1">
                                        <span class="label">
                                            <?php echo __('Earned Amount')?>
                                        </span>
                                    </th>
                                    <th>
                                        <span class="label">
                                            <?php echo __('Action')?>
                                        </span>
                                    </th>			    		
                                </tr>
                            </thead>
                            <tbody>
                                <?php 
                                $i = 0;
                                foreach($block->getAllProducts() as $products){
                                    $product = $block->getProductData($products->getMageproductId());
                                    $i++;
                                    $image_url = $block->imageHelperObj()->init($product, 'product_page_image_small')
                                                ->setImageFile($product->getImage())
                                                ->getUrl();
                                    $salesdetail=$block->getSalesdetail($products->getMageproductId());
                                    ?>
                                    <tr class="wk-row-view <?php echo $class = ($i == count($block->getAllProducts()))? 'wk-last_tr':''?>">
                                        <td class="wk-check-first-td">
                                            <span>
                                                <input type="checkbox" name="product_mass_delete[]" class="mpcheckbox" value="<?php echo $products->getMageproductId(); ?>"/>
                                            </span>
                                        </td>
                                        <td>        
                                            <span class="label pro-status">
                                                <?php echo $products->getMageproductId(); ?>
                                            </span>
                                        </td>
                                        <td class="wk-first_td">
                                            <input type="hidden" class="hidden-id" value="<?php echo $products->getMageproductId(); ?>" />
                                            <div class="label name" title="<?php echo $product->getName(); ?>">
                                                <div class="wk-pro-divide1">
                                                    <img src="<?php echo $image_url?>" class="image" />
                                                </div>
                                                <div class="wk-pro-divide2">
                                                    <div style="width:100%;">
                                                        <?php if($product->getStatus()==1 && $product->getVisibility()!=1) { ?>
                                                            <a href="<?php echo $product->getProductUrl()?>" target="blank">
                                                        <?php }?>
                                                            <?php echo $product->getName();?>
                                                        <?php if($product->getStatus()==1 && $product->getVisibility()!=1) { ?>
                                                            </a>
                                                        <?php }?>
                                                    </div>
                                                    <div style="width:100%;float:left;">
                                                        <?php 
                                                        if($product->getPrice()*1){
                                                            echo $block->getFormatedPrice($product->getPrice(), $helper->getCurrencySymbol());
                                                        }else{
                                                            echo $helper->getCurrencySymbol().'0.00';
                                                        }
                                                        ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                        <td>		
                                            <span class="label pro-status">
                                                <?php echo $product->getTypeId()?>
                                            </span>
                                        </td>
                                        <?php 
                                        if($product->getStatus()==2 && ($helper->getIsProductApproval() || $helper->getIsProductEditApproval())) {	?>
                                            <td>		
                                                <span class="label pro-status">
                                                    <?php echo $disabledStatusText ?>
                                                </span>
                                            </td>
                                            <td class="wk-list-th-display">
                                                <span class="label qty">
                                                    <?php echo __('Pending')?>
                                                </span>
                                            </td>
                                            <td class="wk-list-th-display">
                                                <span class="label qty">
                                                    <?php echo __('Pending')?>
                                                </span>	
                                            </td>
                                            <td class="wk-list-th-display">
                                                <span class="label qty">
                                                    <?php echo __('Pending')?>
                                                </span>	
                                            </td>
                                            <td class="wk-list-th-display1">
                                                <span class="label qty">
                                                    <?php echo __('Pending')?>
                                                </span>	
                                            </td>									
                                        <?php }
                                        else{ ?>
                                            <?php if ($product->getStatus() == 2) { ?>
                                                <td>		
                                                    <span class="label pro-status">
                                                        <?php echo $disabledStatusText ?>
                                                    </span>
                                                </td>
                                            <?php } else { ?>
                                                <td>		
                                                    <span class="label pro-status">
                                                        <?php echo $enabledStatusText ?>
                                                    </span>
                                                </td>
                                            <?php } ?>
                                            <td class="wk-list-th-display">
                                                <span class="label qty">
                                                    <?php echo $salesdetail['quantitysoldconfirmed']; ?>
                                                </span>
                                            </td>
                                            <td class="wk-list-th-display">
                                                <span class="label qty">
                                                    <?php echo $salesdetail['quantitysoldpending']; ?>
                                                </span>	
                                            </td>
                                            <td class="wk-list-th-display1">
                                                <span class="label qty">
                                                    <a href="<?php echo $block->getUrl('marketplace/order/salesdetail/', ['id'=>$product->getId(), '_secure' => $this->getRequest()->isSecure()]); ?>"><?php echo $salesdetail['quantitysold']; ?></a>
                                                </span>	
                                            </td>
                                            <td class="wk-list-th-display">
                                                <span class="label price">
                                                    <?php echo $block->getFormatedPrice($salesdetail['amountearned'], $helper->getCurrencySymbol()); ?>
                                                </span>	
                                            </td>
                                            <?php 
                                        }?>
                                        <td>
                                            <span class="label wk-action">
                                                <img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/icon-edit.png'); ?>" data-url="<?php echo $block->getUrl('marketplace/product/edit', ['id'=>$product->getId(), '_secure' => $this->getRequest()->isSecure()])?>" alt="<?php echo __('Edit')?>" title="<?php echo __('Edit')?>" class="mp-edit"/>
                                            </span>	
                                        </td>			    		
                                    </tr>
                                    <?php
                                }?>
                            </tbody>
                        </table>
                    </form>
                    </div>						
                <?php else: ?>
                    <div class="wk-emptymsg">
                        <?php echo __('No Product Available') ?>
                    </div>
                <?php endif ?>					
            </div>
        </div>
        <?php if ($block->getPagerHtml()): ?>
            <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
        <?php endif ?>	
    </fieldset>	
    <div class="buttons-set">
        <p class="back-link">
            <a href="javascript:;" onclick="javascript: window.history.back();" class="left">&laquo; <?php echo __('Back') ?></a>
        </p>
    </div>
</div>

<?php 
if (!empty($params)) {
    $url = $url.'&order=ASC';
}else {
    $url = $url.'?order=ASC';
}
 ?>
<script type="text/javascript">
   // jQuery(function() {
      // bind change event to select
      jQuery(document).on('change','.sort_by_name', function() {
        var optVal = jQuery(this).val(); // get selected value
        console.log(optVal);
        if (optVal) {
            var url = "<?php echo $url; ?>";
            window.location = url; // redirect
        }
        // return false;
      });

      jQuery(document).on('click','.sort-desc', function() {
            setOrderByName('DESC');
      });
      jQuery(document).on('click','.sort-asc', function() {
           setOrderByName('ASC'); 
      });
      function setOrderByName(assingOrder) {
            var paramName = 'order';
            var url      = window.location.href; 
            var decode = window.decodeURIComponent,
                urlPaths = url.split('?'),
                baseUrl = urlPaths[0],
                urlParams = urlPaths[1] ? urlPaths[1].split('&') : [],
                paramData = {},
                parameters, i;

            for (i = 0; i < urlParams.length; i++) {
                parameters = urlParams[i].split('=');
                paramData[decode(parameters[0])] = parameters[1] !== undefined ?
                    decode(parameters[1].replace(/\+/g, '%20')) :
                    '';
            }
            // delete paramData[paramName];
            paramData[paramName] = assingOrder;
           
            paramData = jQuery.param(paramData);

            location.href = baseUrl + (paramData.length ? '?' + paramData : '');
      }
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "Webkul_Marketplace/js/product/product-date-range": {}
        }
    }
</script>
<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "product-list-component": {
                            "component": "sellerProductList",
                            "template" : "Webkul_Marketplace/product-list"
                        }
                    }
                }
            }
        }
</script>
