<?php 
/**
* Webkul Software
*
* @category  Webkul
* @package   Webkul_MpSellervacation
* @author    Webkul
* @copyright Copyright (c) 2010-2018 Webkul Software Private Limited (https://webkul.com)
* @license   https://store.webkul.com/license.html
*/
$_helper = $this->helper('Webkul\Marketplace\Helper\Data');
$isPartner= $_helper->isSeller();
$magentoCurrentUrl = $block->getCurrentUrl();
$isSellerGroup = $_helper->isSellerGroupModuleInstalled();
if($isPartner){
?>
<?php if(($isSellerGroup && $_helper->isAllowedAction('mpsellervacation/setting')) || !$isSellerGroup) { ?>
 <li class="nav item <?php echo strpos($magentoCurrentUrl,'mpsellervacation/setting') !== false ? "current":"";?>">
    <?php
    if(strpos($magentoCurrentUrl,'mpsellervacation/setting') !== false){ ?>
        <strong><?php echo __('Vacation Settings') ?></strong>
    <?php
    } else{ ?>
        <a href="<?php echo $block->getUrl('mpsellervacation/setting', ['_secure' => $block->getRequest()->isSecure()]); ?>">
            <?php echo __('Vacation Settings') ?>
        </a>
    <?php
    } ?>
</li>
<?php } ?>
<?php } ?>
