<?php 
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) 2010-2018 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

$helper = $this->helper('Webkul\Marketplace\Helper\Data');
$misHelper = $this->helper('Mangoit\Marketplace\Helper\Data');
$profile_hint_status = $helper->getProfileHintStatus();
?>
<script type="text/javascript">
    var shopTitle = "<?php echo __('Your Shop Name');?>";
    var shopText = "<?php echo __('(This will be used to display your myGermany marketplace profile)');?>";
    /*var shopLabel = "<?php //echo __('Shop URL');?>";*/
    var shopLabel = "<?php echo __('What should your shop be called with us?');?>";
    var websiteTitle = "<?php echo __('Company URL');?>";

    /*var websiteText = "<?php //echo __('(This will be used to display your business profile)');?>";*/
    var websiteText = "<?php echo __('(Your own company homepage)');?>";

    var websitePlaceholder = "<?php echo __('Company URL');?>";
    var company_address = "<?php echo __('Company Address');?>";
    var telephone = "<?php echo __('Telephone');?>";
</script>
<div class="field required" id="wantptr">
    <label for="wantpartner" class="label"><?php echo __('Do You Want To Become A Seller / Vendor?') ?> </label>
    <?php
    if($profile_hint_status && $helper->getProfileHintBecomeSeller()){?>
        <img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProfileHintBecomeSeller() ?>"/>
    <?php
    }?>
    <div class="control">
        <input type="radio" id="wantpartner" class="wantpartner" name="is_seller" value='1' title="<?php echo __('Agree as Seller') ?>"  /> <?php echo __("Yes"); ?>&nbsp;&nbsp;
        <input type="radio" id="wantpartner0" class="wantpartner" name="is_seller" value='0' title="<?php echo __('Disagree as Seller') ?>" checked /> <?php echo __("No"); ?>
    </div>
</div>
<div id="seller-shop-field-wrapper"> 
    <script id="wantptr-template" type="text/x-magento-template">
        <div id="<%- data.id %>" class="profileurl field required">
            <label class="label">
                <%- data.label %>
                <?php
                if($helper->getProfileHintStatus() && $helper->getProfileHintShopurl()){?>
                    <img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProfileHintShopurl()?>"/>
                <?php
                } ?>                
            </label>
            <div class="control" id="wk-mp-become-seller-box-wrapper" data-role="wk-mp-become-seller-box-wrapper">
                <span><?php echo $misHelper->getBaseUrl().'marketplace/seller/profile/shopUrl';  ?></span>
                <input type="text" class="input-text required-entry" name="profileurl" id="profileurl" data-role="shop-url" placeholder="<%- data.title %>" title="<%- data.title %>" value="<?php echo isset($_SESSION["profileurl"]) ? $_SESSION["profileurl"] : null; ?>"/>
                <div id="wk-load" class="no-display">
                    <img height="16px" width="16px" src="<%- data.src %>" />
                </div>
                <span class="required-entry" type="text"> 
                    <%- data.text %>
                </span>
            </div>

            <div id="wk-load" class="no-display">
                <img height="16px" width="16px" src="<%- data.src %>" />
            </div>
        </div>
        <div class="website_url field required">
            <label class="label">
                <%- data.websiteTitle %>             
            </label>
            <div class="control" id="mis-mp-become-seller-box-wrapper" data-role="mis-mp-become-seller-box-wrapper">
                <input type="text" class="input-text website_url_field" name="website_url" id="website_url" data-role="website_url" placeholder="<%- data.websitePlaceholder %>" title="<%- data.websiteTitle %>" value="<?php echo isset($_SESSION["website_url"]) ? $_SESSION["website_url"] : null; ?>"/>
                <span class="required-entry" type="text"> 
                    <%- data.websiteText %>
                </span>
                <br/>
                <span class="website_url_issue" style="display: none;color: #e02b27;font-size: 1.2rem;"> 
                    <?php echo __('Please enter correct URL');?>
                </span>
            </div>
        </div>

        <div class="contact_number field required">
            <label class="label">
                <%- data.contactTitle %>             
            </label>
            <div class="control" id="mis-mp-become-seller-box-wrapper" data-role="mis-mp-become-seller-box-wrapper">
                <input type="text" class="input-text required-entry validate-number" name="contact_number" id="contact_number" data-role="contact_number" placeholder="<%- data.contactPlaceholder %>" title="<%- data.contactTitle %>" value="<?php echo isset($_SESSION["contact_number"]) ? $_SESSION["contact_number"] : null; ?>"/>
            </div>
        </div>
        <div class="comp_address field required">
            <label class="label">
                <%- data.addressTitle %>             
            </label>
            <div class="control" id="mis-mp-become-seller-box-wrapper" data-role="mis-mp-become-seller-box-wrapper">
               <!--  <input type="text" class="input-text required-entry" name="comp_address" id="comp_address" data-role="comp_address" placeholder="<%- data.addressPlaceholder %>" title="<%- data.addressTitle %>" value=""/> -->
                <textarea class="required-entry" name="comp_address" id="comp_address" data-role="comp_address" placeholder="<%- data.addressPlaceholder %>" title="<%- data.addressTitle %>" rows="5" cols="40"><?php echo isset($_SESSION["comp_address"]) ? $_SESSION["comp_address"] : null; ?></textarea>
            </div>
        </div>
        <!-- <div class="invoice_settings field required">
            <label for="generate_invoice"><?php //echo __("Generate Invoice"); ?></label>
            <select name="generate_invoice" id="generate_invoice">
                <option value="weekly"><?php //echo __("Weekly"); ?></option>
                <option value="monthly"><?php //echo __("Monthly"); ?></option>
            </select>
        </div> -->
    </script>
</div>
<?php
$shopurl_hint = '';
if($profile_hint_status && $helper->getProfileHintShopurl()){
    $shopurl_hint = '<img src="'.$this->getViewFileUrl('Webkul_Marketplace::images/quest.png').'" class="questimg" title="'.$helper->getProfileHintShopurl().'"/>';

}else{
    $shopurl_hint = '';
} ?>

<?php
$formData = [
    'ajaxSaveUrl' => $block->getUrl("marketplace/seller/usernameverify", ["_secure" => $this->getRequest()->isSecure()]),
    'successMessage' => __("Congratulations! Shop name is available."),
    'errorMessage' => __("Sorry! But this shop name is not available, please set another shop name."),
    'loaderImage' => $this->getViewFileUrl('Webkul_Marketplace::images/ajax-loader-tr.gif'),
    'button' => 'button.submit'
];
$serializedFormData = $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($formData);
?>

<script type="text/x-magento-init">
    {
        "#form-validate": {
            "verifySellerShop": <?php /* @noEscape */ echo $serializedFormData; ?>
        }
    }
</script>
<script type="text/javascript">
require([
        "jquery"
    ], function($){
    jQuery('.form-create-account').on('submit',function(event){
        var radioValue = jQuery("input[name='is_seller']:checked").val();
        if (radioValue == 1) {
            var websiteUrlVal = jQuery('.website_url_field').val();
            var re = /^(http[s]?:\/\/){0,1}(www\.){0,1}[a-zA-Z0-9\.\-]+\.[a-zA-Z]{2,5}[\.]{0,1}/;
            if (re.test(websiteUrlVal)) { 
                jQuery('.website_url_issue').css('display','none');
                return true;
            } else{
                event.preventDefault();
                jQuery('.website_url_issue').css('display','block');
                return false;
            }
        }
    });
});
    
</script>
