<?php  
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) 2010-2018 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
 
// @codingStandardsIgnoreFile
$helper = $this->helper('Webkul\Marketplace\Helper\Data');
$mangoit_helper = $this->helper('Mangoit\Marketplace\Helper\Data');
// print_r($mangoit_helper->getCustomerUpdated());
$partner=$block->getProfileDetail();
if ($partner['shop_url']) {
    if ($helper->getActiveColorPicker() || (!empty($partner['shop_background_img']))) { 
        $mediaUrl = $mangoit_helper->getMediaUrl().'avatar/';
        ?> 
        <style>
            .page-main{
                background-image:url(<?php echo (!empty($partner['shop_background_img']) ? $mediaUrl.$partner['shop_background_img']: 'none') ?>) !important;
                background-color:<?php echo (!empty($partner['background_width']) ? $partner['background_width']: '')?> !important;
            }
        </style>
    <?php } ?>
    <div class="wk_mp_design">
        <?php echo $block->getChildHtml("marketplace_seller_top_block")?>
        <div class="wk-mp-collection-container">
            <div class="wk-mp-profile-block" id="about-us">
                <div class="wk-mp-aboutus-title">
                    <?php echo __("About Us")?>
                </div>
                <div class="wk-mp-aboutus-data">
                    <?php echo $partner['company_description'];?>
                    <?php echo $block->getChildHtml("marketplace_seller_description")?>
                </div>
            </div>
            <?php echo $this->getChildHtml('marketplace_sellerprofile_recently_added_products')?>
            <?php echo $this->getChildHtml('marketplace_sellerprofile_rating')?>
            <?php /* if ($helper->getSellerPolicyApproval()) { ?>	
                <div class="wk-mp-profile-block" id="wk-mp-policy-block">
                    <div class="wk-mp-policy-block wk-mp-shipping-policy" id="shipping-policy">
                        <div class="wk-mp-policy-block-title">
                            <?php echo __("Shipping Policy")?>
                        </div>
                        <div class="wk-mp-policy-block-data">
                            <?php echo $partner['shipping_policy'];?>
                        </div>
                    </div>
                    <div class="wk-mp-policy-block wk-mp-return-policy" id="return-policy">
                        <div class="wk-mp-policy-block-title">
                            <?php echo __("Return Policy")?>
                        </div>
                        <div class="wk-mp-policy-block-data">
                            <?php echo $partner['return_policy'];?>
                        </div>
                    </div>
                </div>
            <?php } */?>
        </div>
    </div>
<?php }  ?>
