<?php

/** @var \Algolia\AlgoliaSearch\Block\Instant\Hit $block */
$priceKey     = $block->getPriceKey();
$currencyCode = $block->getCurrencyCode();
$baseVar         = $block->escapeHtml('price' . $priceKey);
$maxVar          = $block->escapeHtml('price' . $priceKey . '_max');
$baseFormatedVar = $block->escapeHtml('price' . $priceKey . '_formated');
$origFormatedVar = $block->escapeHtml('price' . $priceKey . '_original_formated');
$tierFormatedVar = $block->escapeHtml('price' . $priceKey . '_tier_formated');
?>

<script type="text/template" id="instant-hit-template">
    <div class="col-md-3 col-sm-6" itemscope>
        <meta content="{{__position}}" />
        <div class="result-wrapper">
            <meta 
                {{^__queryID}} content="{{url}}" {{/__queryID}}
                {{#__queryID}} content="{{urlForInsights}}" {{/__queryID}}
                />
            <a class="result"
                {{^__queryID}} href="{{url}}" {{/__queryID}}
                {{#__queryID}} href="{{urlForInsights}}" {{/__queryID}}
                data-objectid="{{objectID}}"
                data-indexname="{{__indexName}}"
                data-position="{{__position}}"
                data-new="{{new}}"
                data-sale="{{sale}}"
                data-queryid="{{__queryID}}">
                <div class="result-content">
                    <div class="result-thumbnail">
                        {{#new}}<span class="product-label new-label"><span>New</span></span>{{/new}}
                        {{#sale}}<span class="product-label sale-label"><span>Sale</span></span>{{/sale}}
                        <div class="hover-effect">
                            <ul class="actions-link" data-role="add-to-links">

                                <li><button data-product-id = {{objectID}} data-title="<?php echo $block->escapeHtml(__('Quick View')); ?>" class="action mgs-quickview" data-quickview-url='' title="<?php echo $block->escapeHtml(__('Quick View')); ?>"><span class="pe-7s-search"></span>
                                </button>
                                </li>
                                <li><button data-title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" 
                                    class="action towishlist-alg"
                                    title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                    aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                    role="button"
                                    data-product-id={{objectID}}>
                                    <i class="pe-7s-like"></i>
                                    </button>
                                </li>
                                
                                <li><button data-title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                    class="action tocompare-alg"
                                    title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                    aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                    data-product-id={{objectID}}
                                    role="button">
                                    <i class="pe-7s-graph3"></i>
                                    </button>
                                </li>
                            </ul>

                            {{#isAddToCartEnabled}}
                            <form data-role="tocart-form" action="{{ addToCart.action }}" method="post">
                                <input type="hidden" name="product" value="{{objectID}}"> 
                                <input type="hidden" name="uenc" value="{{ addToCart.uenc }}">
                                <input name="form_key" type="hidden" value="{{ addToCart.formKey }}">
                                <button class="action tocart primary" type="submit" title="<?php echo __('Add to Cart') ?>" 
                                data-objectid="{{objectID}}"
                                data-indexname="{{__indexName}}"
                                data-position="{{__position}}"
                                data-queryid="{{__queryID}}"
                                >
                                <span class="icon pe-7s-shopbag"></span>
                                <span><?php echo __('Add to Cart') ?></span>
                                </button>
                            </form>
                            {{/isAddToCartEnabled}}
                        </div>
                        {{#image_url}}<img src="{{{image_url}}}" alt="{{{name}}}" />{{/image_url}}
                        {{^image_url}}<span class="no-image"></span>{{/image_url}}
                    </div>
                    <div class="result-sub-content">
                        <h3 class="result-title text-ellipsis">
                            {{{ _highlightResult.name.value }}}
                        </h3>
                        <div class="ratings">
                            <div class="result-sub-content">
                                <div class="product-reviews-summary short">
                                    <div class="rating-summary">
                                        <span class="label"><span><?php echo __('Rating') ?>:</span></span>
                                        <div class="rating-result" title="{{rating_summary}}%">
                                            <span style="width:{{rating_summary}}%">
                                                <span>{{rating_summary}}%</span>
                                            </span>
                                        </div>
                                    </div>
                                </div>

                                {{^<?php echo $maxVar; ?>}}
                                <div itemscope itemtype="http://schema.org/Offer" class="price">
                                    <meta content="{{<?php echo $baseVar; ?>}}" />
                                {{/<?php echo $maxVar; ?>}}
                                {{#<?php echo $maxVar; ?>}}
                                <div itemscope itemtype="http://schema.org/AggregateOffer" class="price">
                                    <meta  content="{{<?php echo $baseVar; ?>}}" />
                                    <meta  content="{{<?php echo $maxVar; ?>}}" />
                                {{/<?php echo $maxVar; ?>}}
                                    <meta content="<?php echo $currencyCode; ?>" />
                                    <div class="price-wrapper">
                                        <div>

                                            <span class="after_special
                                                    {{#<?php echo $origFormatedVar; ?>}}
                                                        promotion
                                                    {{/<?php echo $origFormatedVar; ?>}}">
                                                {{<?php echo $baseFormatedVar; ?>}}
                                            </span>
                                            {{#<?php echo $origFormatedVar; ?>}}
                                                <span class="before_special">
                                                    {{<?php echo $origFormatedVar; ?>}}
                                                </span>
                                            {{/<?php echo $origFormatedVar; ?>}}
                                            {{#<?php echo $tierFormatedVar; ?>}}
                                                <span class="tier_price">
                                                    <?php echo __('As low as') ?>
                                                    <span class="tier_value">{{<?php echo $tierFormatedVar; ?>}}</span>
                                                </span>
                                            {{/<?php echo $tierFormatedVar; ?>}}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="result-description text-ellipsis">{{{ _highlightResult.description.value }}}</div>

                    </div>
                </div>
                <div class="algolia-clearfix"></div>
            </a>
        </div>
    </div>
</script>
<script type="text/javascript">
    require(['jquery','mage/url','mgs_quickview'], function($, url, quickview) {
        $(window).load(function() {
            setTimeout(
                function(){ 
                var compare_product_url = url.build('algoliafix/guestwishlist/index'); 
                $('.tocompare-alg').each(function(){
                    $(this).on('click', function(e){
                        e.stopPropagation();
                        e.preventDefault();
                        var product_id = $(this).data('product-id');
                        window.location.href = compare_product_url+"/product/"+product_id;
                    });
                });

                $('.mgs-quickview').each(function(){
                    $(this).on('click', function(e){
                        var QuickViewAjaxUrl = url.build('mgs_quickview/catalog_product/view');
                        var quickProductId = $(this).data('product-id');
                        var prodUrl = QuickViewAjaxUrl+"/id/"+quickProductId;
                        e.stopPropagation();
                        e.preventDefault();
                        if (prodUrl.length) {
                            quickview.displayContent(prodUrl);
                        }
                    });
                });

                var AjaxUrl = url.build('algoliafix/guestwishlist/add');
                $('.towishlist-alg').each(function(){
                    $(this).on('click', function(e){
                        e.stopPropagation();
                        e.preventDefault();
                       $('.towishlist-alg').on('click', function(){
                        var product_id = $(this).data('product-id');
                        window.location.href = AjaxUrl+"/product/"+product_id;
                       });               
                    });
                });

                $(".result-thumbnail").mouseover(function(){
                    $(this).children("span.product-label").hide();
                });

                $(".result-thumbnail").mouseout(function(){
                    $(this).children("span.product-label").show();
                });

            }, 2000);
        });
    });
</script>
