<style type="text/css">
</style>
<?php 
/*echo "<pre>";*/
$blockNames = $block->getBlockName();
/*print_r($block->getBlockName());
foreach ($blockNames as $key => $value) {
    echo "<br>position: ".$value['position'];
    echo "<br>blockname: ".$value['blockname'];
}
die("<br>002");*/
$storeCollection = $block->getAllStoreList();
$productModel = $block->getProductList();
$productModel->addAttributeToSelect('*');
$categoryCollection = $block->getCategories();
$categoryCollection->addAttributeToSelect('*');
// $url = $this->getBaseUrl();
$url =  $this->helper('Magento\Backend\Helper\Data');
// echo("<pre>");
// print_r($this->getUrl('advertisement/adminads/save'));
// die();
?>

             
<form id="forImage" method="post" enctype="multipart/form-data" action="<?php echo $this->getUrl('advertisement/adminads/save');?>">
    <div class="page-main-actions">
        <div class="page-actions-placeholder">        
        </div>
        <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
            <div class="page-actions-inner" data-title="Manage Pricing">
                <div class="page-actions-buttons">
                    <button id="back" title="Back" type="button" class="action-default scalable back" onclick="goBack()" >
                            <span>Back</span>
                        </button>
                    <button id="save" title="Save" type="submit" class="action- scalable primary" data-ui-id="add-button">
                        <span>Save</span>
                    </button>
                </div>
            </div>
        </div>
    </div>

    <input name="form_key" type="hidden" value="<?php echo $this->getFormKey();?>">
    <input name="content_type" type="hidden" value="" id="content_type">
    <input name="block_name" type="hidden" value="" id="block_name">

    <div class="admin__field _required adBlockName" >
        <label class="admin__field-label" for="internalBlocks">
            <span><?php echo __('Select Ad Block')?></span>
        </label>
        <div class="admin__field-control" >
            <select  class="admin__control-select internalBlocks" name="internalBlock" id="internalBlocks">
                    <option value="0" data-content="0"><?php echo __('Select')?></option>
                    <?php foreach ($blockNames as $key => $value) { ?>
                        <option value="<?php echo $value['position'] ?>" data-content="<?php echo $value['content']?>" ><?php echo __($value['blockname'])?></option>
                    <?php } ?>          
            </select>
            <span id='internalBlocksErr' style='display: none; color: red;''><?php echo __('Please select this field')?></span>
        </div>
    </div>

    <div class="admin__field image advfield" style="display: none;" >
        <table class="data-grid">
            <tr>
                <th class="data-grid-th col-entity_id"><?php echo __('Image')?></th>
                <th class="data-grid-th col-entity_id"><?php echo __('Store')?></th>
                <th class="data-grid-th col-entity_id"><?php echo __('Url')?></th>
                <th class="data-grid-th col-entity_id"><?php echo __('Title')?></th>
                <th class="data-grid-th col-entity_id"><?php echo __('')?></th>
                <th class="data-grid-th col-entity_id"><?php echo __('')?></th>
            </tr>
            <tr class="imagerow">
                <td><input type="file" accept="image/*" class='imgFile' name="imageArr[]">
                    <span style="display: none; color: red"><?php echo __('Image size should be lesser than 2 MB')?></span>
                </td>
                <td>
                    <select  class="admin__control-select" id="storeDrop" name="image[0][imageStore]">
                            <option selected="selected"><?php echo __('All Store')?></option>
                            <?php foreach ($storeCollection as $store) {
                                if (($store['group_id'] >= 1) && ($store['is_active'] == 1)) { ?>
                                    <option value="<?php echo $store['store_id'] ?>" data-storeid="<?php echo $store['code']?>" ><?php echo __($store['name'])?></option>
                            <?php }
                            } ?>          
                    </select>
                </td>
                <td><input type="text" class="Url" name="image[0][imageUrl]">
                <span style='display: none; color: red'><?php echo __('URL is incorrect.')?></span>
                </td>
                <td><input type="text" class='title' name="image[0][imageTitle]">
                    <span style='display: none; color: red'><?php echo __('Field cant be empty.')?></span>
                </td></td>
                <td><input type="button" name="" class="addmore" value="Add More" onclick="onImageAdmore();"></td>
                <td><input type='button' name='' class='removeImg' value='Remove' onclick='onImageRemove();'></td>
            </tr>
        </table>
    </div>

<div class="admin__field product advfield" style="display: none;" >
    <table class="data-grid">
        <tr>
            <th class="data-grid-th col-entity_id"><?php echo __('image')?></th>
            <th class="data-grid-th col-entity_id"><?php echo __('Store')?></th>
            <th class="data-grid-th col-entity_id"><?php echo __('Product')?></th>
            <th class="data-grid-th col-entity_id"><?php echo __('Url')?></th>
            <th class="data-grid-th col-entity_id"><?php echo __('Title')?></th>
            <th class="data-grid-th col-entity_id"><?php echo __('')?></th>
            <th class="data-grid-th col-entity_id"><?php echo __('')?></th>
        </tr>
        <tr class="productrow">
            <td><input type="file" accept="image/*" class="productImgFile" name="productImgFile[]">
                <span style="display: none; color: red"><?php echo __('Image size should be lesser than 2 MB')?></span>
            </td>
            <td>
                <select  class="admin__control-select " id="storeDrop" name="product[0][product_store]">
                        <option selected="selected"><?php echo __('All Store')?></option>
                        <?php foreach ($storeCollection as $store) {
                            if (($store['group_id'] >= 1) && ($store['is_active'] == 1)) { ?>
                                <option value="<?php echo $store['store_id'] ?>" data-storeid="<?php echo $store['code']?>" ><?php echo __($store['name'])?></option>
                        <?php }
                        } ?>          
                </select>
            </td>
            <td>
                <select id="product-list" class="admin__control-select mis_product_select" name="product[0][product_id]" onchange="productSelectChange();">
                    <option value="0" selected="selected" ><?php echo __('Select Product')?></option>
                   <?php foreach ($productModel as $item) {  ?>
                    <option value="<?php echo $item->getEntityId()?>" data-row='1' data-url="<?php echo $item->getProductUrl()?>"><?php echo $item->getName()?></option>
                    <?php } ?>
                </select>
                <span style="display: none; color: red"><?php echo __('Please select any product')?></span>
            </td>
            <td><input type="text" class='ProUrl' name="product[0][product_url]" id="pro_row_1">
                <span style='display: none; color: red'><?php echo __('URL is incorrect.')?></span>
            </td>
            <td><input type="text" class='proTitle' name="product[0][product_title]">
                <span style='display: none; color: red'><?php echo __('Field cant be empty.')?></span>
            </td></td>
            <td><input type="button" name="" class="addmore" value="Add More" onclick="onProductAdmore();"></td>
            <td><input type='button' name='' class='removePro' value='Remove'></td>
        </tr>
    </table>
</div>

<div class="admin__field category advfield" style="display: none;" >
	<table class="data-grid">
		<tr>
			<th class="data-grid-th col-entity_id"><?php echo __('image')?></th>
            <th class="data-grid-th col-entity_id"><?php echo __('Store')?></th>
			<th class="data-grid-th col-entity_id"><?php echo __('Category')?></th>
			<th class="data-grid-th col-entity_id"><?php echo __('Url')?></th>
            <th class="data-grid-th col-entity_id"><?php echo __('Title')?></th>
            <th class="data-grid-th col-entity_id"><?php echo __('')?></th>
			<th class="data-grid-th col-entity_id"><?php echo __('')?></th>
		</tr>
        <tr class="catagoryrow">
            <td><input type="file" class="categoryImgFile" accept="image/*" name="categoryImgFile[]">
                <span style="display: none; color: red"><?php echo __('Image size should be lesser than 2 MB')?></span>
            </td>
            <td>
                <select  class="admin__control-select" id="storeDrop" name="category[0][category_store]">
                        <option selected="selected"><?php echo __('All Store')?></option>
                        <?php foreach ($storeCollection as $store) {
                            if (($store['group_id'] >= 1) && ($store['is_active'] == 1)) { ?>
                                <option value="<?php echo $store['store_id'] ?>" data-storeid="<?php echo $store['code']?>" ><?php echo __($store['name'])?></option>
                        <?php }
                        } ?>          
                </select>
            </td>
            <td>
                <select id="category-list" class="admin__control-select mis_category_select" name="category[0][category_id]">
            <option value="0" selected="selected" ><?php echo __('Select Category')?></option>
            <?php
                foreach ($categoryCollection as $item) { 
                    if ($item->getEntityId() > 2) {?>
                <option value="<?php echo $item->getEntityId()?>" data-row='1' data-caturl="<?php echo $item->getUrl()?>"><?php echo $item->getName()?></option>
            <?php   }
               }
            ?>
        </select>
            <span style="display: none; color: red"><?php echo __('Please select any category')?></span>
            </td>
            <td><input type="text" name="category[0][category_url]" class='catUrl' id="cat_row_1">
            <span style='display: none; color: red'><?php echo __('URL is incorrect.')?></span>
            </td>
            <td><input type="text" class='catTitle' name="category[0][category_title]">
                <span style='display: none; color: red'><?php echo __('Field cant be empty.')?></span>
            </td>
            <td><input type="button" name="" class="addmore" value="Add More" onclick="onCategoryAdmore();"></td>
            <td><input type='button' name='' class='removeCat' value='Remove'></td>
        </tr>
	</table>
</div>

<div class="admin__field advfield htmleditor " style="display: none;">
    <label class="admin__field-label" for="storeDrop">
        <span><?php echo __('Store View')?></span>
    </label>
    <div class="admin__field-control" >
        <select  class="admin__control-select" id="htmlStoreDrop" name="html[html_store]">
                <option selected="selected"><?php echo __('All Store')?></option>
                <option value="0"><?php echo __('Select');?></option>
                <?php foreach ($storeCollection as $store) {
                    if (($store['group_id'] >= 1) && ($store['is_active'] == 1)) { ?>
                        <option value="<?php echo $store['store_id'] ?>" data-storeid="<?php echo $store['code']?>" ><?php echo __($store['name'])?></option>
                <?php }
                } ?>          
        </select>
        <span style='display: none; color: red'><?php echo __('Please select any store.')?></span>
    </div>
    <label class="admin__field-label" for="html_editor">
        <span><?php echo __('Html Editor')?></span>
    </label>
    <div class="admin__field-control" >
        <textarea id="html_editor" name="html[html_editor]" class="required-entry input-text required-entry _required"></textarea>
    </div>
    <span id="htmltext" style='display: none; color: red'><?php echo __('Field cant be empty.')?></span>
    <label class="admin__field-label" for="html_url">
        <span><?php echo __('Url')?></span>
    </label>
    <div class="admin__field-control" >
        <input type="text" class="htmlUrl" name="html[html_url]" id="html_url">
        <span style='display: none; color: red'><?php echo __('URL is incorrect.')?></span>
    </div>

    <label class="admin__field-label" for="html_title">
        <span><?php echo __('Ad Block Title')?></span>
    </label>
    <div class="admin__field-control" >
        <input type="text" class='htmltitle' name="html[html_title]" id="html_title">
        <span style='display: none; color: red'><?php echo __('Field cant be empty.')?></span>
    </div>


    <!-- <table class="data-grid">
       <!--  <tr>
            <th class="data-grid-th col-entity_id"><?php echo __('Html Editor')?></th>
            <th class="data-grid-th col-entity_id"><?php echo __('Store')?></th>
            <th class="data-grid-th col-entity_id"><?php echo __('Url')?></th>
            <th class="data-grid-th col-entity_id"><?php echo __('Title')?></th>
            <th class="data-grid-th col-entity_id"><?php echo __('')?></th>
        </tr> -->
       <!--  <tr class="htmlrow">
            <td><textarea id="html_editor" name="html_editor" class="required-entry input-text required-entry _required"></textarea></td>
            <td>
                <select  class="admin__control-select" id="storeDrop">
                        <option selected="selected"><?php echo __('All Store')?></option>
                        <?php foreach ($storeCollection as $store) {
                            if (($store['group_id'] >= 1) && ($store['is_active'] == 1)) { ?>
                                <option value="<?php echo $store['code'] ?>" data-storeid="<?php echo $store['store_id']?>" ><?php echo __($store['name'])?></option>
                        <?php }
                        } ?>          
                </select>
            </td>
            <td><input type="text" name="" id="html_row_1"></td>
            <td><input type="text" name=""></td>
            <td><input type="button" name="" class="addmore" value="Add More" onclick="onHtmlAdmore();"></td>
        </tr>
    </table>   -->
</div>



</form>
<script type="text/javascript">
var pro_counter = 2;
var product_row_counter = 1;
var category_row_counter = 1;
var cat_counter = 2;
var html_counter = 2;
var image_row_counter = 1;


function onImageAdmore()
{

var imageField = "<tr class='imagerow'>"+
                    "<td><input type='file' accept='image/*' class='imgFile' name='imageArr[]'>"+
                    "<span style='display: none; color: red'><?php echo __('Image size should be lesser than 2 MB')?></span>"+
                    "</td>"+
                    "<td>"+
                        "<select class='admin__control-select' name='image["+image_row_counter+"][imageStore]' id='storeDrop'>"+
                            "<option selected='selected'><?php echo __('All Store')?></option>"+
                            "<?php foreach ($storeCollection as $store) {
                                if (($store['group_id'] >= 1) && ($store['is_active'] == 1)) { ?> "+
                                    "<option value=<?php echo $store['store_id'] ?>  data-storeid=<?php echo $store['code']?> >"+
                                    "<?php echo __($store['name'])?></option>"+
                                "<?php }  } ?>"+
                        "</select>"+
                    "</td>"+
                    "<td>"+
                    "<input type='text' class='Url' name='image["+image_row_counter+"][imageUrl]'>"+
                    "<span style='display: none; color: red'><?php echo __('URL is incorrect.')?></span>"+
                    "</td>"+
                    "<td><input type='text' class='title' name='image["+image_row_counter+"][imageTitle]'>"+
                    "<span style='display: none; color: red'><?php echo __('Field cant be empty.')?></span>"+
                    "</td>"+
                    "<td><input type='button' name='' class='addmore' value='Add More' onclick='onImageAdmore();'></td>"+
                    "<td><input type='button' name='' class='removeImg' value='Remove' onclick='onImageRemove();'></td>"
                "</tr>";
    // var tblRowData = rowAdd();
    jQuery('.imagerow').last().after(imageField);
    image_row_counter++;
}

function onImageRemove()
{
    // var tblRowData = rowAdd();
    console.log('imge removce')
    
}
function onProductAdmore()
{
    // var tblRowData = rowAdd();
    
    var productField = "<tr class='productrow'>"+
                    "<td><input type='file' accept='image/*' name='productImgFile[]' class='productImgFile' >"+
                    "<span style='display: none; color: red'><?php echo __('Image size should be lesser than 2 MB')?></span>"+
                    "</td>"+
                    "<td>"+
                        "<select class='admin__control-select' name='product["+product_row_counter+"][product_store]' id='storeDrop'>"+
                            "<option selected='selected'><?php echo __('All Store')?></option>"+
                            "<?php foreach ($storeCollection as $store) {
                                if (($store['group_id'] >= 1) && ($store['is_active'] == 1)) { ?> "+
                                    "<option value=<?php echo $store['store_id'] ?> data-storeid=<?php echo $store['code']?> >"+
                                    "<?php echo __($store['name'])?></option>"+
                                "<?php }  } ?>"+
                        "</select>"+
                    "</td>"+
                    "<td>"+
                        "<select id='product-list' class='admin__control-select mis_product_select' name='product["+product_row_counter+"][product_id]'>"+
                            "<option value='0' selected='selected'><?php echo __('Select Product')?></option>"+
                        "<?php
                                foreach ($productModel as $item) {  ?>"+
                                "<option value=<?php echo $item->getEntityId()?> data-row="+pro_counter+" data-url=<?php echo $item->getProductUrl()?>><?php echo $item->getName()?></option>"+
                                "<?php } ?>"+
                            "</select>"+
                            "<span style='display: none; color: red'><?php echo __('Please select any product')?></span>"+
                        "</td>"+
                    "<td><input type='text' class='ProUrl' name='product["+product_row_counter+"][product_url]' id='pro_row_"+pro_counter+"'>"+
                    "<span style='display: none; color: red'><?php echo __('URL is incorrect.')?></span>"+
                    "</td>"+
                    "<td><input type='text' class='proTitle' name='product["+product_row_counter+"][product_title]'>"+
                    "<span style='display: none; color: red'><?php echo __('Field cant be empty.')?></span>"+
                    "</td>"+
                    "<td><input type='button' name='' class='addmore' value='Add More' onclick='onProductAdmore();'></td>"+
                    "<td><input type='button' name='' class='removePro' value='Remove'></td>"+
                "</tr>";
    pro_counter++;

    jQuery('.productrow').last().after(productField);
    product_row_counter++;
}

function onHtmlAdmore()
{
    var htmlField = "<tr class='htmlrow'>"+
                        "<td><textarea id='html_editor' name='html_editor' class='required-entry input-text required-entry _required wysiwyg-editor'></textarea></td>"+
                        "<td>"+
                            "<select  class='admin__control-select' id='storeDrop'>"+
                                    "<option selected='selected'><?php echo __('All Store')?></option>"+
                                    "<?php foreach ($storeCollection as $store) {
                                        if (($store['group_id'] >= 1) && ($store['is_active'] == 1)) { ?>"+
                                           "<option value=<?php echo $store['code'] ?> data-storeid=<?php echo $store['store_id']?> ><?php echo __($store['name'])?></option>"+
                                    "<?php }
                                    } ?>"+          
                            "</select>"+
                        "</td>"+
                        "<td><input type='text' class='htmlUrl' name='' >"+
                        "<span style='display: none; color: red'><?php echo __('URL is incorrect.')?></span>"+
                        "</td>"+
                        "<td><input type='text' class='htmltitle' name=''>"+
                        "<span style='display: none; color: red'><?php echo __('Field cant be empty.')?></span>"+
                        "</td>"+

                        "<td><input type='button' name='' class='addmore' value='Add More' onclick='onHtmlAdmore();''></td>"+
                    "</tr>";
    jQuery('.htmlrow').last().after(htmlField);
    
}

function onCategoryAdmore()
{
    // var tblRowData = rowAdd();
    
    var categoryField = "<tr class='catagoryrow'>"+
                    "<td><input type='file' class='categoryImgFile' accept='image/*' name='categoryImgFile[]'>"+
                    "<span style='display: none; color: red'><?php echo __('Image size should be lesser than 2 MB')?></span>"+
                    "</td>"+
                    "<td>"+
                        "<select class='admin__control-select' name='category["+category_row_counter+"][category_store]' id='storeDrop'>"+
                            "<option selected='selected'><?php echo __('All Store')?></option>"+
                            "<?php foreach ($storeCollection as $store) {
                                if (($store['group_id'] >= 1) && ($store['is_active'] == 1)) { ?> "+
                                    "<option value=<?php echo $store['store_id'] ?> data-storeid=<?php echo $store['code']?> >"+
                                    "<?php echo __($store['name'])?></option>"+
                                "<?php }  } ?>"+
                        "</select>"+
                        "<span style='display: none; color: red'><?php echo __('Please select any category')?></span>"+
                    "</td>"+
                    "<td>"+
                        "<select id='product-list' name='category["+category_row_counter+"][category_id]' class='admin__control-select mis_category_select'>"+
                            "<option value='0' selected='selected'><?php echo __('Select category')?></option>"+
                        "<?php
                                foreach ($categoryCollection as $item) { 
                                    if ($item->getEntityId() > 2) { ?>"+
                                "<option value=<?php echo $item->getEntityId()?> data-row="+cat_counter+" data-caturl=<?php echo $item->getUrl()?>><?php echo $item->getName()?></option>"+
                                "<?php } } ?>"+
                            "</select>"+
                            "<span style='display: none; color: red'><?php echo __('Please select any catagory')?></span>"+
                        "</td>"+
                    "<td><input type='text' class='catUrl' name='category["+category_row_counter+"][category_url]' id='cat_row_"+cat_counter+"'>"+
                         "<span style='display: none; color: red'><?php echo __('URL is incorrect.')?></span>"+
                    "</td>"+
                    "<td><input type='text' class='catTitle' name='category["+category_row_counter+"][category_title]'>"+
                         "<span style='display: none; color: red'><?php echo __('Field cant be empty.')?></span>"+
                         "</td>"+
                    "<td><input type='button' name='' class='addmore' value='Add More' onclick='onCategoryAdmore();'></td>"+
                    "<td><input type='button' name='' class='removeCat' value='Remove'></td>"+
                "</tr>";
    cat_counter++;
    console.log('cat_counter '+cat_counter);
    category_row_counter++;

    jQuery('.catagoryrow').last().after(categoryField);
}

function productSelectChange()
{
    // // var productUrl =  jQuery('option:selected', this).attr('data-url');
    // var productUrl =  jQuery(this :selected).attr('data-url');
    // // var productUrl = this.options[this.selectedIndex].getAttribute('data-url');
    // var pro_row_num = jQuery('option:selected', this).attr('data-row');
    // // var pro_row_num = this.options[this.selectedIndex].getAttribute('data-row');
    // console.log('Url '+productUrl);
    // console.log('pro_row_num '+pro_row_num);
    // jQuery('pro_row_'+pro_row_num).val('');
    // jQuery('pro_row_'+pro_row_num).val('productUrl');
}

function urlonly(url){
    var patt = /https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/;
    if (patt.test(url) ) {
        console.log(patt.test(url));
        return true;
    } else {
        console.log(patt.test(url));
        return false;
    }
}

require(['jquery', 'jquery/ui'], function($){ 

    jQuery(document).on('click', '.removeImg', function(){
        jQuery(this).parent().parent().remove();
    });
    
    jQuery(document).on('click', '.removeCat', function(){
        jQuery(this).parent().parent().remove();
    });
    jQuery(document).on('click', '.removePro', function(){
        jQuery(this).parent().parent().remove();
    });
    
    jQuery(document).on('change', '.mis_product_select', function(){
        var selectedVal = jQuery(this).val();
        if (selectedVal == '') {
             jQuery('#pro_row_'+pro_row_num).val('');
        }
        var productUrl = this.options[this.selectedIndex].getAttribute('data-url')
        var pro_row_num = this.options[this.selectedIndex].getAttribute('data-row');
        console.log('Url '+productUrl);
        console.log('pro_row_num '+pro_row_num);
        jQuery('#pro_row_'+pro_row_num).val('');
        jQuery('#pro_row_'+pro_row_num).val(productUrl);
    });

    jQuery(document).on('change', '.mis_category_select', function(){
        var selectedVal = jQuery(this).val();
        var catUrl = this.options[this.selectedIndex].getAttribute('data-caturl')
        var cat_row_num = this.options[this.selectedIndex].getAttribute('data-row');
        console.log('catUrl Url '+catUrl);
        console.log('pro_row_num '+cat_row_num);
        jQuery('#cat_row_'+cat_row_num).val('');
        jQuery('#cat_row_'+cat_row_num).val(catUrl);
        if (selectedVal == '') {
             jQuery('#cat_row_'+pro_row_num).val('');
        }
    });

	jQuery(document).on('change', '#internalBlocks', function(){
		// console.log(jQuery(this).val()); 
        var blockname = jQuery('#internalBlocks :selected').text();
        console.log('blockname '+blockname);
        jQuery('#block_name').val(blockname);
        var contentType = this.options[this.selectedIndex].getAttribute('data-content');
        console.log('contentType '+contentType);
        switch(contentType) {
		    case '1':
                // jQuery('.link').val('');
            jQuery('#internalBlocksErr').css('display', 'none');
                jQuery('#content_type').val('1');
                jQuery('.htmleditor').find('*').attr('disabled', true);
                jQuery('.category').find('*').attr('disabled', true);
                jQuery('.product').find('*').attr('disabled', true);
                jQuery('.image').find('*').attr('disabled', false);

                jQuery('.htmleditor').css('display', 'none');                
                jQuery('.category').css('display', 'none');
		        jQuery('.product').css('display', 'none');
		        jQuery('.image').css('display', 'block');
		        break;
		    case '2':
            jQuery('#internalBlocksErr').css('display', 'none');
                jQuery('#content_type').val('2');
                // jQuery('.link').val('');
                jQuery('.htmleditor').find('*').attr('disabled', true);
                jQuery('.category').find('*').attr('disabled', true);
                jQuery('.product').find('*').attr('disabled', false);
                jQuery('.image').find('*').attr('disabled', true);

		    	jQuery('.image').css('display', 'none');
                jQuery('.htmleditor').css('display', 'none');                
		    	jQuery('.category').css('display', 'none');
		        jQuery('.product').css('display', 'block');
		        break;
		    case '3':
                // /*jQuery('.link').val('');
            jQuery('#internalBlocksErr').css('display', 'none');
                console.log('category');
                jQuery('#content_type').val('3');
                jQuery('.htmleditor').find('*').attr('disabled', true);
                jQuery('.category').find('*').attr('disabled', false);
                jQuery('.product').find('*').attr('disabled', true);
                jQuery('.image').find('*').attr('disabled', true);

		    	jQuery('.image').css('display', 'none');
                jQuery('.htmleditor').css('display', 'none');
		        jQuery('.product').css('display', 'none');
		        jQuery('.category').css('display', 'block');
		        break;
		    case '4':
            jQuery('#internalBlocksErr').css('display', 'none');
                // /*jQuery('.link').val('');
                jQuery('#content_type').val('4');
                jQuery('.htmleditor').find('*').attr('disabled', false);
                jQuery('.category').find('*').attr('disabled', true);
                jQuery('.product').find('*').attr('disabled', true);
                jQuery('.image').find('*').attr('disabled', true);

		        jQuery('.image').css('display', 'none');
		        jQuery('.product').css('display', 'none');
		        jQuery('.category').css('display', 'none');
                jQuery('.htmleditor').css('display', 'block');
		        break;
		    default:
                jQuery('#content_type').val('0');
                jQuery('.htmleditor').find('*').attr('disabled', true);
                jQuery('.category').find('*').attr('disabled', true);
                jQuery('.product').find('*').attr('disabled', true);
                jQuery('.image').find('*').attr('disabled', true);
		        jQuery('.advfield').css('display', 'none');
		}
	});

    jQuery(document).on('click', '#save', function() {
        var option = jQuery('option:selected', '#internalBlocks').attr('data-content');
        console.log(option)
        if (option == 0) {
            event.preventDefault();
            jQuery('#internalBlocksErr').css('display', 'block');
        } else if (option == 1) {
            jQuery(".Url").each(function() {
                if (jQuery(this).val().trim() == '') {
                    event.preventDefault();
                    jQuery(this).next().css({"color": "red", 'display':'block'});
                } else if (! urlonly(jQuery(this).val().trim())) {
                    event.preventDefault();
                    jQuery(this).next().css({"color": "red", 'display':'block'});
                } else {
                    console.log(jQuery(this).val().trim());
                    jQuery(this).next().css({'display':'none'});
                }
            });

            jQuery('.imgFile').each(function(){
                if (jQuery(this).val().trim() == '') {
                    event.preventDefault();
                    jQuery(this).next().text("Please upload image.");
                    jQuery(this).next().css({"color": "red", 'display':'block'});
                } else if (jQuery(this)[0].files[0].size > 2024000) {
                    event.preventDefault();
                    jQuery(this).next().text("Image size should be lesser than 2 MB.");
                    jQuery(this).next().css({"color": "red", 'display':'block'});
                } else {
                    jQuery(this).next().css({"color": "red", 'display':'none'});
                }
            });

            jQuery(".title").each(function() {
                if (jQuery(this).val().trim() == '') {
                    event.preventDefault();
                    jQuery(this).next().css({"color": "red", 'display':'block'});
                } else {
                    console.log(jQuery(this).val().trim());
                    jQuery(this).next().css({'display':'none'});
                }
            });

        } else if (option == 2) {
            jQuery(".mis_product_select").each(function() {
                if (jQuery(this).val() == 0) {
                    event.preventDefault();
                    jQuery(this).next().css({"color": "red", 'display':'block'});
                } else {
                    jQuery(this).next().css({'display':'none'});
                }
            });

            jQuery('.productImgFile').each(function(){
                if (jQuery(this).val().trim() == '') {
                    event.preventDefault();
                    jQuery(this).next().text("Please upload image.");
                    jQuery(this).next().css({"color": "red", 'display':'block'});
                } else if (jQuery(this)[0].files[0].size > 2024000) {
                    event.preventDefault();
                    jQuery(this).next().text("Image size should be lesser than 2 MB.");
                    jQuery(this).next().css({"color": "red", 'display':'block'});
                } else {
                    jQuery(this).next().css({"color": "red", 'display':'none'});
                }
            });

            jQuery(".ProUrl").each(function() {
                if (jQuery(this).val().trim() == '') {
                    event.preventDefault();
                    jQuery(this).next().css({"color": "red", 'display':'block'});
                } else if (! urlonly(jQuery(this).val().trim())) {
                    event.preventDefault();
                    jQuery(this).next().css({"color": "red", 'display':'block'});
                } else {
                    console.log(jQuery(this).val().trim());
                    jQuery(this).next().css({'display':'none'});
                }
            });

            jQuery(".proTitle").each(function() {
                if (jQuery(this).val().trim() == '') {
                    event.preventDefault();
                    jQuery(this).next().css({"color": "red", 'display':'block'});
                } else {
                    console.log(jQuery(this).val().trim());
                    jQuery(this).next().css({'display':'none'});
                }
            });

        } else if (option == 3) {
            jQuery(".mis_category_select").each(function() {
                if (jQuery(this).val() == 0) {
                    event.preventDefault();
                    jQuery(this).next().css({"color": "red", 'display':'block'});
                } else {
                    jQuery(this).next().css({'display':'none'});
                }
            });

            jQuery('.categoryImgFile').each(function(){
                if (jQuery(this).val().trim() == '') {
                    event.preventDefault();
                    jQuery(this).next().text("Please upload image.");
                    jQuery(this).next().css({"color": "red", 'display':'block'});
                } else if (jQuery(this)[0].files[0].size > 2024000) {
                    event.preventDefault();
                    jQuery(this).next().text("Image size should be lesser than 2 MB.");
                    jQuery(this).next().css({"color": "red", 'display':'block'});
                } else {
                    jQuery(this).next().css({"color": "red", 'display':'none'});
                }
            });

            jQuery(".catUrl").each(function() {
                if (jQuery(this).val().trim() == '') {
                    event.preventDefault();
                    jQuery(this).next().css({"color": "red", 'display':'block'});
                } else if (! urlonly(jQuery(this).val().trim())) {
                    event.preventDefault();
                    jQuery(this).next().css({"color": "red", 'display':'block'});
                } else {
                    console.log(jQuery(this).val().trim());
                    jQuery(this).next().css({'display':'none'});
                }
            });

            jQuery(".catTitle").each(function() {
                if (jQuery(this).val().trim() == '') {
                    event.preventDefault();
                    jQuery(this).next().css({"color": "red", 'display':'block'});
                } else {
                    console.log(jQuery(this).val().trim());
                    jQuery(this).next().css({'display':'none'});
                }
            });

        } else if (option == 4) {
            jQuery(".htmlUrl").each(function() {
                
                if (jQuery(this).val().trim() == '') {
                    event.preventDefault();
                    jQuery(this).next().css({"color": "red", 'display':'block'});
                } else if (! urlonly(jQuery(this).val().trim())) {
                    event.preventDefault();
                    jQuery(this).next().css({"color": "red", 'display':'block'});
                } else {
                    console.log(jQuery(this).val().trim());
                    jQuery(this).next().css({'display':'none'});
                }
            });

            jQuery(".htmltitle").each(function() {
                if (jQuery(this).val().trim() == '') {
                    event.preventDefault();
                    jQuery(this).next().css({"color": "red", 'display':'block'});
                } else {
                    console.log(jQuery(this).val().trim());
                    jQuery(this).next().css({'display':'none'});
                }
            });

            jQuery("#html_editor").each(function() {
                 console.log('html_editor '+jQuery(this).text().length); 

                if (jQuery(this).text().length > 0) {
                    // event.preventDefault();
                    // jQuery('#htmltext').css({"display": "block"});
                } else {
                    // jQuery('#htmltext').css({"display": "block"});
                }
            });

            jQuery("#htmlStoreDrop").each(function() {
                 console.log('htmlStoreDrop '+jQuery(this).val()); 
                if (jQuery(this).val() == '0' || jQuery(this).val() == null) {
                    event.preventDefault();
                    jQuery(this).next().css({"color": "red", 'display':'block'});
                } else {
                    console.log(jQuery(this).val());
                    jQuery(this).next().css({'display':'none'});
                }
            });
        }
    });

    jQuery(document).on('change', '.imgFile', function(){
        // alert(jQuery(this)[0].files[0].size);
        if (jQuery(this)[0].files[0].size > 2024000) {
            event.preventDefault();
            jQuery(this).next().css({"color": "red", 'display':'block'});
        } else {
            jQuery(this).next().css({'display':'none'});
        }

    });

    jQuery(document).on('change', '.Url', function(){
        // alert(jQuery(this)[0].files[0].size);
        if (jQuery(this).val().trim() == '') {
            event.preventDefault();
            jQuery(this).next().css({"color": "red", 'display':'block'});
        } else if (! urlonly(jQuery(this).val().trim())) {
            event.preventDefault();
            jQuery(this).next().css({"color": "red", 'display':'block'});
        }
        else {
            console.log(jQuery(this).val().trim());
            jQuery(this).next().css({'display':'none'});
        }

    });

    jQuery(document).on('change', '#html_editor_tbl', function(){
        console.log('Change');
    })
     //your js code here  
 });

function goBack()
{
   window.location.href= "<?php echo $this->getUrl('advertisement/adminads/index');?>";
}


</script>

<script type="text/javascript">
                        require([
                                    'jquery',
                                    'mage/adminhtml/wysiwyg/tiny_mce/setup'
                                ], function(jQuery){
                             
                                var config = {}, 
                                    editor;
                             
                                jQuery.extend(config, {
                                    settings: {
                                        theme_advanced_buttons1 : 'bold,italic,|,justifyleft,justifycenter,justifyright,|,' +
                                                                    'fontselect,fontsizeselect,|,forecolor,backcolor,|,link,unlink,image,|,bullist,numlist,|,code',
                                        theme_advanced_buttons2: null,
                                        theme_advanced_buttons3: null,
                                        theme_advanced_buttons4: null
                                    }
                                });
                                editor = new tinyMceWysiwygSetup(
                                    'html_editor',
                                    config
                                );
                                editor.turnOn();
                                jQuery('#html_editor')
                                    .addClass('wysiwyg-editor')
                                    .data(
                                        'wysiwygEditor',
                                        editor
                                    );
                            });
                    </script>