<?php
/**
 * @category   Webkul
 * @package    Webkul_MpAmazonConnector
 * @author     Webkul Software Private Limited
 * @copyright  Copyright (c)  Webkul Software Private Limited (https://webkul.com)
 * @license    https://store.webkul.com/license.html
 */ 

// @codingStandardsIgnoreFile

$tooltipHelper = $this->helper('Mangoit\MisTooltip\Helper\Data');
$imgHelper = $this->helper('Webkul\Marketplace\Helper\Data');
$section_id = 'amazon';
$amazon_manage_account_tooltip_id = 'amazon_sync_products';
$store_id = $tooltipHelper->getStoreId();
$manageAccountTooltip = $tooltipHelper->getToolTipData($store_id, $section_id, $amazon_manage_account_tooltip_id);



$helper = $this->helper('Webkul\Marketplace\Helper\Data');
$paramData = $this->getRequest()->getParams();
$filter = '';$statusClass = '';$tempTableStatus = null;$exportedProStatus = null;

if (isset($paramData['s'])) {
    $filter = $paramData['s'] != '' ? $paramData['s'] : '';
}

$productsColl = $block->getMappedProducts(); 
$reportStatus = $block->getReportStatus();
$tempTableStatus = $block->getTempCount() ? '' :'disabled=disabled';
if($reportStatus) {
    $note = __('Report id already generated till %1, Regenerate report id for latest inventory.',date('M d, Y', strtotime($reportStatus)));
    $class = 'wk-mu-success';
} else {
    $note = __('Please generate the report id first.');
    $class = 'message-error';
    $statusClass = "disabled=disabled";
} 
?>  

<div class="wk-mp-design amazon-sync-products">
    <fieldset class="fieldset info wk-mp-fieldset">
        <legend class="legend">
            <span><?php /* @escapeNotVerified */ echo __('Amazon Magento Sync Products') ?></span>
        </legend>
        <span>
            <?php if(count($manageAccountTooltip) > 0): ?>
                    <?php echo ( (count($manageAccountTooltip) > 0) ? $manageAccountTooltip[0]['tooltip_text'] : '');?>
            <?php endif; ?>
        </span>
        <div class="grid">
            <div class="hor-scroll">
                    <div class="wk-msg-box wk-info <?php echo $class ?>"><?php echo $note ?></div>
                    <table cellspacing="0" class="border wk-mp-list-table">
                        <thead>
                            <tr id="wk-mp-tr-heading">
                                <th><span><?php /* @escapeNotVerified */ echo __('Product Name') ?></span></th>
                                <th><span><?php /* @escapeNotVerified */ echo __('Action')?></span></th>
                            </tr>
                        </thead>
                        <tbody class="wk-mp-body">
                            <tr>
                                <td>
                                    <form action="<?php /* @escapeNotVerified */ echo $block->getUrl('mpamazonconnect/product/index/', ['_secure' => $this->getRequest()->isSecure()])?>" method="get" id="form-productlist-filter"  
                                        name="formProductlistFilter" data-mage-init='{"validation":{}}'>
                                        <input type="text" class="input-text" name="s" placeholder='<?php /* @escapeNotVerified */ echo __('Search by product name') ?>' value="<?php /* @escapeNotVerified */ echo $filter?>"/>
                                        <button class="button" title="Save" type="submit">
                                            <span><span><span><?php /* @escapeNotVerified */ echo __('Search') ?></span></span></span>
                                        </button>
                                    </form>
                                </td>
                                <td>
                                    <button class="button" id="amazon-generate-report"  title="<?php echo __('Generate product Report') ?>" type="button">
                                        <span><span><span>
                                            <?php echo __('Generate product Report') ?>
                                        </span></span></span>
                                    </button>
                                    <button class="button" id="amazon-pro-import"  title="<?php echo __('Import Products From Amazon') ?>" type="button" <?php echo $statusClass ?>>
                                        <span><span><span>
                                            <?php echo __('Import Products') ?>
                                        </span></span></span>
                                    </button>
                                    <button class="button" id="run-profiler" title="<?php echo __('Create Imported Product') ?>" type="button" <?php echo $tempTableStatus ?>>
                                        <span><span><span>
                                            <?php echo __('Create Imported Product') ?>
                                        </span></span></span>
                                    </button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                <!---->
                <?php if ($productsColl && $productsColl->getSize()): ?>
                    <form action="<?php echo $block->getUrl('mpamazonconnect/product/massdelete', ['_secure' => $this->getRequest()->isSecure()]) ?>" method="post" id="form-productlist-massdisable" name="formProductlistMassDisable" data-mage-init='{"validation":{}}'>
                        <?php echo $block->getBlockHtml('formkey')?>
                        <button class="button" title="<?php /* @escapeNotVerified */ echo __('Delete') ?>" type="submit" id="mass-delete-butn">
                            <span>
                                <span><?php /* @escapeNotVerified */ echo __('Delete') ?></span>
                            </span>
                        </button>
                        <div class="mis_amazon_listing">
                            <table cellspacing="0" class="border wk-mp-list-table wk-mp-list-container-table">
                            <thead>
                                <tr class="wk-content">
                                    <th class="wk-check-first-td">
                                        <span>
                                            <input type="checkbox" name="mpselecctall" value="all" id="mpsyncproselecctall"/>
                                        </span>
                                    </th>
                                    <th class="wk-first-td name">
                                        <span class="label">
                                            <?php /* @escapeNotVerified */ echo __('Product')?>
                                        </span>
                                    </th>
                                    <th class="wk-first-td">
                                        <span class="label">
                                            <?php /* @escapeNotVerified */ echo __('Amazon Product Id')?>
                                        </span>
                                    </th>
                                    <th class="wk-first-td">
                                        <span class="label name">
                                            <?php /* @escapeNotVerified */ echo __('Product Type')?>
                                        </span>
                                    </th>
                                    <th class="wk-first-error">
                                        <span class="label">
                                            <?php /* @escapeNotVerified */ echo __('Error Message')?>
                                        </span>
                                    </th>
                                    <th class="wk-first-error">
                                        <span class="label">
                                            <?php /* @escapeNotVerified */ echo __('Status')?>
                                        </span>
                                    </th>
                                    <th class="wk-first-td">
                                        <span class="label name">
                                            <?php /* @escapeNotVerified */ echo __('Action')?>
                                        </span>
                                    </th>           
                                </tr>
                            </thead>
                            <tbody>
                                <?php 
                                $i = 0;
                                foreach($productsColl as $amzProDetail){
                                    $i++;
                                    $products = $block->getProductDetail($amzProDetail->getMagentoProId());
                                    $imageUrl = $block->getProImgUrl($products);
                                    ?>
                                    <tr class="wk-row-view <?php /* @escapeNotVerified */ echo $i == $productsColl->getSize()? 'wk-last_tr':''?>">
                                        <td class="wk-check-first-td">
                                            <span>
                                                <input type="checkbox" name="amz_mass_del[]" class="mpcheckbox" value="<?php /* @escapeNotVerified */ echo $amzProDetail->getEntityId(); ?>"/>
                                            </span>
                                        </td>
                                        <td class="wk-first_td">
                                            <input type="hidden" class="hidden-id" value="<?php /* @escapeNotVerified */ echo $products->getEntityId(); ?>" />
                                            <div class="label name" title="<?php /* @escapeNotVerified */ echo $products->getName(); ?>">
                                                <div class="wk-pro-divide1">
                                                    <img src="<?php /* @escapeNotVerified */ echo $imageUrl?>" class="image" />
                                                </div>
                                                <div class="wk-pro-divide2">
                                                    <div style="width:100%;">
                                                        <?php if($products->getStatus()==1 && $products->getVisibility()!=1) { ?>
                                                            <a href="<?php echo $products->getProductUrl()?>" target="blank">
                                                        <?php }?>
                                                            <?php echo $products->getName();?>
                                                        <?php if($products->getStatus()==1 && $products->getVisibility()!=1) { ?>
                                                            </a>
                                                        <?php }?>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                        <td class ="wk-first_td"><?php echo $amzProDetail->getAmazonProId()?></td>
                                        <td class ="wk-first_td"><?php echo $amzProDetail->getProductType()?></td>
                                        <td class ="wk-first_td">
                                        <?php if($block->checkError($amzProDetail->getErrorStatus())) :
                                                echo "N/A";
                                         else : ?>
                                            <button class="button" title="<?php /* @escapeNotVerified */ echo __('Check Error') ?>" type="button" id="error-check-butn" data-error = "<?php echo $amzProDetail->getErrorStatus()?>">
                                                <span>
                                                    <span><?php /* @escapeNotVerified */ echo __('Check Error') ?></span>
                                                </span>
                                            </button>
                                        <?php endif; ?>
                                        </td>
                                        <td class ="wk-first_td"><?php echo __($amzProDetail->getProStatusAtAmz())?></td>
                                        <td>
                                            <img src="<?php echo $block->getViewFileUrl('Webkul_Marketplace::images/icon-edit.png'); ?>" data-url="<?php echo $block->getUrl('marketplace/product/edit', ['id'=>$products->getId(), '_secure' => $this->getRequest()->isSecure()])?>" alt="<?php echo __('Edit')?>" title="<?php echo __('Edit')?>" class="mp-edit"/>
                                            <img data-url="<?php echo $block->getDeleteProMapUrl($amzProDetail->getEntityId())?>" class="mp-delete" title="<?php echo __('Delete Map') ?>" alt="<?php echo __('Delete Map') ?>" src="<?php echo $block->getViewFileUrl('Webkul_Marketplace::images/icon-trash.png'); ?>" />
                                        </td>               
                                    </tr>
                                    <?php
                                }?>
                            </tbody>
                        </table>
                        </div>
                    </form>             
                <?php else: ?>
                    <div class="wk-emptymsg">
                        <?php /* @escapeNotVerified */ echo __('No Product Available') ?>
                    </div>
                <?php endif ?>  
                <!---->     
            </div>
        </div>
        <?php if ($block->getPagerHtml()): ?>
            <div class="order-products-toolbar toolbar bottom"><?php /* @escapeNotVerified */ echo $block->getPagerHtml(); ?></div>
        <?php endif ?>  
    </fieldset> 
    <div class="buttons-set">
        <p class="back-link">
            <a href="javascript:;" onclick="javascript: window.history.back();" class="left">&laquo; <?php /* @escapeNotVerified */ echo __('Back') ?></a>
        </p>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "amzsynclist": {
                "importUrl":"<?php echo $block->getImportUrl()?>",
                "profilerUrl":"<?php echo $block->getProfilerUrl()?>",
                "reportUrl":"<?php echo $block->getReportUrl()?>"
            }
        }
    }
</script>