<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Sales\Block\Adminhtml\Order\View\Tab\Info */ ?>
<?php $_order = $block->getOrder() ?>

<div id="order-messages">
    <?= $block->getChildHtml('order_messages') ?>
</div>

<?= $block->getChildHtml('order_info') ?>
<?php $working_days = __(' working days');?>
<input type="hidden" name="order_id" value="<?= /* @escapeNotVerified */ $_order->getId() ?>"/>
<section class="admin__page-section order-view-billing-shipping">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @escapeNotVerified */ __('Payment &amp; Shipping Method') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-payment-method<?php if ($_order->getIsVirtual()): ?> order-payment-method-virtual<?php endif; ?>">
            <?php /* Payment Method */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?= /* @escapeNotVerified */ __('Payment Information') ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <div class="order-payment-method-title"><?= $block->getPaymentHtml() ?></div>
                <div class="order-payment-currency"><?= /* @escapeNotVerified */ __('The order was placed using %1.', $_order->getOrderCurrencyCode()) ?></div>
                <div class="order-payment-additional">
                    <?= $block->getChildHtml('order_payment_additional') ?>
                    <?= $block->getChildHtml('payment_additional_info') ?>
                </div>
            </div>
        </div>
        <?= $block->getChildHtml('order_shipping_view') ?>
    </div>
</section>
<?php if ($_order->getShippingMethod() == 'warehouse_warehouse'): ?> 
    <section class="admin__page-section order-view-billing-shipping">
        <div class="admin__page-section-title">
            <span class="title"><?= /* @escapeNotVerified */ __('Vendor\'s Products Delivery Days') ?></span>
        </div>
        <div class="admin__page-section-content">
            <div class="admin__page-section-item order-payment-method<?php if ($_order->getIsVirtual()): ?> order-payment-method-virtual<?php endif; ?>">
                <?php if ($_order->getVendorDeliveryDays() && (!empty($_order->getVendorDeliveryDays()))): ?>
                    <?php $vndrprodctDelDays = unserialize($_order->getVendorDeliveryDays()); ?>
                    <div class="box" >
                        <div class="box-content" >
                            <?php if (is_array($vndrprodctDelDays)): ?>
                                <ul class="vendor_product_delivery_ul" style="list-style: none;">
                                    <li class="vendor_product_delivery">
                                        <div class="mis_delivery_days">
                                            <table class="table-checkout-vendor-delivery-days" style="width: 100%">
                                                <thead>
                                                    <tr class="row">
                                                        <th class="col col-method" colspan="5"><?php echo __('Vendors') ?></th>
                                                        <th class="col col-price" colspan="5"><?php echo __('Delivery days') ?> </th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <?php foreach ($vndrprodctDelDays as $allKey => $allValue): ?>
                                                            <tr class="row">
                                                                <td class="col col-method" colspan="5">
                                                                    <span class="shop-title"><?php echo $allValue['shop_title']; ?></span>
                                                                </td>
                                                                <td class="col col-price" colspan="5">
                    <span class="delivery-days">
                    <?php echo $allValue['final_days'].$working_days; ?></span>
                                                                </td>
                                                            </tr>
                                                        <?php //foreach ($allValue as $key => $value): ?>
                                                        <?php //endforeach; ?>
                                                    <?php endforeach; ?>
                                                </tbody>
                                            </table>
                                        </div>
                                    </li>
                                </ul>
                            <?php else:?>
                                <span><?php echo __('No information'); ?></span>
                            <?php endif;?>
                        </div>
                    </div>
                <?php endif;?>
            </div>
        </div>
    </section>
<?php endif; ?>

<?= $block->getChildHtml('order_additional_info') ?>

<?= $block->getGiftOptionsHtml() ?>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @escapeNotVerified */ __('Items Ordered') ?></span>
    </div>
    <?= $block->getItemsHtml() ?>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @escapeNotVerified */ __('Order Total') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-comments-history">
            <div class="admin__page-section-item-title">
                <span class="title"><?= /* @escapeNotVerified */ __('Notes for this Order') ?></span>
            </div>
            <?= $block->getChildHtml('order_history') ?>
                
        </div>
        <div class="admin__page-section-item-title">
             <?= $block->getChildHtml('comment_history') ?>
        </div>
        <div class="admin__page-section-item order-totals">
            <div class="admin__page-section-item-title">
                <span class="title"><?= /* @escapeNotVerified */ __('Order Totals') ?></span>
            </div>
            <?= $block->getChildHtml('order_totals') ?>
        </div>
    </div>
</section>

<?= $block->getChildHtml('popup_window') ?>

<script>
require([
    "prototype",
    "Magento_Sales/order/giftoptions_tooltip"
], function(){

//<![CDATA[
    /**
     * Retrieve gift options tooltip content
     */
    function getGiftOptionsTooltipContent(itemId) {
        var contentLines = [];
        var headerLine = null;
        var contentLine = null;

        $$('#gift_options_data_' + itemId + ' .gift-options-tooltip-content').each(function (element) {
            if (element.down(0)) {
                headerLine = element.down(0).innerHTML;
                contentLine = element.down(0).next().innerHTML;
                if (contentLine.length > 30) {
                    contentLine = contentLine.slice(0,30) + '...';
                }
                contentLines.push(headerLine + ' ' + contentLine);
            }
        });
        return contentLines.join('<br/>');
    }
    giftOptionsTooltip.setTooltipContentLoaderFunction(getGiftOptionsTooltipContent);
    window.getGiftOptionsTooltipContent = getGiftOptionsTooltipContent;
//]]>

});
</script>
