<?php
/**
 * @category   Webkul
 * @package    Webkul_MpPushNotification
 * @author     Webkul Software Private Limited
 * @copyright  Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license    https://store.webkul.com/license.html
 */
/** @var $block \Webkul\Marketplace\Block\Product\Productlist */

$helper = $this->helper('Webkul\Marketplace\Helper\Data');
$paramData = $this->getRequest()->getParams();
$usersCollection = $block->getCollection();
$templateCollection = $block->getSellerTemplatesList();
?>    
<div class="wk-mp-design">
    <fieldset class="fieldset info wk-mp-fieldset">
        <legend class="legend">
            <span><?php /* @noEscape */ echo __('Registered Users For Push Notification') ?></span>
        </legend>
        <div class="grid">
            <div class="hor-scroll">
                <form action="<?php /* @noEscape */ echo $block->getUrl('mppushnotification/users/index', ['_secure' => $this->getRequest()->isSecure()])?>" method="get" id="form-userslist-filter"  name="formUserslistFilter" data-mage-init='{"validation":{}}'>
                    <table cellspacing="0" class="border wk-mp-list-table">
                        <thead>
                            <tr id="wk-mp-tr-heading">
                                <th><span><?php /* @noEscape */ echo __('Subscribed From') ?></span></th>
                                <th><span><?php /* @noEscape */ echo __('Subscribed Date') ?></span></th>
                                <th><span>&nbsp;</span></th>
                            </tr>
                        </thead>
                        <tbody class="wk-mp-body">
                            <tr>
                                <td>
                                    <span class="wk-mp-td-span">
                                    <input name="browser" id="user-browser" class="input-text" value="<?php /* @noEscape */ if (isset($paramData['browser'])) { echo $paramData['browser']; } ?>" />
                                </span>
                                </td>
                                <td>
                                    <span class="wk-mp-td-span">
                                        <?php /* @noEscape */ echo __('From: ') ?>
                                        <input name="from_date" id="users-from-date" class="input-text" value="<?php /* @noEscape */ if (isset($paramData['browser'])) { echo $paramData['from_date']; } ?>" />
                                    </span>                                
                                    <span class="wk-mp-td-span">
                                        <?php echo __('To: ') ?>
                                        <input name="to_date" id="users-to-date" class="input-text" value="<?php /* @noEscape */ if (isset($paramData['browser'])) { echo $paramData['to_date']; } ?>" />
                                    </span>
                                </td>
                                <td>
                                    <button class="button" title="Save" type="submit">
                                        <span><span><span><?php /* @noEscape */ echo __('Submit') ?></span></span></span>
                                    </button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </form>
                <?php if ($usersCollection && count($usersCollection)) : ?>
                    <form action="<?php /* @noEscape */ echo $block->getUrl('mppushnotification/users/massdelete', ['_secure' => $this->getRequest()->isSecure()]) ?>" method="post" id="form-userslist-massdelete" name="formUserslistMassdelete" data-mage-init='{"validation":{}}'>
                        <?php /* @noEscape */ echo $block->getBlockHtml('formkey')?>
                        <?php if (count($templateCollection)) { ?>
                            <div class="wk-template-wrapper">
                                <select name='template' class="template">
                                    <option value=""><?php /* @noEscape */ echo __('-- select template --'); ?></option>
                                    <?php foreach ($templateCollection as $key => $template) { ?>
                                        <option value="<?php /* @noEscape */ echo $template->getId(); ?>"><?php /* @noEscape */ echo $template->getTitle(); ?></option>
                                        <?php
                                    } ?>
                                    <option></option>
                                </select>
                                <button class="wk-button" title="<?php /* @noEscape */ echo __('Send Notification') ?>" type="submit"  id="send-notification">
                                    <span><span><?php /* @noEscape */ echo __('Send Notification') ?></span></span>
                                </button>
                            </div>
                        <?php } ?>

                        <table cellspacing="0" class="border wk-mp-list-table wk-mp-list-container-table">
                            <thead>
                                <tr class="wk-content">
                                    <th class="wk-check-first-td">
                                        <span>
                                            <input type="checkbox" name="mpselecctall" value="all" id="mpselecctall"/>
                                        </span>
                                    </th>
                                    <th class="wk-first-td">
                                        <span class="label name">
                                            <?php /* @noEscape */ echo __('Subscribed From')?>
                                        </span>
                                    </th>
                                    <th>
                                        <span class="label pro-status">
                                            <?php /* @noEscape */ echo __('Subscriber Name')?>
                                        </span>
                                    </th>
                                    <th class="wk-list-th-display">
                                        <span class="label">
                                            <?php /* @noEscape */ echo __('Subscribed At')?>
                                        </span>
                                    </th>                        
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 0;
                                foreach ($usersCollection as $token) {
                                    $i++;
                                    ?>
                                    <tr class="wk-row-view <?php echo /* @noEscape */ $class = ($i == count($usersCollection))? 'wk-last_tr':''?>">
                                        <td class="wk-check-first-td">
                                            <span>
                                                <input type="checkbox" name="user_mass_delete[]" class="mpcheckbox" value="<?php   /* @noEscape */ echo $token->getId(); ?>"/>
                                            </span>
                                        </td>
                                        <td>        
                                            <span class="label">
                                                <?php /* @noEscape */ echo $token->getBrowser()?>
                                            </span>
                                        </td>
                                        <td>        
                                            <span class="label">
                                                <?php /* @noEscape */ echo $token->getName(); ?>
                                            </span>
                                        </td>
                                        <td>        
                                            <span class="label">
                                                <?php /* @noEscape */ echo $token->getCreatedAt()?>
                                            </span>
                                        </td>                        
                                    </tr>
                                    <?php
                                }?>
                            </tbody>
                        </table>
                    </form>                        
                <?php else : ?>
                    <div class="wk-emptymsg">
                        <?php /* @noEscape */ echo __('No Registered User(s) Available') ?>
                    </div>
                <?php endif ?>                    
            </div>
        </div>
        <?php if ($block->getPagerHtml()) : ?>
            <div class="pushnotification-userslist-toolbar toolbar bottom"><?php /* @noEscape */ echo $block->getPagerHtml(); ?></div>
        <?php endif ?>
        <h4>Subscribed <?php echo "( ".count($usersCollection)." )";  ?></h4>
    </fieldset>    
    <div class="buttons-set">
        <p class="back-link">
            <a href="javascript:;" onclick="javascript: window.history.back();" class="left">&laquo; <?php /* @noEscape */ echo __('Back') ?></a>
        </p>
    </div>
</div>
<?php

    $releventData = [
        'sendNotificationUrl' => $block->getUrl('mppushnotification/users/sendnotification', ['_secure' => $this->getRequest()->isSecure()])
    ];

    $serializedData = $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($releventData);

    ?>
<script type="text/x-magento-init">
    {
        "*": {
            "usersList": <?php /* @noEscape */ echo $serializedData; ?>
        }
    }
</script>