<style type="text/css">
.contact-index-index .contact-info .contacts-title  {
  color: #000 !important
}

#contact-form .fieldset .fields.col-md-6 {
   width: 100%;
   max-width: 100%;
   flex: 0 0 100%;
   padding: 0;
}
</style>
<?php
    $contacts_config = $this->helper('Smartwave\Porto\Helper\Data')->getConfig('porto_settings/contacts');
    $_infoblock = $contacts_config['infoblock'];
    $_customblock = $contacts_config['customblock'];
    
    if($_customblock) {
        $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
        if($block) {
            $block->setBlockId($_customblock);
        }
        if($block){
            echo '<div class="row"><div class="col-md-12">'.$block->toHtml().'</div></div>';
        }
    }
?>
<div class="row">
    <div class="col-md-8"><?php echo $this->getChildHtml('contactForm')?></div>
    <div class="col-md-4 contact-info">
        <div class="contacts-title"><?php echo __('Contact') ?> <b><?php echo __('Details') ?></b></div>
        <?php echo $_infoblock; ?>
    </div>
</div>