<?php  
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) 2010-2018 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

// @codingStandardsIgnoreFile

/** @var $block \Webkul\Marketplace\Block\Transaction\View */

$helper = $this->helper('Webkul\Marketplace\Helper\Data');
$collection = $block->sellertransactionDetails();
$items = $block->sellertransactionOrderDetails($this->getRequest()->getParam('id'));
$sellerPriceArray = $this->getHelper()->getSellerPriceArray($items->getData());

$orderslist = $block->sellertransactionOrderDetails($this->getRequest()->getParam('id'));
?>
<div class="wk-mp-design">
	<fieldset class="fieldset info wk-mp-fieldset">
		<legend class="legend"><span><?php echo __('Transaction Id %1 - %2', $collection->getTransactionId(), __('Paid')) ?></span></legend>
		<div class="wk-mp-order-info-box">
		    <div>
		        <div class="box">
		            <div class="box-title">
		                <h2><?php echo __('Transaction Information') ?></h2>
		            </div>
		            <div class="box-content">
		                <div class="wk_row">
							<span class="label"><?php echo __('Date')?> : </span>
							<span class="value"><?php echo $block->formatDate($collection->getCreatedAt(), \IntlDateFormatter::LONG); ?></span>
						</div>
						<!-- <div class="wk_row">
							<span class="label"><?php //echo __('Amount')?> : </span>
							<span class="value">
								<?php //echo $block->getFormatedPrice($collection->getTransactionAmount()); ?>
							</span>
						</div> -->
						<div class="wk_row">
							<span class="label"><?php echo __('Type')?> : </span>
							<span class="value"><?php echo $collection->getType(); ?></span>
						</div>
						<div class="wk_row">
							<span class="label"><?php echo __('Method')?> : </span>
							<span class="value"><?php echo $collection->getMethod(); ?></span>
						</div>
						<div class="wk_row">
							<?php
							if($collection->getCustomNote()){
								$customnote = $collection->getCustomNote();
							}else{
								$customnote = __('None');
							}
							?>
							<span class="label"><?php echo __('Comment Message')?> : </span>
							<span class="value"><?php echo $customnote; ?></span>
						</div>
		            </div>
		        </div>
		    </div>
		</div>
		<div class="order-details-items ordered">
			<div class="table-wrapper order-items">
			    <h2 class="table-caption"><?php echo __('Transaction Order Information') ?></h2>
			    <table class="data table table-order-items" summary="<?php echo __('Order List Per Product') ?>">
				    <thead>
				    	<tr>
				            <th class="col price"><?php echo __('Order #') ?></th>
				            <th class="col price"><?php echo __('Product Name') ?></th>
				            <th class="col price"><?php echo __('Price') ?></th>
				            <th class="col price"><?php echo __('Qty') ?></th>
				            <th class="col price"><?php echo __('Total Price') ?></th>
				            <!-- <th class="col price"><?php echo __('Total Tax') ?></th> -->
				            <th class="col price"><?php echo __('Shipping') ?></th>
				            <th class="col price"><?php echo __('Commission') ?></th>
				            <th class="col price"><?php echo __('Currency Exchange Fee') ?></th>
				            <th class="col price"><?php echo __('Payment Fee Deducted') ?></th>
				            <th class="col price"><?php echo __('Subtotal') ?></th>
				        </tr>
				    </thead>
				    <tbody>
					    <?php $i = 0; ?>
					    <?php $_count = count($orderslist); ?>
					    <?php
				    	$subtotal = 0;
				    	$totalAmountArray= [];
                    	$totalFeeArray= [];
						foreach($orderslist as $item){
							$i++;
							$mageorderid = $item->getOrderId();
							$sellerId = $item->getSellerId();
							$item_status="";
							// $subtotal=$subtotal+$item->getActualSellerAmount();
							$totalShipping = 0;
							// if ($item->getIsShipping()) {
							// 	$totalShipping = $block->sellerOrderShippingAmount(
							// 		$sellerId,
							// 		$mageorderid
							// 	);
							// }

							$totalShipping = $sellerPriceArray[$item->getMagerealorderId()];
							$sellerPriceArray[$item->getMagerealorderId()] = 0;

							$totalAmountArray[] = number_format($item->getTotalAmount(), 2, '.', '');
	                        $totalAmountArray[] = $totalShipping;
	                        $totalFeeArray[] = number_format($item->getTotalCommission(), 2, '.', '');
	                        $totalFeeArray[] = number_format($item->getMitsPaymentFeeAmount(), 2, '.', '');
	                        $totalFeeArray[] = number_format($item->getMitsExchangeRateAmount(), 2, '.', '');

	                        $itemTotalAmount = $item->getTotalAmount() + $totalShipping;
	                        $totalItemFee = ($item->getTotalCommission() +
			                        $item->getMitsPaymentFeeAmount() +
			                        $item->getMitsExchangeRateAmount());

	                        $itemSubtotal = $itemTotalAmount - $totalItemFee;
							?>
							<tr class="border">
				            	<td class="col price" data-th="<?php echo __('Order #') ?>"><?php echo $item->getMagerealorderId();?></td>
								<td class="col price" data-th="<?php echo __('Product Name') ?>"><?php echo $item['magepro_name'];?></td>
								<td class="col price" data-th="<?php echo __('Price') ?>">
									<?php echo $block->getFormatedPrice($item->getMageproPrice());?>
								</td>
								<td class="col price" data-th="<?php echo __('Qty') ?>"><?php echo $item->getMagequantity();?></td>
								<td class="col price" data-th="<?php echo __('Total Price') ?>">
									<?php echo $block->getFormatedPrice($item->getTotalAmount());?>
								</td>
								<!-- <td class="col price" data-th="<?php echo __('Tax') ?>">
									<?php echo $block->getFormatedPrice($item->getTotalTax());?>
								</td> -->
								<td class="col price" data-th="<?php echo __('Shipping') ?>">
									<?php echo $block->getFormatedPrice($totalShipping);?>
								</td>
								<td class="col price" data-th="<?php echo __('Admin Commission') ?>">
									<?php echo $block->getFormatedPrice($item->getTotalCommission());?>
								</td>
								<?php
								$admintotaltax = 0;
					        	$vendortotaltax = 0;
					        	if(!$helper->getConfigTaxManage()){
					                $admintotaltax = $item->getTotalTax();
					            }else{
					            	$vendortotaltax = $item->getTotalTax();
					            }
								?>
								<td class="col price" data-th="<?php echo __('Currency Exchange Fee') ?>">
									<?php echo $block->getFormatedPrice($item->getMitsExchangeRateAmount());?>
								</td>
								<td class="col price" data-th="<?php echo __('Payment Fee Deducted') ?>">
									<?php echo $block->getFormatedPrice($item->getMitsPaymentFeeAmount());?>
								</td>
								<td class="col price" data-th="<?php echo __('Subtotal') ?>">
									<?php //echo $block->getFormatedPrice($item->getActualSellerAmount()+$vendortotaltax+$totalShipping);?>
									<?php echo $block->getFormatedPrice($itemSubtotal);?>
								</td>
							</tr>
						<?php 
						} ?>								
					</tbody>
				</table>
				<?php
					$netTotal = (array_sum($totalAmountArray) - array_sum($totalFeeArray));
                    $totalInclVat = number_format(((array_sum($totalAmountArray)-array_sum($totalFeeArray))*19)/100, 2, '.', '');
                    $totalToBePaid = number_format($netTotal + $totalInclVat, 2, '.', '');
				?>
			</div>
			<table>
	            <tbody>
	                <tr>
	                    <td width="30%">&nbsp;</td>
	                    <td width="70%" style="float: right;">
	                        <table>
	                            <tbody>
	                                <tr>
	                                    <td style="text-align: left;"><?php echo __('Gesamt Betrag / Total Amount') ?></td>
	                                    <td style="text-align: right;"><?php echo $block->getFormatedPrice(array_sum($totalAmountArray)) ?></td>
	                                </tr>
	                                <tr>
	                                    <td style="text-align: left;"><?php echo __('Gesamt Gebühren / Total Fees') ?></td>
	                                    <td style="text-align: right;"><?php echo $block->getFormatedPrice(array_sum($totalFeeArray)) ?></td>
	                                </tr>
	                                <tr>
	                                    <td style="text-align: left;"><?php echo __('Gesamtsumme (netto) / Total (net)') ?></td>
	                                    <td style="text-align: right;"><?php echo $block->getFormatedPrice((array_sum($totalAmountArray)-array_sum($totalFeeArray))) ?></td>
	                                </tr>
	                                <tr>
	                                    <td style="text-align: left;"><?php echo __('zzgl. 19% USt. / incl. VAT') ?></td>
	                                    <td style="text-align: right;"><?php echo $block->getFormatedPrice($totalInclVat) ?></td>
	                                </tr>
	                                <tr>
	                                    <td style="text-align: left;"><?php echo __('Gesamtsumme / Total') ?></td>
	                                    <td style="text-align: right;"><?php echo $block->getFormatedPrice($totalToBePaid) ?></td>
	                                </tr>
	                            </tbody>
	                        </table>
	                    </td>
	                </tr>
	            </tbody>
	        </table>
		</div>
	</fieldset>
</div>
<div class="buttons-set">
	<p class="back-link">
		<a href="javascript:;" onclick="javascript: window.history.back();" class="left">&laquo; <?php echo __('Back') ?></a>
	</p>
</div>