<!-- last edited 29-Jan-2019 -->
<?php
$helper = $this->helper('Webkul\Marketplace\Helper\Data');
$paramData = $this->getRequest()->getParams();
$filter = '';

if (isset($paramData['s'])) {
    $filter = $paramData['s'] != '' ? $paramData['s'] : '';
}
$productsColl = $block->getMappedProducts(); 
?>  
<div class="wk-mp-design rakuten-sync-products">
    <fieldset class="fieldset info wk-mp-fieldset">
        <legend class="legend">
            <span><?php echo __('Rakuten Magento Sync Products') ?></span>
        </legend>
        <div class="grid">
            <div class="hor-scroll">
                <table cellspacing="0" class="border wk-mp-list-table">
                    <thead>
                        <tr id="wk-mp-tr-heading">
                            <th><span><?php echo __('Product Name') ?></span></th>
                        </tr>
                    </thead>
                    <tbody class="wk-mp-body">
                        <tr>
                            <td>
                                <form action="<?php echo $block->getUrl('rakutenconnect/producttorakuten/index/', ['_secure' => $this->getRequest()->isSecure()])?>" method="get" id="form-productlist-filter"  
                                    name="formProductlistFilter" data-mage-init='{"validation":{}}'>
                                    <input type="text" class="input-text" name="s" placeholder='<?php echo __('Search by product name') ?>' value="<?php  echo $filter?>"/>
                                    <button class="button" title="Save" type="submit">
                                        <span><span><span><?php echo __('Search') ?></span></span></span>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <!---->
                <?php if ($productsColl && $productsColl->getSize()): ?>
                    <form action="<?php echo $block->getUrl('rakutenconnect/producttorakuten/exportproduct', ['_secure' => $this->getRequest()->isSecure()]) ?>" method="post" id="form-productlist-massdisable" name="formProductlistMassDisable" data-mage-init='{"validation":{}}'>
                        <?php echo $block->getBlockHtml('formkey')?>
                        <button class="button" title="<?php echo __('Export Product') ?>" type="submit" id="mass-export-butn">
                            <span>
                                <span><?php echo __('Export Product') ?></span>
                            </span>
                        </button>
                        <table cellspacing="0" class="border wk-mp-list-table wk-mp-list-container-table">
                            <thead>
                                <tr class="wk-content">
                                    <th class="wk-check-first-td">
                                        <span>
                                            <input type="checkbox" name="mpselecctall" value="all" id="mpsyncproselecctall"/>
                                        </span>
                                    </th>
                                    <th class="wk-first-td name">
                                        <span class="label">
                                            <?php echo __('Product')?>
                                        </span>
                                    </th>
                                    <th class="wk-first-td">
                                        <span class="label">
                                            <?php echo __('Product Id')?>
                                        </span>
                                    </th>
                                    <th class="wk-first-td">
                                        <span class="label name">
                                            <?php echo __('Product Type')?>
                                        </span>
                                    </th>
                                    <th class="wk-first-td">
                                        <span class="label name">
                                            <?php echo __('Action')?>
                                        </span>
                                    </th>           
                                </tr>
                            </thead>
                            <tbody>
                                <?php 
                                $i = 0;
                                foreach($productsColl as $amzProDetail){
                                    $i++;
                                    $products = $block->getProductDetail($amzProDetail->getId());
                                    $imageUrl = $block->getProImgUrl($products);
                                    ?>
                                    <tr class="wk-row-view <?php echo $i == $productsColl->getSize()? 'wk-last_tr':''?>">
                                        <td class="wk-check-first-td">
                                            <span>
                                                <input type="checkbox" name="rktn_mass_export[]" class="mpcheckbox" value="<?php echo $amzProDetail->getEntityId(); ?>"/>
                                            </span>
                                        </td>
                                        <td class="wk-first_td">
                                            <input type="hidden" class="hidden-id" value="<?php echo $products->getEntityId(); ?>" />
                                            <div class="label name" title="<?php echo $products->getName(); ?>">
                                                <div class="wk-pro-divide1">
                                                    <img src="<?php echo $imageUrl?>" class="image" />
                                                </div>
                                                <div class="wk-pro-divide2">
                                                    <div style="width:100%;">
                                                        <?php if($products->getStatus()==1 && $products->getVisibility()!=1) { ?>
                                                            <a href="<?php echo $products->getProductUrl()?>" target="blank">
                                                            <?php }?>
                                                            <?php echo $products->getName();?>
                                                            <?php if($products->getStatus()==1 && $products->getVisibility()!=1) { ?>
                                                            </a>
                                                        <?php }?>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                        <td><?php echo $products->getId()?></td>
                                        <td><?php echo ucwords($products->getTypeId()) ?></td>
                                        <td>
                                            <img src="<?php echo $block->getViewFileUrl('Webkul_Marketplace::images/icon-edit.png'); ?>" data-url="<?php echo $block->getUrl('marketplace/product/edit', ['id'=>$products->getId(), '_secure' => $this->getRequest()->isSecure()])?>" alt="<?php echo __('Edit')?>" title="<?php echo __('Edit')?>" class="mp-edit"/>
                                            <img data-url="<?php echo $block->getDeleteProMapUrl($amzProDetail->getEntityId())?>" class="mp-delete" title="<?php echo __('Delete Map') ?>" alt="<?php echo __('Delete Map') ?>" src="<?php echo $block->getViewFileUrl('Webkul_Marketplace::images/icon-trash.png'); ?>" />
                                        </td>               
                                    </tr>
                                    <?php
                                }?>
                            </tbody>
                        </table>
                    </form>             
                    <?php else: ?>
                        <div class="wk-emptymsg">
                            <?php echo __('No Product Available') ?>
                        </div>
                    <?php endif ?>  
                    <!---->     
                </div>
            </div>
            <?php if ($block->getPagerHtml()): ?>
                <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
            <?php endif ?>  
        </fieldset> 
        <br>
        <div class="buttons-set">
            <p class="back-link">
                <a href="javascript:;" onclick="javascript: window.history.back();" class="left">&laquo; <?php echo __('Back') ?></a>
            </p>
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            "*": {
            "rktnsynclist": {
            "importUrl":"<?php echo $block->getImportUrl()?>",
            "profilerUrl":"<?php echo $block->getProfilerUrl()?>",
            "reportUrl":"<?php echo $block->getReportUrl()?>"
        }
    }
}
</script>
