<!--
/**
 * @category   Package
 * @package    Package_RakutenConnector
 * @author     Author
 * @copyright  Copyright (c)  Author
 * @license    license
 */ 
-->
<?php

	$params = $this->getRequest()->getParams();
	$productList= $block->getProductIds();
	$productCount = count($productList);
?>
<fieldset class="fieldset">
	<div class="wk-mu-note wk-mu-box">
		<?php echo __('Starting Execution'); ?>...
	</div>
	<div class="wk-mu-notice wk-mu-box">
		<?php echo __("Please don't close or refresh the window while exporting product(s) to rakuten."); ?>
	</div>
	<div class="wk-mu-success wk-mu-box">
		<?php echo __('Total '); ?><?php echo $productCount; ?><?php echo __(' product(s) to export to rakuten'); ?>.
	</div>
	<?php if($productCount > 0): ?>
		<div class="wk-mu-info-bar">
			<?php __('Importing '); ?> <span class="wk-current">1</span> of <?php echo $productCount;?>
			<img id="loader-image" src="<?php echo $block->getViewFileUrl('Mangoit_RakutenConnector::images/loader.gif') ?>" />
		</div>
		<div class="wk-mu-progress-bar">
			<div class="wk-mu-progress-bar-current"></div>
		</div>
	<?php else: ?>
		<div class="wk-mu-note wk-mu-box">
			<?php echo __('No product to import.'); ?>
		</div>
		<div class="wk-mu-note wk-mu-box">
			<?php echo __('Finsihed Execution.'); ?>
		</div>
	<?php endif; ?>
</fieldset>
<?php
	$releventData = [
		'importUrl' => $this->getUrl('*/*/profiler'),
		'backUrl'	=> $this->getUrl('*/producttorakuten/index'),
		'fieldsetSelector'	=> '.fieldset',
		'progressBarSelector'	=> '.wk-mu-progress-bar-current',
		'infoBarSelector'	=> '.wk-mu-info-bar',
		'currentSelector'	=> '.wk-current',
		'amzProductCount'		=> $productCount,
		'productJson'		=> json_encode($productList)
	];

	$serializedData = $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($releventData);
?>

<script type="text/x-magento-init">
    {
        "*":{
            "syncToRakuten":<?php echo $serializedData ?>
        }
    }
</script>