<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) 2010-2018 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

// @codingStandardsIgnoreFile

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');

if ($customerSession->isLoggedIn()) {
    echo 'Customer Id: ' . $customerSession->getCustomer()->getId() . '<br/>';
    echo 'Customer Name: ' . $customerSession->getCustomer()->getName() . '<br/>';
    echo 'Customer Email: ' . $customerSession->getCustomer()->getEmail() . '<br/>';
    echo 'Customer Group Id: ' .  $customerSession->getCustomer()->getGroupId() . '<br/>';
    $customer = $objectManager->create('Magento\Customer\Model\Customer')->load($customerSession->getCustomer()->getId());
    echo "<pre>";
    print_r($customer->getData());
    die();

}

$helper = $this->helper('Webkul\Marketplace\Helper\Data');
$orderHelper = $this->helper('Webkul\Marketplace\Helper\Orders');
$myHelper = $this->helper('Mangoit\Vendorcommission\Helper\Data');
$isPartner = $helper->isSeller();
$misMrketplaceHelper = $this->helper('Mangoit\Marketplace\Helper\Data');

if($isPartner == 1){
    $order_id = $this->getRequest()->getParam('id');

    // DHL Weight 

    $dhlHelper = $this->helper('Mangoit\Dhlshipment\Helper\Data');
    $dhlFees = 0.00;
    $dhlApplied = $dhlHelper->isDhlFeesApplied($order_id);
    if ($dhlApplied['result'] == true) {
        $dhlFees = $dhlApplied['dhl_fees'];
    }
    // $product_id_array = '';
    // $productWeight = 0;
    // $weightArray = array();
    // foreach ($order->getItems() as $item) {
    //     $weightArray[$item->getProductId()] = $item->getWeight();
    // }

    // DHL Weight Ends

    $order = $block->Order->load($order_id);
    $orderStatusLabel = $order->getStatusLabel();
    if ($order->getShippingAddress()) {
        $countryId = $order->getShippingAddress()->getCountryId();
    } else {
        $countryId = $order->getBillingAddress()->getCountryId();
    }

    $euCountry = $misMrketplaceHelper->isEuCountry($countryId);
    $paymentCode = '';
    $payment_method = '';
    if($order->getPayment()){
        $paymentCode = $order->getPayment()->getMethod();
        $payment_method = $order->getPayment()->getMethodInstance()->getTitle();
    }

    $marketplace_orders = $block->getSellerOrderInfo($order_id);
    if(count($marketplace_orders)){
        $tracking=$orderHelper->getOrderinfo($order_id);
        if($tracking!="" && $paymentCode == 'mpcashondelivery'){
            $codcharges=$tracking->getCodCharges();
        }
        $is_canceled=$tracking->getIsCanceled();
        if($is_canceled){
            $orderStatusLabel='Canceled';
        }
        ?>
<!-- <style type="text/css">

@media print {
                table {
    border:solid #000 !important;
    border-width:1px 0 0 1px !important;
}
.vendor_total{
        display: none!important;
    }
table {
        border-collapse: collapse;
        
    }
th, td {
    border:solid #000 !important;
    border-width:0 1px 1px 0 !important;
}}
table {
    border-top: double;
    border-bottom: double;
    border-right: double;
}
thead, tbody, tfoot {
    border-top: solid;
    border-bottom: solid
}
th, td {
	border-right: solid;
	border-left: solid;
}
colgroup {
    border-right: solid
}
</style> -->
        <div class="wk_mp_design">
            <div class="fieldset wk_mp_fieldset" id="wk_mp_print_order">
                <div class="order-details-items ordered">
                    <div class="order-title">
                        <strong><?php echo __('Items Ordered') ?></strong>
                    </div>
                    <div class="table-wrapper order-items">
                        <table class="data table table-order-items" id="my-orders-table" summary="<?php echo __('Items Ordered') ?>">
                            <caption class="table-caption"><?php echo __('Items Ordered') ?></caption>
                            <thead>
                                <tr class="mark" scope="row"> 
                                    <th class="col name" ><?php echo __('Product Name') ?></th>
                                    <th class="col sku"><?php echo __('SKU') ?></th>
                                    <th class="col price"><?php echo __('Price') ?></th>
                                    <th class="col qty"><?php echo __('Qty') ?></th>
                                    <th class="col price"><?php echo __('Total Price') ?></th>
                                    <?php
                                    if($paymentCode == 'mpcashondelivery'){?>
                                        <th class="col price"><?php echo __('COD Charges') ?></th>
                                    <?php
                                    } ?>
                                    <th class="col price"><?php echo __('Admin Commission') ?></th>
                                    <th style="display: none ! important;" class="col price vendor_total"><?php echo __('Vendor Total') ?></th>
                                    <th class="col price"><?php echo __('Subtotal') ?></th>
                                </tr>
                            </thead>
                            <?php

                            $_items = $order->getItemsCollection();
                            $i = 0;
                            $_count = $_items->count();

                            $subtotal = 0;
                            $vendor_subtotal =0;
                            $totaltax = 0;
                            $admin_subtotal =0;
                            $shippingamount = 0;
                            $couponamount = 0;

                            $vToMgmbhCost = 0;
                            $vendorShippingCost = 0;

                            $exchange_rate = 0;
                            $mits_exchange_rate_amount = 0;

                            $payment_fee = 0;
                            $mits_payment_fee_amount = 0;

                            $codcharges_total = 0;

                            foreach ($_items as $_item){
                                if ($_item->getParentItem()) {
                                    continue;
                                }
                                $row_total = 0;
                                $available_seller_item = 0;
                                $shippingcharges = 0;
                                $couponcharges = 0;
                                $itemPrice = 0;
                                $seller_item_cost = 0;
                                $totaltax_peritem = 0;
                                $codcharges_peritem = 0;
                                $seller_item_commission = 0;
                                $orderid = $order_id;
                                $seller_orderslist = $block->getSellerOrdersList($orderid,$_item->getProductId(),$_item->getItemId());
                                foreach($seller_orderslist as $seller_item){
                                    $parentitem_falg = 0;
                                    $available_seller_item = 1;
                                    $totalamount = $seller_item->getTotalAmount();
                                    $seller_item_cost = $seller_item->getActualSellerAmount();
                                    $seller_item_commission = $seller_item->getTotalCommission();
                                    $shippingcharges = $seller_item->getShippingCharges();
                                    $couponcharges = $seller_item->getAppliedCouponAmount();
                                    $itemPrice = $seller_item->getMageproPrice();
                                    $totaltax_peritem = $seller_item->getTotalTax();

                                    //MIS Coading
                                    $vToMgmbhCost = $seller_item->getVendorToMygermanyCost();
                                    $exchange_rate = $seller_item->getMitsExchangeRateAmount();
                                    $payment_fee = $seller_item->getMitsPaymentFeeAmount();

                                    if($paymentCode=='mpcashondelivery'){
                                        $codcharges_peritem = $seller_item->getCodCharges();
                                    }
                                }
                                if($available_seller_item == 1){
                                    $i++;
                                    $seller_item_qty = $_item->getQtyOrdered();
                                    $row_total=$itemPrice*$seller_item_qty;

                                    $vendor_subtotal=$vendor_subtotal+$seller_item_cost;
                                    $subtotal=$subtotal+$row_total;
                                    $admin_subtotal = $admin_subtotal +$seller_item_commission;

                                    // vendor to mygermany shipping cost
                                    $vendorShippingCost = $vendorShippingCost + $vToMgmbhCost;
                                    $mits_exchange_rate_amount = $mits_exchange_rate_amount + $exchange_rate;
                                    $mits_payment_fee_amount = $mits_payment_fee_amount + $payment_fee;

                                    $totaltax=$totaltax+$totaltax_peritem;
                                    $codcharges_total=$codcharges_total+$codcharges_peritem;
                                    $shippingamount = $shippingamount+$shippingcharges;
                                    $couponamount = $couponamount+$couponcharges;

                                    $result = array();
                                    if ($options = $_item->getProductOptions()) {
                                        if (isset($options['options'])) {
                                            $result = array_merge($result, $options['options']);
                                        }
                                        if (isset($options['additional_options'])) {
                                            $result = array_merge($result, $options['additional_options']);
                                        }
                                        if (isset($options['attributes_info'])) {
                                            $result = array_merge($result, $options['attributes_info']);
                                        }
                                    }
                                    // for bundle product
                                    $bundleitems = array_merge(array($_item), $_item->getChildrenItems());
                                    $_count = count ($bundleitems);
                                    $_index = 0;
                                    $_prevOptionId = '';
                                    ?>
                                    <tbody>
                                        <?php
                                        if($_item->getProductType()!='bundle'){
                                        ?>
                                            <tr style="border:1px solid #ccc;" class="border" id="order-item-row-<?php echo $_item->getId() ?>">
                                                <?php
                                                if($_item->getProductType()=='downloadable'){ ?>
                                                    <td class="col name" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
                                                        <strong class="product name product-item-name"><?php echo $block->escapeHtml($_item->getName()) ?></strong>
                                                        <?php if ($_options = $block->getItemOptions()): ?>
                                                            <dl class="item-options links">
                                                                <?php foreach ($_options as $_option) : ?>
                                                                    <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
                                                                    <?php if (!$block->getPrintStatus()): ?>
                                                                                                <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                                                                                                <dd>
                                                                                                        <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                                                                                                <?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?>
                                                                                                        <?php else: ?>
                                                                                                                <?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
                                                                                                        <?php endif; ?>
                                                                                                </dd>
                                                                    <?php else: ?>
                                                                        <dd><?php echo $block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value'])) ?></dd>
                                                                    <?php endif; ?>
                                                                <?php endforeach; ?>
                                                            </dl>
                                                        <?php endif; ?>
                                                        <?php /* downloadable */?>
                                                        <?php if ($links = $block->getDownloadableLinks($_item->getId())): ?>
                                                            <dl class="item-options links">
                                                                <dt><?php /* @escapeNotVerified */ echo $block->getLinksTitle($_item->getId()) ?></dt>
                                                                <?php foreach ($links->getPurchasedItems() as $link): ?>
                                                                    <dd><?php echo $block->escapeHtml($link->getLinkTitle()); ?></dd>
                                                                <?php endforeach; ?>
                                                            </dl>
                                                        <?php endif; ?>
                                                        <?php /* EOF downloadable */?>

                                                        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                                                        <?php if ($addInfoBlock) :?>
                                                            <?php echo $addInfoBlock->setItem($_item->getOrderItem())->toHtml(); ?>
                                                        <?php endif; ?>
                                                        <?php echo $block->escapeHtml($_item->getDescription()) ?>
                                                    </td>
                                                <?php
                                                }else{ ?>
                                                    <td class="col name" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
                                                        <strong class="product name product-item-name"><?php echo $block->escapeHtml($_item->getName()) ?></strong>
                                                        <?php if($_options = $result): ?>
                                                            <dl class="item-options">
                                                            <?php foreach ($_options as $_option) : ?>
                                                                <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
                                                                <?php if (!$block->getPrintStatus()): ?>
                                                                                <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                                                                                <dd>
                                                                                        <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                                                                                <?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?>
                                                                                        <?php else: ?>
                                                                                                <?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
                                                                                        <?php endif; ?>
                                                                                </dd>
                                                                <?php else: ?>
                                                                    <dd>
                                                                        <?php echo nl2br($block->escapeHtml( (isset($_option['print_value']) ? $_option['print_value'] : $_option['value']) )) ?>
                                                                    </dd>
                                                                <?php endif; ?>
                                                            <?php endforeach; ?>
                                                            </dl>
                                                        <?php endif; ?>
                                                    </td>
                                                <?php }?>
                                                <td class="col sku" data-th="<?php echo $block->escapeHtml(__('SKU')); ?>"><?php echo $_item->getSku() ?></td>
                                                <td class="col price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
                                                    <span class="price-excluding-tax" data-label="<?php echo $block->escapeHtml(__('Excl. Tax')); ?>">
                                                        <span class="cart-price">
                                                            <?php echo $order->formatPrice($_item->getPrice()); ?>
                                                        </span>
                                                    </span>
                                                </td>
                                                <td class="col qty" data-th="<?php echo $block->escapeHtml(__('Qty')); ?>">
                                                    <ul class="items-qty">
                                                        <?php if ($_item->getQtyOrdered() > 0): ?>
                                                            <li class="item">
                                                                <span class="title"><?php echo __('Ordered'); ?></span>
                                                                <span class="content"><?php echo $_item->getQtyOrdered()*1 ?></span>
                                                            </li>
                                                        <?php endif; ?>
                                                        <?php if ($_item->getQtyInvoiced() > 0): ?>
                                                            <li class="item">
                                                                <span class="title"><?php echo __('Invoiced'); ?></span>
                                                                <span class="content"><?php echo $_item->getQtyInvoiced()*1 ?></span>
                                                            </li>
                                                        <?php endif; ?>
                                                        <?php if ($_item->getQtyShipped() > 0): ?>
                                                            <li class="item">
                                                                <span class="title"><?php echo __('Shipped'); ?></span>
                                                                <span class="content"><?php echo $_item->getQtyShipped()*1 ?></span>
                                                            </li>
                                                        <?php endif; ?>
                                                        <?php if ($_item->getQtyCanceled() > 0): ?>
                                                            <li class="item">
                                                                <span class="title"><?php echo __('Canceled'); ?></span>
                                                                <span class="content"><?php echo $_item->getQtyCanceled()*1 ?></span>
                                                            </li>
                                                        <?php endif; ?>
                                                        <?php if ($_item->getQtyRefunded() > 0): ?>
                                                            <li class="item">
                                                                <span class="title"><?php echo __('Refunded'); ?></span>
                                                                <span class="content"><?php echo $_item->getQtyRefunded()*1 ?></span>
                                                            </li>
                                                        <?php endif; ?>
                                                    </ul>
                                                </td>
                                                <td class="col price" data-th="<?php echo $block->escapeHtml(__('Total Price')); ?>"><?php echo $order->formatPrice($block->getOrderedPricebyorder($order->getBaseToGlobalRate(), $row_total));?></td>
                                                <?php
                                                if($paymentCode == 'mpcashondelivery'){?>
                                                    <td class="col price" data-th="<?php echo $block->escapeHtml(__('COD Charges')) ?>"><?php echo $order->formatPrice($block->getOrderedPricebyorder($order->getBaseToGlobalRate(), $codcharges_peritem));?></td>
                                                <?php
                                                } ?>
                                                <td class="col price" data-th="<?php echo $block->escapeHtml(__('Admin Commission')); ?>"><?php echo $order->formatPrice($block->getOrderedPricebyorder($order->getBaseToGlobalRate(), $seller_item_commission));?></td>
                                                <td style="display: none ! important;" class="col price vendor_total" data-th="<?php echo $block->escapeHtml(__('Vendor Total')); ?>"><?php echo $order->formatPrice($block->getOrderedPricebyorder($order->getBaseToGlobalRate(), $seller_item_cost));?></td> 
                                                <td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal')); ?>"><?php echo $order->formatPrice($block->getOrderedPricebyorder($order->getBaseToGlobalRate(), $row_total));?></td>
                                            </tr>
                                        <?php
                                        }else{ ?>
                                            <?php foreach ($bundleitems as $_bundleitem): ?>
                                                <?php $attributes_option = $block->getSelectionAttribute($_bundleitem); ?>
                                                <?php if ($_bundleitem->getParentItem()): ?>
                                                    <?php $attributes = $attributes_option ?>
                                                    <?php if ($_prevOptionId != $attributes['option_id']): ?>
                                                    <tr class="options-label">
                                                        <td class="col label" colspan="8" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
                                                            <?php echo $attributes['option_label'] ?>
                                                        </td>
                                                    </tr>
                                                    <?php $_prevOptionId = $attributes['option_id'] ?>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                                <tr<?php echo (++$_index==$_count)?' class="border bundle"':' class="bundle"' ?> id="order-item-row-<?php echo $_bundleitem->getId() ?>">
                                                    <?php 
                                                    if (!$_bundleitem->getParentItem()){?>
                                                        <td><h3 class="product-name"><?php echo $block->escapeHtml($_bundleitem->getName()) ?></h3></td>
                                                        <td class="col sku" data-th="<?php echo $block->escapeHtml(__('SKU')); ?>"><?php echo $_bundleitem->getSku() ?></td>
                                                        <td class="col price" data-rwd-label="<?php echo __('Price') ?>">
                                                            <span class="price-excluding-tax" data-label="<?php echo $block->escapeHtml(__('Excl. Tax')); ?>">
                                                                <?php echo $order->formatPrice($_item->getPrice());?>
                                                            </span>
                                                        </td>
                                                        <td class="col qty item_status" data-rwd-label="<?php echo __('Status') ?>">
                                                            <ul class="items-qty">
                                                                <?php if ($_item->getQtyOrdered() > 0): ?>
                                                                    <li class="item">
                                                                        <span class="title"><?php echo __('Ordered'); ?></span>
                                                                        <span class="content"><?php echo $_item->getQtyOrdered()*1 ?></span>
                                                                    </li>
                                                                <?php endif; ?>
                                                            </ul>
                                                        </td>
                                                        <td class="lin-hide">&nbsp;</td>
                                                        <td class="lin-hide">&nbsp;</td>
                                                        <td class="lin-hide">&nbsp;</td>
                                                        <td class="lin-hide">&nbsp;</td>
                                                    <?php
                                                    } else { ?>
                                                        <?php
                                                        $row_total = 0;
                                                        $available_seller_item = 0;
                                                        $shippingcharges = 0;
                                                        $couponcharges = 0;
                                                        $itemPrice = 0;
                                                        $seller_item_cost = 0;
                                                        $totaltax_peritem = 0;
                                                        $codcharges_peritem = 0;
                                                        $seller_item_commission = 0;
                                                        $orderid = $order_id;
                                                        $seller_orderslist = $block->getSellerOrdersList(
                                                            $orderid, $_bundleitem->getProductId(), $_bundleitem->getItemId()
                                                        );
                                                        foreach($seller_orderslist as $seller_item){
                                                            $parentitem_falg = 0;
                                                            $available_seller_item = 1;
                                                            $totalamount = $seller_item->getTotalAmount();
                                                            $seller_item_cost = $seller_item->getActualSellerAmount();
                                                            $seller_item_commission = $seller_item->getTotalCommission();
                                                            $shippingcharges = $seller_item->getShippingCharges();
                                                            $couponcharges = $seller_item->getAppliedCouponAmount();
                                                            $itemPrice = $seller_item->getMageproPrice();
                                                            $totaltax_peritem = $seller_item->getTotalTax();
                                                            if($paymentCode=='mpcashondelivery'){
                                                                $codcharges_peritem = $seller_item->getCodCharges();
                                                            }
                                                        }
                                                        $i++;
                                                        $seller_item_qty = $_bundleitem->getQtyOrdered();
                                                        $row_total=$itemPrice*$seller_item_qty;
                                                        $vendor_subtotal=$vendor_subtotal+$seller_item_cost;
                                                        $subtotal=$subtotal+$row_total;
                                                        $admin_subtotal = $admin_subtotal +$seller_item_commission;

                                                        // vendor to mygermany shipping cost

                                                        $vendorShippingCost = $vendorShippingCost + $vToMgmbhCost;
                                                        $mits_exchange_rate_amount = $mits_exchange_rate_amount + $exchange_rate;
                                                        $mits_payment_fee_amount = $mits_payment_fee_amount + $payment_fee;

                                                        $totaltax=$totaltax+$totaltax_peritem;
                                                        $codcharges_total=$codcharges_total+$codcharges_peritem;
                                                        $shippingamount = $shippingamount+$shippingcharges;
                                                        $couponamount = $couponamount+$couponcharges;
                                                        ?>
                                                        <td class="col value" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
                                                            <?php echo $block->getValueHtml($_bundleitem)?>
                                                            <?php $addInfoBlock = $block->getOrderItemAdditionalInfoBlock(); ?>
                                                            <?php if ($addInfoBlock): ?>
                                                                <?php echo $addInfoBlock->setItem($_bundleitem)->toHtml() ?>
                                                            <?php endif;?>
                                                        </td>
                                                        <td class="col sku" data-th="<?php echo $block->escapeHtml(__('SKU')); ?>"><?php echo $_bundleitem->getSku() ?></td>
                                                        <td class="col price" data-rwd-label="<?php echo __('Price') ?>"><?php echo $order->formatPrice($_bundleitem->getPrice());?></td>
                                                        <td class="col qty item_status" data-rwd-label="<?php echo __('Status') ?>">
                                                            <ul class="items-qty">
                                                                <?php if ($_bundleitem->getQtyOrdered() > 0): ?>
                                                                    <li class="item">
                                                                        <span class="title"><?php echo __('Ordered'); ?></span>
                                                                        <span class="content"><?php echo $_bundleitem->getQtyOrdered()*1 ?></span>
                                                                    </li>
                                                                <?php endif; ?>
                                                                <?php if ($_bundleitem->getQtyInvoiced() > 0): ?>
                                                                    <li class="item">
                                                                        <span class="title"><?php echo __('Invoiced'); ?></span>
                                                                        <span class="content"><?php echo $_bundleitem->getQtyInvoiced()*1 ?></span>
                                                                    </li>
                                                                <?php endif; ?>
                                                                <?php if ($_bundleitem->getQtyShipped() > 0 && !$block->isShipmentSeparately()): ?>
                                                                    <li class="item">
                                                                        <span class="title"><?php echo __('Shipped'); ?></span>
                                                                        <span class="content"><?php echo $_bundleitem->getQtyShipped()*1 ?></span>
                                                                    </li>
                                                                <?php endif; ?>
                                                                <?php if ($_bundleitem->getQtyCanceled() > 0): ?>
                                                                    <li class="item">
                                                                        <span class="title"><?php echo __('Canceled'); ?></span>
                                                                        <span class="content"><?php echo $_bundleitem->getQtyCanceled()*1 ?></span>
                                                                    </li>
                                                                <?php endif; ?>
                                                                <?php if ($_bundleitem->getQtyRefunded() > 0): ?>
                                                                    <li class="item">
                                                                        <span class="title"><?php echo __('Refunded'); ?></span>
                                                                        <span class="content"><?php echo $_bundleitem->getQtyRefunded()*1 ?></span>
                                                                    </li>
                                                                <?php endif; ?>
                                                            </ul>
                                                        </td>
                                                        <td class="col price" data-th="<?php echo $block->escapeHtml(__('Total Price')); ?>"><?php echo $order->formatPrice($block->getOrderedPricebyorder($order->getBaseToGlobalRate(), $row_total));?></td>
                                                        <?php
                                                        if($paymentCode == 'mpcashondelivery'){?>
                                                            <td class="col price" data-th="<?php echo $block->escapeHtml(__('COD Charges')) ?>"><?php echo $order->formatPrice($block->getOrderedPricebyorder($order->getBaseToGlobalRate(), $codcharges_peritem));?></td>
                                                        <?php
                                                        } ?>
                                                        <td class="col price" data-th="<?php echo $block->escapeHtml(__('Admin Commission')); ?>"><?php echo $order->formatPrice($block->getOrderedPricebyorder($order->getBaseToGlobalRate(), $seller_item_commission));?></td>
                                                        <td class="col price vendor_total" data-th="<?php echo $block->escapeHtml(__('Vendor Total')); ?>"><?php echo $order->formatPrice($block->getOrderedPricebyorder($order->getBaseToGlobalRate(), $seller_item_cost));?></td>
                                                        <td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal')); ?>"><?php echo $order->formatPrice($block->getOrderedPricebyorder($order->getBaseToGlobalRate(), $row_total));?></td>
                                                    <?php 
                                                    }?>
                                                </tr>
                                            <?php endforeach; ?>
                                            <?php
                                        }?>
                                    </tbody>
                                    <?php
                                }
                            }?>
                            <?php
                            $refundedShippingAmount = 0;
                            $totalCouponAmount = 0;
                            $totalTaxAmount = 0;
                            $taxToSeller = $helper->getConfigTaxManage();
                            foreach($marketplace_orders as $tracking){
                                $shippingamount=$tracking->getShippingCharges();
                                $totalCouponAmount=$tracking->getCouponAmount();
                                $totalTaxAmount=$tracking->getTotalTax();
                                $refundedShippingAmount=$tracking->getRefundedShippingCharges();
                                $taxToSeller=$tracking['tax_to_seller'];
                            }
                            if($paymentCode == 'mpcashondelivery'){
                                $count_td = 8;
                            }else{
                                $count_td = 7;
                            } 

                            /*DHL Work*/
                            $count_td = $count_td - 1;
                            /*DHL Work ends*/

                            ?>
                            <tfoot>
                            <tr class="subtotal">
                                <th colspan="<?php echo $count_td ?>" class="mark" scope="row">
                                    <?php echo __('Subtotal')?>
                                </th>
                                <td>
                                    <?php echo $order->formatPrice($block->getOrderedPricebyorder($order, $subtotal)); ?>
                                </td>
                            </tr>
                            <?php if ($shippingamount > 0): ?>
                                <tr class="subtotal">
                                    <th colspan="<?php echo $count_td ?>" class="mark" scope="row">
                                        <?php echo __('Shipping & Handling')?>
                                    </th>
                                    <td>
                                        <?php echo $order->formatPrice($block->getOrderedPricebyorder($order, $shippingamount)); ?>
                                    </td>
                                </tr>
                            <?php endif; ?>
                            <tr class="subtotal">
                                <th colspan="<?php echo $count_td ?>" class="mark" scope="row">
                                    <?php echo __('Discount')?>
                                </th>
                                <td>
                                    -<?php echo $order->formatPrice($block->getOrderedPricebyorder($order, $totalCouponAmount)); ?>
                                </td>
                            </tr>
                                
                            <?php 
                            $admintotaltax = 0;
                            $vendortotaltax = 0; /*
                            if ($totaltax > 0): ?>
                                <tr class="subtotal">
                                    <th colspan="<?php echo $count_td ?>" class="mark" scope="row">
                                        <?php echo __('Total Tax')?>
                                    </th>
                                    <td>
                                        <?php
                                        echo $order->formatPrice($block->getOrderedPricebyorder($order, $totaltax));
                                        if (!$taxToSeller) {
                                            $admintotaltax = $totaltax;
                                        } else {
                                            $vendortotaltax = $totaltax;
                                        } ?>

                                    </td>
                                </tr>
                            <?php endif; */ ?>

                            <!-- here  -->
                            <?php
                            if($paymentCode == 'mpcashondelivery'){ ?>
                                <tr class="subtotal">
                                    <th colspan="<?php echo $count_td ?>" class="mark" scope="row">
                                        <?php echo __('Total COD Charges')?>
                                    </th>
                                    <td>
                                        <?php echo $order->formatPrice($block->getOrderedPricebyorder($order, $codcharges_total)); ?>
                                    </td>
                                </tr>
                            <?php
                            }?>
                            <!-- here ends -->
                            
                            <!-- here  -->

                            <tr class="subtotal">
                                <th colspan="<?php echo $count_td ?>" class="mark" scope="row">
                                    <?php echo __('Vendor to myGermany cost')?>
                                </th>
                                <td>
                                    <?php
                                       if ($dhlFees > 0 ) {
                                           echo $order->formatPrice(0);
                                           // $vendorShippingCost = 0;
                                       } else {
                                           echo $order->formatPrice($vendorShippingCost);
                                       }
                                    ?>
                                    <?php 
                                    // echo $order->formatPrice($vendorShippingCost); 
                                    ?>
                                </td>
                            </tr>
                            <!-- here ends -->

                            <!-- here  -->
                            <tr class="subtotal">
                                <th colspan="<?php echo $count_td ?>" class="mark" scope="row">
                                    <strong><?php echo __('Total Ordered Amount'); ?></strong>
                                    <span class="mis_inclusive_label"><?php echo ($euCountry == true ? __(' incl. VAT') : '');?></span>
                                </th>
                                <td>
                                    <strong>
                                        <?php //echo $order->formatPrice($block->getOrderedPricebyorder($order, ($subtotal+$shippingamount+$codcharges_total+$totaltax-$totalCouponAmount))); ?>
                                        <?php
                                         /*echo $order->formatPrice($block->getOrderedPricebyorder($order, ($subtotal+$shippingamount+$codcharges_total+$vendorShippingCost-$totalCouponAmount)));*/ 
                                         ?>
                                        <?php
                                        if ($dhlFees > 0) {
                                          echo $order->formatPrice($block->getOrderedPricebyorder($order, ($subtotal+$shippingamount+$codcharges_total-$totalCouponAmount)));
                                        } else {
                                         echo $order->formatPrice($block->getOrderedPricebyorder($order, ($subtotal+$shippingamount+$codcharges_total+$vendorShippingCost-$totalCouponAmount))); 
                                            
                                        }
                                         ?>
                                        </strong>
                                </td>
                            </tr>
                            <!-- here ends -->

                            <!-- here  -->

                            <?php if ($order->isCurrencyDifferent()) { ?>
                                <tr class="subtotal">
                                    <th colspan="<?php echo $count_td ?>" class="mark" scope="row">
                                        <strong><?php echo __('Total Ordered Amount(in base currency)')?></strong>
                                    </th>
                                    <td>
                                        <strong><?php echo $order->formatBasePrice($subtotal+$shippingamount+$codcharges_total+$totaltax-$totalCouponAmount); ?></strong>
                                    </td>
                                </tr>
                            <?php } ?>
                            <!-- here ends -->


                            <!-- here  -->

                            <?php if ($order->isCurrencyDifferent()) { ?>
                                <tr class="subtotal">
                                    <th colspan="<?php echo $count_td ?>" class="mark" scope="row">
                                        <?php echo __('Total Vendor Amount(in base currency)')?>
                                    </th>
                                    <td>
                                        <?php echo $order->formatBasePrice($vendor_subtotal+$shippingamount+$codcharges_total+$vendortotaltax-$refundedShippingAmount-$couponamount); ?>
                                    </td>
                                </tr>
                            <?php } ?>
                            <!-- here ends -->

                            <!-- here  -->

                            <tr class="subtotal">
                                <th colspan="<?php echo $count_td ?>" class="mark" scope="row">
                                    <?php echo __('Total Admin Commission')?>
                                </th>
                                <td>
                                    <?php echo $order->formatPrice($block->getOrderedPricebyorder($order, ($admin_subtotal))); ?>
                                    <?php //echo $order->formatPrice($block->getOrderedPricebyorder($order, ($admin_subtotal+$admintotaltax))); ?>
                                </td>
                            </tr>
                            <!-- here ends -->

                            <!-- here  -->

                            <tr class="subtotal">
                                <th colspan="<?php echo $count_td ?>" class="mark" scope="row">
                                    <?php echo __('Exchange Rate')?>
                                </th>
                                <td>
                                    <?php echo $order->formatPrice($mits_exchange_rate_amount); ?>
                                </td>
                            </tr>
                            <!-- here ends -->

                            <!-- here  -->

                            <tr class="subtotal">
                                <th colspan="<?php echo $count_td ?>" class="mark" scope="row">
                                    <?php echo __('Payment fees')?>
                                </th>
                                <td>
                                    <?php echo $order->formatPrice($mits_payment_fee_amount); ?>
                                </td>
                            </tr>
                            <!-- here ends -->
                            <tr class="subtotal">
                                <th colspan="<?php echo $count_td ?>" class="mark" scope="row">
                                    <?php echo __('DHL fees')?>
                                </th>
                                <td>
                                    <?php echo $order->formatPrice($dhlFees); ?>
                                </td>
                            </tr>
                            <!-- here  -->
                            <tr class="subtotal">
                                <th colspan="<?php echo $count_td ?>" class="mark" scope="row">
                                    <?php echo __('Net Vendor Payout')?>
                                </th>
                                <td>
                                    <?php
                                    if ($dhlFees > 0) {
                                        $actualPrice = $block->getOrderedPricebyorder($order, ($vendor_subtotal+$shippingamount+$codcharges_total+$vendortotaltax-$refundedShippingAmount-$couponamount));

                                        echo $order->formatPrice($actualPrice-$vendorShippingCost-$dhlFees);
                                    } else {
                                        echo $order->formatPrice($block->getOrderedPricebyorder($order, ($vendor_subtotal+$shippingamount+$codcharges_total+$vendortotaltax-$refundedShippingAmount-$couponamount))); 
                                    }
                                    ?>
                                    <?php 
                                    // echo $order->formatPrice($block->getOrderedPricebyorder($order, ($vendor_subtotal+$shippingamount+$codcharges_total+$vendortotaltax-$refundedShippingAmount-$couponamount))); 
                                    ?>

                                </td>
                            </tr>
                            <!-- here ends -->
                            
                            <!-- here  -->

                            <?php if ($order->isCurrencyDifferent()) { ?>
                                <tr class="subtotal">
                                    <th colspan="<?php echo $count_td ?>" class="mark" scope="row">
                                        <?php echo __('Total Admin Commission(in base currency)')?>
                                    </th>
                                    <td>
                                        <?php echo $order->formatBasePrice($admin_subtotal+$admintotaltax); ?>
                                    </td>
                                </tr>
                            <?php } ?>

                            <!-- here ends -->
                        </tfoot>
                        </table>
                    </div>
                </div>
                <?php if ($helper->getSellerProfileDisplayFlag()) { ?>
                    <div class="block block-order-details-view">
                        <div class="block-title">
                            <strong><?php echo __('Buyer Information') ?></strong>
                        </div>
                        <div class="block-content">
                            <div class="box-content">
                                <div class="box">
                                    <div class="wk_row">
                                        <span class="label"><?php echo __('Customer Name')?> : </span>
                                        <span class="value"><?php echo $order->getCustomerName(); ?></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php } ?>
                <!-- <div class="block block-order-details-view">
                    <div class="block-title">
                        <strong><?php echo __('Order Information') ?></strong>
                    </div>
                    <div class="block-content">
                        <?php if ($helper->getSellerProfileDisplayFlag()) { ?>
                            <?php if ($block->isOrderCanShip($order)): ?>
                                <div class="box box-order-shipping-address">
                                    <strong class="box-title"><span><?php echo __('Shipping Address') ?></span></strong>
                                    <div class="box-content">
                                        <address><?php echo $block->getFormattedAddress($order->getShippingAddress()); ?></address>
                                    </div>
                                </div>

                                <div class="box box-order-shipping-method">
                                    <strong class="box-title">
                                        <span><?php echo __('Shipping Method') ?></span>
                                    </strong>
                                    <div class="box-content">
                                    <?php if ($order->getShippingDescription()): ?>
                                        <?php echo $block->escapeHtml($order->getShippingDescription()) ?>
                                    <?php else: ?>
                                        <?php echo __('No shipping information available'); ?>
                                    <?php endif; ?>
                                    </div>
                                </div>
                            <?php endif; ?>
                            <div class="box box-order-billing-address">
                                <strong class="box-title">
                                    <span><?php echo __('Billing Address') ?></span>
                                </strong>
                                <div class="box-content">
                                    <address><?php echo $block->getFormattedAddress($order->getBillingAddress()); ?></address>
                                </div>
                            </div>
                        <?php } ?>
                        <div class="box box-order-billing-method">
                            <strong class="box-title">
                                <span><?php echo __('Payment Method') ?></span>
                            </strong>
                            <div class="box-content">
                                <?php echo $payment_method; ?>
                            </div>
                        </div>
                    </div>
                </div>
 -->            </div>
        </div>
        <ul class="note-list">
        <li class="note-list-item">
    <?php 
        $commentAvailable = 0;
        $customerId = $myHelper->getCustomerIdFromSession();
        $commentCollection = $myHelper->getSellerComment();
        $userComment = $commentCollection->getCollection()->addFieldToFilter('seller_id',['eq' => $customerId])->addFieldToFilter('order_id',['eq' => $order->getRealOrderId()]);      
    ?>

    <div class="block-title">
        <strong><?php echo __('Comments') ?></strong>
    </div>
    <?php if ($userComment->getSize() >=1) { 
        foreach ($userComment->getData() as $key => $value) {
            $commentDate = $value['created_on'];
            $commentName = $value['seller_name'];
            $commentUser = $value['comment'];


    ?>
    <ul class="note-list">
            <li class="note-list-item">
            <span class="note-list-date"><?php echo $commentDate; ?></span>
            <span class="note-list-status"><?php echo $commentName; ?></span>
            <div class="note-list-comment"><?php echo $commentUser; ?></div>
            </li>
    </ul>
    <?php
       }
     } ?>
     <br/><br/><br/>
        <?php
    }
}else{ ?>
    <h2 class="wk_mp_error_msg">
        <?php echo __("To Become Seller Please Contact to Admin."); ?>
    </h2>
    <?php
} ?>
