<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/modal',
        'prototype'
    ], function(jQuery, $, modal){

        var url = "<?= $block->getAjaxSyncUrl();?>";
        var collectSpan = jQuery('#collect_span');
        jQuery('#api_test_btn').click(function () {
             var params = {};
            new Ajax.Request('<?= $block->getAjaxSyncUrl() ?>', {
                parameters:     params,
                loaderArea:     false,
                asynchronous:   true,
                onCreate: function() {
                    collectSpan.find('.processing').show();
                },
                onSuccess: function(response) {
                    console.log(response);
                    console.log('-------------');
                    collectSpan.find('.processing').hide();
                    location.reload();
                }
            });
        });

    });
</script>

<?php echo $block->getButtonHtml() ?>
<span class="collect-indicator" id="collect_span">
    <div data-role="spinner" class="admin__form-loading-mask processing" style="display: none;">
            <div class="spinner">
                <span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span>
            </div>
    </div>
</span>
